### ISSUE TITLE
[ossia-pd][ossia-max] add [set ...( method to model and view to set particular node value

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#102]
with the ability to use pattern matching
- [ ] pd
- [ ] max

**Comment by avilleret** [comment]
with a `[set /foo.[0-5/bar* $1 $2 $3(` message we have to parse regex each time we send the message
while if we use a `[ø.remote [0-5/bar*]` all the matching nodes could be stored (and updated on namespace change) then it will be more efficient

but we could have both and anyway a [set ...( method may be useful in some case (and one example is welcome) but it's not on top of the feature list right now

**Comment by bltzr** [comment]
I guess you mean: [ø.remote /foo.[0-5/bar*] ] , right ?

anyway, that absolutely makes sense to me !

just a question, do you see a difference between bar* and bar.* ?
does the * wildcard extend beyond the next slash ? e.g. would bar/kokhba be included ?

I guess we should have a simple set method (no regex) for devices and models for now, in order to allow to simply make cues...

**Comment by avilleret** [comment]
`bar*` matches `bar.36` and `baron` while `bar.*` doesn't match the second

**Comment by avilleret** [comment]
this obviously doesn't work anymore on Pd

**Comment by bltzr** [comment]
Does that work in pd (it's checked)?

Also, shouldn't it be called (send)? (As for ossia.remote.... I'm not sure, but there's some possible confusion with attributes, that also use (set)

Finally, I was wondering if we could have a way to ask for the value of a particular parameter (and not ask for the whole thing with (namespace)?
If we keep on the idea of avoiding confusion with attributes, then we have to find another term than get... Query?

Concerning pattern matching I don't think we should do that. This is where ossia.remote comes in handy 

And

**Comment by bltzr** [comment]
After thinking about our, I don't think we need constant updates from the parameter values, this is certainly overkill

**Comment by bltzr** [comment]
What we might want, though it's too have the same things than here for ossia.device and client

**Comment by jln-** [comment]
I was also wondering if we could use (send) as for remotes, indeed. Not so much to avoid confusion than to make it consistent with remotes.

Hence, using (get) doesn't seem a problem to me. It's quite common term.

**Comment by bltzr** [comment]
> 
> Hence, using (get) doesn't seem a problem to me. It's quite common term.

Yes, but it's used for attributes (for pd, in particular)
That's where some confusion (for the user and for the code) may lay
