### ISSUE TITLE
[ossia-pd] avoid more than one [ø.device] per patcher

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#107]

**Comment by bltzr** [comment]
what should we do then ?

**Comment by bltzr** [comment]
and why should we do that ?
this could help exposing the same device under 2 different names for different protocols eg.

**Comment by avilleret** [comment]
to expose one device over severals protocols just use [expose( message as many times as you need

**Comment by bltzr** [comment]
yes, but it will have the same name for all protocols
while, with the current behavior, this becomes possible (and I don't see any downside, except maybe in performances ???)

**Comment by bltzr** [comment]
OK, so if that's posing problems to other OSes than MacOS, maybe we can implement this policy - how would one enforce having no more than one ø.device per patcher, though ?
and, BTW, what happens (/should happen) if there is an ø.device in a subpatcher of a patcher containing an ø.device ?

**Comment by avilleret** [comment]
if there is already one device in the patcher, the enext one will trig an error in Pd console and appear with red dashed line.

the case of having nested device is not treated yet, and I think we should avoid that too

**Comment by bltzr** [comment]
> if there is already one device in the patcher, the enext one will trig an error in Pd console and appear with red dashed line.

great !

> the case of having nested device is not treated yet, and I think we should avoid that too

shouldn't that be similar to the way ossia and ossia.device interact ?
i.e. if there is a device in a subpatcher, it takes control on all nodes below (and removes them from the device above....) 
would that make sense ?

that's absolutely not hi-priority, though

**Comment by avilleret** [comment]
hum... why not, actually it is working more or less like that I think
maybe we can have a try  ?

**Comment by bltzr** [comment]
I confirm that it does indeed work this way

**Comment by jcelerier** [comment]
... maybe there should be some unit tests or something, that guarantee it ?
