### ISSUE TITLE
[ossia-pd/max] add [disconect( method to [ø.device]

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#108]
with connexion index as argument

- [x] pd
- [x] max

**Comment by avilleret** [comment]
the message is [stop <idx>(

**Comment by bltzr** [comment]
it works in pd

in Max there are several problems:
- (get protocols) always return "protocols 0"
- (stop) doesn't do anyhting (which sounds sensible, because it shouldn't
- (stop 0) crashes, which is understandable because of  point 1

**Comment by bltzr** [comment]
crash log:
https://gist.github.com/bltzr/c20eece598482608620855772cd2b33a

**Comment by bltzr** [comment]
this seems to work, and is now documented both in max and pd, so I'm closing the issue - tell me if I oversaw something
