### ISSUE TITLE
[ossia-pd] add pattern matching support for remote

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#114]
then `[ø.remote /foo.[0-5/bar*]` will send values to all matching nodes and return values from them
the address of the source of value should be returned with `[address /foo.1/bara(` message via dump outlet

**Comment by avilleret** [comment]
currently (without pattern matching) when a `[ø.remote foo]` is created, the value of `foo` is fired (if it exists) just after the  connection to the corresponding `[ø.param foo]`
with pattern matching there is not only one `[ø.param]` but possibly lots of.
Should we send out the value of each [ø.param] when connecting ?

**Comment by bltzr** [comment]
I'd say "yes", and also that, anyway, we need to have an extra outlet to [ø.remote] that returns the address of the [ø.param] from which the value is coming

**Comment by avilleret** [comment]
why a new outlet ? which will be inactive most of the time
what about my proposal to use an [address ...( message through the dump outlet ?

**Comment by bltzr** [comment]
Yep, sure... Sorry I forgot about this..

Would that output the address at each pattern matching value output?
If yes, that sounds good to me!

**Comment by avilleret** [comment]
this is done in pd
