### ISSUE TITLE
[ossia-max] crash

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#122]
I get a consistent crash with the attached patcher:
- delete [ø.view truc]
- rebuild [ø.model truc] (e.g. delete a letter and type it again)
- witness Max crashing

[ossia.maxhelp.zip](https://github.com/OSSIA/libossia/files/1179664/ossia.maxhelp.zip)

crash log: https://gist.github.com/bltzr/ea052ae9a3e1e95525b7b1a1e1540afc

**Comment by bltzr** [comment]
actually, this did change: now, having two similarly named model and view in a patcher crashes Max when loading the patcher (it should just refuse to instanciate ossia.view)

**Comment by bltzr** [comment]
related to #121

**Comment by avilleret** [comment]
@bltzr is this still relevant ?

**Comment by bltzr** [comment]
more than ever: I can't even open the attached patcher, it directly crashes !!!

**Comment by bltzr** [comment]
simplest way to crash Max with this

[model+view-Crash.maxpat.zip](https://github.com/OSSIA/libossia/files/1552823/model.view-Crash.maxpat.zip)

**Comment by avilleret** [comment]
can't reproduce it anymore, could you confirm this is fixed @bltzr  ?
