### ISSUE TITLE
[ossia-max] build for Windows 64bit produce `ossia-max.mxe` instead of `ossia-max.mxe64`

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#123]
Cmake fail to detect 64bit on windows apparently

**Comment by jcelerier** [comment]
you have to call it specifically with `-G "Visual Studio 15 2017 Win64"` to get 64 bit builds

**Comment by avilleret** [comment]
it is already : see https://github.com/OSSIA/libossia/blob/master/appveyor.yml#L28
and CMake should detect it and change extension to "mxe64" here : https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-max/CMakeLists.txt#L73

but it doesn't as you can see in the archive here : https://ci.appveyor.com/api/buildjobs/b2xqfeh6f0honbcc/artifacts/ossia-max-windows-x86_64.zip

**Comment by jcelerier** [comment]
mhh... it's behind a `if(WIN64)` but WIN64 isn't a cmake variable. One sure way to test is to replace with `if (CMAKE_SIZEOF_VOID_P MATCHES "8")`... or do somewhere 

```CMake
if (CMAKE_SIZEOF_VOID_P MATCHES "8")
  set(WIN64 1)
endif()
```
