### ISSUE TITLE
[ossia-max/pd] model/view nesting

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#125]
If that doesn't create problems, and is not overly complicated:

when a view is in a subpatcher of a patcher containing a model, it should bind relatively to this model

see attached patcher for explanations:
[nestedViews.maxpat.zip](https://github.com/OSSIA/libossia/files/1191058/nestedViews.maxpat.zip)

- [x] pd
- [x] max

**Comment by avilleret** [comment]
could you check https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-pd/tests/test-pattern.pd
in device2, there is a [ø.model sub] and a [ø.view sub] somewhere

**Comment by bltzr** [comment]
this seems to be OK for pd - thanks, you rock !

**Comment by bltzr** [comment]
works for Max now, too
