### ISSUE TITLE
[ossia-max] ø.client crashes when connecting

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#128]
https://gist.github.com/bltzr/d4527e2034906edc8cf9e20f2cc95fca
and 
https://gist.github.com/bltzr/cec58dbbae4a49f23a00aebf1c4aede8
i.e. crash log is different when there is and there isn't a device to connect to

**Comment by jcelerier** [comment]
interesting, both crashes don't look like crashes in  our code :p

**Comment by avilleret** [comment]
@bltzr could you confirm this is still there ?

**Comment by bltzr** [comment]
No I can't because I don't know how to reproduce the problem, the author didn't document the steps for that - so I'm closing the issue
(and from the tests I've done, it seems to be OK)
