### ISSUE TITLE
[ossia-max/pd] reset feature

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#135]
wouldn't it be useful to have a reset message, that would reset values to the default
this could be the case in ossia.parameter, of course, 
but maybe that could be sent recursively, e.g. to models and/or devices, which would propagate to every further nodes downwards the hierarchy 
opinions ?

- [x] pd
- [x] max

- [x] downwards propagation

**Comment by avilleret** [comment]
this is a good idea, I admit

**Comment by avilleret** [comment]
should [reset( message only send the default value of the parameter (as defined with `@default`)
or should it also reset all attributes to the state they were when the patch opened ? (i.e. discarding all changes made with setter method)

**Comment by bltzr** [comment]
I don't really know... that sounds like a good idea to do so, I'd say... (but I might change my mind :-p )

**Comment by jln-** [comment]
Not sure how did it behave with Jamoma, but I'd tend to think it should reset the model to its very initial state, thus including other attributes value.

**Comment by bltzr** [comment]
I don't think it did do anything to the attributes in Jamoma, (actually nobody ever thought about it, I guess), but I tend to think that's a good idea to do so

**Comment by avilleret** [comment]
since the `[setdefault ...(` message changes the default value, the [reset( message should send the new  value, not the one we typed in the box.

This seems to be an answer to myself :-)

**Comment by bltzr** [comment]
thinking out loud, but maybe these are two separate functions:
- we could have a 'init' (or whatever) message that would the (last set, if applicable) default value, and just that (this is what Jamoma did)
- and also a 'reset' message that would put the whole model or device to the state it was at startup (including resetting the default attribute to its initial value)
how does that sound ?

**Comment by avilleret** [comment]
it sounds like another feature tu implement :-)

**Comment by jln-** [comment]
mm... 'init' and 'reset' sound like the same thing to me, dont they ? I'd rather like if we can keep it simple and just have the right behavior implemented.

I hardly imagine a situation where I'd want to reset or intialize a model knowing that some attribute got changed thus my model will be put in an half init state. Do you ?

And to add more thinking to this, in Jamoma, we discussed a few times having the possibility to set default parameters value using an attribute-like syntaxe right in the object box. ie. [mymodel.model @sources 4]. In that case, mymodel would get initialized with @sources == 4 rather than the value set within the model itself.

In such a scenario, it would then make sense imho that mymodel gets initialized using its default parameters value (and their attributes) except for @sources that would be initialized with 4.

**Comment by bltzr** [comment]
concerning passing attributes to the enclosed ossia.model, that kind of made sense in Jamoma (as the model name was put as an argument to the model abstraction object, not to j.model itself.
my impression is that this feature is maybe adding complexity, while this could be easily done with \#2, \#3 and such, or by including a patcherargs object in the model patcher...
I mean, that could be a possible future feature (in which case feel free to add an issue), but IMHO that's not top priority for now...

**Comment by bltzr** [comment]
so, @jln- what should the init or reset message do ?
reset the (all ? some ? which ?) attributes to the initial value or just the value to the default
if resetting also attributes, what about the default attribute itself ?

**Comment by avilleret** [comment]
currently a Pd `[reset(` message sends the default value, as defined with `@default` in the box or with the message `[default ...(`

**Comment by bltzr** [comment]
I guess that's good enough for now... we'll see the other parts of the issue once a consensus has been reached

**Comment by bltzr** [comment]
well, that probably got lost in the debate... but @jln- and I were thinking about this for the model
even better, this could also be implemented in the device and client (and ossia ?)
so that, when [reset( is received, it propagates to each and every child node
would that be possible ? (not completely critical, though)

**Comment by avilleret** [comment]
everything is possible, it's just a matter of means

**Comment by avilleret** [comment]
and yes, I agree this could be great
but what about the behavior of [reset( message ?
currently it only send default value, but I hear at some point that you want it to also reset object to its state at patcher loading (resetting all attribute to the value entered in the object box with `@`)
what about that ? is there a consensus ?

**Comment by bltzr** [comment]
> I hear at some point that you want it to also reset object to its state at patcher loading

I'd say that, until someone has a really strong reason or use case for that, we'd better forget about it

One thing we shouldn't forget about, though, is the recursive (reset): on models but also on devices (and [ossia])-> then also remotely on clients and views (as Remotes do for parameters)

**Comment by bltzr** [comment]
so, to sum it up:
- [reset( seems to be working well ATM
- it could be nice that it worked also on models and devices, and propagated downwards, to lower-level submodels and nodes
- this is not critical nor urgent, so we'll postpone this to a later time
