### ISSUE TITLE
[ossia-max] add min and max attributes

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#137]
also, uncomment sections about them in ossia.parameter.maxref.xml

**Comment by avilleret** [comment]
@bltzr could we close this ?

**Comment by bltzr** [comment]
well, they are there, and they actually do work with vecs (as ossia.parameter.maxhelp demonstrates)
though, when used with a param \@type float they kill everything, and the range has to be set again from the range attribute in order to have the param working again

<pre><code>
----------begin_max5_patcher----------
482.3oc0UssTjBCD8Y3qHUdl0BHbwYex+isrrBLQMVPBURiKVV9uugNf6n6H
xn0L59BP5bRe5yIoCOFFPqzCBKk7SxuHAAOFFDfgFCDLMNf1xGpa3VDFspG.
shF4mR02JUMB.mKYJnEdnQff2AltGdMtNNTeqTcyUFQM3qAVd7YwQjT1F7U1
7SxkSqQtESrt5terYN69TCOzI7IgVwU2PIWNN6SggiOh9dnN14iBhUl89pq7
HntqaztZcNwWqMsbrxJ9L5McA8VV50KtaNs0lte8lSeNOFdq.DlqDJdkm532
xKnQ+W4GYLzB71xx9A6KvOThe6ndlXPL.9xwZk7ydtNHb2WjKLhNAHAoVYIw
jKpajcjJMbK83ZdrzBz1JxWx8RnK4PeL2gCfoWdfxabQX.G5C99h7hT+4ETx
IKefI6sk7Wgb4Ce.4Vtyk+uibK9VIWiqmSbvBNKNc8B97UJXbszFo50+WGKf
w3uzEr5dS8bplHh72JXqvBREerOeGLIdL60mWKOEmHdxNQ7jrBdxeAFsYq.O
+DezItb+Dm7oHlchb1MqfG1+viuQf20cuvXm.iT3Z7uSixuLBGJU9gLbnQbu
bFeFFgabctfqss236+GJ721Ra0NiT4t2v6kNleJ7Oj30VpL
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
could be related to #321
