### ISSUE TITLE
Question about nominal duration of constraints

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#14]
Here is an use case : 
![automs](https://cloud.githubusercontent.com/assets/2772730/11928643/8592ef2a-a7d5-11e5-9ff1-88a57d74861e.png)

Here we have a constraint with three processes : one of duration < of the min of the constraint, one approximatively equal to the nominal duration of the constraint, and one that goes after the nominal in case our trigger takes a long time to start.

Currently, for this case in i-score, it's okay because it's only curves. In the translation i-score -> API Scenarios are created with a single constraint of the length of the process here.

But this means that for instance, if we replace the automations by processes that are less "temporal" (such as loop processes, JS processes, mapping processes) and if the parent constraint is made infinite, this means that the process will still end at some point in time and not continue indefinitely.

How should this be done ? 
I see two options : 
- Marking processes as describing an "invariant" (for processes that I mentioned) which doesn't really have a duration.
- Adding a field in i-score that says if a process should directly be in its parent constraint in the API (for instance a checkbox "use parent duration" next to the process).
  I am going for the second way for now since it does not require changes in the API.

Any other ideas ?

**Comment by jcelerier** [comment]
I will set the "use parent duration" functionality by default for all the process that don't really have a duration like JS, mapping, loop.

For automation I think that it should have its own duration by default.

**Comment by theod** [comment]
about the use case : 
   - automation 1 should be ended by an empty segment.
   - automation 2 is ok.
   - automation 3 is already allowed by the API as a Curve can have segment starting from an abscissa greater than 1.

so Automation process doesn't need to have its own duration by default.

about cases where processes are not automations (the "less temporal" ones) : 
you said "if the parent constraint is made infinite, this means that the process will still end at some point in time and not continue indefinitely" but this is not true : the process simply have to handle time positions greater than 1. this is the case for the Mapper and Loop processes and for JS it depends of the code inside.

**Comment by jcelerier** [comment]
closing since it's not done like this anymore in i-score
