### ISSUE TITLE
add enable attribute

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#140]
when turned to 0, this would disable the output of the value 

when done in libossia, implement in ossia-max/pd and potentially others

- [x] libossia
- [ ] ossia-max
- [x] ossia-pd

**Comment by avilleret** [comment]
Needed for :
- [ ] ossia-max
- [ ] ossia-pd

**Comment by bltzr** [comment]
shouldn't we check the libossia checkbox: if that is implemented in pd, I guess it is also in libossia, isn't it ?

**Comment by jcelerier** [comment]
nopoe, the attribute is there but isn't used

**Comment by jcelerier** [comment]
now it is

**Comment by bltzr** [comment]
I just added a test patcher (testAttrs.pd), and it seems that enable doesn't work in pd ... both by setting it at a box's attribute, and by sending the [enable 0( message...
or did I do something wrong ?

**Comment by jcelerier** [comment]
from what I am seeing in the code of ossia-pd parameter.cpp, it seems that x_enable isn't initialized

**Comment by avilleret** [comment]
it should be ok now in Pd

**Comment by bltzr** [comment]
OK, so it's normal that this doesn't work yet in Max, right ? (that's not an urgent problem, though)

**Comment by avilleret** [comment]
I think this is done for a while now
