### ISSUE TITLE
[ossia-max/pd] add support for pattern-matching for parameters

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#141]
@jcelerier mentioned that this now works in libossia with  ossia::net::create_nodes(device1, "/foo[0-9]/{bar,baz}/{a{b,c,d},e}[x-z]")

- [x] ossia-max
- [x] ossia-pd

**Comment by avilleret** [comment]
I was thinking about merging `ossia::net::create_node` and `ossia::net::create_nodes` (and the same for `ossia::net::find_node` and `ossia::net::find_nodes`)
What if the address in `create|find_nodes` is not a pattern ? do they return a one-element vector ?
This could reduce code verbosity a lot.
What do @jcelerier think ?

**Comment by jcelerier** [comment]
> What if the address in create|find_nodes is not a pattern ? do they return a one-element vector ?

> This could reduce code verbosity a lot.

mhh.. yeah, but this comes at the expense of performance (especially for allocating a single element, the ratio cost / benefit is not very good imho). I think it's good to leave the choice to create a single address if someone is sure, with create_node, and just use create_nodes by default in max / pd which could be modified to return a one-element vector. (gonna test but it's almost certainly already the case).

**Comment by avilleret** [comment]
yes I was referring to Pd/Max implementation while thinking about reducing the code verbosity

actually address is checked for pattern validity then we choose between find_node or find_nodes.
if find_nodes do the same check, then it should be painless to use it all the time and remove `is_pattern()` call and all surrounding code

**Comment by avilleret** [comment]
we can't use curly braces in pd vanilla, but we can on [PurrData](https://forum.pdpatchrepo.info/topic/10493/purr-data-rc4) since rc4

**Comment by avilleret** [comment]
this should work on Pd now (with the no-curly brace limitation)

**Comment by bltzr** [comment]
what should we do with this ? use a replacement or make a feature request to add support for curly braces in pd ? (or is this caused by tcl/tk ?)

**Comment by jcelerier** [comment]
that sucks a bit since braces are what's proposed in the OSC spec: 

> A comma-separated list of strings enclosed in curly braces (e.g., "{foo,bar}") in the OSC Address Pattern matches any of the strings in the list.

Using another character, for instance < > or [canadian aboriginal syllabics ᐸ ᐳ](https://www.reddit.com/r/rust/comments/5penft/parallelizing_enjarify_in_go_and_rust/dcsgk7n/)  means that its usage /in/addresses would have to be forbidden (which would certainly cause all sorts of bugs in the future if for instance Pd interacts with another software which does use the character).

**Comment by avilleret** [comment]
few googling on Pd list show that curly brace is a separator in TCL/TK GUI communication.
we can use it (for example with [123( -> [makefilename] ) but we can't display it.
one workaround would be to use another character and replace it with curly brace silently.
another solution is to fix this bug in Pd and make a PR to Miller...
I sent a message to mailing list today : https://lists.puredata.info/pipermail/pd-list/2017-08/120002.html

**Comment by bltzr** [comment]
I just had a look at your pd-list message, and it seems you used a wrong syntax (AFAIR, {} are used for enumerations, like {one, two, three}, rather than ranges (which are expressed by [1-5], right ?)
I guess people will get the idea, but you might get exposed to sarcasm too... ^_^

**Comment by bltzr** [comment]
it all seems to work... are there things you still need to implement, @avilleret or can we close this issue ?
