### ISSUE TITLE
[ossia-max/pd] allow to set attributes with a message

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#142]
- this could be done from the parameter's inlet, by sending the attribute name and value of the attribute to the first inlet
e.g. range 0 2
- [x] pd 
- [x] max 

- wouldn't it be nice if that was also possible to do this from models and/or devices ?
hence that could allow in particular setting the \@priority attribute for implicit nodes 
somehow related to #102 
- [ ] pd 
- [ ] max

**Comment by avilleret** [comment]
concerning point 2 : you want to be able to change e.g. a parameter priority attribute by sending a message the model it belongs to ?

**Comment by bltzr** [comment]
yes and no, what I want to do is that, if I create a parameter sub/thing
then I want to be able to somehow set the priority of the 'sub' node (that has been implicitly created by declaring the parameter, and is not associated to any pd object)
that could be e.g. by sending the message [set sub@priority 123( to ø.model 
do you like it ?

**Comment by avilleret** [comment]
no I don't, it'll add confusion to me
I'd rather add an [ø.model sub] besides the [ø.param thing] intead

**Comment by bltzr** [comment]
OK
