### ISSUE TITLE
domain filter on vecNf output erronous value

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#148]
when min is set to `FLT_MIN` for one of the value of a `vec[2-4]f`, then the filter output `FLT_MIN` as soon as the value is <= 0

see this video : https://files.gitter.im/OSSIA/i-score/sDGk/domain_bug.mp4

**Comment by jcelerier** [comment]
but... FLT_MIN ~= 0 (FLT_MIN is defined as the smallest value > 0 if I remember correctly). Maybe you're looking for `std::numeric_limits<float>::lowest()` instead ?

**Comment by avilleret** [comment]
:door: (and sorry for the noise)
