### ISSUE TITLE
[ossia-pd/max] Preset support

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#149]
- [x] pd
- [x] max

**Comment by avilleret** [comment]
Currently in the implementation, preset applies to device directly, isn't it ?
Wouldn't be nice to be able to make preset from arbitrary node ?
To be able to save a model state for example.

**Comment by jcelerier** [comment]
yep, one just has to change 

    ossia::devices::apply_preset(...) 

to take an ossia::node_base& instead of a device. from what I can see the algorithm should work with "relative" paths.

**Comment by bltzr** [comment]
could that work with an arbitrary (non-continuous) set of nodes ?

**Comment by jcelerier** [comment]
do you have an example ? a preset is just a list of nodes associated with their value: 

    "foo": { 
      "bar": 1
      "baz": [ { "blop": 123.23 }, { "blop": 456.67 } ]
    }

would be equivalent to setting: 

    /foo/bar 1
    /foo/baz.1/blop 123.23
    /foo/baz.2/blop 456.67

**Comment by avilleret** [comment]
Works in pd

**Comment by avilleret** [comment]
fix with https://github.com/OSSIA/libossia/commit/ce908966946a18b54fc11ac63e03c5b62ce01664
