### ISSUE TITLE
[ossia-pd] unknown bounding mode: CLIP

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#156]

**Comment by avilleret** [comment]
should be fixed in 546ad3e1866c55a58889afe2c8ba913627792c62
could you confirm @jcelerier  ?

**Comment by jcelerier** [comment]
I only saw it quickly on @bltzr screen so I can't confirm, but I guess we'll just reopen the issue if it isn't

**Comment by jcelerier** [comment]
I only saw it quickly on @bltzr screen so I can't confirm, but I guess we'll just reopen the issue if it isn't

**Comment by avilleret** [comment]
don't trust @bltzr's screen anymore ! ;-)
