### ISSUE TITLE
[ossia-pd/max] add filename parsing ?

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#163]
ossiadev `[preset save foo.json(` write a file beside the patcher we are editing ?
or should the user handle that himself ?

**Comment by bltzr** [comment]
How would the user handle that himself?

**Comment by avilleret** [comment]
in Pd, with the [ggee/getdir] object, in Max with [thispatcher] iirc

**Comment by bltzr** [comment]
Ah OK you're talking about where on the disk goes the file (but ossia.preset] or whatever does the saving - then yes, the user handles it themselves

**Comment by avilleret** [comment]
ok so let the user do it
