### ISSUE TITLE
range values should be converted when using a remote/mirror with a convertible unit 

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#171]
a good example can be found in ossia.remote-help.pd -> [pd unit] subpatcher
e.g. by moving values of [ø.remote freq @unit time.cents] below 1548 (or the param's input below 20) -> values should be clipped at 1548 in this case

this is probably connected to https://github.com/OSSIA/i-score/issues/622

**Comment by avilleret** [comment]
no it not related to i-score, I just have to swap 2 blocks I think

**Comment by jcelerier** [comment]
yes; the i-score UI code for this doesn't touch the api either

**Comment by avilleret** [comment]
iirc this have been fix a while ago

**Comment by bltzr** [comment]
Yep, I just tested and that is fixed indeed
