### ISSUE TITLE
[ossia-pd/max] mute attribute

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#173]
on ossia.param : mute should disable incoming message, so it's more like a `deaf` attribute, but keep `mute` word for that anyway, but ossia.remote beside this param should continue to work as before

on ossia.remote : mute should unregister the object from the local node, so we won't be able anymore to set or get node attribute or to send or receive value or to get noficiation

- [x] pd
- [ ] max

**Comment by avilleret** [comment]
@bltzr @jln- could test if that works as expected both in max and Pd ? 
and update the issue accordingly ?

**Comment by jln-** [comment]
mute doesnt do anything so far either on param or remote with bae95d3fb

**Comment by avilleret** [comment]
oups wrong issue id...

**Comment by avilleret** [comment]
in Pd : 
- mute on remote, unregister the remote, so the remote doesn't interact anymore with anything 
- mute on parameter : input is disabled, but output still works (at least from a remote besides)

**Comment by bltzr** [comment]
> mute on parameter : input is disabled, but output still works (at least from a remote besides)

from my tests (in ossia.remote-help) -> [pd attributes] -> [pd mute] that doesn't work: value doesn't get out from the param when the remote's value is changed

also, this only works when sent as a message, when put as an attribute in the object box, the param/remote remains whatever is sent to its input
(also see in help patcher to test that)

**Comment by avilleret** [comment]
<pre><code>
----------begin_max5_patcher----------
588.3oc4W00aaBCE8Y3Wgk0dLKBrg.YO0+GSUUFhC0UfcjsoKUU8+97Gjzr1
DBkhRV2d.K4KFetmy02iLOGF.KDaoJH3GfeBBBdNLHvExFHnad.rgrsrlnbK
CpEUU0T3L+q3sMhVcMU6dYbWzMDc48Ld0cRZo1u4oIQyilARxsinjcifa69D
1J2tKJd36Kg62FIogpox6nbRgATyJh5dmGU8San98Gx3Fjt80zhweaVozO42
CHzF3kvP6vrAx6FpRQp1SbMcq1GuUSAeKdrBRN1Nl5EDzwEj3H3oX8InLZRn
7HK0njLGahvmuVm8eQsdmhfyOewN45TqOEkKqYa.EB88e7C33k9iAN5ll1Go
y+6hzRphp+vDNI+PBiy5skN65v300Bytdbpg5gZn3CO.G0K0RGUOMbF.VP3U
CuwtKxZgrg3xyEiPP3zeYR52cBPnTLxbIsQX53klz5D1f39NNbnlEGi6Uzvv
9DF2y0vwabcBwKQdSez.5DPeo5DhicG9wnEmuS3KUivmSO5J08qG3+YLF1S.
u2.3Fa9BLRHQCtYEcMosVChlmNZ4rqAZwhdac52yXL9EtuAVy3u8mBb4pM9e
JYJQqrbGpcWdG7ZxthpzLNQyD7CVi89r1EczpxPAJeH.gm.fxF.PIS.NICgP
S.N3KDNwYWpJj8FGWHjFj3kNEHgtTkonKl3M.fduz4cjHa17HUp5VrCBic8C
BocZ1L2TF2O0cmLyMWdjsa8ItHDowsUarZakdiusK7+rErQrhJ4sLm+XnE4W
B+8jXf9c
-----------end_max5_patcher-----------
</code></pre>
