### ISSUE TITLE
[ossia-pd/max] what about a [dump( message

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#175]
at the very beginning I set up a [dump( message in ossia-pd to print some info in the Pd's console about registration and attribute.
since attributes are now fully integrated with set/get methods and Max' inspector, is this message still useful ? if yes, what should it do exactly ?
At first it was sending out the node informations, but now an object can hold several nodes, so the dump output could be huge.

**Comment by avilleret** [comment]
@bltzr @jln- your input is welcome :-)

**Comment by bltzr** [comment]
we could dump the dump

**Comment by avilleret** [comment]
thanks for your input @bltzr !
