### ISSUE TITLE
[ossia-max] ossia.remote do not output when sending 'bind' to parent ossia.view

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#178]
Sending bind message to a ossia.view do make the view bind to the addressed model. However ossia.remotes subscribed to that view only output value when the corresponding parameter value change.

It would be useful (ie when building GUI views) if ossia.remote output value when sending the bind message to the view.

<pre><code>
----------begin_max5_patcher----------
1504.3oc6aszbihCD9L9WAEWxEut38i81bcOu2RMkKAHaqY.IJPNwyN07ee0
KHBrwA6LNwoFt3GcKI59qkZ05yx+bggUJ4.rwx7uMezzv3mKLLDh3BLTe2vp
DbHq.zHZlUIroArEZsTpiBOPExSQ3bS.lP2AqWWRxgEsMAuuDgKfTQ+cUBQ4
hdQR+1eEn0PxdZaKcTRkhn+nBJMSKKyupT0P+QgPpU6PTAnY6P3sqqgYTY6i
BsWYuzz02i+liSj3atqrM+JuO+ZwB9KK+c39M6SuHO2+154gAgZddbxaxwSE
O.Xc6y6ID74mPMnTTAh9idl8lMMPkIHfda9iTorfj8cXddMXaSVMonf2Lakt
rBT12o6pI62tSWNDCRKf6NtCREOcrhzs73fNpmRpyYFuVa5EbrON33d5fi83
3smO2a8CCDu4J9laXhl2CKSg45XUKnJwcEvaXsAwbKXcChf0ZsgEnpRSrgVW
3QquQDCTzxNQHrTjWmnZHOnI6ePmTPMyWnLGYesbV0g3PqWFFFVVi2iDlhTH
adyh1Ar08iCbk9uX5VnuH16GqE84AF4D.MjjMgoBhQ3pZXCDSATk00oNGtAr
uftdCASaP+mv.c3OpSneCHCNZmwfRo28kZDncQpg01ZTNAyMhdXMWb6i6QSG
QPk+5KNinEXP0I5LaBDCWFQYCyI22jBpEqeJzmmxxnPHE8U00uB3FpRcEBiG
fhTR03JqQa2cl9lRXJKO2XKzzrdOVpcMKu.ccC3o9nMETTfgOy79AC+A.FUB
nPJRFBbs6Tdzpam9Zd5DZxYyhyfOixoxDE5SFXMGU0NIxpKJmi1Ban8kQYYg
5K4n7pLQ6aS8slBKqJXdQ+FzaKT8kj5oT6IePp0MEDVNlt0aCyM4noPK+j2f
NnkixUSywahrjkLGf21sYhLiColEe3MITSZEnlslgxbcYrPOpdZ3ZjTipkO9
h2Br6uSjQ6tQpLKuqvX3mOXz0y6FBip0uZFRWQNjlFDXUm2XBVK97kB4wuAH
uObeoy+RrkSCitIHWForjsC1Igt+cGpwTTbnI6Ch5.xg4lHrIvrM+xJyIgj7
wLiTH2YmWhkmafeBuLKO+.6jXwmhjxbz1uZPTHZ7nvaXtouqDZkUdZ+NhveQ
Au7c4yMen2QQd3Rmh5jLMzoWMIwqdC.mr57DGwaQ2EoFC9TkZLJ7dcKF+Og3
38ydLp0wW0NMte.6znlGp1pI14iA.k4BOEeLSOG33fmyYAu2xVzIpyYEeVX6
kyfUfviU7s3Yv0eZ7rgruNq0lUkkX1e2R1gInHb2IRerqhQyoFMuTaHXh1f6
MzF7lnMDeCsA2IZC9iZCJgRIybcc7x8SUQ9z45pkawDwBUO4xV2D6+TH6JLQ
TvlWTjrpWIL3mLS10LYWyjcclJWD4gFsTD6KljlaWoHwhJf8raes2X0dRzgi
FBmCOnk63C7XGepHHTdbCW+jOxScTCKIT30Rq0YNtr2qdXiIdfid793mX6jD
tT7oXaOAEPArye3GcLwOiC41xyq3Y+wvIFu1pYJwtUThIPW9uMMyvLoDyGZ+
Ipev75NS3LuXe13yIw+NJy5MhLm6x7qsHuJAan+GCzKRAL3lobWvATOrNINw
MPh0NQ9gthSR64D6GLMrVdhE2H4aNu+rGENQFKbtCXOx6FZC9WFCVZsqDkWQ
PXpJf3Z6sJfmyWrtwIRtQP+uYK2ZU0R6ou15VwIVvq4UrhAzbpXceJVykTM6
F5QyLr8tdaxbtxaSli7Z6MeaxluMYyDrMSv1LYQy2lr4aS17sIa91j89dax5
nMalvr4KR1LwiyWjr+vtHY2i7G9Z2grW4WzZ9NjMeGxtBFtDCX+oLRBuFZdJ
ZuNe340gkiHVapOG+q54HcuALCweDCXDZ.aPGyDz3r.MjAHA6Ox03CfzNJV9
GPIoDrdGZKyy2tiByWSpYano9e31xKSeDAjkwptSq1VGI8gAKkDI57x+D1kJ
jsl0ggIarJYirvVsUHzhes3+A.8Y7bB
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
yes, that would be very useful!

and that would be even better if that did so by order of (nested) priority, but maybe that's for later... :-)
