### ISSUE TITLE
[ossia-pd][ossia-max] changing attributes changes them locally, not on the bound parameter

### ISSUE THREAD

**Issue by bltzr** [ossia/libossia#180]

**Comment by bltzr** [comment]
this has to be fixed in Max, too

**Comment by avilleret** [comment]
could you try again ? it should work in Max now but it has to be tested with all attributes

**Comment by bltzr** [comment]
yes, it seems to work for all attributes I tested... though, the changes are not reflected in the attrui's and inspector of remote or parameter when changed remotely

**Comment by bltzr** [comment]
I just noticed that this doesn't work in Jamoma either, as demonstrated below.
so maybe that's just not possible in Max

that's the notifications thing you told me about, right ? (and that I didn't understand the problem with, at the time...)


<pre><code>
----------begin_max5_patcher----------
492.3ocyU0sajBBF8Z8ofv0VWAc9qW02iMMMnCcJSTv.X2ooou6q7gN6Ls5D
mV6t6MZ3yO3v434.uFFfyUG3FL5VzOQAAuFFD.kbEB5FGfqXGJJYFnMbE2XX
633H+2r7CVndRLhF2WU0XK4V6K0b+Riwn669jXKztJe+Mjj99kMUBY6L.Hn+
onecfpjtpF6Kkvph6mbMyV7jPt6AMuv5wKc853jHDIIw8ZA7jRiSP26lxagg
tGQSjwOVpZ2JiSsHDNmI2MHE2LHCIG24ZVE2x0OvkrbOsRFj8zQY+iJcECn8
xw0ikfbPIKcuxV+OSNV8+jbLOtiwxC2PhQjqLPr3aKOPylOFK4+pcy9ABuO1
vkaQ+vxrra0sNfiZRoPxKTMR6orYZJB8hFlYPQxN0JjtXtkjiVZjSVP2A5BB
NqDcWQontRskixU1mFTrRuTJa3yTuBAidMBVWl4L8JaymTuXVqtQbcgizKxL
2JBsdly6KXPHzSYJYjLCrQg+Yu6RTXEc0OWELpFcQOM6uCDkbjua4FqPxrBk
7jln9dFTnmJPK9KgCYB3rYFvY0DvgLC3j9ovw6KX00Oy0ltlAHZyA6UfScUD
LTH8CgnNVyeVz2eFTgoacl1VaYi16YOrLC6mZ6QGZYaLxYsCcH+V3uQAZ4S2
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
it does work but attrui has to be updated (ie choose another parameter and go back to previous one)
I'll look if there is a way to do that automatically

**Comment by avilleret** [comment]
I thought I fixed this a while ago, can you confirm @bltzr @matcham  or @jln- and update issue accordingly ?
thanks

**Comment by jln-** [comment]
Just went thru all attributes. All works fine both way (set from param attrui -> reflected to ossia.attribute attrui or the other way around), except:

- `recall_safe`
- `queue_length`
- `mute`

Actually, `mute` is not sent at all to parameter when set from ossia.attribute

- `unit` half works. It's ok when set from the parameter attrui (ossia.attribute properly reflects the change), but NOT ok when set from ossia.attribute. New unit is not set at all.

**Comment by bltzr** [comment]
> Actually, mute is not sent at all to parameter when set from ossia.attribute


That’s perfectly normal, since mute is local to the remote or parameter (it allows to mute the actual max object, not the ossia parameter)

Isn’t that documented in the help patcher ? I thought it was...

**Comment by jln-** [comment]
Well, I know `mute` is local to parameter and remote. While it is fine and useful for remote, is it really for ossia.attribute ? I was expecting ossia.attribute to be just an interface to remotely get/set all attributes value with no other embeded feature. KISS.

But if it is not broken as of today's design, then fine. This is not release-critical.

**Comment by bltzr** [comment]
> Well, I know mute is local to parameter and remote. While it is fine and useful for remote, is it really for ossia.attribute ? I was expecting ossia.attribute to be just an interface to remotely get/set all attributes value with no other embeded feature. KISS.
> 
oh, yeah, sure, I missed the part when you said it was about ossia.attribute
What should it do, then ? Reflect the state of the mute attribute of the bound ossia.parameter ?
I’m not sure that’s an easy one, though, @avilleret is the one who knows
If it’s not, I guess we should drop it from ossia.attribute
> But if it is not broken as of today's design, then fine. This is not release-critical.
> 
agreed

**Comment by jln-** [comment]
> What should it do, then ? Reflect the state of the mute attribute of the bound ossia.parameter ?

That was my expectation, yes and what I feel would be desirable user-wise.

Unless changing this is a snap (but indeed IIRC some previous discussions, it's not), my feeling is we could leave this as it for now (or hide this exception) and keep this kind of refinement for an updated package release.

**Comment by avilleret** [comment]
there are still some attribute to test and `recall_safe` doesn't work
this is mostly because (like invisible) this attribute is called `recallSafe` on the Ossia side
`invisible` is called `hidden` and I made an alias so it works on max too

**Comment by avilleret** [comment]
test patchers passes so I think we can close this one
