### ISSUE TITLE
[ossia-max] range values defined as integers are ignored for param of type float

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#184]
This is also true for type list and vecnf.

Idem on ossia-pd @bltzr  ?

<pre><code>
----------begin_max5_patcher----------
554.3ocyVE0aaBCD9Y3WgkelUgMDfrmx+iopJCwMyUfMxX5RUU+uO6yvR6Bs
krAQUQAKeb3u66tuy1OGFfKUG4cXz2Q+.ED7bXP.XxYHXXd.tgcrpl0Atga3
ccrCbbj+cF9QCXWyjG3nXDINBUp5k6ExC20n1yQU0h1Q2E6AmUkO7MBcznru
QHq4F..5IipdynUxfUuIySsbeLiwnaGdUm4oZvJdbcaYlpe5BCMux38Oc6M1
3Kk5dRJfAp8I5V2W7RXn6QzLyDR9ur73rDQqVHMHMuQY3SP6sSxZxjrN9Rn1
lDhmU4tg7M+Wb69ZkMTFQ6dktgAvjcNgJt.BQe2xXDBWZUPmJmsLMqga3563
RVom9WT9HIMExGwPZYS7ZTqUccB1M9ZMxF+1eSTxyufLTxGkgf+WnfOyqJHf
vmPSVMI+DDOasz5TeQklm4FRRuVZ8junZc+1ZzjUWp+mHcPsi14HFxlBYFzt
SmAf1Muy.Vp74+zw.jsP2PZb70R+P+RqeHYIKf9gYL5dwTE63Oj8tuC78MJG
7pdc.RL8UDm7NLGVSbsP922TBVQm82lN5T85pwHZ7pN11hwPaOuyHjLiPIes
SdelLiOWftV3PlANIKDNjOAmrk.m3qThqXF3ju.3jOCbJVHbneBNaOCGeCEq
s8QttavY.B6NIOnfcAxifoBoeJbsHrl+nXz+MfEl11Rar8y8Zey9wB+kNvtM
OzR6FQtsKBcH+R3uAHlD7yD
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
The same way, param of type int ignore range values if given as floats.

**Comment by bltzr** [comment]
nope, that doesn't happen on pd, because pd doesn't know the difference between int and float :-p

**Comment by avilleret** [comment]
fixed with https://github.com/OSSIA/libossia/commit/3f95176b94be8c9080700ecbfae4075902a38630
