### ISSUE TITLE
[ossia-max] changing clip attribute value not taken into account

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#187]
Clip values do work when set as object attribute but cant be changed via attrui or message.

In the example below, sending 'clip free' do get displayed in attrui but output by ossia.parameter ignore the change.

With build from f96c0d66f977b49fbe1fdb357fcdfd84a1c90f3c

<pre><code>
----------begin_max5_patcher----------
705.3ocyV1rbaBCDG+L7TnQmod.wGF2SoW6qPmNdDfrsR.IFgvwdxj28JsBn
3DaO4CmN8hs05Uq18G+2E8juGtPdf0gQeG8Kjm2S9ddfIqAug0d3F5gxZZG3
FtT1zvDZbf6+zrCZv9iR0CHZGhcnkUpYUnhinJ1FZe8ju0bAqT1KfMPFL1pX
cl3Q0boXsxrUWxrJaQX.JJLZQZ.Jz9ayGneOrIQeCWTyzPJEMFIptbGWrcdT
hfnDECekBwIN9z.I60iQJbvJuBJIYw8eirbL66zGqYfcr0vy991OB9jXyT6U
HA6QTYMuEsmV2yVf9gVq3E8ZDWf5aqnVbRKKkpJS4UezZlZbomirNIjZjl9.
SXrqkfi8hyC8jOD+Hg41mBC7KK7cwuraC+ZXcczsrWwO.aaTro+4B5ojPmFX
0nV5JBJxkABIAzkDxRKQRicKtHPFQqyj9XKyEFLdZCyXU9sAUapklrXhGTEs
goYp0LAsvE1v2oLXnpiiVY+xICtRUStXUGfvETw1yV8SMZajpFJbxY+eyinn
7uPdj8UwCyzFS7eUmjrqiSWLgGDUbbMLOBcmMkQFLR0n6Tl7kY5cPQKP2Ace
ER8N7Gifj7kfvJk7FQXorVpbgHbwp7UjzLaibRzxjLBzRGGkmXGVMKTmk6mk
4jaSGna37UYh0koAX3KCpjjb2H34uB6lMwIJ85ELrG3UHu3NBPlZseJE5j8p
xwSb.nn+lpUrNMW.ilm4yRmOmkyu0yI6MbNjav4j+O5brOX9.Gj64EsscOS0
M3LbFF848tFmkAvRtvsLFVpX64i9mBVnJiRTajg8Jmr3PtafDtQVwTBi71p1
7sUm+f74EZDgYPBr0eRajMz063aMk91clayrVBiQbhO730DOAIlqwXdM9r98
H26rGuNHzf6J8fAzpLaXlN1YtwDYHWCGHj+y9+wonbof
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
Did you try "clip off" instead ?
Enum values have changed this afternoon.

**Comment by jln-** [comment]
This was before a naughty boy change 'off' back to 'free'...

**Comment by bltzr** [comment]
also, values are not reflected in score
this happens only for range and clip on max, and for clip on pd
all other attributes seem to work well...

**Comment by bltzr** [comment]
clip now works in pd

**Comment by bltzr** [comment]
fixed by c390055f fixing range and clip
