### ISSUE TITLE
[ossia-pd/max] there is no default range any more

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#188]
- [ ] pd

- [x] max

**Comment by avilleret** [comment]
<pre><code>
----------begin_max5_patcher----------
357.3ocySFsaBBCEF9Z3onoWyLTTzsckuGKFSAOp0.sj1hCiw280dJnyskMM
YYY2.472+d9O7cBGiinEpNvPIOSdgDEcLNJBk7BQ80QzZdWYE2f1nqqTx1ZZ
R3n0JcM25OXZuh6PgrBrnaVuXC2VtUH2rTCk1PZrmFOJMgjwvW4oXQ1nTxh9
6HVg4oJ18PN8bez7ZvB5kfjWTAdGoWBV0ZGRNqW0XODrQG5Qvj8PCDFD2ADZ
AWtgRV3cbJN1+H4OmGS7HfkM6m4w3+w7PBu5FwglagNaXrMFAez44kncA.j4
9XINDxsj4kUhFRgxtkd2nCoEa5iHzxy+N1wn+F74Z1f4PqDxO9qDNrd8qAlQ
0pKGZW+BkbYZWAFqPxsBk7cdXAOe4J4VygcC4j+obBed7ll8f1zaFivs42oz
9xYIXoPFJGikZXuXv+DTgqc6Nqaw0pCPta5DZ3ppUfV1JvUcrO4SwuwlVZwC
-----------end_max5_patcher-----------
</code></pre>
