### ISSUE TITLE
enable and repetitions don't do anything (in max and pd)

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#190]
- [x] enable should stop the parameter from emitting and receiving anything

- [x] repetitions should filter out similar consecutive values

apparently this doesn't come from the pd/Max implementation, but from the lib, says @avilleret , so I'm assigning to you, @jcelerier

**Comment by avilleret** [comment]
it's better to add one ticket per issue, and one issue per ticker :-)

**Comment by bltzr** [comment]
it's really a detail, but repetitions should be placed *after* the clip processing, not before... 
because moving the number box over 1 triggers the output while, IMHO, it shouldn't

<pre><code>
----------begin_max5_patcher----------
391.3oc0TsraCBCD7L7UX4yzJdEnsmx+QUUjg3j3HvFYujRTT92qYMj1jRih
hTkZuXytd2Y1YrEG78nEpNtgRdg7Jwy6fumGlpOg2PrGsl0UVwLXYzhV.TRZ
f6HYaspEp3.dXzP1FFTtQHWuPyKAG3IIO8XX.IIOseK9zJ4sgdDKQ3UEaeHe
DcGzv9FtCDZAStldpEK4B4kbaf8UX4TZehi998KA2n5VUornNs5huh5xycp6
49sYgn5hmVcyFQekRWyP.xNgrlUyAtdAWxJbxH7m7BZveX+HMAs.msbc+H4+
jeH4uam4wIF3cfSGFif83owkvreQlq4MbP.BkzPBIyKqDMjBEr4dsyj3LzHy
lcM+LhdMG5tbGrGZkPd4uJvYsO+4VlQ0pKGYc3Nl74vtja.gj0aLeolHWMSd
obq7DcC7L6rZT5kbM9t5Wm37oIN5aFMqoYGWaF5F4z9JbqBKOO.CERWXBFp4
6Di0mhYXZ6iHv9BpU6tO6xRotVUVhkshAtsLez+CJ9zYH.
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
> it's better to add one ticket per issue, and one issue per ticket :-)

I will never do that again, I promise

**Comment by bltzr** [comment]
enable seems to be working as well so I'm closing the issue - making a new one for the repetition/clip thing
