### ISSUE TITLE
[ossia-max] : multiple parameter instances created with {1..16} does not support default values

### ISSUE THREAD

**Issue by reno-** [OSSIA/libossia#191]
Create a parameter :     
    ossia.parameter color.{1..16} @type vec4f @unit color.rgba @default 1 1 1 1 @range 0 1 @clip both @description "color of the cell"    

Expected : all instances have default value : 1 1 1 1
Result : only first instance have value 1 1 1 1

**Comment by jcelerier** [comment]
okay, it seems that Max doesn't like having an attribute named "default". it works fine when renamed to "defval".

**Comment by jcelerier** [comment]
makes sense, "default" is already used by CLASS_ATTR_DEFAULT.

**Comment by bltzr** [comment]
thanks for fixing this!

the strange thing is that it *used to work* with 'default' in ossia-max, and also, for years, in Jamoma - so I guess there must be some interaction that caused this to stop working (and probably a workaround to make it work ?)

if we cannot have this attribute name back to being 'default' I would recommend that we choose a better name than 'defval', then... what about 'init' @jln- @reno- ?

**Comment by jln-** [comment]
My vote would go to making 'default' work again since it use to. :-$

If impossible for whatever reason beyond my head, then yes, 'init' sounds much better than defval imho.

**Comment by reno-** [comment]
I would prefer initial than init.
Init sounds to me like an action.
I can init / reset a parameter to its initial value.

**Comment by bltzr** [comment]
yes, initial is better, I agree

still, that’s quite strange that this used to work and suddenly stopped working...
