### ISSUE TITLE
[ossia-max] [ø.remote] besides [ø.model] is not registered properly on loadbang

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#193]
to reproduce :

- create a new patcher
- add `[ø.model foo]`
- add `[ø.parameter bar]` 
- add `[ø.remote bar]`
- send some values to `[ø.parameter bar]` and `[ø.remote bar]` they should be talking to eachother
- save the patcher 
- close it
- re-open it
- they are not talking to eachother anymore

**Comment by bltzr** [comment]
that's strange because I have been doing this a lot of times, and it worked, see attached patcher... maybe that comes from who's created first ?
[testMute&Co.maxpat.zip](https://github.com/OSSIA/libossia/files/1288935/testMute.Co.maxpat.zip)

**Comment by bltzr** [comment]
this is probably related to #223

**Comment by bltzr** [comment]
I've tried this several times, and that failed a couple times in the beginning, and now it works every damn time I try - so this is a little bit surreal

**Comment by jln-** [comment]
Same here. I've been trying to narrow it down for an hour and now I cant make it bug. Definitively something weird somewhere... *head scratching*

Probably a stupid question, but doesn't hurt asking: could it be related to the order ossia.device and ossia.model are created/saved in patcher ??

In the patch below, the view did not bind to the model. Then I tried once removing the top ossia.device: the view bound fine. Then tried putting back the device then removing the top ossia.model and the view bound fine. But now with both ossia.device and ossia.model it seems to work !

I did the steps above a couple of time, saving and relaunching patcher. Not sure which ossia.obj I removed first, though.

<pre><code>
----------begin_max5_patcher----------
842.3ocyWssahCCD8YxWQTdlEEGxEX+D1egpJjIwj3VGajsSJnpte6quBAHs
.ZoZ2G.6LyDOy4LyX67dvjn0rcHQT3OCeJbxj2ClLwHRKXh64IQsvckDnvXV
z5sPYYChGM0prGidqGKvqwDrbu1DfSCayFARZW63YwS0+E9rSIgU9JpphCqE
kbFgnMK1oqjfKeU1vYc0MCkinv0DTykufUQ+kJVW2xpPZIIdILdkJ3GXiAOX
Z8JNpzEsofk53MII0Lrbtd.jsbP7S6ZwTBRJFhXbkghXqe4GfXOAQgslHHRr
mJalo4qYJFU41niqEqS5WLebA40tDSTOCWhlAhBeVq5if.8eSuwDFE8lJf79
Rh1IsAoPfgyzzCIrc+JSv4MpjQXbehCjjktTm7JVlGWrPOawxT.PMCLfP9bZ
DjmNKSMj3H06fESlONG4MUH2Srjq2NqQx8aQNt6afzpP8p7gl01zt5r1gGL0
kjant742M0U7Oh4ZQBArFcA0oaCDagkGzLBpK.KrEL45ghq.5jQ55.+eUurk
ioxu.vKx.1zbldXd5cmkW706gL.uONPUAK+czUKcUk7FLUb2Iw7uSLQv8nY0
PL8.D5g7CaQeT6SfmuNFSyh0smo1p1442AHyNt5bk2kH9J6oXCSzmR.YeVIq
.WSgjnoCmo+sgvzGxngkPE39PS.6QUqfRIGutShNNS33MGwooFRGhswK1KeX
PSXz5wnuDO8ch0hFFW9kr8Il6wX7H5ZU7qV2OJz2sXL8PScP9nZwTrDCIWx4
iYkklMNxShmXVmxrCUkoV8lxR+viouScXi4T5P+0AtZ847kIlJyXvcuwR53M
gI29FoWTUdxFql.QUAPO+1mFznkeJAIXc7R+R6NeK7HbpPBIlBkXFcfMKr1L
ZJ3V8S1M3m7Gje.2fe.+k9I8FvS1C.Oo2.dxd.3Qej+UATwE.xV+A2tsGwEN
iM9P0J9h8FbESMOho1Gmadjizeri09TiDHW08IUsdcbaGwtE1SvhzWtlS6vl
Vr.M5BbcNmUyeXGweAaYsvUM3ZEzqajp8oYbH0ecJE51.6HxSoDXYIhJGbwS
f8isxlZ+rKyUMsPepiZ4pW37V3nV0Jah0XGCE7QvevAKW0M
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
> 
> could it be related to the order ossia.device and ossia.model are created/saved in patcher ??

that’s not a stupid question: that’s exactly what I noticed previously
I could make a patcher break or work by sending ossia.device to the back or to the front (which conditions the loading order)

but with this patcher, I can’t succeed to break it - which is maybe a signe that @avilleret fixed it ..???

**Comment by bltzr** [comment]
should we close this, then ?

I'd say: yes

**Comment by jln-** [comment]
I dont think it should be close. I had this very problem during the last hour.

**Comment by bltzr** [comment]
ah OK, then yes, let's leave it open - I understood you couldn't reproduce it...

**Comment by avilleret** [comment]
since the behavior describe in the very first post now works both in Pd and Max, I close this issue
