### ISSUE TITLE
About using RPC mechanism

### ISSUE THREAD

**Issue by theod** [OSSIA/libossia#20]
this is the continuation of the discussion opened here : https://github.com/OSSIA/i-score/issues/128#issuecomment-177871072

**Comment by theod** [comment]
especially does it means this (capnproto for example) will be a new protocol to add next to OSC, Minuit, MIDI, ... ?

**Comment by theod** [comment]
adding @jcelerier and @reno- explicitly to this thread

**Comment by jcelerier** [comment]
I feel that we should reopen this the day where we want to actually implement a new protocol absolutely not based on OSC and its legacy. For now it does not seem critical...
