### ISSUE TITLE
[ossia-max] path with ~ doesn't work when saving presets on Max

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#200]
this is what it says in the Max console
ossia.client: Can't open file ~/test.json, error: ios_base::clear: unspecified iostream_category error
print: preset save 0. ~/test.json

**Comment by jcelerier** [comment]
yep, ~ is something that is expanded by the unix shell but is not a "standard" file system thing (for instance it does not exist on windows).

**Comment by bltzr** [comment]
so I guess we'll manage this in Max (with conformpath) and I'll close the issue
