### ISSUE TITLE
ø.client messages to fix

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#202]
- [x] disconnect -> crash!
- [x] getdevices -> #198
- [x] update -> that doesn't do anything (still changes are updated automatically)
- [x] preset works 
- [x] help -> works, but why not just (connect)?

**Comment by avilleret** [comment]
update does something, but with Websocket tree and attributes are automatically updated on changes

**Comment by avilleret** [comment]
afaict this seems to work fine now,

@bltzr could you still reproduce some crashes with disconnect message ?

**Comment by bltzr** [comment]
nope
