### ISSUE TITLE
[ossia-max] remote doesnt work with param of type impulse

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#206]
As stated in the title, ossia.remote do work fine when binding to parameter but not if the parameter is of type impulse.

I'd expect being to send or receive impulse to/from parameter

<pre><code>
----------begin_max5_patcher----------
730.3ocyX0zbaBCD8L7qfgytd.AxX5odtcllK8VmNdDXEGkAI4QHRsmL4+d0
mNNNNM.Fm1CAMZyxt58X2mj7igAwU7c313nOG8ynffGCCBLlzFBbyChonc0M
nViaw0bJEyjwyr+OIdmzX+627ina9l27VAtU4ERR3rUBbszlhEkkySlEsHOQ
O3eD8K2a0J22fMQ6PbPx56HrMmKFo5gTnIJfiCCqiRXMXoYAm5LRVaBLu59O
AVF+rm7No20DswmBC0OlcgzwyTQOAEPCCXV1nA0hoCTUcRIm4imMXx8aw10Z
bEhsI9vB6M9TCA1OSEKG+m5WFCPt+Y+IEv4IkzqMoLH3klOR3kVLcvig+sJj
upNl21RPyEXJWhin6WQna6ZZwuIMDOy823nh7h4PU8uZPyEfgvEommKxFAWH
4a1z71Xjn52eux+7RSmLzpR8px+sHAhhkXwJLCUY4mjgPX93mUpIrQT6.+vK
cp37FLhckJcbLQZ9xgW5LcUNSuHQZ4BqHwX0.yx9eVCzCuhwpAlA9fJjOzxd
jLXzWznOpWhhiiWrBhfyHHVya3BqyIyKWVBfKzZL4oE4K.F0lrzk45VhgvlI
mmMAigM6nUXwekTN4jDWpnnizfEPyPxfUB.voC9CZSjoB4IisMBj8unMxskf
qMRO6JzC42iztOw0uGBj99EQlfE2PXmd4KCLz1eI+1x6D0dpvebmnmWSqwsR
BybHjibRe7WsSm8aXuyTQOxje4bYYpGIBNA4A1G.MA4Quy66lHsh6kmoj9jo
onZ.zGLAlB1CzqJ7WWOXasPa29.Vz571jDkH081t8hYloDlcZlYp.+.w6OzX
AITJJRkbRmvp0rao8R1wT9Zrf0QbJjJ3E5zjNocloz5Lu5WQTNEs5NxFE12b
mDudEWn18ysAgBd2h5ZjujSP00pqVbjHk6xDP2MJLpRVnOywsB0Kbp3XLUEY
h+GCPyPgOE9Gh+MI5.
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
you're right that it's wrong
