### ISSUE TITLE
[ossia-max] What is at_mode supposed to do ?

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#207]
In the patch below, I see no difference whether parameter mode is set to bi, set or get. Is it broken or am I missing what it is supposed to do ?

<pre><code>
----------begin_max5_patcher----------
859.3oc2X00biBBE8Y8WgCOmMi.JQ2m5y6egc1ICIglZmnlAIcSmN8+9BWHe
zrltDi4itODY.w6w6gCdtj2BCPSpWKZPQeO5mQAAuEFD.CYFHv0O.UxWOcAu
AlF5wE0UqJQCr2pdkZgPodcovFCDZPDZBuZNJ5Wto7XsrjqL2l4FYoTzHpTb
UQc0XoXpx9rLLdX7fnDZpoI1cYabVxk7RgRHGKp3SV..F6tWi5U6.Hz1Yql9
TQ078ie7Ha7yMMo..DxdHnyqhJc5.IJ1MXwLHt0Sd9aIoncyzl4vTIlAeOLz
bYfmzXk325PtIdJwZkElllB9PonrVIhJecrls4J5mx1vus4vovDz7LSC1R3m
FUvZmJncfJtbJJRb7vT8JdB4xnnHwTPQYieWTTjqjhZaptSTE8fgjifNQOTV
OSDMWn9bo1oIy1POXngjQ9K9YZ8hZocxwCyyxIoLyRTBdTBi.KVTbVhdIDeJ
jJs+HUtRIWUbbRYmV5HJvTpQARyZWA5GMlxfcq1Xf8UlYd0gPaVZQsPSIsSS
36psvLL7MJZR7ExTfBrJkLpqagiuMlBjd2TvxDjLVmMEveMLEfLihuPkYPzA
1rkmf6nhhN5lYJPZwTnomMErzCI2o1vWGSAZ18jo.7MMRZ5YXJvx.Zjg6USA
Z9WBSA6VXrM4u.lB378heW1By5O0VePi8zQmx5LebiN4Tu6Q5DFjXaS1oyD2
YdjmsaGwVUJqyGA5+qcJtpKx5Z4jzal2eKV+SJ5UmemTwUmIK6537StAF+dd
tNfAb0a2WN3DObvADPKJpN7u9CdKMi+QRnodkb5lrzoRi18dNSznJp.S58lS
xGmTsblPdbh2ajS8AZ1k.5Ch5Qf189cdHkbB764gjWqjjd.Ie.xTjdaqa3qf
jA2NzwmG8h8A539fdyOA987PJyGjF0CHQ7g7tRRSxkPdPx8G4yKC8QGRY8AR
9rYih+26ysdT7kKeQHabONfp1R9YaUBiF.cKprcoPWo3khMyOEFgK0NuJss6
Jo0Sdcl83YfEprR6nawVmugNu6C7Eqz0JAO5O3k0k7wOULWSFyeRIlMtVpqo
z4Dqy2G4qVn9HIwmNUeH18Jtwcr0T2YWgpYro9.GYK0OvgEQfJ0QtXipyvPg
uG9G0StXVA
-----------end_max5_patcher-----------
</code></pre>

**Comment by jcelerier** [comment]
it's not supposed to do anything, it is only an indication (for instance a vu-meter should be "get" because there's no point sending messages to it ; likewise a "play" message should be "set" because it doesn't have a "value" that you can look at, you can only send it messages.)

**Comment by bltzr** [comment]
well, actually, it does the same than this:

<pre><code>
----------begin_max5_patcher----------
774.3oc4XssbaBCD8Y3qfQO65QW.YneB8WHSGOxXEGx.RdDhT6IS92qt.N0t
w1JMDOwtOXCr5xt6gc2yJdNNBrPtg2BR9dxcIQQOGGE4DYED0+bDngsorl05
lF39ZonqALwODSHjZltRJbCJjB9vPs5s0bmzAI2KUMLsUDsWhYmjc5Zt1s23
doqY5xGpDqlq3kZusQgylBmjjRJrWxf1+w3ovje1ulpkNUIW732Ry.61HEqg
q4p4bAag2Zf8i40qd6ZtWCFqLArfIVA1smFqqRLXbHqrWhis+MIPrRv+kwfF
rFMeiya.ONUwajZdRy14F3joIGGy1GgROKBQJbWPjrSBQTvofgc+FOnX+vlQ
M1.CItXiTb.wF3qfXCcmR79iMB.gPtK3b7eAQkxZoxOY3zh7BbFch4tTzrTJ
1dGjfxSyLAVGAWImNfZ7vMlVq5pNNnXG2InQtj+1HE5DHUF0kE4gHzYBlROt
S+Yk4bwJ3RbH.AOKfjJ30VAW7XTv0iP3bZHEbQ2REbQYSyrwFnyGaPl8kO1n
g21xV8ODbbdHBWzGifF8Jtj7ajJtzbGRQQATwkTbCWwE45sEQCIqh9UIq5Sr
LSeGs4gfGWcs7OFDP8ALXn+R9IQnaJBHru8LZHc7+ePlBF5Z9HOfd0He4ST1
YXu6bk.hXHdhXZ9nyGi+nzwtY.pqDG98XbtiU99nYqrSUNnigC0m7pssj2pq
D6Htt60ONhcRu4arP0DIKDMsu4HUK4N7EeATM5sUM7Co5C10inZ3kBeIGwIQ
eLUGhSRnifSZ+jAmGNwiglRCQSjw3E26PQibdQdHu2lMF9XQHZJ+BglG32iT
V.Nj2iWHODe9ZYdpC150OwUs8q1oSCk6idVsYSbOVI7ORbOp3OUMLeWil.lx
vbpMzlcJOS6FpuAJ2g6TBy4.8fqwai6YjOftRXXucK8GrFYCa9CUqLPwpGz7
kykJSSD8Gex3t2y5p06CQrxRtP+GjwNBan8Hh91bmtCymzC0JyBNr0.PiYmq
FvIKBE+R7uAWW1Jg
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
can we close this issue, then ?
