### ISSUE TITLE
[ossia-pd] find an alternative for commas in brace expressions

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#212]
while such things as [ossia.parameter /source.{1..3}/gain.{L, R, C, Ls, Rs}] do work in Max 
apparently pd wants to put spaces after commas, which makes /source.<1..3>/gain.<L,R,C,Ls,Rs> become /source.<1..3>/gain.<L, R, C, Ls, Rs>, which fails to create a bunch of parameters (it cuts at L)
adding "" around the address doesn't help
what should we do about this ?

**Comment by jcelerier** [comment]
> what should we do about this ?

fork pd

**Comment by jcelerier** [comment]
we could use '|' instead.

**Comment by bltzr** [comment]
that’s pipe, right ?

I thought about it as well… but isn’t it used in RE... for OR ?

**Comment by jcelerier** [comment]
>  I thought about it as well… but isn’t it used in RE... for OR ?

well, yes, exactly (actually the ',' is translated to '|' in other environments)

**Comment by bltzr** [comment]
so... that's just perfect ! let's do that, then ?
