### ISSUE TITLE
[ossia-pd/Max] presets don't like params and nodes at the same level

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#213]
it stops reading the preset when both are at the same level

**Comment by bltzr** [comment]
reported by @reno- - please correct if I reported it wrong

**Comment by reno-** [comment]
I've narrowed a bit the issue from a big patch, and I can reproduce it with this little patch

<pre><code>
----------begin_max5_patcher----------
3439.3oc6ct9iiaaD.+y69WgfyW2ygjRTOZ+xcIsHEEMsoHEEnHHXgrMWu5h
rjqj7d60f7+d4CIYJqGlVhR1aNc.mOeRVTy7iCGNTOl4Wu+tEqhekjtv3OX7
SF2c2ud+c2w2DaC2k++uawN+WWG5mx+YKhHeJd0GW7fXWYjWy3aNNMMve4d+
D+cjLRhwlfcFuO6y6IFuPVidx38I9QaIFPCDv38aHO8hengqgaQ6r2Oa8yAQ
aeLgrNSHNVP2kfGLfXH6eLM4+ODZIv3myOn3CYgjL1IQbDKV7.8uk6NXiPxV
8w2grJNQQG1EDQOJtx.OtQQaw2JJeqoYeNj2xKVv1vuc+8rOdPQNwHypCYYw
QcniHLXIB4hg1TMzaosKxwzipy..WYARJaIo+a+iO7mVzIAn+MHJ6HHdJNJK
M3+w+MbnViOdchmxd0GIQ9qDLAzH5L0B5ns4JRRGXChL47A5v9GLPMKiUTKv
FsNvZR60igSmCvRH6hyHFe8N+rjfW+58woe8ZRX3RXWzx0VhVPGKEGH01fI3
ELVxbLQxdCp9GjEz4PLKpl5XCbrPOX3wUcGg8hkD.pLBwpoQHlkZM62FQsH3
65CIA9gMxih1XcbXbhPT.KsL8Prw5fkNVd.D6KHr3aPIwoJCA0Ynr5RRxIWN
5nRXPH4ERRJCLG6Ytag+98Ra9NoCgw6OJDSmGJ2TPjXSlkaJg7RPwwaUtU+D
JzynD+PhP9d0tveKqYh2PRhNDvEEwFo872WzfE8SdbqSJK3+iovV0RxJkZjr
MLd8uP1HAEps6dRTPz9DRJIJyOKW3J2McpF+CgYOVoGFsrw8+j+ZRqGbic42
sXaRvl3HlPTA0rMWb5ni.whYxjUF9uHxeeCGL0dihkV1YJUIOjtxOg0Sj6NB
Uryr33vp6p73BIOkku68AQQmPwr38suyjfsO2wwtJltycc0178j93gHwdejN
vN6wT+WpR6L+vv7Q5Ua9W8iBnN7HYAht.DnbmBWxOmtNINLrh9J1yKMrmMTi
30jOErI6Y9IR1Xf9yC1WXDsnrWdSvVRZV0sk4uMs5VpM.ktoCqxGj9XFY29P
pVT8GTI9K4Qjx9Dqr8tlrr03L3ipbaY5REmxrlKQ4SZSyEbtoOaeJzlly3th
4Mx8fzWdIOWRSSwx7WExlYQIlB4ysJbdo.SaikPkXYUVAu9r5X79hnPxC4mF
8YYP9fhP+ATGfFuecXvdCpGimUhtXdbdlNNpax1JhQ.yd.Y0MHO5ZOLHpswz
bMks+loeZ7gj0EZSoPaTUsodoxBhJmp6mJGMdxu64fMaHQmNdaSPJaXnvEcm
pAWcaQONNa3gMAw+HeNoG+dRzgiHtX1yl0zUaoQoDVFbzc09ETas7N17PndP
ZWUBpB4YAgtrXoLglNHd3UlzufwzgmxDI+3fkQigKBByxF4Xg4eyEYhMYeCz
vghNdNAPOwYB34BrDeitIXkH4xiOJZa97zNGmrQXNjDuONoLnkkzE+IebGxh
2l3uIfDkUo65X+0wPoDtZo+x5yBwFVS6HBjailbJT1o5uJMKwesTj0JzeVoO
w01Bay4iK1zFvApKzAhv03SkfuowJcB44tb3s8iAQrvWIEmCvCRezTiVnO+T
QPaF+7nhMwx8+lvCjdRMSniskCSirKMM8XapvpZBD+e3Px9vdq.NrkyvDa5P
AfiqXDEcvEdJTfmBOjJMuRsFdWvlfmhSngR16SAcEHqnSpkzS9XaYaax4iKc
43NNhAHVXOyKfOIF4RwtO+sw61UYLZuzlzNXVp1NYgAuPVJVZSecp3Y5h3tZ
csccE9qcMsgfqrSEoeg+50T7UQpYyN4vcEZWNoQwniweLQXr+FdT7cOrHkDV
se4xNK6TsG8J0sngnMf8XpsAE0vkMyva53MZzw7XXlRahfnw+bPW+v3eRp0D
p6JElOJ53Gc46Dc87cdVO9ipYoX4ur34jWed2btAk35FUmjRfdiqDe6m8iFT
OA.4gsDW9cGSSjSdfXPn4zoDeWBgLPsfI1XS1e3wRXyBvd5Tfu2eK6JsOHUv
0BPCDl6ovFPU.dWhsGzaBGW+eHggweRc0ntWQrG.3dVWXHLjan43BcgbUFSs
BmdEE86YEkeQv+t3vMCxrj4OCv8Of8PPLWafxwmMpJQ7PBhVEISCAdDWgu5S
0qXcpslc+DDcz3sDFiugZOe9PjrrssN1zVXW2IYxf89q+kw8ZsrOXOYbCiNw
3cu6cMckMtnqJgCzBJhGBiAPdegMxyFgttQVOp89UIm5Nc0G6thWQGm7oD.K
sfXZzW7vHmrqx4onGLy9qE6Qyn+ZgdyYzesPu0L5uVnGOi9qE5smQ+0B8Nyn
+Zgd2YzesPu2L5mPzKdJGt12fjtVaW+zn4qtQuf2L0tbpkpmqlFFXZIO5m+b
yfsMqqjW.ZTQwSG9y3TpttrXiBDFpO5q1MdLUWW1kYr1AVMmw5XfUqI.q2Pw
w4ZYJluCZgAd76rO.YhQdWAzimsnGCrZOi0w.qNyXcLvp6LV0DV0yJJ4O56B
txdoq3q4muj+2HQ3OP02AArESKBscPhmANW.eMhieeXVheTJ+kPdTetJNDov
SGhJmibbTvhEr2Y7MOJdIRdzOKKIX0gLw6nnbBP3hdOtEV04uk1kpPWuT2Ge
yuu+3CGu1RoErLYPVZWIMFjUYRiABvKg4YMFGXs7ZQ6u.xJjxKPnFSrElZKw
V.+hHwVf839n.Vh7agnSx1aNwVLmXKlSrE8K4C.NSxC.B3IKLKt0IxaIVkjG
fbJyplqvVyb.nayzyv4HjI1bIFJxJR5CSv2ZXZcbD6gTkBnmMnGiwp33L4eH
KSMrN9f30gC0MREIWEt6cWt4GKi0c97UQMdVwgto76uWETasnkURT0O9njpK
Fgdhr3zOuaUbnZirc3YcEwLqCHqqXa9VKsqPCGfNu4l7nDM3S0blDoBFUNRG
hEoTQDbffC67VCbqi2shNX13G9v+5uTPukeLMNx38zUQrcKM7QC3kfRXtwGT
ColFLtUbZ9ld3p7zLZZLKF8knomHc3oSaNS22Z1bm36ikYCThZ4N8DqUY.Vd
naSmdboPEPvG+YBJ9ruYpL6Vo.3RofzVoCR1km1Apr8fnMjWkVg8jgr7HMzD
zbtNPCMwPS1eulHm60gblZjbBISkgnHQNutEpI6KpOILPv3LJbTR7c1Jm26n
FHUSya8Lw28vfkYVTwJIyrdOsjr9zfLiUTlaP4tZxLRUYFeyXavMSUx131gy
n2f1ypZZXadyHxPUMMtcnLTYKiaGQ1VUJac6HyVWhitKVlkCHKYi31sckUjF
bS1SEANNJhpcHHskNd+85c.WsBjhic4851AnVAR4G+v+9OqkBjxo26UXCkNj
9W4Tja8J01DVZ4y0ikEOvfxatew09wq06l9nVpMXWrkcjzTC1sJoqZMhkYSE
zFWOEp4HMUqQbufZMBbLAP1yAoEOUBpo9MXt1yhWzvpcQRNNxOSe0emctpnQ
FK9irO9p+I6SRzFwVDNezY8qQbKpY2qstnH+VQBAdGs9Al8z.BhtYLgjKu.h
52ipOjOTqpRSIHrujvEeqPBFAv.vYMArPKcswVNdpUjmZs.OY6znlildM+jz
waGV+GUc6Ao51SdmNadB+sjZ5N408woDi3z0+2CjjOeVD3fWZli.HnuV8V5q
qm27UuFWBbbZPj4PoVvidxwD11BlPxWxh5AMVOfwZ8NpJNtpHNU9MiozX6nf
3X4LcxisBxi8zIOXksdPSi7nf3.mL5Xoh0COVfIRfPHUDHW7zIPU7qzg4yzH
NPEvSegivQ8IOTvLA4jGF3SdPfq+P.29C.7oO7u70meREyQ.jyTobN4cGHGW
Mju5KVYey4o99TQb5Y0vom4z9lyJ8smQ5aIazWboFd391ewHp9lDHacV1Y7W
82Euy+wmC1RMV29bF6ZpvKSUc0qT6swAl+13b56gxfEuZEfm1LS5SQ2oi2Vz
K+EYpqLMvfwvoETGknfRIhCMIZxEKG0DNUJPNCV3jJDNmMwrpPyUsn2njdpT
gtoM8rkbWh5RZZK5dZua3ZEuF0FPpVAqYRFP9v8s8FEpTApYv1jUW46YeivT
nE20UOwDhzdNY8EWPY56Du8pPxbaMccMmV5v7QpXvnq1qrvunqFrxgbdWNsm
5x6HMCME9XTpPtLXyj5ErEECjaphZndwX4lT.kKzJJKfJUbUzj.VoHpntDdl
WcdMIbmTfTTV7TpnnnIYrZwOQooPOsNfzyZ.hdU.zaQEnVwJQYSDkJPICV.i
uz.q55r1iI9JKxHCPEJsL5cSreDl0U+ggVsHgziBDxfsVNlpGzwZMOVzOzgk
TSE3C0V4lZIvwIIpJszK0bA6XLYwDuJVkRfrZGifYNpCNhlwnNvn4LF0AFsl
wnNvHdFi5.i1yXTGXzYFi5.ityXTGXzaFi8DixEpgo4hm1VL+pKsyq.sghpv
WlTHs+WQBkRGsWZJSsMEJ8xuG4oC4RLnckqu9wF8aRP5PV56WrXxbFSpfIqQ
.SW43JTofBnaLhms1TAS1yXREL4LiIUvj6LlZAS8eUDJlr8upQM1C0Rkjn+f
49IIKecb+HkSL9Wb6QUqe69+O0kcLK.
-----------end_max5_patcher-----------
</code></pre>
