### ISSUE TITLE
[ossia-pd] crash when sending [get*( to ossia.param

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#214]
this happens apparently with all attributes

**Comment by bltzr** [comment]
this is not the case for ossia.remote

**Comment by avilleret** [comment]
it doesn't on Linux with b41f65a
test made with ossia.param-help.pd

**Comment by bltzr** [comment]
it still does on Max with c9ad2d3f

**Comment by avilleret** [comment]
So we should rename the ticket :-)

**Comment by bltzr** [comment]
I'm sorry that was in pd - I don't think there are get methods in Max
