### ISSUE TITLE
 [ossia-max/pd] max crashes when closing a patcher with exposed device

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#219]
to reproduce, 

- open ossia.client.maxhelp
- open corresponding device
- connect them together
- close the device's patcher

**Comment by bltzr** [comment]
it doesn't crash here

**Comment by bltzr** [comment]
update: I was closing the client patcher, not the device one - closing the device patcher indeed does crash!

**Comment by bltzr** [comment]
just got the same thing with pd (with connected helps for device and client) so I'm changing the title

**Comment by jcelerier** [comment]
I think the same also happens with python so it's a deeper cause

**Comment by bltzr** [comment]
deep down into the rabbit hole!

**Comment by avilleret** [comment]
can't reproduce in Pd with both pathers in the same instance.

**Comment by avilleret** [comment]
can't reproduce with Pd and 2 different Pd instances with steps from the first post

**Comment by bltzr** [comment]
let's forget about this for now, then...  wasn't that some general problem in libossia ? (also in python) - maybe @jcelerier silently fixed that ?

**Comment by jcelerier** [comment]
I think it was a fix from @pchdev related to websocket closing actually!

**Comment by avilleret** [comment]
@jln- or @bltzr could you please reproduce the step in the first message and confirm or not that it is working ? so we can close the issue

**Comment by bltzr** [comment]
seems to be OK
