### ISSUE TITLE
[ossia-Max] unit conversion doesn't work with vecs

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#220]
this is probably the case as well in pd

see patcher below

<pre><code>
----------begin_max5_patcher----------
737.3oc2XssbaBCD8Y7WAUO6xHwc5S4+noSFYrZhxfELRBWm5I+6E1EbbZSZ
vXHwSdvlQRK5r5niNKv9ENjUk6DFh62b+tqiy9ENNPWsc3z01grguKufafvH
apKrRSgbsPSVhiWVaKDV6CUBbhHjkM+b+Q2vUba9cR0s2nE4VLhvHO5R2DJb
wOj0dgwndzC2jQX2HUMHi2.Eh3nwU0MC2fJjTrtNkqgTrb08ekkQN.uluQXE
5aDJ9pBHGocikWprq4V9wSRyLiKHXp86yG6C3sR5mWi72PGAsMebwh1+VNPR
TI9USR1OSVwNKl3Fij6oEaJsB2pRizJKUdL2qpURqaNWaCV++I8gQ7oAI.w2
w+9m.u5SIuHOE7u7zH3kIQbEjjhpK1rot7Ye5TWlp6DZYNu37DXcjeuBKM9z
UX9W7JL7TjeRHJvhQAV5TZekNDAVkVXDJKuci738.Luxfs.Z2eGf9iRUNILe
Dv7Qrz4qvQzmki1eYBqaf7dbDcr0MXwW90MRSQwU37ItBOmi0onmZD6h5b8X
jjSUwFbGqWVNhhMrf4TV9JTSkVprjWeYECKmvHrtBkd5qpCkPeEoTHHwCCBd
QkzyoB5bREnJ4vggmdrj8LOunGcupUR3tUjG7yNoygHFhs1aWDOjBTQPT1oy
xLxPOl8w8nvAnk174nQeuJWFNSdS4kEk05dmo6LaO2G.FnbVVvX8jxtDsjfR
OL+QaIkR93MWvcZu8Zw5qud4sZgP0bcUQsn2ngquc03Os4CdHYQiciOYL9Iv
rSJjp+9y3.IXa+Om3LMTPd+Rp+cYceJIWKLVoBJXbbP9XPu3lyPQp8ax71HQ
mBjBG.Rs09OejhFBRwSARoCAI1TfzPTDL+oBI16BRzArlxl.fRFvJJchvgdx
3ftE7ppsBsoKX.hFC06K0sMSVBMkJrIT1gnEak8wGB8v0M1e1FuuZMZJsKFe
4FxlxlmYQUKAWtEsH+3h+z1Y2LJ
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
it does work in Pd afaict

**Comment by bltzr** [comment]
I confirm that it works in pd - I have added test patchers for both Max and pd

**Comment by bltzr** [comment]
actually remotes do convert from the input to the output
the thing is that they should accept input in the remote's unit, not the parameter's
IMHO this is  a bug

<pre><code>
----------begin_max5_patcher----------
663.3oc6WE0aaBCD9YxuBOdNKBCjPxdp+OlppbfSMtBrQ1Gsoqs+2m4LjksV
RnYzoMo8.f7E66699t6rcdZVP3V8dvFx9B6qrffmlEDPlZMDzMNHrRrOuTXo
oElqqp.EFN2+aHrGI6ZU4iLbGvpEFQEffgY2oaJXh7bnFYBysaYBKSppaNrZ
K9XIPKu2hpoRpJAj.i2YrVf46jpauw.4nOXS3KVNmEGsHx8d4Z5ia.65tkHK
7Q0169Le4QNW2f8dOp26Fv5Xj.kZ0QHj046z1OQcuXW2tlWlMq807eSIijB1
Nv.jTUVv1Brc16m.0YcTuhLmw2jcR4I8hjmUIdmyW8goOTICIO25hIVtVcOX
PnnsLxEnSRcTZzRhFYoiQpRFPpt.RqfGbt7Ub11r0hRrAc0D.19TJsG3oGS7
wZvG8N55dNDpmQFhOQASVBQ7zM9jJIJwwusLLfJDeApPUSIJskxBvLMbrOU6
JVvBAJNWihm2IQbO84d5OP9Od.h2GZ.5hDG+7912ebjmNry3MfRr0yh9tLq7
az3z+AEwXpoYUzXjP9+kvSTGtbTkg7n+NEwA1RSasRwBCTocapkqK0MlOwtp
QIwiOr6sk6KQxOw1abZW930qN01aada0MY5TjZiTMAmc466hSHtwihNEoV+g
exkOM+ia+4yzKdRqfmwGzOi6L.7B6p1TLcavosQaP8gulOhjd14OSiVVXoT8
qWXlft09OKZVG8y64TGFL9AvK.2A8J5ZUGMGWdhMzsndO3D8G.G9HvIaBvYy
HvIYBvIYD3DOE5VzH.Zyq.xW+Ipqc2B11MYBCW64cZS6vr4zPoxOLgFZf6k8
yOkrHLtVEz0mzX7cV6W4+S.gUZ2IfpFI0YMqE4Wl8cfQT3T0
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
again pd works well

**Comment by bltzr** [comment]
and that's the same with single parameters

<pre><code>
----------begin_max5_patcher----------
650.3oc6W1saaBCEG+Z3ovhqYQ1.IP1U68XZpx.VMtBrQ1lrjU028YebHMYM
gPSSqZkVjffcL9+w+74CmGCChJkaX5Hz2Q+DED7XXP.zkqifcsChZoapZnZX
XQUx1VlvDE6+MCaiA5WJZ1hLqXnNph1xLLERuR1WinUUrNChptuDQ0Htnqe+
aK5a4hFlAlZxtN6nlpUbw82oXUFuokRlMOFkfmgs2mW.eYaf90tWgW6sgxG9
FY9AStr2LL63CL3JYiT4mY7rEywKKhcO39j6eJIOyJH4.IzlsMLPkHWGOEF5
tE+FoFPCzJlhAzpoFUxPqzqe0.p.O.EqYuLeTBk8UhPfeC.n6s1IpRJVyTFV
syWxZ7WgyTFdNPo7ro.qzOivRv9s03dAqz8kZC2zardSLi6pgq2yGu0a11w7
1ZTTr8ZuEcD9RFwUKOE.V1R.eD.lIImFemgdI2DJz12X35FdMScMqwAWDKlr
8Zm4gsP7waUmmAoXhGEDOJNiOTx3PXeBy6XBZomGCtWV2cSM0POxd4+AFS1W
bHl.AdKvSAgj+ivQ7CmOI2PB9yLDOSJMoVyoyTrVoMolKQauB8idA2bXUxSS
6KS7QxtQ7EGxSFK61xSCzz2Sfzo3hWcIOenVRJr1HX7XKphwK38NtK+7IGG1
ncaovIGeKwUmkGjBebSwhw3Q90TBClnnFt3eObMXLt9OFRZ6xsZXMsy0B8r4
Tyr00ETCWJNXLo9wbxsgopiKovEEZ4MPHKFQjKnSwMRG7GfNjInS9MPmzInS
xKzw6+Q65rGVVuavfD1vwG7GVMOFZxE9lPRqHEaMeX7Pdc64usAOFajSux6l
uYg++OD0JsE7D8bHVKzo7Sg+Ezt.Q8N
-----------end_max5_patcher-----------
</code></pre>
