### ISSUE TITLE
[ossia-Max/pd] unwanted instance creation

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#222]
when adding two multiple params, such as:
[ossia.parameter source.{1..3}/gain]
[ossia.parameter source.{1..3}]

I get instance duplicates for the 'source' nodes, i.e. it creates:
source.1/gain
source.2/gain
source.3/gain
source.4 
source.5 
source.6 

where I would expect it to create just:
source.1/gain
source.2/gain
source.3/gain
source.1 
source.2 
source.3

I thought params didn't implicitly create nodes when they already exist... ??? 

<pre><code>
----------begin_max5_patcher----------
683.3ocwVssbaBCD8Y3qfgmoDIDW6mP+E5zwiBn5nLFIFgbpy3w+6UW.WrSL
FGCtuXytHztmytZOZuqi+y7cjVeuu68SOGm8tNNFWZGNc1N903ckavslk4yH
+g+7q9A1WII6jF2MBJS16sU99FhwcuG11ZJaCQZ1CXmyFrr7EJa8JAoTZyAX
dVHHvKJx7GJ1ZDB79U22PqL6qJE9VDZvty2J62df14AWW8OASDU0j1V7ZxGf
EtpRndkWKeqnjDldYDZS.46MDKR78Olym.9nKC9DnAtoIVTCGC7P3mCd3LBd
PHDsn.NFMnXCg4iVsAyGfuPOLuskhCavBbMQRD8E88vvPzgagHBtHY.uFY.y
Lr.LMaTxH5yIidttjugKraKHLt..KRCLOkCPE5mRfYowYp3n2+4iAmoo.nTn
kDrbA.LJWjOeiAFqw39OILADixlBhyV9y9L0Yf1FbIYQG.zCafoPmgFE0oK9
.f4RDqHUCjh7IngE+v0vPOsFSYKqPVxfl4qHjgdH5XwQO.gLaA+J5Xw+ekwt
4h+cnkYuOCrX7i0KjRlIV9anryudqIc09OkYsrTGp60X89WJWQZkTFVR4rgK
RcqDO3wEUSqZ3pYHcgLIJLQgbnYD.TQG8VG+.tnhHtb8+lxU3UxU8UFGrnig
Fr7gVeUcukA0fuXnuSTOgHGe8Vi7jAcFZiYmhlPwAsHsESozDuTkF3WLx2IY
mMEPmaWz8EozoDorODI6PQbSyaDQa2pMAQIr7pcNaVfwjxrlHiof7Fse8wFO
XgZluTMveqvpfrK0pr4WyUjIaKsiOUvysSo4rAw5qXZ9zefq403UuPWqv95W
jjpUbAl0qjqf2uwa2HOkSvkkDlbf7fQrAnOHYt77.8ffNtUn9fyk77qU6Lsu
qSyPtGb+KTCkbCJ
-----------end_max5_patcher-----------
</code></pre>

**Comment by jcelerier** [comment]
> I thought params didn't implicitly create nodes when they already exist... ???

no, an ossia.parameter will always create nodes currently

**Comment by bltzr** [comment]
could we make this rule that, only end nodes get duplicated, e.g.:
[ossia.parameter my/node/param] and [ossia.parameter my/param] will NOT create two instances
[ossia.parameter my/node/param] and [model my/node] will NOT create two instances
only:
twice [ossia.parameter my/node] will create two instances and
[ossia.parameter my/node] and [ossia.model my/node] will create two instances (not 200% sure about this one, but that seems the most reasonable)
would that make sense ?

**Comment by bltzr** [comment]
opinions about this @OSSIA/users ?

**Comment by bltzr** [comment]
well, I probably had some other [ossia.parameter source.{1..3}] laying around because this works with a clean Max

**Comment by bltzr** [comment]
This is actually what happens, so I'm closing the issue, sorry for the noise

**Comment by jcelerier** [comment]
... that's weird

**Comment by bltzr** [comment]
it's actually not so weird that it works as it should... sometimes, things DO work ;-p
(actually, I think we discussed this and things were actually explicitly designed this way somehow - I just got confused and forgot about it, apparently...)
