### ISSUE TITLE
[ossia-max] problem with the creation sequence of  remotes and models

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#223]
this works out of the box:

<pre><code>
----------begin_max5_patcher----------
1325.3oc6Z10biZCEF9Z6eETtpsiqKR7oyccZyNs8h8hN8tc6vHikcztfDiP
jjsYx+8pO.LXaHjrraxl5LiicjP5nyiNbNuh36lOydM6Vbgs0EVuyZ1r6lOa
ltIUCyp96Y1YnaSRQE5KyNgkkgoB6El9D3aE51+6e+Rqe6Odyat7ut7s+5kW
X88avWSRv+P8EVH9TJVek0sPKyHzTrPOufpFyQhjqHzcwbbhvrth.KcVXAhB
0uE.UuAcV5X8OUigrQOur0e3m.gslcVond5cZsbSXoLtYpcVFE53GEsP9IOf
ePTf5SNAvPOeosT1PMt6mOW8qEelHRbEt.asq7SEVaXV2v3e7hohNQZp.7cF
DNdOR33nnguq5G0m.R9.Ce5bYaJSZ350fYAH9TN1XNomaYuFQ2Y2r1GIU1x3
YHMNB5mSPuUKU6oPekaUAJ3oAUOAQvlYmixvBLOFSQqMqPmm.On3ajV6nvDV
QAAsjiyXBrUQ453L1Fb5cu+8KVd+O9yn3FyOHI0udrj7Dby0IpE2ftvg.Gv+
zjy8atnEefxqiFQvB.9BLZ46dthSLDCBcGDYtuVBShbTNMbk6HhSbdAFmrD7
0OPwMrEydnHEvqrHEO3CGoD8BLP4qeXhjTJf4FoQEXvvjfoKJYPpXzzZoIRL
gVHPzDo74d4wDvAnLipp9qIwJHbvHmdJ+BlNNjuOjHt.mvnarp4vH0x5zuuF
rpUlAP3fa4vg0xpmcLuxAq7P48pjT70XdAgQaw8Y1n77VMOq0PTX4CFIwgKZ
ZhPMM41zDWFZTOdulVQboOJjNXI2fjaCpEgqlFIF4zRRydjdCZd8DViE.zMP
gBWn4MfIFHvaOYj6l6RYIeDuoEDjQj4XJglykm6fJPhpkWS2avaQkoh3sLpn
f7u5UHPkf5D8uEkf6cvTYhAs68KbBJs1As2wIaXT0hnCrUMWaNo2YBr8a6L5
qfhxOwfk68RvzSmx.QQYwZDWsWTkZDV2ofwR61Uy3RwaEUcmSnzCnnfk2emb
xtqFXrqYxNyFZt08TDWRM8FKuCTDWfttKsEnzzpaI6N82hnDY4GrfX1BfNMc
ZJObUQBmkl1weM8b8I5wjg6FxFwUZC0NXPd4j75fH6lc4Mjc3BQ21DncEca4
nrBxlJWWcaZr.mkmJ8htWPmGNQ66Iam7pS6CUxejk86Y01WN6SKAn2pZAlf8
nSqBnu748qFXXEAypy6WkZ4IhwN0BNUcwlEfEhxDpMzCEKLffgOGv2OhiL5F
bfODicGfwOSL74mdvUlG1VzCQO3KD5oUjrWaxvb6KBy7LpVbCeHjA5GYsMTm
mD2pnUP+.yioLzK.peLktfnNOlxCX89xooDZe4Q0tip+SuITvJ4I0bqZ+1pq
mIqKHHzFwEuqIykUeKq4sE5XqJ0sI1TVOFIDbx5RgY41V41ip7iTKzZTZUwk
FwICUKZeAq46WuStj4IPhr9z.PecvV3pAO67+mTH6ousKXkNcuqi4nCd9mUH
eVg7YExeCpP1y8rB4uvZ7ppdbVg7Shd.vYExORl45cVg7qSExZ2sKDMBlODd
UxlOBZQsgVO.KXOvNRX9XsS3HrCveBLTvHLTzDXm5E6fFJbJLj6XPGbJrDbL
VxcJrDXLVxYJrjyXrD3HKYtw5fydoLxAm45fyac7Ys5+bVGdFKcZGSBfCtYt
IMwehxXYn3qjB6SUh6UYm3REhU+KfpO3SWlfRRjGwpUNaP02unEluoQs9VEs
nhsb4.NLSjclblI052zIKue9+A70f81N
-----------end_max5_patcher-----------
</code></pre>

while this doesn't:

<pre><code>
----------begin_max5_patcher----------
1419.3oc6ZszaaaDD9rzuhs7TZgrJ4xmxGJPQiCZ6gDfhbKofXI0JoMgbWAx
kN1wv+269fjhTVjl1l9Qb0AKAuOlYmuY1Y9FRc0zIFQrKv4FfSAeBLYxUSmL
QMjbfIk++DiTzEwInb0xLhYooXJ2XldNN9BtZ7O9mmAd6e8t2c1+b16+iyNE
7lT1RbxOWstb9kIX0BqFgVjRnIXtRrVkCtEwi2PnqCyvwb8wxyct6Lfk+h4l
hu7fxuflyMA+a4dHKUxkE8kSr7aHcVAuR7lUhOCmKN7HNgQanBeSsJBjx1r7
iZ4KMwXVBKSuXy4A9ltAAxE4X45E3oVtGz2QJD4Fk665oSkeL6ABq7M3KAaP
miAbFHBCxvmDUPR.uAOe8bf.gEVH3jeCTPWxpA6DBEGyJnJQ.evd.AtHsLKG
kGvUAP11c3A7ted.OsJrFlGvOvw1xQtHKGWyEJegIz1Et3QwCjiAqKtLG71O
.d+G9H3arrudpwHAqAMQ0Niqc5GUeR.nUILg1qNH5SA+xsXsNElOvHBQWaTa
.CDZVwxRQJLwqavB5rPEg.ck3TIZAOLZ0QR.XszyPoXNNKDSQQ5Sn48.On3u
Iz1MhWX44Dz7LbJiiA4EQgpDgW84OOa90+xuhBqUeuHo5u6JRd.by1LnAtAs
g8AbVtGF4r+gKZw0Rc2Z.AKVvWfQK+zyUbhFwfP6dgL6WKgIApB+vE1CHNw7
EXbxbqm9.Ea+FX1sEoX8JKRwAd6QJAu.CTd5CSDHkDvrUbpgV8Fl3MdQI8hJ
Jn.n9LjPy4HZrn4mNgiQ.FfAAM6dwu2.mNp9ZMdvv1cQDg4hVDnKAU3v.4yZ
1SiZJFZRKVYp85wg2RWBRoiyJMvRKTbUkjfOGmkK5cnAtOw.scaigmzXKRX4
KZZw9ypGhP0CYWOTF9bR09cpGEkIrQtv.KxzPxEdUDwkhQ.iYzBRsOR4flVI
vJXwBZ6o5XBp+xRGC34rCYDdy0Ir3uhW1.DDQjawTBsYGSsldIdEpHgGthQ4
4juqNgVx7SGX9UnXbmalJxKnLueOifRpLPi0YjkLp7PzBrkCWoNg04paeoow
nVAEs8.aV36E.SGSJBD4E4QnLounLyHrZRNikzdp58kfWwKmdKgR2CE4rscO
YFY8ld1aDSLYZexVMSdXAUOan3FHOLWzud60gRRJuR1V7WfnDQ0GLmncAPy5
I0UG1jGmwRRZYu5YN+.yrTDFGi+FYIeiRQMCFDKmrsJHxn1KujrFmyaOFGsN
u8H2HqfXnhnxqogbb51DgUzdAsdzRMuS1L4Uqw6qh+.q52wosqb1GlAPmE07
zA6AGlDPW4y6lLP+DBlTk2uL0x8DFaUK3PkEqO..DkwkNz84JzCegGBv2MDq
Kh.Mg2FFa2CF+LggO+nGr7YkFbanG7EB5oIlUyMoeb6QAybTzUrDM2bKPlU2
PVSE05owsHXAz0S+.i8c7fpmFmsUPqGX7dX8txoxmlaG4QUlib9C6DxYEYwU
3Vo+Fz1xD0E3DZM4hOUm4Bz0wZZShNFxRcKC0k0CQbdFIpfqOtMYtcmJ+H3B
EgRJKtTSNouZQ6JXMc24czoLOZTj0MEo6InyVm++DCYG00NuEpz81l5VGbbO
xP9HC4iLj+Ajgri8QFxOxb7Jqdbjg78B8zun4iLjuCXlsyQFxuNYHqL21fnl
v79fWIs4a.Zx2M1NTqCDS9tf.c8KOXvZxZHZxbLzDbHZxdLzj8PzDbLzj6.z
j+HnHuAnmfQPO9CA4bGAEEL.E4cC8nuXsWuWRUrWOW60u0M60p69r1uGKUZG
cBf8tLWml3uQorTT3FAw9DI4dY1oLACwxWATUiOsQDTbrnEqF4rK+kZ4V9y0
pwOpnYkHalXC6mIxHUHYRE+MUxxqm9ePcdZx+
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
This also happens for view - see bottom bpatcher of ossia.view.mahelp "Nested View" tab

had to do this to make it work:

<pre><code>
----------begin_max5_patcher----------
550.3ocwU0zabBCD8L7qvhyT.a9XgbqG6odH8VUUkAb20IfMx1r6FsZ+uWrM
jRRnsjjcUjVsX+rm4M5waFN453UxORjdfa.eG33bx0ww.oAbF2630hOV0fkl
q4wHG3k244aORQNpLv0jeQDM7CSGHUOzPLmLgv5a48pFhxjG3H5NZcMgMGoC
qp1QYa+ofTorUVVbPjOHNMU+.FEoefPAQfeLFiMwpG5H1.77d7HZsoJFp4Ok
OqTnrGqDM1YWW8e9qTDp3ssDl5Epv21QkfgeXvAt3drf2ypAJN.rSo5j2DFt
kp10WFLDe3Wu81u74vFZIWJo3PpT1SjgHT7TVanLR0PFLoNdk5ZzqQWgEaLR
YZrUQyzOR1LSXmodP3xx2LMnh2vE1TGEDiRSJ70KRRiJxMq1XwfZFdCx9Gn2
CV797dvnKl4qkHk3sjWHCkzAylrurkWSZBNACBPmuhRBJ2XWfn2pjTrnhftb
9hFNttDy1dMEgTzp8ElRYIgH6hYM9KBgYBSvdJ4v60e7jN7h7BTZltwNAtII
CoWEECySRGaw+GSdLixKrCzmF+75ap9uBmIJyjzm8QNSMowepZJ48hpINGMo
f+TV0DohxvJJmM6N5d6YWZl8YwWgqk570P8Ug4rUvbwUg4mIkKSc9Jn19hG2
0smHjigaXcng4NqEdiuYKkY2Z9BqmfrmNc+DCBVLXdUCN2dgsC4XVhmMzgFI
AqmNx8.ymc+MVSPIZ.
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
actually this is the same problem than #263 - which is unrelated to poly~ but due to the creation order: bound objects need to be created AFTER the upper node they bind to - this is a critical problem as it can break a lot of patchers

**Comment by bltzr** [comment]
so I'm closing #263

**Comment by bltzr** [comment]
this seems to be a problem for models and views, not for devices, if that helps

**Comment by avilleret** [comment]
so this one involved several bug that takes me long to track down, hopefully it should be fixed in the next commit

**Comment by bltzr** [comment]
that seems to be OK, I'll reopen it if I see it happening again
