### ISSUE TITLE
[ossia-max] sending values to parameter thru ossia.model

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#224]
In good old j.model, it was possible to address parameters in a model by sending parameter name + value at the j.model input.

It would be great to have this feature in ossia.model. It's super useful, if only when patching and quick testing

**Comment by bltzr** [comment]
also, j.model used to output values as they changed…

I don’t know if this has an impact on performance - if it does, maybe it could nice to add a mute attribute to model to, welll…, mute its output

**Comment by bltzr** [comment]
at some point, @avilleret mentioned using the [set paramName value( - I think that's probably better, at least in terms of code complexity...
concerning the output, how bad do you need it to output stuff (because, again, this has a cost...), knowing that the [namespace( message will output all params values

**Comment by jln-** [comment]
I'd rather reduce user experience complexity than code complexity :-) Does it really make things more complicated code-wise ??

Personally I really dont need ossia.model to output model activities (I always shut as much as I can with j.model for instance).

**Comment by bltzr** [comment]
is adding a prepend set adding so much to the user experience complexity ? or does it just change your habits ? ;-p

concerning the implementation, it’s also a question of balance between this and more urgent things, so I’ll let @avilleret tell us about that

personally I’m OK either way

**Comment by avilleret** [comment]
in fact, this used to work a while ago, at least in Pd, 
but looking at the code today, I'm saying to myself : how this could have worked ?
...
concerning the `set` prefix, I'm sorry but it's necessary
if there is no prefix, then you can't send value to the nodes named `priority`, `tags`, `description` ... i.e. to every node which name is also an attribute name.
And this is not possible, in a user experience wise. :-)

**Comment by avilleret** [comment]
duplicate https://github.com/OSSIA/libossia/issues/102

**Comment by jln-** [comment]
> is adding a prepend set adding so much to the user experience complexity ? or does it just change your habits ? ;-p

Well... Please note that I happen to think a little more than based on my sole habits...

It just adds another syntaxe element to think about, so yes, it adds complexity. But nothing unmanageable, for sure. Fine with me.

**Comment by bltzr** [comment]
> 
> Well... Please note that I happen to think a little more than based on my sole habits...

Sure, sorry for the irony!
