### ISSUE TITLE
[ossia-Max/pd?] add ossia.attribute object to remotely access attributes

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#227]
since the current way to get/set attributes remotely (through a bound ossia.remote's own attributes) seems to be suboptimal, @jcelerier suggests that we create a dedicated objet

it could be something like this:

[ossia.attribute /my/address range] 
inlet sets attribute value (and reports values to the output when receiving the message get)
outlet reports current value when: 
- the object is created
- the object receives the [get message(
- optionally, when the attribute changes (if that's possible/not too heavy)
  - in this case we could add a \@update (or \mute) attribute to the object, so things could be optimized...

opinions @jln- @reno- @avilleret ???  

- [x] pd
- [x] max

**Comment by reno-** [comment]
sounds perfect !

**Comment by jln-** [comment]
I like that !

**Comment by avilleret** [comment]
That's sounds good 

But how to deal with multiple parameters attributes ?
If the object binds to several parameters, what should [get unit( message returns ? The unit of the first match ? All unit one by one ? All unit in one list ? Nothing if they don't all have the same unit ?
This question applies to ossia.paramrter too.

**Comment by bltzr** [comment]
I'd say : just as usual 
I.e. address from right outlet, and value from left 
Then one address at a time, until they are all done

**Comment by avilleret** [comment]
I push a proposal that works just like [ossia.remote] without sending back value.
I also remove the ability to access parameter attribute from [ossia.remote]
So it's basically a split.

Could you test and make feedback ?

**Comment by bltzr** [comment]
@jln- @reno-

**Comment by bltzr** [comment]
NB: the current implementation has no 2d argument and allows to address (and monitor) all the attributes from the same object
why not...

**Comment by bltzr** [comment]
![o attr](https://user-images.githubusercontent.com/113982/30513838-5078385c-9b0a-11e7-9fcb-9c003c32763f.gif)

**Comment by avilleret** [comment]
What is missing for closing this ?

**Comment by bltzr** [comment]
Maybe that we test it ?
