### ISSUE TITLE
fix TimeConstraintTest on getPosition()

### ISSUE THREAD

**Issue by theod** [OSSIA/libossia#23]
there is a test that doesn't pass :  

QVERIFY(constraint->getPosition() == 0.25);

because the position is not updated when setting up the durations (nominal, min and max).
but this is also raising a confusion on what should be the position : does it supposed to be relative to nominal or max duration ?

**Comment by jcelerier** [comment]
> but this is also raising a confusion on what should be the position : does it supposed to be relative to nominal or max duration ?

for me it should be relative to nominal duration : else with infinite max it would not work.

**Comment by jcelerier** [comment]
let's reopen the issue if there is a problem with the current behaviour at some point
