### ISSUE TITLE
[ossia-python] : Crash when getting a value

### ISSUE THREAD

**Issue by reno-** [OSSIA/libossia#230]
From what I understand, there is 3 different methods to getting the value of a parameter, and each of the three crash python : 

```
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import ossia_python as ossia

local_device = ossia.LocalDevice("super software")
local_device.create_oscquery_server(3456, 5678, False)
foo_bar = local_device.add_node("/foo/bar")
float_node = local_device.add_node("/test/numeric/float")
float_parameter = float_node.create_parameter(ossia.ValueType.Float)

float_parameter.value = 2.5

print(float_parameter.value)
print(float_parameter.value.clone_value())
print(float_parameter.fetch_value())
```

**Comment by theod** [comment]
@reno- I look at it ! it is crazy that there isn't such a line in the example line ...

**Comment by jcelerier** [comment]
I've fixed it and forgot to close the issue, sorry ! (I changed the python methods so that they don't use ossia.value at all but only work with native python types directly which solved a lot of other weird crashes...)

**Comment by theod** [comment]
great ! thanks
