### ISSUE TITLE
[ossia-max] ossia.device [getprotocols( and [stop( messages should be improved/fixed

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#232]
- [x] currently, getprotocols only outputs the number of open protocols, such as:
```ossia.device: protocols 1.```
also, it seems a float is output, while it should be an int

- [ ] I haven't found a way to use the (stop) message, e.g. sending (stop 1) or (stop 1.) will print in Max:
```ossia.device: Index 2091928592 out of bound.```
(which is not very informative)

- [ ]  in pd, that's a little better (we get the ports of the current 'expositions', but there's no way to stop them either

**Comment by avilleret** [comment]
[getprotocols( becomes [get protocols(

last 2 points should be fixed now
