### ISSUE TITLE
[ossia-pd][ossia-Max] ossia.client still outputs Max:/ as device name 

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#233]
when it receives update or connect
i.e. create Max:/paramName

- [x] pd
- [x] max

**Comment by bltzr** [comment]
also in response to the (getaddress) message

**Comment by avilleret** [comment]
This is an interesting issue :-)
I have to investigate from where this come.
Pd is affected to.

**Comment by avilleret** [comment]
should be fixed, test need @bltzr  @jln-

**Comment by bltzr** [comment]
yup
