### ISSUE TITLE
[ossia-pd] not loading on ms-windows

### ISSUE THREAD

**Issue by Lucarda** [OSSIA/libossia#235]
I can't make [ossia] work on Pd/Windows. I'm trying v1.0.0-b3 32bit version.

This is the list of Dlls that ossia is asking:

API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL            
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL              
API-MS-WIN-CRT-CONVERT-L1-1-0.DLL                      
API-MS-WIN-CRT-ENVIRONMENT-L1-1-0.DLL                  
API-MS-WIN-CRT-FILESYSTEM-L1-1-0.DLL                   
API-MS-WIN-CRT-HEAP-L1-1-0.DLL                         
API-MS-WIN-CRT-LOCALE-L1-1-0.DLL                       
API-MS-WIN-CRT-MATH-L1-1-0.DLL                         
API-MS-WIN-CRT-MULTIBYTE-L1-1-0.DLL                    
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL                      
API-MS-WIN-CRT-STDIO-L1-1-0.DLL                        
API-MS-WIN-CRT-STRING-L1-1-0.DLL                       
API-MS-WIN-CRT-TIME-L1-1-0.DLL                         
API-MS-WIN-CRT-UTILITY-L1-1-0.DLL

And when I supply them I get: "Entry point terminate could not be located in the dynamic library VCRUNTIME140.dll "

**Comment by avilleret** [comment]
Hi thanks for the report, 

could you try this one : https://ci.appveyor.com/api/buildjobs/le6koqxu84pmtfi4/artifacts/install%2Fossia-pd-windows.zip

thanks

**Comment by jcelerier** [comment]
This looks like these are the windows 10 DLLs, but they should also be here on older windows if they are kept up-to-date with Windows Update

**Comment by jcelerier** [comment]
maybe the pd externals & such should be statically linked (/MT) with the vs library ?

**Comment by Lucarda** [comment]
The above one starts asking me for:

msvcp140d.dll
ucrtbased.dll
cruntime140d.dll

then it ask me for:
APPCRT140D.dll  -- this one apparently can`t be downloaded so I'm stuck.

The normal procedure for win32 [externals] is to place all .dll dependancies in the same dir as the external. This allows to include the needed 3th party .dlls in the Deken Package.

OTOH there migth be some -flag for the compiler that reduces these dependancies, I've seen these testing other pd externals.

Let me know when there's a new one to test.
:-)

**Comment by jcelerier** [comment]
ah, damn, it seems that it wants the debug version instead of the release version of the dlls which is why it doesn't work fo you.

**Comment by Lucarda** [comment]
Further more:
Analisys of "ossia.dll" with "www.dependencywalker.com" 
Missing dlls (testing on standard win8.1 machine (should work here BTW)):

API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
MSVCP140D.DLL
UCRTBASED.DLL
VCRUNTIME140D.DLL 

:-)

**Comment by Lucarda** [comment]
> ah, damn, it seems that it wants the debug version instead of the release version of the dlls which is why it doesn't work fo you.

Drop me a line for the next test.
:-)

**Comment by jcelerier** [comment]
hmmm... this is weird. I just ran dependency walker on the binaries and I don't see the ones you posted: 

MSVCP140D.DLL
UCRTBASED.DLL
VCRUNTIME140D.DLL

Instead I have : 
![untitled](https://user-images.githubusercontent.com/2772730/30549253-96c3807e-9c94-11e7-9d2a-46f690744d44.png)

**Comment by Lucarda** [comment]
Looks that your analisys is **not** from the version **avilleret** ask me to test above in this thread.

This are the diff (the left one is the same as yours, the other is the "........le6koqxu84pmtfi4/artifacts/install%2Fossia-pd-windows.zip":
![ossiadiff](https://user-images.githubusercontent.com/25239522/30550325-8025eed2-9c6d-11e7-832e-2c769d1ccfbc.jpg)

**Comment by jcelerier** [comment]
could you try installing the MSVC runtime ? 

* https://go.microsoft.com/fwlink/?LinkId=746572 if you use the 64bit version
* https://go.microsoft.com/fwlink/?LinkId=746571 if you use the 32bit version

**Comment by Lucarda** [comment]
I cant try but that's not what's expected for a "normal" Pd [external].

**Comment by Lucarda** [comment]
Could you try doing a makefile for MingW using the  ["pd-lib-builder"](https://github.com/pure-data/pd-lib-builder).
This is the normal Pd [external] compiling way for w32.

Is this possible?

**Comment by jcelerier** [comment]
yes, everything should build under MinGW. @avilleret what do you think ?

**Comment by avilleret** [comment]
I didn't know that pd-lib-builder is officially the normal way to build pd-binary.
It might be possible to make a makefile based on pd-lib-builder to build just pd binary and link against a pre-compiled version of libossia and I will appreciate PR for that :-)
But the lib itself should also be compiled under MinGW for that to work.
And the last time I tried I had issue with cutting edge C++ feature we use in libossia that are not supported by MinGW. 
The only time I make it to work it was for building Jamoma for Pd external and iirc I had to build MinGW myself against the right version of GCC and blahblahblah... 
So @Lucarda be sure it will be way simpler to download the free version of Microsoft Visual C++, CMake and follow the [building instruction](https://github.com/OSSIA/libossia/wiki/Building) than trying to write a Makefile that uses MinGW :-).

**Comment by jcelerier** [comment]
@avilleret I tried building with mingw (5.3 IIRC) a few weeks ago and it worked if I'm not mistaken

**Comment by avilleret** [comment]
Also @Lucarda concerning the debug DLL it was asking, it might be possible that Appveyor (who build the archive I send to you) build it in debug mode. Which is indeed an issue that should be fixed  now. :-)
A release is on the oven, coming soon but if your impatient (and since the release might not work :-) ) here is the last one : https://ci.appveyor.com/api/buildjobs/0b8eiqu7rcrdq2n2/artifacts/ossia-pd-win32.zip
Please tell me if it works !

**Comment by avilleret** [comment]
@jcelerier : you're living in the future ! 
good to know by the way

**Comment by avilleret** [comment]
hum... I'm sorry I was referring to cross-compiling ossia-pd for Windows from Linux with MinGW-64.
This is not the same than building on Windows for Windows with MinGW, which is indeed much simpler :-).
So maybe we can setup a MinGW build somewhere for people who wants to write a pd-lib-builder based Makefile.

**Comment by Lucarda** [comment]
OK I was not saying is impossible for VS to make a workable [external], I was suggesting MinGW+pd-lib-builder because some guys on the pd-list asked me to compile for w32 and thats how i helped them (succesfully).
But looks like OSSIA is more complex than a normal [external].
I'm about to test the new APPVEYOR.

: )

**Comment by Lucarda** [comment]
This is what i get:

![1](https://user-images.githubusercontent.com/25239522/31036705-dad61724-a543-11e7-9376-60a669099219.jpg)

and with "Dependancy walker" the next .dll that it wil ask:

![2](https://user-images.githubusercontent.com/25239522/31036736-00481f48-a544-11e7-81a1-d4fb9d445889.jpg)


there must be a -flag or something to prevent this needed dlls. I remember having this issue when testing https://sourceforge.net/projects/jygsdownloads/files/abl_link~4windows/
and Jean Yves fixed it.

**Comment by Lucarda** [comment]
@avilleret 
I have setup MinGW like Fred Jan suggests here:
http://puredata.info/docs/developer/WindowsMinGW/?searchterm=building%20with%20mingw

With this setup i have succesfully compiled some [externals]: cyclone and others. Always using the pd-lib-bulder.

**Comment by Lucarda** [comment]
@avilleret & @jcelerier 
If any of you have a “pd-lib-bulder” working on your OS is most likely that that one will work on other OS.
: )

**Comment by Lucarda** [comment]
FYI:

Here is the same issue that I mentioned for [abl_link], the list of .dlls is basically the same and Jean-Yves solved it very fast:

https://lists.puredata.info/pipermail/pd-list/2016-11/117001.html

**Comment by Lucarda** [comment]
Also I think here are some clues:

`I was able to solve this by setting the  C/C++ > Code Generation > Runtime Library compiler option
For Debug: from /MDd to /MTd
For Release: from /MD to /MT
This removed all the API-MS-WIN-CRT-* and runtime dll references and caused all the CRT code to be statically linked.`

https://stackoverflow.com/questions/35805113/visual-studio-2015-run-time-dependencies-or-how-to-get-rid-of-universal-crt

https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx

Hope it helps.

**Comment by avilleret** [comment]
@Lucarda I understand your interest in pd-lib-builder but it's not on our TODO list for now.
I will discuss with @jcelerier about that, but to be honnest I'm very found of because it will add one more build system to maintain and we have already a lot to do to make it build on all the platforms we support.
Moreover, each push are build on Appveyor so we can put a link on the website which point to nightly build for Windows as soon as the DLL issue will be fixed.
I just push a fix attempt here https://github.com/OSSIA/libossia/commit/b0ed6c75114f3bad6b1d30d83d88f00293f9f039
Will post here the link to the archive as soon as it finish.

**Comment by Lucarda** [comment]
Cool,
I gladly test it.
: )

**Comment by avilleret** [comment]
here it is : https://ci.appveyor.com/api/buildjobs/pxvsf5ulwjcoc009/artifacts/ossia-pd-win32.zip

**Comment by Lucarda** [comment]
Needs further investigation, unfortunately it didn't get rid of the API-MS-WIN-CRT-*'S 
Also same fail to load on Pd.

![3](https://user-images.githubusercontent.com/25239522/31048707-5ab965b2-a5f9-11e7-8bb9-28941930aab0.jpg)

**Comment by avilleret** [comment]
Thanks for the test.
Which version of Windows are you using ?

**Comment by Lucarda** [comment]
win 8.1

**Comment by avilleret** [comment]
@Lucarda I successfully load ossia on Pd 0.48.1 under Windows 7
unfortunately the CI builds are currently broken, 
but the binary uploaded on 20117-10-20 works (with all bugs that have been fixed since :-) )

could you give it another try in the next days ?
or you could also wait for a release, I hope CI build will be fixed by the end of the week, so I can launch a new release in the week end.

**Comment by Lucarda** [comment]
> but the binary uploaded on 20117-10-20 works

You mean: 1.0.0-b8 ?
from Oct 19, 2017.

**Comment by avilleret** [comment]
sorry, I was referring to the one available from Deken

**Comment by Lucarda** [comment]
I had the same troubles as described above. It looks that it is as @jcelerier said:

> could you try installing the MSVC runtime ?

But I normally don't do that just to detect this types of issues.

It could be documented somewhere that this needs to be installed to run [ossia] on windows Pds.

**Comment by jcelerier** [comment]
I think that this blog post outlines the procedure that we should follow to ensure that it works everywhere: https://peteronprogramming.wordpress.com/2018/02/05/detecting-if-the-visual-studio-c-redistributable-is-installed/

**Comment by Lucarda** [comment]
@jcelerier 

It looks good. Also given the fact that ossia is a dll you can statically link ossia with the c/c++ runtime.


We are discussing this same things for MinGW on https://github.com/pure-data/pd-lib-builder/issues/42#

**Comment by bltzr** [comment]
is this issue stil unresolved ?

**Comment by avilleret** [comment]
I successfully loaded and tested ossia 1.0.1 under Win7 VM, so I close this issue
