### ISSUE TITLE
crash/disconnect when sending/receiving values from "critical" parameters

### ISSUE THREAD

**Issue by pchdev** [OSSIA/libossia#236]
tested on **sc** & **qml**, both on **macOS**

this is what the logger has to say : 
> [error] handle_read_frame error: websocketpp.transport:7 (End of File)

in score, the console used to display : 
> Error while parsing: The state of the promise has already been set...

the crash/disconnect seems to happen on the **client side**, the server is not compromised and seems to receive the value correctly

**Comment by jcelerier** [comment]
please test ! it was an unexpectedly complex interaction

**Comment by pchdev** [comment]
**reopen**: it works with **client -> server**, but not with **server -> client.**
the oscquery_mirror treats the value as a ws_promise, so it doesn't get any address and doesn't update its value.

in _oscquery_mirror.cpp_, line 558

```
 case message_type::Value:
        {
          // TODO instead just put full path in reply ?
          auto p = m_getWSPromises.peek();
          if (p)
          {
            auto node
                = ossia::net::find_node(m_device->get_root_node(), p->address);

            if (node)
            {
              auto addr = node->get_parameter();
              if (addr)
              {
                json_parser::parse_value(*addr, *data);
                m_device->on_message(*addr);
              }
              else
              {
                m_device->on_unhandled_message(p->address, detail::ReadValue(*data));
              }
            }
            else
            {
              m_device->on_unhandled_message(p->address, oscquery::detail::ReadValue(*data));
            }

            p->promise.set_value();
            m_getWSPromises.pop();
          }
```
so I don't know how you want to proceed with this, as a really quick fix I just did a `else` after `if(p)` with a `json::parse_parameter_value`-like function, it seems to work

**Comment by jcelerier** [comment]
👌
