### ISSUE TITLE
[ossia-python] auto increment instance number ?

### ISSUE THREAD

**Issue by theod** [OSSIA/libossia#242]
In many bindings, when multiple nodes with the same name are created, they will take instance numbers but this is not the case with python.

@reno- is it something we decide or is it something I forgot to do ?
as I see in the C++ code it is just a matter of using another function so it is quiet easy to do.

**Comment by reno-** [comment]
@theod : I don’t like this feature, as I prefer to not have an automatic mechanism that make something else that I initial did.
So I prefer to keep this as it is.

**Comment by reno-** [comment]
I keep the issue open, maybe we should discuss this later when releasing 1.1

**Comment by theod** [comment]
agreed !
