### ISSUE TITLE
[ossia-python] are values coming from callback ok ?

### ISSUE THREAD

**Issue by theod** [OSSIA/libossia#244]
@reno- for the following code in ossia-python_example.py : 

`# attach a callback function to the boolean parameter
def bool_value_callback(v):
  print(v)
bool_parameter.add_callback(bool_value_callback)
### TODO : v must be a Bool, not a ossia_python.Value`

is the TODO still correct as there is an implicit conversion from ossia.value to python value ?

**Comment by reno-** [comment]
You're right.
This is now handled by the bindings
