### ISSUE TITLE
[ossia-python] default_value should be an attribute of the Parameter

### ISSUE THREAD

**Issue by reno-** [OSSIA/libossia#249]
For now it is an attribute of the node

**Comment by theod** [comment]
this have been discussed with @jcelerier on gitter (around October 3 14:50)
at the end there will be no distinction between node and parameter for API user so I have to postpone the issue to the next version.

**Comment by reno-** [comment]
I understand, but for now, as every attribute related to the value is attached to the parameter, default_value should be an attribute of the Parameter… if it is not a huge amount of work to do for you @theod

**Comment by theod** [comment]
done !!!

**Comment by theod** [comment]
we decide to let some attribute into the node and some other into the parameter and to move the default_attribute into the parameter
