### ISSUE TITLE
[ossia-python] Build Python Wheels during CI

### ISSUE THREAD

**Issue by reno-** [OSSIA/libossia#252]
We should distribute ossia_python.so integrated in a python wheel
A python wheel is a format for Python package.

During CI, we should address : 
• Python 2 + Python 3
• MacOS + manylinux + rpi + Windows

**Comment by reno-** [comment]
Wheel distribution allows user to :
- install last stable version (last git release/tag). This will donwload the wheel from pypi wth binary.
- install from a specific git commit. This will checkout libossia and build the binary.

**Comment by jcelerier** [comment]
didn't know about this, looks very nice!

**Comment by reno-** [comment]
[Python Wheels](https://packaging.python.org/tutorials/distributing-packages/#platform-wheels) are a modern format to distribute python package.
The wheel filename itself contains its target's platform if compiled extensions are part of the package (which is the case).
We need to provide a few wheels to pypi such as : 

pyossia-1.0-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl     
pyossia-1.0-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl    
pyossia-1.0-cp35.cp36.cp37-none-win32.whl    
pyossia-1.0-cp35.cp36.cp37-none-win_amd64.whl    

[about arm wheels for rpi](https://github.com/imrehg/arm-wheels)

**Comment by avilleret** [comment]
If I understand correctly, to build a platform wheel, we need to use `setup.py`.
There is no such setup in ossia-python, maybe it's time to merge pyossia into ossia-python ?
Then we could tweak the script to build a platform wheel, or maybe I misunderstood something ?

**Comment by reno-** [comment]
@avilleret  : Exactly. Maybe we could this together tonight?

**Comment by reno-** [comment]
done

**Comment by avilleret** [comment]
this is not completely done, wheel are built, but some are not installable
we have to figure out how to produce valid wheel for all platforms
the issue might be in the platform tag
