### ISSUE TITLE
[ossia-max] ø.model preset file : parameter address shouldn't contain model's name

### ISSUE THREAD

**Issue by matcham** [OSSIA/libossia#255]
/my_model/my_parameter int: 123
parameter address shouldn't contain model's name 
/my_parameter int: 123

**Comment by jln-** [comment]
addresses should then be relative, shouldn't they ?

**Comment by matcham** [comment]
absolutly !
so it should look something like that :
my_parameter int: 123
sub_model/my_parameter int: 123

**Comment by bltzr** [comment]
situation as of now:
- .txt saves with model (or device name), but doesn't want the model (or device name) when recalling (i.e. when removing the model/device name, presets are correctly recalled)
- .json saves with model (or device name) and correctly recalls them

ideally, none of them should include the model/device node name, so they can be used as presets in other instances of the same patcher
is that a hard one, @avilleret ?

**Comment by bltzr** [comment]
addendum: .txt doesn't include the device's name when saved with ossia.device (so it works)

so, to sum it up:

- remove the "root" name for [ossia.model], [ossia.device] and [ossia] objects when saving and loading presets in the JSON format (even if that currently works this way, but that prevents presets to be "portable" across different instances of the same patcher)

- remove the "root" name for [ossia.model] only ([ossia.device] and [ossia] DO work correctly)

**Comment by bltzr** [comment]
update: now, .txt format works, but it still prepends the model name, which we should avoid if possible
still the same for JSON

**Comment by avilleret** [comment]
@bltzr, @matcham @jln- could you test that ?
both JSON and .txt preset should be fixed now

**Comment by jln-** [comment]
Looks good to me. @matcham : Wanna check so we can remove it from tasks before release ?
