### ISSUE TITLE
[ossia-max] add set method for ossia.remotes

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#261]
It would be nice to have a set method for ossia.remote so one can send a value to bound parameter without causing output at remote's outlet.

It is usefull when building GUI for example (used that a lot with Jamoma).

At the moment, Max shows a set method for remote but I am not sure what it does.

<pre><code>
----------begin_max5_patcher----------
756.3oc6XssaiBCD8YxWAhmSQXatjc+UpppbBtccKXirMYSUU+2WeARHs.gF
XUeIQMP7LCywykiwtuuxKXK+.QF3+a+6887dekmmUjQfWyXufR7gcEXo0r.F
4u7suDr1oRQNnrhqDjJBK2WRTs5jp2JHVksRpvpc+gxd9QAYmxAJBlFFs1Gk
kYtkEatBggQ9Oz7LzbqKzXdGHq0Qr5RJqfnrSIvIg7Z0mk5Dodqh3.LHv+Ai
lOVsxbY8LCa7q9Qgt+tp3N1FwfnMgH8m33Qh9zdidzOXzWydgSY9nqIxgaP1
HOAMZIO4aTxiGLnW246Rl.DZnHWaOOLAZtkjMZBHt2D.r2D.bzDvUE3Ez8jP
MJFqZ79drfgKIeV88nGNFyBthaf+ncX8zjoNomHILEVQ4rN4EvFapXi4RZpq
6nSVoBKztSQDOp86VWZFLbVNV+vsbJDv1kEi9hS6lpQi1q0cRObO3nkfmJ3X
8rqEabUEQGSrcjtOoDumj+HVoDzs5tqS+R1TlZpSlBQQMg+Tq3V4cyTTFUQw
EeMiclUEb1yiWR6yot.K5Tx7Lij+gKT84z97Xs1iGoN8MCaSjQ8nqTWrL5tC
D1uZrsAuesxJBIufVZcduVTPYuZhCWyfSukD0d6+GiBNaFEDsfLJTVTXp9SR
5TYTvaLpgJo2XT+DLJvbYTI+ZIITMaBbRbIvMtzPEyaboEiKMvFc4RIEGJHk
b89cq3RpsO6Z1zq6MR.33mzK5arsezE21+Y670hmtjy974dsSZi7ySORdsXW
qKaOFp+oocNQpnriDu6OEAcLpjlWoOpjpARDJILQy3ifN9u814if.6JMMVZG
MvF3m77NcJy6lfadHoO0lO7RHgVJj.WBI3RgzEydfk.o3ofTxRfDZJHk5Jly
CI3TQBLWj.SEoYm8hlBRweAI2BP5WutmHjMVaAQuR7KbgYX1Z6PJyMztBWff
rm1ZehUBVnWkUoWhsV3V+8vF2+jnfRdNQvpoMuUPi7Gq9GvceU8B
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
this should work but user should take care of value type
