### ISSUE TITLE
[ossia-max] objects creation order problem when within poly~

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#263]
I really don't know what doesn't work
maybe @jln-  and @bltzr can help describing this issue ?

**Comment by jln-** [comment]
As of b7, models in poly~ are not created in namespace on patch loading. Steps to reproduce:

- Open patch containing model in poly~ (ie. score/Documentation/Examples/Max/Video/circle_machine/circle-example.maxpat)
- Add device in Score
- Only an empty device 'Circles' is seen
- In Max patcher, delete poly~ then undo
- poly~ model do get created and is exposed in Score

**Comment by bltzr** [comment]
that looks like an initialization order problem between the device and models, because if you create the poly~ first (by sending it to the back before saving, for instance) then it works correctly

is that a hard one to fix, @avilleret ?

**Comment by bltzr** [comment]
also I DO think this is quite release-critical

**Comment by bltzr** [comment]
duplicates #223

**Comment by avilleret** [comment]
@bltzr  @jln- oculd you please test this one against https://github.com/OSSIA/libossia/commit/ed30fdcab9e66c900ec8dccf4cda970e3a671cc5 ?

**Comment by bltzr** [comment]
I'm sorry, but that still doesn't work

when bringing the poly~ to the front and reopening circle-example.maxpat, the namespace is empty
when saved after being sent to the back, it works
