### ISSUE TITLE
[ossia-max] Send messages to parameters via model

### ISSUE THREAD

**Issue by matcham** [OSSIA/libossia#266]
It could be very useful to be able to send messages to ø.parameters via ø.model
(This would let users build for example custom preset / cues manager…)

Example :
<pre><code>
----------begin_max5_patcher----------
712.3ocyWsrbaCBEcs7WACSW55Qfd5rqa6uPmLYv1jDkJAdP3DmIS9u599iU
3hriSrsLoF63MhgKHc3b3pyEdYPDdhbIuEitB8KTTzKChhfP1.Qc8ivMrkSq
YsvzvhEMS3J7P2PldUhZtFFi7VP4B8pnztnyY5o2WIt6FEep1gXFcT7PTRbt
sIK19jZBgtt6UplAPJm7v2IE30eGEqgq4pa3B1jZtcJwci4fU+7btC.LdHBO
gItCu9a1pe18NXrMvqCFXeLzS12vaaY2wWsVz7k.UvZoVh9FYmxBcmxB4fxR
BHKoE8JKk38R8SLkiGEF1Rxx.5lmc3rfzSNaE7mL.sEYeXz5zNjcuNL4+jzw
.0ok1lwY8tSOF2WR9Im+MxY75f9aeNPdmDrOVSiOKrdprogKzaQ6ezhpznEs
7YlcczSR0uQUBzOYMxFF5pOgZDue0HETCZYhsgTjB8h2SRPNNH781ZoY8s1Q
UwaMrmoqjhMyNSfUFgBMwcOVurtUpZXvTyCyOCYfBj5gM.I4htXPyy2H02aV
SvpaixBGPny1sPer1qfrV.xJgT1qtldtqlrGEo6HAzRxIPQnDPQnDpGYZjOm
hzEYlTnU740roPbR3Lh+6e1nRz6SzBi4bm5PJJcM8KOzyh876sqBswSFwaem
3KcemO53bjGDk7l0QYZeJyW2wPKFERt5koP9EtmP.cCbpxJy.2MR16Y09JOf
pQCfSnZ4+m8npGLqfPJbMI85N7e+O.LLttR7wqhCqHa72KHsxEpoq93qtb.5
sE0LdqtR.EU2XRlh6HB55cp4dCTgG.YuTpcRGGRkdfj85AGORo9voP.ThO.k
FBjn9fDIDIDwdfTHxGJOSaR9nb4aIbt+fYym+HW01MY.Bi40CRksawPnakv0
MA5p3OVsZ9oPDlx3AoMFPKTNihkkt5MXqslRrnpq5gA4WG7OjJwgJB
-----------end_max5_patcher-----------
</code></pre>

**Comment by matcham** [comment]
it works in PD prepending the message with "set".
please make it work the same way in Max :-)

**Comment by avilleret** [comment]
closes with https://github.com/OSSIA/libossia/commit/2ebd9beb1e5f3abdb6091a96c1329a441ea3fdab
