### ISSUE TITLE
[ossia-max] model preset bug : if there is one parameter @type bool : preset files can’t be restored

### ISSUE THREAD

**Issue by matcham** [OSSIA/libossia#267]
Model preset bug : if there is one parameter @type bool : preset files can’t be restored

If there is (anywhere in Max) a ø.parameter @type bool : model preset recall do not work

(For example : ossia.model.maxhelp cannot restore presets)

A simple example : 

<pre><code>
----------begin_max5_patcher----------
883.3oc4X0zbaBCD8r8uBFN65hj3ydp+.5odsSmLBrpix.RdjDoNMS5u8pO.
aRrwPhwNyjdQCrVV69d5sqVziym4my2Rj9dew6Gdyl837YyrlLFl079L+J71
hRrzNM+BdUEgo7W39MEYqxZeifHIJYqcVcEkUZLn+Qvdi7ZUq0fFqavphaor
02HHEJWn.gYKCV3AfKiV3EEXdFpG89Yyegtx5Sd9ceJJn0kR0CkDqceigmlO
2Lr3LwkNnvkkuAXkWmmWRjzU1XB1OXAwV.FYGBZG2gU25XhmJrXMkY8bvgDQ
XVaP9KNSwvUNt3aXE266j00kXQWvUvK4BW.DrDsny.niy6vocVbI8OVi58mm
iVqwIj7k36IWRpOJaGyGF+1Y9zOdLOlsZZRkAfv8oxnrSkJGlLMoxUDoDulb
.l96mUDoBtTsUcTrAOJ1.8isDfANYgFnk.sPC1CzBa8nakUOrg3VCe+iskO4
nFLcnFDlXfptp0vvFcwgMi7asmN1wQaHrUdtik7J43c54RJiTvqYpWf9gD4C
SI.sfvvIHyKnnd3jf2YovDl..RBGcF.38RJTvY+hKpzg+sd546ky4pyUK.GV
KfrGkmBOoV.1OorvymZhqqYZR2yau.oIttaFUVBJ6iSASGrGS8RT7+IIIMJg
wji.SuV4H8IHBlFYPrU1GBQ6azuOc.H8hqCT70qKeMMWeJjYk1nXKxfgsiGE
YQ96VGgtSYEQbCgga5fMnOTeE1kSBmnr8TKY39B1A1lgW9z85pbhveZRZQFj
AigCir32ztrIeNGyVegq0wkRJd4tHyCy3pa0Q3dKe0DTlZfkSDyYaI.k4J9G
GexFkNY4tqL0T8vArBkolT4TlkafHvIOX78mTp3qHkFBw9vMuRwwfsG.c0MA
MEQ6gGdkELZr7rabHKMCFEatwgPc66wPySAHPZXTyEPzg3rqo87+WbGgVXXr
+b1TxqEEsQTSc.u8.YktuJJCqnbVm4fby4n6Wi0OluudPGY5j378DZDdxzW+
46I3X7TvT3IvUCSAiYeZJbzH7ioKKOvY5HyGpbUPDJ9ZIwGiB2z5xYycsQ6o
KOjMAPxz14vJ7Cbjq9Gdyl6IBYyjs9PetwctRpIKruRYtWQ1WEj6osyOzZAK
zk8U5Z90BWs4sotdj7MGmHX0zlavU64ml+O.Xcz3aC
-----------end_max5_patcher-----------
</code></pre>

A working example (type bool repacked by int) :
<pre><code>
----------begin_max5_patcher----------
885.3oc4X00aaBCE84jeEV7bVF1FHvdZ+.l1j1qSSUFhaJUfcjsoKcUa+1m+
.RnsgOZCIUp6EK3FGeumiO2qu3GlOyKkuiJ8.eB7CvrYOLe1LqIigY0uOyqj
rKqfHsSyKiWVRYJuEteSQ2or12JnRpR1XmUUlyJLFz+H7fQdkpwpes0sDU1M
4rMWInYJWnfPIK8W.fnkgK.g9lmQ5QvOq+K4qs9jmd6GB8aboTceA0Z2yX3O
ymaFVbh3RGTjhhWArRqRSKnx701XB0MXgQV.FZG7aF2iU25XhmRhXSNy5Y+m
SDAIMA40blhQJcbwWHJN36zMUEDQavkwK3BW.3uDun0.rkyawosVbY9usF06
OOFsViSH4KI2QOmTeXxdlOH50y7wu+XdBa8zjJCgAGRkwI8kJGrZZRkKoRIY
C8YX5ueTQkJzR0N0QwF5nXC1M1VAMvIIv.sUHKzPc.sfFO5VY08aot0vy6Xa
4SNpgSGpgAqLPUW0ZXXiO6vlQ+k1SG63nsT1Zf6XIPAmrWOWjynY7Jl5IneH
Q9vTBTKHLbB17BNrCNw+MVJLgI.vUAiNC.9VIEx3rq4hRc3eCPOePJmqNUs.
ZXs.1dTdLpWs.paRYAvK2DWWxzj1m2dFRSbc2LprDbx6mBlNXOl5k3n+SRRp
UBiIGAEeoxQ5RP.mFYPjU1GfvGZzuKc.L9rqCT7MaJdIMW2GxrRabjEYnflw
ihrPu8qiP2orhJthxH0cv52EpuD6xgST1drkLbeA6.aynye5dUYJU3MMIsXC
xPQngQVzqZW1jOmRXaNy053RYNY49HCPXb0M5H7fkOaBJPNSMQDmsi.bhq1e
XTu8I0a0tKLyTd+YjTbpoDK2fvvdOW7smTJ4qoEFBw9vUe8aWoOhrvaB6KB4
pbBiW0GU7BKYTa4Q24PRbhVDZtyg.cC7QHyS9XXbPX8UPzh6rqosCfmbKgVX
Xr+XBUxqDYMQTck.vAfrV2YUNinx4rVyA6lyQ2xFqeLeg8fNxzKwo6I7H7jo
y9S2Snw3I+ovSvKFl7Gy9zT3nQ3GSeV.3I5HympbQPDN5RIwGiB2z7xIycMQ
a+kGRl.HYZuaXE9ybjq9GY616nBY8js9PezwstRpqVXeMm4dEaeUPuKuY9AV
KDgtruRWyuR3pMuK10kjm4DEAqJu9Nb0d9Oy+GfwOQ9c
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
according to a quick test
the issue is in the preset file parsing when recalling
if the preset.txt contains bool parameter nothing is restored
if we remove those boolean line, then other parameter are well restored even if there is a bool parameter in the patcher

**Comment by jcelerier** [comment]
working on it

**Comment by avilleret** [comment]
related to https://github.com/OSSIA/libossia/issues/287

**Comment by bltzr** [comment]
is it related or does it duplicate #287 ?

**Comment by bltzr** [comment]
this is only happening with the .txt format

**Comment by bltzr** [comment]
now, only the bool parameter seems to be lost, AFAICT

**Comment by avilleret** [comment]
by me, KISS preset doesn't work at all tonight

**Comment by avilleret** [comment]
so this morning, kiss is back 
and kiss on bool have been fixed
