### ISSUE TITLE
Relation between Jamoma and OSSIA

### ISSUE THREAD

**Issue by theod** [OSSIA/libossia#27]
Even if OSSIA use the TTData and TTProtocol (from Modular) classes and managing namespaces using the NodeLib (from Foundation ), I plan to remove those dependencies (and to rewrite some parts from scratch). In the future I would like to get a very light C++ layer dedicated to :
- ease [RPC](https://en.wikipedia.org/wiki/Remote_procedure_call) (as this seems to be what we usually call "device manager" between us and as @jcelerier told me this is not a new problematic in computer engineering) : what we can expect to be new here is to design a C++ interface to get this complex feature easy to use in artistic projet.
  - ease the authoring of interactive scenario according to the OSSIA formalism : this is the really new feature.

Then I expect Jamoma to be built on this layer (or at least the RPC part). Of course this have to be discussed with all the Jamoma team as there are some efforts made by @tap and @nwolek that are somehow parallel to ease the reflexivity of C++ object.

**Comment by theod** [comment]
this is related to this thread : https://github.com/OSSIA/API/issues/20

**Comment by bltzr** [comment]
do we still need this issue ?

**Comment by jcelerier** [comment]
let's say that no
