### ISSUE TITLE
[ossia-max] ossia.remote misses the zombie attribute

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#276]
so it complains when a bound parameter disappears
```ossia.remote: no attribute zombie```

**Comment by avilleret** [comment]
I also noticed that on Pd. But what is zombie attribute ?
Should it be exposed to the user ? Should  is be settable or read only ?

**Comment by bltzr** [comment]
the zombie attribute indicates that a node isn’t here anymore (because libossia doesn’t remove nodes when they are deleted, in case they are resurrected at some later time)

> Should it be exposed to the user ?
nope, as the node should disappear

> Should is be settable or read only ?
RO

**Comment by jcelerier** [comment]
> (because libossia doesn’t remove nodes when they are deleted, in case they are resurrected at some later time)

that's not the reason. The nodes aren't deleted because for performance reasons, the processes (for instance automation) have pointers on the tree nodes. If a node happened to be removed during execution, there would be a bad pointer which would cause crashes.

**Comment by bltzr** [comment]
thanks for the precision - at least I didn’t say bullshit on the how, just on the why

**Comment by avilleret** [comment]
this should have been fixed with https://github.com/OSSIA/libossia/commit/3523cc74f46cf3fab1d09f186bb2d12e7b39f05e

could you confirm @bltzr ?
