### ISSUE TITLE
JSON preset loading is broken

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#287]
I can save JSON preset, but can't load them afterwards.

It doesn't crash, just say something like "can't modify tree"

**Comment by bltzr** [comment]
does that require @jcelerier 's input ?

**Comment by avilleret** [comment]
I asked him several times in the hope he will fix it silently but nothing for now :-)
so I may dig into it this week, but, wow there are still lots of things to do !
but I think this one should be on top of TODO list.

**Comment by jcelerier** [comment]
heh, yeah, sorry I tried to look into it multiple times indeed but didn't find the problem yet :(

**Comment by avilleret** [comment]
could you at least reproduce the error ?
