### ISSUE TITLE
when moving with flexible intervals, change the flexible duration before the fixed one 

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#288]
@bltzr please add a screenshot

**Comment by bltzr** [comment]
<img width="689" alt="capture d ecran 2017-11-17 a 14 39 37" src="https://user-images.githubusercontent.com/113982/32950037-33543aac-cba5-11e7-8fab-05cfbfcafcd2.png">
here you go

**Comment by bltzr** [comment]
shouldn't this be a score issue ?

**Comment by bltzr** [comment]
this is now: https://github.com/OSSIA/score/issues/698
