### ISSUE TITLE
Crash when adding nodes in minuit device 

### ISSUE THREAD

**Issue by nvuaille** [OSSIA/libossia#29]
It appears when device has incremental nodes, e.g. : 
minuitDevice
- a.1
- a.2

[device_crash.scorejson.txt](https://github.com/OSSIA/API/files/132776/device_crash.scorejson.txt)
(I added .txt in filename so github accept it)

It seems that the API increment by itself the name and return "a.3" instead of "a.2" (where a.1 is ok)

**Comment by jcelerier** [comment]
not sure this is still relevant due to the entire rewrite of the network part last year. Besides, adding nodes on minuit devices has been disabled anyway since it did not make a lot of sense.
