### ISSUE TITLE
speedup cloning by updating only needed submodules with CMake

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#290]
For example `CicmWrapper` is quite huge and only needed for `ossia-pd`.
Also `pybind11` is only needed for `ossia-python`.

So I propose to checkout submodules with CMake so we can choose which one is needed for the current build configuration.

`git submodule init` shoud be enough to get submodule list before running CMake.
This could also checkout submodule changes automatically if someone forgot to pull recursively.

**Comment by jcelerier** [comment]
http://s2.quickmeme.com/img/45/45439cd6d55d18f83d442376405d61d076fd70bcef2f56b231e8ec853324fdab.jpg

**Comment by avilleret** [comment]
http://foonathan.net/blog/2016/07/07/cmake-dependency-handling.html

**Comment by avilleret** [comment]
we can also automatically download boost if not found

**Comment by avilleret** [comment]
fixed with c83c418735ba8db4d2a1446372f62f513b06a700

**Comment by nvuaille** [comment]
FYI, I just discovered git options that can be usefull in this case : https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt and https://git-scm.com/docs/git-clone#git-clone---no-shallow-submodules .

The idea is to download only last X commits instead of full history
