### ISSUE TITLE
why `ossia::is_numeric(addr.value)` return false for VECnF ?

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#291]
VEC2F, VEC3F, VEC4F are numeric arrays for me, so this is strange
at least it should be a `ossia::is_vecnf()` method somewhere

**Comment by jcelerier** [comment]
that's certainly a case of lack of documentation :p there is an is_array somewhere that does this (value.cpp:602)

**Comment by avilleret** [comment]
I saw that but isn't a tuple an array too ?
and a tuple could have non numeric value
and it could be dangerous to my mind to consider a tuple numeric at instant t because it contains only numeric value, because at t+1 it could have non-numeric (yep that's weird, but you know, people are doing strange things :-))

**Comment by jcelerier** [comment]
> I saw that but isn't a tuple an array too ?

mhh... depends if you use the C++ definition, the LISP definition, the "theoretical computer science" definition... :p certainly this could be renamed to be clearer.

**Comment by avilleret** [comment]
this is not really an issue, 
it looks more like a general discussion on the idioms we use
this discussion should happen on the forum nowadays, so I'm closing it
