### ISSUE TITLE
réparer ofxOSSIA

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#297]

**Comment by bltzr** [comment]
any help needed from @jcelerier or can you manage it yourself, @pach ?

**Comment by avilleret** [comment]
since we have a safe C++ interface, it could be at least worth to refactor the code to use it and simplify things

**Comment by jcelerier** [comment]
+1 for using the safe interface, this way there is no problem with any dependencies of boost or stuff like this... just use the ossia-cpp98.hpp header and be done with it

**Comment by avilleret** [comment]
so we close it ? :-)

**Comment by bltzr** [comment]
I updated with ossia-cpp, and anyway there is also https://github.com/bltzr/ofxOscQuery which is maybe more of-styled
