### ISSUE TITLE
annoncer ossia-SC

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#298]
-[] liste SC 
-[] FB SC ?
autres ?

**Comment by avilleret** [comment]
woohoo another burried issue !

**Comment by bltzr** [comment]
ping pong @pchdev @thibaudk 
I think this is plan for complete revamp
we could probably close this tho

**Comment by thibaudk** [comment]
Yes, I think it can be closed.
The new version will not use this repos dirrectly .
