### ISSUE TITLE
[ossia-max] \@default is broken

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#312]
just open  ossia.model.maxhelp and you should notice it

**Comment by avilleret** [comment]
FYI default wasn't broken itself but attribute setting was broken due to a line swap
so this one is fix, and some other related too

**Comment by bltzr** [comment]
```@default``` seems to be broken again (in Max only) - could you test if that's also the case on your side, @avilleret ?
(also sending (reset) doesn't reset the value to the default)

**Comment by avilleret** [comment]
we definitely should setup test environment for max to avoid that kind of annoying regression

**Comment by avilleret** [comment]
yes I confirm this is broken

**Comment by avilleret** [comment]
the test I made yesterday was biased, and today, I can confirm that it works
could you test @bltzr against 8921ac7ad3bdc28d26b39b30df72bb9b4d7defdc ?

**Comment by bltzr** [comment]
confirmed!
