### ISSUE TITLE
[ossia-pd] some attributes don't work as arguments

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#318]
some attributes don't work when set as arguments of ossia.param : 
e.g. clip, unit, range, default, mode and description have to be set by messages,
while type and enable do work

also [get description(, [get tags( and [get priority( don't do anything

[attributes.pd.zip](https://github.com/OSSIA/libossia/files/1540547/attributes.pd.zip)

**Comment by avilleret** [comment]
thanks for the detailed report

**Comment by avilleret** [comment]
related t https://github.com/OSSIA/libossia/issues/312
