### ISSUE TITLE
Generic attributes for addresses

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#32]
Maybe the API should allow for setting / getting custom attributes ? 
For instance this would allow to add tags, description, etc... without too much hassle.

e.g.  in Address : 

```
virtual void setAttribute(const std::string&, Value*) = 0;
virtual Value* getAttribute(const std::string&, Value*) const = 0;
```

However not all protocols may be able to support this (e.g. MIDI) so it could be an extension, or have a default implementation :  

```
virtual void setAttribute(const std::string&, Value*) {
    // do nothing
}
virtual Value* getAttribute(const std::string&, Value*) const {
    return nullptr; 
}
```

**Comment by jcelerier** [comment]
@thzebra this would be necessary in order to support all the attributes in the examples files

**Comment by thzebra** [comment]
ok, i'll see to it

**Comment by jcelerier** [comment]
done since a long time.
