### ISSUE TITLE
[ossia-max] clip attribute bug: parameter received an invalid data error message at loading

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#321]
In the patch below, parameter having a clip attribute defined as arg (gain, pan and modulation/index) throw a '*parameter name* received an invalid data' at loading. When removing their clip attribute value defined as arg to the object, I dont get the error message.

If I delete ossia.device, then save and reload patcher, error message is gone.

<pre><code>
----------begin_max5_patcher----------
848.3oc0W0sbiBBE953SgiW65HF0jrOB6qPmNYPknzhPF.sISmtO6K+nIZh0
llM6E6EsBGNvguO9NGHu6rvKic.I7b+o6StKV7tyhEFSZCK55uvqFdHm.EF2
7nn2XYu34aGRhNHMlYBAFFTfZw4H25ia2UucOTlWg38tRapwTBRZVFPmQiOX
Z4VNJWZ2FwfMAg9tfnzfD0mzk5dQQAgtO2MIbgMjYu7iUCVcVi7xkWHORPFm
68y5j73djMZddmV1bFgwsVCC.QIwa7UMVsIMb0Zcq0ahA.UKfdqnmxGNN5+4
eiLW1EDRKF8VKVfyvDr73vsMa2NAR1uUB0A+L5Ir7WQEEbXoHmyHDsag8Pff
yeUVwYMkUCsinvLBp55IXGn85AxJqYEnQVX7BDenka8DMcoADKireRMe.owS
ejBl9H8TPg01STwQprJPShAJZVE194A4kcJZuVlRNF.7tqyqYU5Z1gnE5lsw
8pwUbfViGsYNMdzx+iD40Hg.Vhth0zGah8vbzjTUzmSUq.qsTUp9ypYqF..O
Bl5wIU1ywT42UarNAXq+kXxVhmCvqmOWY.debfp.l+6u6gXmdWIyLXZ0bXJ8
eIlH3VTPIDSOAgVH+TIkyi9D346DiwIg5b5XqpcY5zfLw6zBwUQWh3askhGJ
NFS.IeljUfKoPhm+vV5+1QX5hhZXIjmq.HfsnhsPojiyZjnysDc7VGwooFRC
hsq2bu8gaZBiVNE8E0Sei7VTw3xYY6Qt2iwvIFqVcnnG6Gqz2lL03PiNHcxQ
wTrDCIWy4S4kklMApmDG4VixsSpxX63FYY+mGSdm5EUl6Zb6uT69tyY4lHix
LDLWRX7zIgQ2dgzqTkiJrZhoRAPu7wmlMt19XBRvZ348KcWBj64cdARHwTnD
ynC7I05yjGAem3.tg3.9KiS7MfmjG.dhuA7j7.vi9QKeIfV+..j9N+uLP86l
qTfv86aQbQm2lfnRFew9DoU9ltXps6RSWNR+lcq+wFKPtJUSpxyZ31bhCqs2
g4oejHm1fMYlNZ34zk6bgp+TMweAqY0vsU3RE1KqjpJ0LNj1+fJE71AaHxwb
BLOGQkCdYGv9aFR7s+5gAukyuia4pIbYRrWsZkM60vNFx4Cm+TCwWYO
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
For further information:

In the patch above, if I open synth model in modify read only, delete the 3 mentioned parameters (gain, pan and modulation/index) then undo, the binding is correctly done and error message is gone.

**Comment by avilleret** [comment]
here is the simplest patcher that trig the error :

```
<pre><code>
----------begin_max5_patcher----------
382.3ocuS1saCBBEG+Z4ofv0NC3r05tpWuWgkkFpRaoAAChs1zz28AGzktk8
wMK6BEN+gyG96b7JJgr0LJ5I3mvufSRthRR.ofPxjcBokOVq38v0HZwYy1ij
z3QNwnCjM88RdVG2xaENgEuyXvqaD63CJGlQwqqUxNrxbd1S8PqYvoDNHr4S
pcbW8Aod+Fqn1EKqJVFMEyVTFVxKnvRdFE+5jOxlXEr83C4z4vGis6RmHFEB
I0+7tO0FkwFOglwxWTTk52TVsjVtJraUUAi42wtKO9JVpmKX1jXu6hBRAgDD
tgPgWo+EvrQbRVKv9kulYreiYKWjsHEWU8SDq76A1+Er.eH7ttSBauznAdEn
kmUGiItLELk5n4ifo0ym46W.JbqGDNOEFrwzLtrfDc0zHr5AITMnPGBMUNeZ
3W6meAWel2ZZ4aNH2eP4ebhlMFKWuWDAFYZ19iMWdcsP6tiWPefFZCvbKPn3
mdLJ9eX7NbGWhxs9HC0JchPnan2.bYt2m.
-----------end_max5_patcher-----------
</code></pre>
```

**Comment by bltzr** [comment]
yep, and this very much looks like what's happening with this: [ossia.parameter bar @type string @default aa @range bb cc dd @clip both]

maybe a quick workaround could be to do #181 ?
so we could kill two birds with one stone...

**Comment by bltzr** [comment]
I also have a lot of those errors when adding the remote below to the second tab (Namespace exploration) of the overview, and playing with the gain value

maybe that can help finding where the problem lays...

<pre><code>
----------begin_max5_patcher----------
428.3ociSFkaBCCCF941SQTdtqKsPAocD1U.MgBESISsInDWFHD28k5jtALl
TenTk+XW+4eatjlv2XNANN6M1JVRxkzjDRZPHIdNg2IOU2JcTX7csFceGOKb
kCO2Bj9nh+RSO1BHEdYTcmw1IwAkEQkCRrduR2r1B0X.fxEKxqxXKKVN7pRj
KxXkk4B1GwbBeX77AHjfunL9Fotg+SHpsDMlMe9xLwMLoziHU7C.VYGffcMn
kaBcgX7NK3.MJQkQeGfU2.HwmX.ugjtllN7S1DsQM7kmwQ.Q3DF314TxbKzY
Pfcznpg7hWajJ8TM7Y+u8Nm.NBeYw7oYuzySs2pmau2XFTZ7Vk9wULhtA86c
Hmo2VOV7wZv9EvsfCUZZpbaPhPPOcJL4JIlRkp9SkBsn7vgif0EilJheb+ow
NbbYFcToCGoID2BGUiwOmTjV+.C8SqdaX.eZwbdHUyVvp6UQ602dowEgGrUs
eglR8cYmoStdupw26M6QX6Zi0++DHLx7s2NYeKdumHqq8670l1.mqXEgE7wU
8heW0yhdq0mviaj7N+WlXUDcnzqoeujyJ3B
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
kudos @avilleret !!
