### ISSUE TITLE
[ossia-max] ossia.maxhelp needs some work

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#323]
maxhelp would need to be rework so it is useful. As of now, it contains various information (messages etc.) but would need to be more focused on use case

**Comment by avilleret** [comment]
is it done now @jln- ?

**Comment by avilleret** [comment]
ping @jln-

**Comment by avilleret** [comment]
I think we can close this issue for now.
If needed open new issue with a list of help patcher to improve and how it can be improved.
