### ISSUE TITLE
[ossia-Max] crash when ossia.parameter is created after its bound ossia.attribute

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#328]
this can be easily reproduced by changing the value of an attribute in one of ossia.attribute.maxhelp's [ossia.parameter] objects, then asking to its bound ossia.attribute to change or get the attribute value -> should crash

**Comment by bltzr** [comment]
the gist of it: https://gist.github.com/bltzr/98551a54cf1f039174b9df901739a320

**Comment by avilleret** [comment]
I can't reproduce with b9e2286a7930b5c50190d1cd5fa25fe9e197e3c5
@bltzr could you confirm this is still happening ? 
if yes, which version of Max are you using ? 32 or 64 bit ?

**Comment by avilleret** [comment]
sorry @bltzr the configuration details are already in the gist you posted 23h ago...
my bad

**Comment by bltzr** [comment]
so, could you make it crash ?

**Comment by avilleret** [comment]
definitely no, could you ?

**Comment by bltzr** [comment]
yes, I just changed the range to 1. 2. in the parameter (which rebuilt it), pushed (get range) and: kaboom!

**Comment by jln-** [comment]
I could not make it crash.

@matcham : I'll get you a fresh build. If you can test it works ok then we can close the issue, I guess.

**Comment by jln-** [comment]
Cannot make it crash and it seems to work fine hence removing 'release critical' label.
