### ISSUE TITLE
[ossia-Max] min and max attributes don'break the clipping mechanism

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#333]
as demonstrated in the patcher below (notice that this works with vecnf's)

this also happens in pd

<pre><code>
----------begin_max5_patcher----------
735.3ocyV0zaiCBD8bxuBDZO5ZY7WIdO0yq1S60UqhH1jD5ZCV.tMcq5+8c.
rSbRZRSZuTIjCCLyv7dLyPdY5D7R4VlFi9N52nISdY5jItkrKLoWdBtgtsrl
pcpgaXZMcMCG32yv1Z7qyEnnPzcjPTbHLK.Alg.I6.1HKbvjZtfUJ6DN6h6W
rkZJ2vEqWnXkFe7jjlDFEfJJByB.WPrBIYgQn+zaCuxcxxkObWZ1f2kclZlw
7bKy6ELdm9hNHHgM0iOXs44ZmpX7d07NwoGwt3qSmZ+DbkbTorogA36XNpSC
HDUwWshof8QZ3LPxUHK2QEUNF6QZcGSiVpXz+pQlMLzSaj0LXFX6MSgIoVVK
M2RgwyxuHElL38URgQy+miUHwfM6gQorVp79NJLOXzGxHud.QSF4UAswy0+j
ZjnewV2USU3q7lH5CbSrpVBNAedFhL2kWUjYYnrH6733yPPwmOGK.gWRg6mc
10RU.VML0BlftziqnKSOpFpKnxuR9H9CvGmq5E.dF5vOuOoESl4JMSHWh1R9
RUZdNB3aDzv38ANAvJ.7YoWD2Eekvsf8DDTm.aoVyog6RVQzE0bsAcuMXQ9o
JHul45qCi6Kq4snkRyFz8UrUztZisq+v3V6OMvm49Lnj3SZPcPCGRbVZgsey
rh7nYysylWjRHyOr8y3Z1nKVyhubKqaoBz4IGvO54TGrsqe3siV1oJGhkg1K
n8fnhoMbA0vkhQJYSprJ8lY.W8IEcMmDT1hH6TpgW0J4BSO3HEQtmThxCige
Shh2K9IitAHdwn6HH71QGI08f2XoOKykcCw1IIGz11GYJcu1tCAJRevmeOKv
IxEdwDmnh8HeP+T2JTETCYfBnNkOybadJ1aprhoDc79ND.7l1mAeTB4tGg+A
sQ1PWrguFv95MFV0BoqZ2msi6KvOjSnkkvecYTYoqz0wvtWOI6I4fdt09ecN
tTB2.dlO7rtkgl95z+iDtKmC
-----------end_max5_patcher-----------
</code></pre>

[list-test.pd.zip](https://github.com/OSSIA/libossia/files/1551523/list-test.pd.zip)

**Comment by avilleret** [comment]
I'm sorry I don't understand your isssue... I see there is something wrong when testing, but I really don't understand what you mean :-/

**Comment by avilleret** [comment]
a quick test demonstrate that min and max are not taken into account when set as argument, maybe this is what you meant @bltzr ?

**Comment by bltzr** [comment]
this and also that, when provided as message, nothing comes out of the param anymore (I'm not completely up to date, though

**Comment by bltzr** [comment]
![list-break](https://user-images.githubusercontent.com/113982/34098372-5b8b7996-e3dc-11e7-93dc-f3334a5900bd.gif)

**Comment by avilleret** [comment]
>  nothing comes out of the param anymore 

but a red message appear in the console :
`ossia.parameter: a_list received an invalid data`

**Comment by avilleret** [comment]
there is still something wrong with min/max, start with ossia.device help file
