### ISSUE TITLE
[ossia-max] pattern-matching doesn't work with parameter @type string

### ISSUE THREAD

**Issue by matcham** [OSSIA/libossia#337]
only first instance of parameter receives value

<pre><code>
----------begin_max5_patcher----------
778.3oc2XsyaaCCDd1AH+GDzrqfHoDkbWR26PG5XQQ.sLShBjHEHoRcZP9uW
piV1xI9grsrSPWLAO9338ce2CqWt9pQ9Sky4Zeuu58KuQidwJYDHqQxnVAi7
KYyyJXZXi9YxxRtv3OdwhF9bCrvM2rTlntTVaJ3F3HgshymAaTN8wufRWt4J
lI6gbw82p3YF2aAGmDDN1KBgaFHozlgX6Due2dJs44BNbcc0ZtnUonVo2IEF
c9eg8RlDPnIgDDr1qWeUyncX7oa8Bow6Ge+PPfv0tjLYgT4r9vFqs6ODzJ6d
SnEBvGbjafRZFRSOJzpRw0V6iYxkhNp.E5taK.14ss596BxIgASHXRBY3A4C
BfiGJ7EEF4ngNH.lfnImLaDYQynnIjH5QiTkbslcO+8HklUTa1BXg1DaLYWw
inETqHHrLFfM79BGcZz7bE2cI99q19ZfCdOju3XD.4330IeCFp0C3YEYZl0C
p3UErL95QNaMMFIE8Q.aTJj8DmFNPvlf+GKV7dtlTqyYAULEqja3Juxm+oQY
Qh.r22ZrCOMLc4AKxE7LYsvrlUrtS.uIm.sG0LHDGYIBhVIzCFsGucDGM7wo
SkhGk0pCgJFsKTHEeNCTOSTGEuTZ3q3MufBBvudP7ExlPJbOPJWzABiNA5xm
dJC5XxdkhOmIutbYgPCaVnI6mT84LGzcER6M4upSDUICd1z9a76rKALA57Dk
fOIFi03mxrNpt8jsvodKWvl5tgvipOVbL7DwSnW3ZhFoQtrdn0SvLmLQLsO9
BLXnHWSq+OwD2Yu.IPfmqo0OFd34sRIvlFnpjQ6GHSh+jVibHHRj8a+enYzt
LolPCZpITOvzKXlI21.q4serK380rvaPRssCqrVc011sWm23Lt1jKf5Kc2E1
sqs6z5uBStvJj1G8EMb1WuzWye71CMHJbRuzGZvzWZezWxvgm8QcjMptEwGr
ppm3J8hS3zjMkxituaVxX27bgatqVhuh+Td6QhbhXJaHuwFuWqbQwyoKJx3W
JmwUh571nT3MX+4e++w+JC
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
might be related to https://github.com/OSSIA/libossia/issues/334

**Comment by avilleret** [comment]
as demonstrated in the snippet below, ossia.remote is well bound to parameter
but only the first one in the liste receive change made from the remote
communication in the other way (parameter -> remote) does work

<pre><code>
----------begin_max5_patcher----------
874.3oc0X1rbaBCDG+r8SACGy35gcEBL8TeG5wNY5fMJNjwVPQhTmlIu6EIv
0zXa.gI1jKlAXMK+z9e+.85zI1KS1wD1Ve05GVSl75zISzWRcgIUmOwda3tU
aBEZyrWlKkIb6Yk2JMTt5wX95elwVIKeLDO+4Nyrbof5.5t+Wq6q9O77sw7M
Lo94AUWLNR+zSV9zWbcsOXYRt78lJjurgosduckFIeIkU9JXuLju115d0cea
5T0OyFR7nyrHXuwCug3wY+t3cX+CVx1ooxNMKlKa.ZfpionOUcfTBMZBzNmF
ZmigtGTskIDgqYGg0ZlzJLJJq31M.WIT.EUG7IMyFdLajfKNf9AoUAPiF5Q6
oVk3eC0pmKpVEQs19x2kE510yuqgk.WTksBNd5XLflGco2nn64vW7qnGDQcH
pGrPWG1ybjIiLjidXsfI9SSgYPiIYgtNEsGgYbjwLKLZWisgfZ.S7MGXmwAv
mfMzKPqbc0ErnNFyFtvT1hR3xLV5lvUr5FNPHelttIBQb37zvrvsLIK6PAMh
02T9zRnOscUfKDTtFsv3Fy3YZdgFHClM3k3XaJP7v5A1T0NOMzPY0Nvw792n
+nMSfFTq+ceRDFcMuJxxV+PT6HW07x75Z3sp4UOGslhkctpZfY9n0HbKFslW
TyRjpJW1JZHkzyIqQmwUrTWvtC.uPGEIAFGKgEir70kI7mRxyZZxqxAPV.8r
DUvm6V0PWaUW7cWpsMf.8sSM.iwN0gaxap5VfWsly8Pc.i2dyH8BU9.8yszG
OozeSLmsJImKqS8oFcEcp0b.b0JDB0jDBuQXBQ6ELI3ElR3NBaJNOisMQx9m
33tVW.vxJg.gZdkvy7s5DCC7GE70uAZE761RbMEpq++KOhhH8p8Ox8eMk0AP
hXBYLOTFmvqYjZ+sqYTRVDKSOv1IiIc00prg1cMdybspZmEbrqgKx0cZAWsc
.CuqUafR6tt586x7Dds7jJyxBaSD4LDL0k.GfCESPKdRsQ2CehgZuiuNPp1x
118DL.dB8GUAN7CorB3d0f7psbhWMIh5qXaud0fHF6RM38uNWFSPG7TPoV7n
IJBSSelkIpLV6ihQqdJQqT8moOMlWdpdHF6L1yw6s2Uekvrh4njECQkmUNay
NuxAAs2lTn444wUx9BO+1z+BfprOzC
-----------end_max5_patcher-----------
</code></pre>
