### ISSUE TITLE
[ossia w/ juce] make_zeroconf_server throws bad allocation exception

### ISSUE THREAD

**Issue by benkuper** [OSSIA/libossia#341]
Hello,
i'm trying to take advantage of the zeroconf integration of libossia to declare other OSC servers, but this line throws a bad allocation exception :

`ossia::net::make_zeroconf_server("Test", "_osc._udp", "Test", 6000,6001);`

there is no problem with port availability.
I tried to use Servus aside of ossia but i got "class redefinition" errors, so i guess i gotta make it work through ossia..

I'm on Win 10 x64, using the latest native-win-x64 ossia release

**Comment by jcelerier** [comment]
mh... this is just a very thin wrapper over the servus library so I don't really see what could go wrong: in your case it's equivalent to calling Servus like this

```  
  auto server = std::make_unique<servus::Servus>("Test");
  server->set("LocalPort", "6000");
  server->set("LocalName", "Test");
  server->set("RemotePort", "6001");
  server->set("Description", "Test");
  server->announce(6000, "Test");
```

do you think you could get a stack trace for instance by adding a breakpoint on `throw` ?

**Comment by jcelerier** [comment]
by the way, what happens if you create an osc or minuit server directly in ossia ? those should expose themselves along through zeroconf.

eg 

     ossia::osc_protocol proto{"", 6000, 6001, "Test"};

for instance

**Comment by avilleret** [comment]
is this issue still around there ? or should we close it ?

**Comment by benkuper** [comment]
Didn't test for a long time, you can close it and if I encounter it again I'll recreate
