### ISSUE TITLE
preset do not respect parameter @priority attribute

### ISSUE THREAD

**Issue by matcham** [OSSIA/libossia#344]
recalling a preset do not always respect parameters priority order :
*sometime*, order is reversed !!

<pre><code>
----------begin_max5_patcher----------
1077.3ocyY0zjiZCD8r8uBUbl3EgvfImlK4RpbHUxdKaJWxfFasEHQIDS7ra
s42dzWLlYFFaFaM14hYPtQsdO2c+5l46ymErgumzF.9YveAlM66ymMyrjdgY
t6mETi2WTgaMlETvqqILYPn86jj8Ry52K30.Isl.jby0P.WTRD.ZKPPdfHZI
kZ6bOGqqlxpHRylBcKRKMaEeyW+oX3.K4cxdSibq1JerhXrt2tFrrXGkscsf
THsHBtJcQTH.kEouDGkYurHB725m4Gymq+HbhHulz1h2RdExyyyAvXznHK1s
38blrk9MyIFktXELChFA0v7wQM7MQcoZiEjlJbAYngiPFn7XCYjXXAXZh9xR
CY3dHqCkO1PrOQPvYwSLx+nvxqnouUA1J3cMf3ixTCYirwYi32SL.JO27qdt
AuvHanP7Qgc34B82J4nPPvRB.CZDjVhLD7ElbGgoRLJvUU.pDzpSQvUlLm1u
v52gJJiTv6Xxg39T4NPjGxcVlMf1PPj9hNzwq7hE+8KuoaylJRKsjbRzZMUu
O0XwVJy7cQijrA0A8G7ZAuhKr.LZAJbvGvAQDC3xjmxH06JCWaIteCqpx8Gj
scUXw6krsm8SjsFGYH9jk8Yo84pdj8awOP9eM2u51v8ooGn9jzKh5eKMi+8S
RRqDtPtWN0pgIn2q1vXJh4v9xfKCAYwSnXnO0.Tk+ZHrRWYPPEGWdQU5Rh7H
mjszvIlJcnkWMNofytmKpUGrc.k8fMbt7xHkXOHa1SJHSYnUwSfTTplT8I8i
KdYXAqyhZP4dHdwpL9gGt3wRGnT+A6aTkCumkDuxCYINN4ZkjzUugHN5DTMX
gRlTRDqILrSoK50fO2CXOI11gXR7gVTNce0avrs2ZzCW5u4JfvzqD7GOuf21
RwKdB3f5GWyUiVH98mV4N8Q.nB5.2URtG2UIA5IVuqQP4Bp7wCyicdpMdLTJ
BZmPMYZIRezDYyw3P0D+C3P3kIK4u3wrL67ZvaFEVyKIUfdl4y+xe94dCe1.
.v3kI459+yxSixVo+qU4IP3pmONvIKi6MksXjSWG9QIsgkRQG8nUvzl357wx
eAiT9xGM85BWbuLnIU95lhYnGvrqLi6W3y.zF6Lo3u3UlZbld8myDs7NQQ+V
0+Fs.GbWopQNJCKob1PiTpy.3av1S0S4SwQtSyE4HsX5UxSvI3oDe3nnI3Hj
GbTxTbTrGbDJ+J4nDzT9MxKdJdJdJxGjW5THuUdvS8axwC7x8A6MAG4C+Lkv
g9JHupPKtoQ++MxYswGJwkuZ6gHKzbKkYuEYtUPdf1aehYErPoBHUR.cBq9v
9TaGqA59TDLk1jVFYtFcyc5Hun39Su3weEWyqwq2Q2pf91cRR4ZtP0PuaF8.
WqgOmRvEED1v28oQ7wLDsQ+Ad3MKF5nVg5AdofVPsZmMm0HGCM+Gy+O.jkLm
f
-----------end_max5_patcher-----------
</code></pre>

**Comment by matcham** [comment]
change parameters priority attribute
re-create a preset :
open test1.txt : parameters are still in the same alphabetic order
(is it normal ??)
I mean : where do parameter ordering is supposed to happen ? 
In the model itself ?
(apparently not in the preset file...)

**Comment by avilleret** [comment]
priority are not supported in preset file at all for now

the preset is recall in the order the node appear in the file 
and should be saved (but it's not the case yet) according to priority

sorry for that

**Comment by avilleret** [comment]
moreover this is not specific to `ossia-max` but affect all implementations

**Comment by avilleret** [comment]
@matcham, @bltzr, @jcelerier, @jln- et. al. should preset be save by priority order and then restored as is (trivial for KISS but not for JSON).
Or should the preset be saved without taking priority into account and use priority when restoring ?

On my point of view, the first allow to change parameter loading by editing the preset file and whithout touching parameter priority, but if we need to do weird things like that, this is more likely there is a design issue in the patcher.

What do you guys think ?

**Comment by matcham** [comment]
I like to think the presets as cues : when recalled, they should outputs parameters in the order they are written in the file. It's a sequence of events.
+ this is a nice & easy way to check that the priorities are OK : just open the preset file in a text editor.

if for some reason, priorities need to be changed for one specific preset / cue, it's easier to edit the file that modifying parameters attributes...

**Comment by matcham** [comment]
@avilleret : you said "the preset is recall in the order the node appear in the file"
but this doesn't seem to work either, actually.
(editing manually ~/test1.txt to reorder parameters do not change the way they are recalled when reading the preset file)

**Comment by matcham** [comment]
another example showing that sending 'set' messages to a model to set parameters value in different order DO NOT change the order the values are received by the parameters.

Looks like the model do not send param value immediately, but waits for a while, buffers all received messages and reorder them before sending them to parameters.
Am I right ?

<pre><code>
----------begin_max5_patcher----------
1129.3oc2Y0zjahCD8r8uBUbl0kj.LPNkK6k8zV0laaskKYP1lDPhRHxXmT4
+9pO.aOyXXvikcRkKfQHTq2Sc2uVxee9Lu078zFOvG.+KX1ruOe1LSS5Fl08
7LuJx9rRRioadY7pJJS54aemjtWZZ+ocTFngxxKXaU2qoBhjlCpnMMjszFeP
gD7DW7kF.oAP2WSyTuteTJKXzLdKyLTAcMxZq3sxRpzXXXWqMxCkTiE6+3Zh
LamxpqDpwzBELLYAzGfhP1aP8sv3EPv+08QE4lwfu9y+ANz6jEKX8FDoa6Gy
mqu3OQxoCsuhbpNrplHHUTIU.P3.uKBQz0.wkgFnkfM2PFfhwCfPb+.Ysl7P
M0NJddG6esfpV9jDYAmctcBLFPSd9.X2kiezyXLraYLtbGU72GoszzT2QacN
FgvQoM3MPaV6fVdenMF8I0L7UrlZxTqBAUweRGvUnHK6Xv.BNJWgRl.WcywW
Ck7YwhEMJ2DfZsnsb.necIPv13Jn4VRpA5vAf9w7GC3KfQVpKJ8scFbIqjWr
YCUndCfKxoBEIcw7sXGPWV+bqSergyBBFfsBbV11ACBJXtvGHHvHhfSMqXAo
i49m3LPstUJ4LGD8FDEXWGrQwg8WuzzOZvf20D1VGF.eUo68ACoaNA+2qiqB
O49hVZVo0z1knp3qMOG9NVGgggFVmz0zjUP.gWDokPiFilV9HnogR7QTRfaD
7JfrPIJH4l69.gpcdU4Aea9PPQiRv3qTQipNU0Wc6YLPvHM0DDay2mfFS1.i
t6kcp7PbTYSAo1j51x.Q1HknyQ1FNS1T7MyHErbQBJFEzahb06TUlTRxnma4
yUEReD9KCHX7sRvVAusFfuLSguNlxJTjZ0BCGsnoQRl36Vj2VslJb.7BwwVg
DbuGvvvK8z3zkbZEkQVaMBbLj6XUGmg9tE2tx5GG8nneYf+kc64MMEjEmzSd
sTxG0yKfpZJvGyoaHpRqGNcx6xKBhrYUFMJI78Djbe4o5wnnA2e+6wUK1PTA
iu+9feIXnJdNsDnp9lKJjG9ze9Oexc6AcoU2Id7i4nebx3kbg86gKP3nvT8N
thSWBiSz+JIMDgT+Bc13bO21JQJEsE8yN8S8aTwPUNQeNs+HtNddWClXB58a
Al6Rhz4T7VfFcKf1zCS4zu3rRMSKc6OmIZ3shr9wu+D3.mlX4zFYAybNAm0I
8Ynn6zEY6IaI3ixR8CxnVB6.CE+nPzxGF0EMAK8b50rkkgCFmpkS+YYXzTVE
i9YA4WL6NZY3MY4vIX4TG3NELEDF4B+1IEJpgDx0b4jBYtOKiZsi2zzgtfdm
Rt6fWYHq5DotVeVFcc1XCkh7msEBE6adrfYez7Wr4Inesnu+glVHBkHqTov1
Jrxu6WZq91SWbmfoDzsgiJzMuSl9EJhLUgwlO8uHU7JxpcEaUPe6NIMeEWn1
XS2wT30Ut7yoDRVFkIOq9Mj8zxi5N2bSEaVn62Qs5C39k0K3UoF4h9UdMCM+
Gy+e.tu8rHA
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
> I like to think the presets as cues : when recalled, they should outputs parameters in the order they are written in the file. It's a sequence of events.

I completely agree about this

also I guess it's much more efficient if there is not priority test when sending (because that certainly takes some time, and time is a critical asset when recalling a cue)

so I +100 this!

**Comment by jln-** [comment]
> so I +100 this!

+ whatever, as well

I also make a separate issue with @matcham patch example

**Comment by avilleret** [comment]
the only way to solve this is to reimplement `apply_preset` method in ossia_pd / ossia_max and to fire the value as they come (and don't wait for the callback)

**Comment by avilleret** [comment]
@bltzr, @matcham @jln- could you test that ?
