### ISSUE TITLE
[ossia-max] model namespace message should output parameters in @priority order (?)

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#345]
IMHO namespace message should output parameters regarding priority attribute, no ?
(that would be very convenient in order to build homemade preset / cue manager !!!)

<pre><code>
----------begin_max5_patcher----------
651.3ocwW87aaBCF8L7WgkOyhrARBrS4xtrSSZ81zTjCwKwUfMxX5RTU+ee9
WzRSPIzV5xkX7Ge1O+dwuOadLL.tQbf1.AeE7KPPvigAA1Pl.A99AvJxghRR
iMMHm9Wwl6gQtWonGT1v0RFW0Ek2Vw3kTkcDXeP1Vah5A+krdIJZUcYh7QaT
GKo1j6xqlnJ1y36VKoEJ2pMIeFJBfQotFjoINdFB7ayPdJLz7SzHIUEsogri
dFq3D8apIEzAYV74LawvLC+1YVZxr4QfkIuvK+HbSq5XM0kND9tnrdAtgJu3
+X0Dol+JpbMkS13V3ny4b9vbN9sv43EYNhFaZliFAqi.vMD9taM6wymN5iw+
un+vlXQSCiL6YhCpNtVn1Sk+34HqLKAf1pCVsk9GRaoBjmmCVos+BIScDf6l
zRFmVHZ4p9hw0JLjNgZYF1zjjZKPjL+Zh4msPVeIMDGmzSCi+PZXxzogtpOI
X7MSBqDaokfNk4tu8y65RrPTJjNvQyvwySyizOrLeAZYl4or7TLV+Dt2p9ZR
W7jU81ob3k3Oqx2DkR1xtXALSJcmMakO3.UuPS.k86VRcbdTUutobFOcbFOG
+NIsMOqC+jqeYAyD+0JQinUVzMU9MqfWPaKsQw3DESv6kSlKmA05whiQttJP
oS.Poi.m7ofPnQ.TxD.TxHvwb8gOLPKFAPwmgiaGHot9AprwmrEBsq6dWs0k
Q1tLtqahsqj9.qK+TaDhTaOTZuQqzYbNrvcRNzT+Vx0lVi+JzPtPuA6jc8la
ZaG52IUhJx58rcZluauhtcsPpuni+J3P+QluVQHEETtp2QBVWIxbCZqwD+x2
ED4UVod.m5zgU5Y1tVQdEJ7ov+QtPGA2
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
this is a good idea, what do @bltzr and others think about it ?

**Comment by avilleret** [comment]
what about adding a parameter to choose sorting criteria to [namespace( message ?
something like [namespace name( to sort by name, [namespace priority( by priority and so on

the priority listing is almost ready

**Comment by jln-** [comment]
Didn't we discussed something like 'namespace name_of_a_device' sent to ossia object at some point ? Or did I dream about it ?

Otherwise, yes, something as simple as that would be great !

**Comment by avilleret** [comment]
I remember you evoked an option to get the namespace of all devices inside Max/Pd from the `[ossia]` object but IIRC I was not strongly convinced by the idea :-)

**Comment by avilleret** [comment]
here is the discussion about such a feature: https://github.com/OSSIA/libossia/issues/269

**Comment by blueyeti** [comment]
+1 to have an argument to the namespace message to get values sort by priority. I'm developing a preset system outside of ossia.device and I cannot get the parameters in the right order.

**Comment by avilleret** [comment]
currently ossia preset are recalled in by priority order iirc
but I'll reopen this issue since it seems to be relevant

**Comment by avilleret** [comment]
this is fixed since a while
