### ISSUE TITLE
ossia.remote doesnt output value on view connection when bound parameter repetitions==0

### ISSUE THREAD

**Issue by jln-** [ossia/libossia#346]
When sending 'address my_model' to an ossia.view, containing ossia.remotes do not output parameter value if the parameters has its repetitions attributes set to 0. See model and view patcher below.

<pre><code>
----------begin_max5_patcher----------
1246.3oc6Z80bppCD+Y7SACO6sCADTOO06miNmwIBQMmClvjDrs2yzu627GP
CpXSqGv1N8gR0cSxt42t4WHa7Oi7BVReBwC7+g+C9dd+YjmmVjRfW828B1Be
Jq.x0MKXYITjsAwBFaTtCidbGliWhKvhmUMATqgtZEGILic3cgiUO7+YsxBZ
1uQ44L3ZdFiVTnZVXstrBb1uEaXzp0arkiHvkEnMm1AihcmpX45szbTKITVt
z4sbS87ASVufgxp81j34J+cRj5Yx7YluDY49jpsXRARvsGaoPZk3XokLDGQD
PAlRdS1.mqAb5xe8OQMnMZ6RT9IduYB4sOh4ErBKwCDiKsoUq8BfkkVh8r5h
JL+KpdflMduHLwHJbuHFREsM8+fTHShgB4jqhog6fmRmDbXXjAAFoBqcEivW
F03RGfjzXEHLCndlNQmxLYlURiJdZxarMd.sDQvDaXtk5bzJXUgXwJJQvw+m
18.JT+L5WAyPc1YBbqYt8uLLrnY1ErlgyoDkSzBoUhaL2C9fD0rQ87vjQ2BB
r7LcVFyknRGJ4xIYEeIjoW1UnsPTiRAkVzV099UfVIpUWhIjiPQAsrakL75M
WnuKoRkauzXq0vWTQLZWHoSDK3vcsQaArnffdTN6OZ3eBRvagBj.aBAQg6Ud
Bo.nslcmQStLGNC8HNWX3WrSFjMGW1jDErOJmiWi3h1xDRxq1R3hmMftknpF
FyEBz1xB4rncCZw.aufzlItk7iXj2h3b3Zz9kaJOC8jwWgRJVoZ+M3MX6Fbp
i1AUHPuTwGDpWNNUuB0lk5T1vn1JrXDA1l57rhNYNKhQPps+ark34x5UcAA9
+rQ6KiF07gw+8.Zmww33v6Rjyk45IVRXOiiNYtyrAyMBFOIesjVRsaPAlfxn
UDwwHSq4emsx8vzzIJnJN0B2hS5uvjKlyJLMa.CSqJnx4y6JYOJI0jvM20jc
PmnXzqihNYNKTbda2mI2WWHomM6Wz58ZNKJOV9RvPx5fVC+JJStAkpIo+EiA
0aFdtUJTNGCuig1REnSVt3d9NXlEzABmdMgpXGR3cxd1D7gAuVvP+2GFhdPz
jgjn2IyYgmS+fQzmAyf2BhdP5rgjn2IyYElR9bPz2juML77tXMKLL8KGM+wK
VdquE+dZ2zdll2M6YEqlbCX4eUTWUZqq5PSwolRYbMn8a3PSWzb16o9NHWNT
1BE2aGmWUCEJ8mG84zJVViYpeQL+1do772BLYeQbd3vKAnZnSA+2pSj5nSLo
G8A0XCbvGlZZWu4CtfCo8LND4fOjzi3.v0DBPOBDMY7upSLuucBWBGy5yvQn
iqMh5zIpEZjneZbruuti5yOGd3lHlLedebaGupINy1SesurilTjuupiuupiu
upi9+np.SkmhmENHmU0IyYQ5E+o4vpWeLHZdxPFCtr49ZVvf8dutzv92q7Se
YjCJ7uulnW9xR2yPkRhFErw8AW0xp35+AFn0UW1dtWvywefplVS9ZRzft73h
lqqZR9EmhBjNcHiAW1bcUmrO2TTp2St38+CSvfU0+PALL78XI1bwZ2nqS+Mr
Wfp9wNsWP3UweALWuQ7PQfcY64dgOGOnE+bpiU3I9CPsOm1y076lWtMG8gjN
8gyUiI8.dbUHTtwQUe3nJObZUG5thCGWsAokeYz+CXOHQsB
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
I like the code snippet you're always including in your report

**Comment by avilleret** [comment]
btw this only happen is the parameter value have not been set (I mean the default value is not output by the remote)

**Comment by avilleret** [comment]
but the default value is not output by the parameter itself either

**Comment by avilleret** [comment]
it does work in pd, this is max specific

**Comment by avilleret** [comment]
one more strange behavior in Max : when opening your test patcher, the default values are output from ossia.parameter or not randomly on loading...

**Comment by bltzr** [comment]
is this still happening ? because, with a fresh build, everything seemed to work OK - or did I miss anything ?

**Comment by jln-** [comment]
With a build from a couple of days ago, there is still a problem. But Antoine may have fixed this since ?

> one more strange behavior in Max : when opening your test patcher, the default values are output from ossia.parameter or not randomly on loading

Actually, this doesnt seem random here. If I open Max, then open the test patch from disk, parameter 'caca' does output its default value (1) on loading.

If I close patcher, then re-open, parameter 'caca' wont output its default value.

If I quit Max then re-do the above steps, I get the same result again.

In both casesn remote binding to 'caca' parameter wont output value when the view binds to the model

**Comment by bltzr** [comment]
or did I completely miss the point ?

**Comment by avilleret** [comment]
what does not work for me : 

the default value is not fired from the remote when binding the view to a model and if the parameter as its `repetitions` attribute set to 0

all with this patcher: 
<pre><code>----------begin_max5_patcher----------
1325.3oc6YssbihCD8Y7WAEO6MEha1deJy2QpsbICx1ZVrDEHRxrSk+8UW.L
XavxwFBoFdAmzsDz8oa0R8Q+dlg0F56nLKy+17ESCieOyvPJRHvn3+MrN.eO
LFlIGlEA8FcyOslqTwPuyjhSLOPiPwkxSfrv8Xxt0onPl50657j8bS2Uhm9t
hmNbIl+SwLvQx2C+c+WffxWCI+.lDiXxOscgvL1uhQxAWaXzb1oiSZCnzBeo
vYLr1hiQuhRyvThPEXdgbXRRMwF0lh.A9IU9hVLuRDlnD4VIJE8Jtb9dURgo
bjfwgg7TkU+dfm0wWCG0RI4XoonD9wrRS5H3szS.X.GI5E3YK9wao8Q7iG11
ESC+WTTMHvvhlfHXRRJJCQXPVgwUoNBsElGyVukRXY3+SZe.Qb5B52BCQsNY
B7fx49QJFVlEXXsKEGQIBinATKDW94dwD3K8M+5NibDDXxElLOCgCKsnLi6j
4YafohHwFUZhSoRFkF2TU07hQaYEpSvDxInHilztxT7t8cL2MTtxCc8tkZxV
mSTZWyWpwVmAesIZyfwwEq8Z95eGRvGfLDCqBAN1UJQDH2Q2mElRiia3uJMu
dAMQ7j3Pza3H1d4Gpdx.e33jxjHqpnbDdGJi0TFCtKqojyV1xEkuoXQ5ZF5P
RL2KZNfFUmpuhrdUpFxOoZ01XJu3P0xsKWYB.VJKMsTtrx29zZSpxFzTNJKl
PPMopxNrekTjKyMcSqMPxNqFStVwM25FSi5afFVYJeEEiCLpHU8XtTesUz2p
mbdf37ZnNkJ9X1rx+X9.DCbV4O.wffAHFzsmLzwfF6Z2bmaZVFF9TkyZlPSn
lOKfSSdjCxLetnPuIv074TTBuRivkyLAZttRsmuq2kghKF9ZMzsPqP2nNE22
Y.Rw8GhT7N8jwbL.DrX.hAdCPLnaOYzUlQ1jf4d3d3UBTJGBXW7iulkNZKT3
7vJa.9ZpJGBCgsTU1oYUYaMKCArqUb9NqJC50pxGaKHFSZ67fROUn+x3dFMO
MrzWJ1HwroKyOeKCSpZR5kpyqIFmVQ8a0FBzzFVzi1fml1.nGsAfl1feq1Pg
vxVmsDsOEsV0p3ZHikh2jyToN04B3lZog2e8FXbQCKUM71U+MGaBZ1Q6U9Tg
ZC.eKKAZv2h+DeKS7sLw2xDeKS7sLw2xDeKiE9Vbb9j7srbhukI9Vl3aYhuk
R9Vv6w2BeKqFF5VZAo0wT9VxTiCXholIlZlXp4OMlZdEidqKhZBTbMHWr642
ISMNSL0bJSMpdu.fEST0LQUyDUMZejlCnrL3NzEOSCLJhutHSmKpCXKYXdg7
4R267fif1OehyW3w+zBqt9grAxBHkGscwcCVAZAVs1PiFFyXBn4IWWAeccse
xWPETWzw8H5hQC3UKaYLlGK3ip9.DmNLjlSXc53sOpKDlVHucE2fZPiq+mNL
s7tBS5XKCcXRKpUb7CT4TqF.pUV0mTqnkmL5nVIEcfxPmsb4R46E8wq7Of8h
anO9N6k29dnYQOqRGX2cfpPE7j601f0w6QtAvh6Z+Ucrkw3F.BBr52M..AKe
ja.3eWgIcrkQ4F.koTq9teCd53Hi0x+mtXo8S8WUnM3AU926dp9qmQMzU+uJ
pWiJsq0jkhVs.u6sIqG.J2ss7YKtzKjsuRWRlsGArs60yrsCzjwevWLi+A8L
N3nIi+8EN.BFCW8AXLXD1ZZDq5aiPmbhk8YNgslKPcZ0H99cUTR28z6iQXWm
bOLmbGLme+Kse2KmduK7u7Gy9e7aDS.N
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
fixed in v1.2.3
