### ISSUE TITLE
[ossia-max][ossia-pd] remotes send a 'set' message without any arg on initialization when bound param has no default value

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#367]
remotes send a 'set' message without any arg on initialization when bound param has no default value.

The bound parameter does not output anything on loading, as expected.

This seems to only happen with parameter of type 'list', as shown below.

FYI, there was the same issue with Jamoma and parameter of type array. Not sure if and how it was fixed.

<pre><code>
----------begin_max5_patcher----------
1234.3ocyX0sbaxCD8Z7SACW63hDf+46pljGiLc7H.Ya0BBFgriyWm9tWgDf
ALfUwgjbS7jcQZO5rqNZk98LCK+jy3LKy+y7ESCieOyvPZJ2fQw+aXEiNGDg
xjelULNKCsGaMW4Ki+VDV5nzRJhGbfP2ukgC3pY1c0xE1yM8VCj+3k+WHbgs
4OJFC8XbxQdDlKiAnvpxD+sTrZZrrpF.ITFyD+e9.nJvLbFlxQbRB8eL3DZY
rg419yrY4+YtlTBE+p.HkvfiOKirESferYFlOJtxYiVbErWtZdO70RM4qg.v
jvWIYYDzBFNNQPaeK9sswIgeKHHXLzm6lU4+.7.2f+bFj+5iCWoGGNLJtPhf
QPhs1GVwh1K7LsWLFNCBmhsmd5QUCF76qbqOlxGQ2OpZKvxIfmb0rjZnf+0S
FyYk6DIiAbzivFDAe8HLvZ3DQXZxWCBfONceee+QUu4.UJtNShtOTyZtAQw8
o6+uPhHDZT0ftKmTRTySOGFF2GK5KW8XVIRNQvudhjQ7IQD9aMTu2sKeqrDX
O3J0RdXkWMrDkD7KbXHCsOKfkDEk+o1E9BhHA+hePnHr+Pc6XJxOBe35Anbb
5ZG96EITbCKIrPwBnFT6HiBWqz.UUkpiN.d8lPs6Pm0tjivw93vFwq6zmNw7
R1ytN3UqGipjlg0NhfNvrLQHpEZCKTZZMyF0FRdl9mIxIZ87JSDpxjckIFNO
gqF+EqHlfB4h0xQlZ6x40kMLmOMhb.idjTU1Iq4lUNgUL.T16ryFYk6RWa4I
2qsuvA4ITUgS8vakjhoDZcdsg6P7NzwH91cITdF4+k.DjK0zg+cn.buClhhU
qtGYDTT45yZOiDlPyAQCtN2bY3dwD3o1UVewH+BJJsiAKpgD7RONyDKxiY9H
lbumRfBV5jmjD0zU03hv63EtSITZKVjmj1uSFY+gAFqehvY7PyszS11iTk2s
BME91LzolrMGEEUHU2b5OinjXDGyIpT.ztx4UpBfldN0gmPQUb.9URHWIvTu
XP74jzxhHqprbHYONi2zFWnd0zxUGXHLcrT1bKGGmFIVEM+fFOlP8sj0kiaX
evV06AG8H0A.NJcGo7yF21GZzeG52nK895TeHMPcASqFpLJOIqPYYjzXidDZ
1mPJiP4lO+7yihicWUaUsDnAEa2MGtVCNTyf0pQfomBUsZkhXBQTNlYFDDX9
87BGycQIH98PrpCMAqs0fYgCV7NefB3M5S92DPSC6+NnC.UMQNg5.qzWG3lf
4SRG3omd5NJWKVUdaFuNvRsKEuYv9v0ATT3iO93cPgf0atWJzSaJ7lA6SWJU
bq+BozHR18njBcTcotxcRURczu78l.5Sm7QHTMx276EWXvT9hx2SMdwE38VN
o4Bn96CtIf9jxE4WuLxT83MihvgdxCpA1pefvI6vOfFrs1nYX59x0LiHz9te
gjLx82cdHK4HKnbQUzCjYSbHtuDmPqtz8KUMp156t7rKZUZLU.SbKDSP2.yd
R.lil.a0WUfs7iNUB0DXdpuqyR+YWrT7DmxIr4VA0Kd1FdEu64UvZUcXMLW0
4KqpabVpQb.phk6JNNZDGu2g3.0g3bdGHNnND26Qf.5PctWQcpJvVu.adLZ8
xqsd00qew09es01uzpHx+Y1eATWfilC
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
Pd might be affected too

**Comment by jln-** [comment]
Fixed in ossia-max.

Need testing in ossia-pd ?

**Comment by jln-** [comment]
Maybe @bltzr would you mind checking in Pd ?

That being said, as it is now, remotes binding to a parameter of type list with no default value output nothing.

remotes binding to a parameter of type float with no default value output '0.'

Both parameters output nothing. I think it is not critical for now but maybe at some point we'd have to think about something consistant between types and parameters/remotes?

What do you guys think ? @bltzr @avilleret @jcelerier

**Comment by bltzr** [comment]
>  remotes binding to a parameter of type list with no default value output nothing.

don't they output an empty list, instead (since there's a set message)

concerning the parameters, I think they should output the default default value:
- 0. for floats
- empty list (even though I don't know if there's such a thing in Max) for lists

would that make sense ?

I'll try to have a look at pd, but I haven't reinstalled it yet, since my recent clean OS install, so I might forget... or maybe @avilleret you can try that ?

**Comment by jln-** [comment]
Not sure I totally follow you: in any case remote and parameter should both output something, right ? (and the same thing)

I bet outputting an empty list will cause troubles in some patch. 

I think that default list value could be anything - if I decide when building a model NOT to set a default list value, chances are that when I'll use that model in a use case, this default value fitting what I need are thin.

**Comment by avilleret** [comment]
it seems to work fine on ossia-max but no for ossia-pd
