### ISSUE TITLE
[ossia-max] set message on remote is broken with parameter of type list IF list is less than 5 items

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#368]
When sending to remote's inlet 'set value', bound parameter outputs value but not the remote. OK.

If parameter is of type list, both parameter and remote outputs value when sending 'set a list of values' to remote's input.

I think we discussed this one but could not find any issue. Sorry if I missed it.

<pre><code>
----------begin_max5_patcher----------
1636.3ocyZ88iahCD94r+UXgN0m1tELPH4dpaa08xIc8k6spSQFvIwsDaDX1
t6U0+2O+Cf.IAvKAZNotIamA64a9lwiGa1eb2BqP1y3bKvuC9BXwheb2hEJQ
RAKJ++KrNfdNJAkqdLqH1gCXJ25dsNN9YtR9evx.78XPN5aX.aKfiy4D5t6E
BI4.TRNCrGklho.xV.BDi2hJR3fmPIEXglbPHVnSHlPww.BEjhxPGvbbVkoR
DZhXETk87JEllgyEvAwIL5lK9D47WRvJHVMQoHdzdA11jgi3ZeOvY0C12C7c
Ue43aK+Zo3Sv+TNHZwAVAOAyUzfcoTRrZlYge8sqrtDjdklfPqrfiT1Ou6N4
G2aXrIrfyYTqWii6uN3AeApV6K+B5IAk7yN7amRoZQ7WRw5owJDQ2YUOnFzB
b.ZwD.bcrx1DlXNdcrhKThCufUJroBUPXmrBrKVw59dXF2J.rkkc.or7xA3p
gfU8ZlMXJJT6m12xrKMfmurKOKiXrYL65.NOGsCeV8vbLG7aN.Wf2nXLGUHd
oy.YdcxXWjs7Mjs5y3GYK3HXKJ96BfbFYwxyInGxvGXbL3cGdYyAV76hiiGE
0IVW3KKv5N.2412pV0OWhCCLjC6EE2px7dNdy0BQOypy2KBtAzhJSG5rtBNS
Ms3NHsLLBtNZoqF19qO+2e9Oe.HqSUVCS76z3xNx3riMfAdya.kqMiY3bfv8
SKTstcwVybGr0L2QzZlqePi9l7BdMsl4AMq2r9sw7DFLMFHxtaFDnLdYb3WR
LvV2zJDN9XfyPw.SrwspSPXYWpyTmfAisUvtw0+SaEb9J05BMam4YrT63yub
bT8ILW4W1iM+pabMq4W82T8nHXOUocuosgZ3Jyx4505WWG0ieo370LniiYzx
L1L37brLW2fY3XYKMis503+5NVFBgF0BvUq06qOOGKCZ34x5GFWWN2qgEihh
FUB3x05iU5LKrngqa6GEWYqEJm+3s99DA+8mH4jPRBg+RqEWa2JVMqA1ag9R
n7VYE1Zrjvh9FNNNCsKOJikjzbKpnDRz236yXE612Ttdyr8mO.shmNWQ3NQ7
r01egrrXgCz.pWHfBazEhmshVCja1ZdG0N06piODhiaYuKG9LwlGid1MAu1e
VTGzDsRPDzANKWXhFldgEJMsg3EMFhLR+UlZhVcesHBUKxtVTFVFv0i+nTTl
fB4BeoHSuZ44UUENkSiHFjQKH0ocpbt6plvJFvw1dod8uhJV5oOkwpFWCuLh
pybZZeKVJlRnMI1VpKeeFa1xn7bx+pPnijguf9snHbmClJ5pR4dOlQpOf8Bq
cYjXFUBhVjsTbk4Ddmu12Z5LpmfhRuvfEIQBhoCk4BmrHODkoV7oKPAqTxYr
j1ppGWBdKuTcJgROgE4rztUlQ1sumwFxDJOz2bqzjuofp0tQTTguIG8Ta1li
RRJKU2d5eFQIhtiwbhND.sqUdVYAm1Zd5BZhEowQ3uSh45JLMSFDONIsJIxp
NJGS1gy4skwEkuZK4rMLDhJppatgiOjlH7h1OPq2yWy0jMqG2Rdeat0dCtzL
BkC9zm9TSsmCxt1YS0Z7RG86C6rcT5tVXWu.td2.yLicxVXKp1FqrrxzSg5d
DNdaOwwwf2K20FjPx4f2W85RseP7Oe4WuWv5rLwVhf0quBd2OPUOz0yDhG1P
ykarn0faDaVabrYX.8KO3nyu+3G+30vy1AWa9cf4b3PF6FQge3CeXbTndWZs
Wo24dbT3RSnPyL1MhBe7wGuBJzEZesTnuwT3fF6lWkUbHrVUYmlRpdA5yV5Y
OqkT8Ltbvv.5lGIBCCKiDaSXnVa342Ht3X6bMY+K0as.WOqAFWyWgLHft4AF
DB0Yf4JBEvU567y2aVCEPiCECCnaTnPdv1Df9ViFEgC0Nn3juMd8ZCv3N8x3
cw1NFv1Fil9o6imuU9RM63fMJxPp+xwgbVQVTkSU1jJnMNhU+QLVeZ+uTePC
4yYTVvqECdFhgfYDCtFhgkyHFfFhA+NwPoPsjxKgTMgsSYz2I4ovq7lIOCV9
Mg0vglyt6SSsibNbFvNvIxNC4OdSfcbMvN9SfcVZfcblB+wDha4TXHaCLDb0
DXopIoeKMEI2PSxt8bmJKMjO4NEKjbLwk7lHCMXF94o35Jemb27Rabxcxex8
we9cw288ve5cvKr7Ou6+.Ku54BB
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
Finally found back the issue about this. https://github.com/OSSIA/libossia/issues/261

So yes, the method was added at some point, but seems it broke with type list.

**Comment by jln-** [comment]
Well, I am missing something I guess. 'set' message seems to be working ok with the test patch provided in this issue: https://github.com/OSSIA/libossia/issues/355

*head scratching*

<pre><code>
----------begin_max5_patcher----------
1594.3oc6ZssjZiCD8YluBWt1GYmXIiMl7T1Of8KHYKJAVvnDiDkrLgrox9s
u5huHavXALlLUpT0DXltkkN5nVcKcb99SS7WwNhy88du2G8lL46OMYh1jxvj
x+dh+Nzw0Ynbcy7Wy1sCSE9SM9D3iBs8CD7WqLlK9VFVasxxdjX8KD51kb7Z
gY3hAyeNXp2hH0mfn.0WP4md+S4yPK1wJDYXgdfCJsRR0cLa0m+yn5dmiykX
BIHL5UNBDZ0..T19wSOo9X5cRF6Xo3rqhMfPfFkAI2LcLa.5vog393iU5YFl
WgjCHNEsyL42xddGZ+dL++d1NVQ86GH4jUjLh3a5AtzCaylbbI10X0FpYr0e
AmlxQayWyYYY1bx5Lx5uHdgyJ19hscLEsJC+xoOfwwgScrZqZkrkEFOUN+rf
4YVLmEFpvahNvKFBUeMKIt2Ey5Yr1j3a6wl9w2u4A5gFk+wQIB7OMb.VYCua
ENsEhOe7gSn1J9vd9anjI0gES72PjLJlmKGCqVOwWhcKySrdDUrzmY5NJYZs
IB0XJn1DGqhWLOeiUDWtJHjSlBtgnNlD62zMxkQNsfTGXqipeppCqnf4g5.s
nXcdCf4qXq3NUHgIzydz8Y6wTB0lWa4NEuAUjIVtgQE4j+UiOfheOi+Mn03d
e35nf+hSPUIXl3ukSRYTEHZQ0JyUC2Gka3Ma6smL5VPQ6OyCKCgjzRONykSx
h7UHtdmqI6FrxofwxZ6p94xvaDkt2SnzNrnfsuembx1WtvythIct6R8s1S9x
Bpw6RYRKwxbzg1rs.kkQweUN66z8GQTxNj.KHlk.XPsySxq.Z64vY7jJChWi
+JIUXRQYGLHaNYeUPj+ei16sGwkq7BL2iw83XYLN06.Jq.m6IXdHJSH2A1tU
6v44ns35XjTxVbtvtLjZxt0j2VkQQlBap2lB5Z8H2rR2o3kzTQUZ9kB7t8YR
RocCZclB6M31kOZYuSYjNXuUoUYIAIa07CP+i92sa+o3tuBuQ5Dcf45hivEl
phPqcI8ludfb1cSHCBZAkdJR6JbZRDCqrqKVWlZ6FY9MYLYeeaDYH34HIx0E
QhbgFgWjFmJONAhtsW5btMd1v3xMmJewNvwNfz58RKM6gaUr4rGU5UZEvgX+
+.3EXE52Ixu0jNiPwqYETQW99ZWVmMWSYvjQa6QhuyqbCBlwYywpBYMF5cs4
.X1VOq5yakEu3NiX2YxAAz3DjeGLYHTug8wvjf4NPkthnwgJKOrx4RWvxyIn
m43cLAttx96pyrkeOQxIlIa.vg7AgCkmW+udyKbEgyChpwYMvLotI5LdlB2K
.5LZP8QzgQWjMCNOME5Rnpii1IWxybs5RwN5NqHzT7wWaJUCgahQiJKNTM4F
jPusxUgNP2tAkF1N3mEaOXRDkTCduKsHeqci58zEuxmAYAngGi0Z5ENFKof1
mn7r2Uux04uI9EhEbaNb47SMWbWwo8bEKM+o7e908bVAecEUTke0qMPjWAUP
n05X7wl6u3AZ0vZwvBbJX7pgliHqZJLJfXtqfXDwfyqQm1tF8JGOjAbI5Ydu
7SoQik6Uw4eAkS1jzvnK6rfE5uVD1qZxvdUSd5PJJqeuE8KoL3ZkT1EjeR4u
eoTTNLoQP44IIlr++VP4eKn7uET9AJn7cn2Ph997y.IOB4FfNbPRGAziWcxR
I46WYRm47Yg56mFGade0QillivYNP3thlwQzwAXbvyyl+J8lP.wA1QVgw5o8
n7lPbQRGmgy3v6Cdk3ljimQZMuOn3AuLRtv6Cb7dYVdUKxk6I9PY8WuA2u7n
tdMvnGTXj9Eh.muvgaXO36t4BuFrEtr56Jld3ppJuIPwsob8Bs3aF0fV7y80
L5FVdyoVJLQmEHIB9PjK00g6F0KE91fTMwBPvLmULsGNMx4.uAGr2.JPOXA.
8kk8TZhpxoWeFauO4iSIBOjGihUmlV8UJRf7JOT7m7uikIvrDSlvvwKAxXJC
pqyhwI0CRH3xqraMTJKZWVEo8umhnvP6+2UNJqOgWQ8yAgyOAEmANJlYzHpn
pVLamT8dTAwBWQA7QKr6Ufs3G86EPsCvwWYwhQb4Sc6w6FFmS7acW1UWSER5
nmYGsLOUGy90vrq9kxQ9GO8+.RAuR3B
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
OOOOOk. This was a fun one. Set method is broken only when list has less than 5 items:

<pre><code>
----------begin_max5_patcher----------
734.3ocyX9sjZBCEF+Z7ofgoWZcH72Pup22K5CPmNNQMqksPhSRXqN6ru6kD
.WaUBw.p6LNfbLjuy4Ge4LAecli2J5dL2y8Kt+v0w40YNNpPx.NsW63Uh1ut
.wUCyaMsrDSDdya9MAduPEeEi9aLoKLWbn.qh2EYGRr9W4jsKY30hFAifIK7
m6FBCjm.w9xSA0Gc+Y6MQpJoUhBrPoseaz7MpYlt54OG3eb9YXdcdgD4Tx0p
QNoSBfL1aylIOL+wQD+TqIBHyPhnUiOZDIHLxdh.MiH5031Pju+ManQTbn8z
HwLZnWiwQimJn0ywUU4gvvSdF0lTA8V3AsQaBINrC2LM0RTaCQjsdGuwSYSX
WF7DkUhTRmnmVClW6PLTIVfYKwDzplB0ep.YIlyQawmYq3Xg6m.t9Vg3D3h3
5RAL.hA8h3Kh1HOy.oN0eGVA2UWW6ZgakqCXqqq+75g55b8Wz7wJVCSkFfrI
19EXl8Sq5OJ6W6lWtQ1uLace8mVe.beVY8.IxG9ovo054an0Sm5iy50Gx7Wj
dbspkLKsYe0YwSJyhMCYZEebHif+SchbFwnbdNZwQ+sa4gkE4bg6WkUjayW2
feBUUHFiOTUOoiZ89E4ZnoVQMIviZqeg.vMrKXp0cA6MsdzcAsBxQwxlPIS6
xYnY1NshOtkyqpDBJwFhDCyToST2wqkH8Z4RLiJZSfwYhrfJQopmQ2Np.RG5
8SMHCFGVz16mgKoBbWieqbTwpLG.FZeFgZ6u2WOdno9JsowkInZDdE4j+++L
TUsx3+KV4zJ15trtK4beWnMXtHmnRvSFT6Xt3StqRHv.BI8ZiWICpH3TTRol
HzDnSlA5H2T6nEpaRt8nS9J1CWSASgRA2sZJzjZJZJTJ5dUSlTRwMKrOqqDZ
2tWvLd6fURT2V+YJSdIbt5xbRykpsg4wvuj2M9lHHVcOaQcmxJVS278scS8J
oavLRUdaGwZkea1eALHyEWM
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
0_ô

**Comment by jln-** [comment]
Actually, then I guess that's what Antoine meant with this comment, here https://github.com/OSSIA/libossia/issues/261 :

> this should work but user should take care of value type

@avilleret Am I right understanding that 3 items-long lists MUST be vec3f type, 4 items-long lists MUST be vec4f ?

**Comment by bltzr** [comment]
I'm sorry I have to say that, but "it works on my machine"
did you try with the latest build ?

![lists](https://user-images.githubusercontent.com/113982/36091293-971939b6-0fe3-11e8-82e9-758b6387c2b7.gif)

**Comment by jln-** [comment]
Hein ? Bah ça marche carrément pas non plus dans ton gif... remote should not output anything in any of the cases in your example. At least that's what I expect.

This is with the build you sent to @matcham and I last friday. As replied to your mail, the one you sent yesterday unfortunately crashes Max when opening a simple patcher... :-(

**Comment by bltzr** [comment]
Oh yeah, sur this is (set), sorry about the noise

**Comment by avilleret** [comment]
@bltzr could you bisect this one and tell which commit break the things ?

**Comment by bltzr** [comment]
@jln- do you know if that has ever worked ? could you test with old builds ? then I can setup the bisect thing from that on...

**Comment by jln-** [comment]
Not sure if I tested it with list type. Maybe did I test with vec3f ?

I just tested with the release from 14th october (b7) and the `set` is not yet implemented with type list (or vec3f). Next Mac release goes to b12 where I get the same broken result as reported here.

Not sure it helps...

**Comment by bltzr** [comment]
I think it helps, because that seems to point to the fact that this never worked at all

thanks !
