### ISSUE TITLE
bogus deken filenames

### ISSUE THREAD

**Issue by umlaeute** [OSSIA/libossia#375]
i see two recent uploads to deken, which have weird names:

>     ossia-vv1.0.0-b18-(Linux-amd64-64)-externals.tar.gz ... 2018-02-26 19:41:02

this has an actual version that starts with `v`, which will always sort after numbers. so it will appear on top of (e.g.) version *2.0* of ossia (if you get the version string right again: `ossia-v2.0-...`)

>     ossia-v-(W32-i386-32)-externals.zip ... 2018-02-26 16:34:10

if you want an empty version, you should omit the version part entirely.

also, i don't think that `W32` is a recognized architecture in deken, so when searching for "ossia" on a W32-Pd, all results will be marked as "incompatible" and will be displayed as "greyed out" (though you still can click on them).
The OS should be `Windows` instead.

**Comment by avilleret** [comment]
thanks for reporting that

**Comment by avilleret** [comment]
I renamed all the files for the 1.0.0-b18 release directly on puredata.info
and I updated the script that build and push package to Deken
