### ISSUE TITLE
please don't use `l_ia64` for Linux/amd64

### ISSUE THREAD

**Issue by umlaeute** [OSSIA/libossia#376]
`ia64` is really the itanium architecture, which you are most likely not supporting.

there's a bug in Pd, that uses the `ia64` extension for the `x86_64` architecture, but in order to fix that bug it shouldn't be used widespread.

so please use `pd_linux` for now.

**Comment by avilleret** [comment]
ho sorry, I was mistaken
but then, there is no possibility to distinguish `x86_64` and `i386` architecture ?
I know the later would disappear in a not so far future, but I was dreaming one day of making a fat package for Linux that contains several arch.

**Comment by umlaeute** [comment]
btw `.l_i386` as an extension for Linux/i386 is fine.
it's just that `l_ia64` is plain wrong.

also this really only matters if you want to ship packages that have both/multiple architectures (which afaict, you currently don't do)
