### ISSUE TITLE
[ossia-max] parameter triggering dict query freeze Max (forever)

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#378]
(only when overdrive is enabled)
when a messages that trigs a dict query passes by a ossia.parameter, it can freeze Max forever.
When the same message comes from Max or passes thru a deferlow object, no problemo.
Looks like a scheduler issue... ?

<pre><code>
----------begin_max5_patcher----------
1099.3oc0YssjahCD8Y6uBJd1wCHC13jWxy6VakOfcS4RFZ6Qo.gWgvwSRk+
8na3KiMiz.Lyj4EQ4l1m18gS2pQ9miG4ut7.T468Qu+0azneNdzHkIogQlOO
xu.eHMGWobyOsrn.nb+I56wgCbk8u72Ml1wfJgGXNojthAobM7QyBlFLQbQt
hlqVEV79p4qUweHGTPcDHLO8dBc6y.DZcAglCb0u0PiQRlB1x0e6CgI9m7rr
l23Zfz3uFOVtLomLw+fO3sgAvOfJuMkLXOvrPMgIQmxpvv3twMVQwJ4D9xSN
VkIyl2eUhELrwCKe4oAfhWmCdeQnMxXj8fERINNTkEQIpmsAAciWrCiUIx7g
ianv2EPdE0jWhyVioacjRVnRhXUFgPckQZEEqDRzsIjFW0l3OrCzAzWkZdes
C7UATUg2BWQXe5+XB+7D7DTri6crHNmPgzxZpxKzsXS6dbMSsbg7hdcV7M46
LXCtNm6.s2JXWP6naP6ydlzd2n700bdI0sM1luPWa0r1oM1ZEDa5PzqlLrkx
15ePjcTBBbisVFedKHTGoq1Qwl.J9170rmjulb5JQVz7hIoLakGtLpOZJqnX
s4F5Mu41Vf6QnDtaDFJR0WItipJqnXSUs3OmtR5Yf5WSIKXXU9D7doojNQ6Y
OIafXS7fV7dnmT+TT1.w51bIuWjTlLsmZJqnXSTE8VooZg9DyFBr7xu61TBg
wymF2+wDdBXrJ3rLe+5sok4kLySKI7AGWBOKNCTq+VX0xpJBd5NLCW.bf4IX
.bdNx6yx.5UwYDquOUCUgzklAQ8iwaGFqLdKCcfZkIm7pvlOGxrYxKMKDpeA
mNW8+DvXcK32ZtLijx8tKsFplJVxIUbuOCEqgrSumpkQ5Vn4f3k8alt1gwVK
zV1xIpMNTlxhTAydPwlSNxpluPFliMDogIEgSNhqwViwQ9aJlFd2VLgJukXZ
bwO8Kt0Nr5NAO1tP3tiSJT+fPWc2TLiQ.1caXv+WCzzGTYSz09UyK2r4R2RD
sPiCmMa9hK8snLqNW8D7NBMCTBkvqP7LuXxKp.eoSn1yWTK4K5IyWji4K5l4
abPvU94RthrlqUYaL4h1hpbSUvYD238P1Jg9SnjWg4htNhozzGU+4BGUszYE
+xZ.SeqU5CY73wyYBgotVIGUmQziN9eUMjz9kE6Uk0rzFIt4DG7NUDkAUbBU
kum4Sr1ma1Nw03D6PbPnAHPKbHPICPbhbHNgCPbPINDnngHPtvbgCwiHTzqV
jbQdiFB1KzobZ1PDIWxoECQfBbg7FjH0M8ft4Gd2t8.qx3sJFhYZ9ldZ9jIp
ORn5OpZb6yf8jF+0VvLw.GbQO5ZldTjCI5+hDewF..iVSTMmGqarqGY4QMbo
X8NW9+Etnr.u5dxVQpu8dtr+OS7dXlSE634peAkfSSECOc8KgDe9KgL9zNKx
8GDegGO6jeg.YRydERFZ7uF+a6jl8o.
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
this sounds like an overdrive side effect and I'm not sure can fix Max bugs with ossia-max.

**Comment by bltzr** [comment]
@matcham : @jln- told me you had another problem with overdrive - could you please explain how to reproduce it ?

**Comment by matcham** [comment]
I just noticed that my big patch randomly freeze if overdrive is on (no need to uzi a dict ) 
ossia.parameter is just not compatible with overdrive. I've managed to live without overdrive until now, but it remains a real problem, and don't know how we will deal with that the day someone will want to do accurate timing in Max...

**Comment by bltzr** [comment]
Hi @matcham yes, Overdrive is widely used in Max, and thus at some point we should fix that to support it (but that requires quite a bit of work)

As a memento, here’s what @jcelerier said about it on gitter:

@jcelerier Apr 04 16:36
> https://cycling74.com/tutorials/advanced-max-learning-about-threading
> Only when overdrive is enabled, are high priority events actually given priority over low priority events. With overdrive on, Max will use two threads for the execution of events so that high priority events can interrupt and be executed before a low priority event has finished.

est-ce que du coup il ne faudrait pas s'assurer que tous les évènements ossia soient dans la même "catégorie" pour pas qu'il n'y ait de pb ?
(et s'assurer que les messages en entrée soient aussi dans la bonne catégorie)

Pascal Baltazar @bltzr Apr 04 16:38
bonne question

Pascal Baltazar @bltzr Apr 04 16:38
j’imagine que les 2 threads c’est dû au fait que l’interface est super lourde
problème qu’on n’a évidemment pas avec pd

Jean-Michaël Celerier @jcelerier Apr 04 16:40
bah c'est surtout pour pouvoir faire plus d'évènements en parallèle
l'initiative est louable mais il faut que tous les objets jouent le jeu pour que ça crash pas


Let’s hope somebody find the time or resources to work on that. Maybe we should do a kickstarter ? ;-p

**Comment by jcelerier** [comment]
I tried to look into it this morning, and noticed indeed the problem of @matcham, starting at 3000 messages (it works fine at 2000). The weird thing is that when debugging, the stack trace didn't seem to pass through ossia objects when stuck

**Comment by bltzr** [comment]
strangely enough, I just tried your example patcher with overdrive on (audio on and off) and it didn't freeze.... no conclusion on this, just noticing

**Comment by jcelerier** [comment]
I wasn't on the last commit, so maybe disregard my message :p

**Comment by avilleret** [comment]
I can't make max freeze with @matcham test patcher with f2863e19
So closing this one.
Feel free to open another issue with an updated version of the freezing patcher
