### ISSUE TITLE
[ossia-max] scripting a model cause ALL models to reinitialize

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#381]
When creating a model via scripting, all models in patcher get reinitialized. This does not happen when creating a model "by hand".

I think it's fine that the scripted model get initialized but models already in the patcher should not get initialized again.

At least, in my case, it makes my patch go https://media.giphy.com/media/Eb4HAUeQrq608/giphy.gif as I have a model with a parameter that script number of needed submodels... :-)

<pre><code>
----------begin_max5_patcher----------
997.3oc6XsraaqCDcs7Wg.6V2.IY0Xma2z9CbAtqCJLnjnkYKEo.IkicKx+d
4CIYRY6TUmGN3BugIYF9XlyL7HdxulD.xXaQBP3+DdeXPvulDDXLoMDz92Af
J31bBTXlFHqFJyWi3foVmavnG1fE3LLAK2omRbqG1pUBjzt2Q2DMUOD9sVmD
V9OPEEbXoHmyHD8zhZ8kSv4+PtlyZJW6ZGQgYDz5CWf0wlCcjUVwJPdVX7BU
v6DlzlJLkfjB2oUyQBDUBkXFcIGk2lFyVXRjjOoGmklZ9i424jWpci0HGtcn
pLTg6gZ.QLs7uZuwls.vx99GS.tajMgB5qXAfUXEdf3BU36brA.Xcsi4.mkn
KyemY1nES6MgoVSQ8l3Hc01t98VgbU5HU4RC2.2fsKtEreaTEANsAaBEqwGm
zERNHP5LSRe2B8OtM0fGoKbZazUTami6wCX0HJl5Vy7bWfVAaHxkqXTo.+SS
.FmbyQ8uBliN4hovJa18UNFR5xOPIGWvn5fvCq0l6Nt6CiM0U839jwLCJr9H
KVUjU3xIbJTIYiHCxMW7HlSHoyojwH9t5WGAsR15tFSoCPQIq9zN43x0OwZy
XJmUO0da7HV1PsdWpHTjKEvM9nsDRHTzCprev1uERwUPIRhskfjndmGPKD66
YyQ7Tn5hyQOfKjVFF2lA0zw0cMQf9pbAtDIj91jJ5KeKB4NKn6XpoiyboDUU
STYg+D73fcuR5xE6YeHmbiB8o822FRpE633DDawVZm3Ywlafoci88pGxs4tq
Vyxc0sM6fLHsD3s3CAlSvCNpPwgJLNFzY+wIS59komITVgDBXIxMFkns1xdz
IQ3j+LBOO1Iq9jkpO47A3yDbGST3fsoujPa685igrLg.CuoFxUDrRDOTQEE9
Ec1FhoxvuzxAGF8rZwizT9g2Y5tRlMlJPxSVAld1UgQEJdes+srLn+ZMIri0
ZWxyAzShLcZ2Y65leg55GST3xnbL3d+WsIX5onqMms1+wqCBVCOuKWZeFWne
Xn97iDS6eCy8c2CUAt271+L1Q0Z7ZEXJx2gSrOxhNJJNYuEynMZup73Oo7H8
0S3Q530cDeU2wUcGW0cbU2wUcGuc5NrMFg19SU719apWHqlQ3ppkhcTU+zyP
bRrUVvBaRmL6B8NsQEFNkf4uQuKVtFK7e7w40ra6rLeBH714WRAHiHRbv4Yt
aWG2oJB9v+piAOzID7Y8vG9O8HhVXsz9ruW+qJwW0neg0nG+RJRe96GQ5yeW
KR+kSid76BM5wueznOejRgmYm2EUN9+q++DXV8Pkj5fafBxApGOT43oUMNTw
n5jebxuANRIV6.
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
[scripting_bug.zip](https://github.com/OSSIA/libossia/files/1845397/scripting_bug.zip)

Strangely, I can replicate the behavior with this patcher of mine only if main patcher as an ossia.device in it. If no ossia.device is present, model does not get initialized again (expected behavior).

**Comment by avilleret** [comment]
hum... another Max' strange behavior...
my guess is that scripted object received a loadbang while 'created by hand' ones doesn't

**Comment by jln-** [comment]
This seems to be fixed as I cant reproduce the problem anymore. Do you fixed this @avilleret or is it a side effect of another fix ?

**Comment by avilleret** [comment]
there where a bug in the loadbang routine that I fixed few days ago, it might fix this one as well
