### ISSUE TITLE
[ossia-pd][ossia-max] ossia.model outputs absolute addresses when asked for namespace

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#382]
Sending the message 'namespace' to ossia.model causes output of all parameters' address in the model as absolute addresses.

It would be handy (and consistent with ossia.device) if addresses were output as relative addresses (no leading slash).

**Comment by avilleret** [comment]
it seems to be relative addresses with leading slash in ossia-pd, is it the same in ossia-max ?

**Comment by avilleret** [comment]
should  be fixed in 07ce184f33f000112cf6cd5eccba9ec5b6ca5526
could you try  @jln- ?

**Comment by jln-** [comment]
it is ! Thanks @avilleret !

**Comment by jln-** [comment]
@matcham -> Note that this got fixed and that cue_manager will need to be updated accordingly
