### ISSUE TITLE
[ossia-max] remotes output wrong address after number of instances changed

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#384]
Assuming a model with several instances of a parameter (ie. `source.n/position`) that are declared dynamically, remotes binding to the parameter, either with full address (ie. `source.1/position`) or pattern matching (ie. `source!/position`) output a wrong address (in that case `position` - stripping the `source.n/` part) once the number of instances got changed in the model.

Using the test patch below, use to following steps to reproduce:

- Set `source.1/position` to some values using the remote in the view;
-> Value is properly sent to parameter ; both remotes (with full address or pattern-matched) output the value and correct address;
- Change the number of instances in the model using the message box `address source.{1..4}/position`

=> BUG : Remotes are still connected to parameter but output `position` as address.

- resetting address in the topmost remote make it output the correct address again (`address source!/position`
- alternatively send the `address /spat` message to ossia.view make all remotes properly output addresses again

<pre><code>
----------begin_max5_patcher----------
1946.3oc6bs0aaaCE9YmeErBCHs.Ith5lkVwJ1kG16aX6k1g.ZKZa1JKZHQm
KKn+22QjRxR1V1TIQRdEAnvoljhmO9cN7i2D8iWLxXJ+dZpA5GQeBMZziWLZ
jLorDFk+8QFqH2OKhjJKlwL9pUzXgwUp7Dz6ExzuF8mTAJkuIYFcL98q4oLA
iGiDbHwUTzsjnMzTzlTV7BjXIEkPWwETDKV9saYz69vmi+b70eD82YEEwRQq
S3qoIQOfRAKlUSqIIjUTAMA8AzTtXYdkjhd6cL3ay2DEgHggIzzTDOAJt.Ja
70qHhYKoguCw2HVuQnLnzHj3PzLdRBcln3AUn.8aKIwKnxhFuY0Tvj74.XSE
j3YfAyg8JdHMpRiZETAD3w.NDcYARxIkGwiG67sRl4xL67SeD8q+0uC72ej2
PHITTpfAsiY73X.Vzv5M7o.9yaFWVVUHRZA7GqfO7eoBQFrJPQNhE70q3ohB
5eE4q.UKpxL6vGHxBB7rucmlya11PdmxjjnLxlHX2RUtrPY0U9buOE7GWVRQ
PqhmlxHiyb8JbPflcgGsz2mir7Zglimh3uHFPR7MwxfPradpqyZ9wBRF7tIq
wnhvCLmL17JD1zI6ONSjeyxzerI5exeRvWyhinBYvNdah.JJR0LO0TwCQTYr
eAXVmEmAbd6LIKTVI7oe4ZGirj91EWj8wUZ1ibpzrzjBTjwm2xRYSYQLwCUa
G74ygnBEvLy.hYEXDwm8UJPxjEoyR3QQUapyhXy9pXYBeyhkUSmFSlFQWt+C
nx318yX5hrtL0RgmDBfuBLav643XmgYWESp9iqYPSNOyi57Nfq5z0OEzABqh
zJtNqZAApFznRO1Hi4LfOnIoPapRMLxfrdckjGU4QxbyegKqH+qJShEqRxrL
oDZl2V87aSkj.sOAz31jnBRu22yXa0.Ngj3MLITTIBAbWTTgEThOVxBXEy34
HCZbsc2xIYdTUjSUya.8ciYwUcj0xNjNmrIRbybdrHk8uR.hsFev7mSlQa7g
iAUQYq6WRXjnh1mwhDVHONCD035rjKL2m.0BYaqViQVhXx5C7vfSF3kFxDFV
PrIcJIQ1wSIKXUjofyipmU4yEQmKxydMCz6qyhfVcyYlvVr7HOKL7nfu5X0s
Lmza1Dqx8FPPQbSJ415rs.Dkio2As9cp96IwLXfUpfobAVlkYtmr.tdN2dfb
Bgn3Yz6XgBkBS0fAn3r0EAQFkd4P1BZpndZBP9pdJ6ISCIsoPy7FAc05HnUT
u.0lUT0tjU0hqk9NZx4CxU1gq5LkpMdX0RzftmsqLP0W9AVN9gUkX18D9rpm
QEwObkb1mVZPVTCyqLg3g048rLLpkcUURWihzkixkK7zgrb9jurJmthFLN1T
1Zs87Tpet8NoqGBZAu6LP7NtU7NVMYIemAi20BAsf2sGFd+Msg1ck8psUCGZ
Gz6jtN1uETt0KIkCK2RnEIZYaolguriqkSwmMyh3WVVTK.rGMNEVkayTIdHo
Rq.ugkJON.ZGUhmLLTokZ.Da7PQk5.fVRkunygXdDGZl5qRZOQstvCpRUtMM
2nlnaskjoOSa8LTQOJ91WE8pCQ1y4IvL6yJhWCtff9ZXse.CKE.9m9NH0Tlb
FrgwNp8awvXlCXTNVMm+y1n7iiuWrnb+y1n77InNXQ4G295Gki8dIo378o3P
LbBfIZwlHqy.mlxs7xQMqTeqmCO+jBz0B.GLRuYxF2WwyOkEcGDTY5qXK6dO
xVK.zhPaq9hswic2W9n1AiX0D8qWopvQdUBJUxu01M3N2Gog8agKxtmTeTGz
U9Qt8T5bjO2h.Ur4DM1EvlG209YL4liCfCKGcTIImya8eKW6gU++3.nc5+98
r7Ot8x+4K4d3j+OA.zWaIn+T+w3f9U+OOnbvz+Ot8ag9u4.p+iau9uE1aX0+
OA.Zu9+jyT4ebfbaT78GH0ecre6D+8Nqm6uckMIbPD+0A.5Kr3983T+s2FQN
DJ+m1756ebFNc+mvIy4ohJ8bGHU+ia+1K5a0qru70KT220B+xW0g.6mCa+jB
wOowawLaNDEu80bJqueCueKRbkk+g4dUPbt4yeiNtBUGlgzTAKt7s95SEPRV
Nsb8sFD1ZBhIcIHbzkIb5RTXoIJr5PP3qIFBfxgqGhW9xfNn.COYuBVhLyNA
YYFzRCj42gtsI64NZfcLUErS.gmltH29N1QWfgc66XGKyyBkGMif85XLnSDr
SGF.iCzUA1rCYBr1Rcco+.6cFLvL1QWcM6tLrvQy9G3tblREU9oCNw8sJl1P
Ca0No+bpTkxqWtllW3S9Uewz8k9p0bpZ+XWrF72iWrl.O0d54aV4h033a95E
q40KVyqWrld5HdcCTuj+C0l7qE.NuOh21csZTutX3IpMa2p+e40zCA5uMaS9
Nbe9ssqPQCvF8qi802C4MP26octr+F5x6dlp8ZeR+eO+zv9mqmvx1edD1+Gf
heNCtnHVpPamPwA.57rNwEqmQz+wAP6FSneOtE0uHFZebKtvzdkm3Qv.bbKm
v3mkG2hlqQ1qC2ICc2jstbqpc9ezobLoQewg1YBYEt6pWyfwNqZcmUrt+pUa
dkp6tJUvxe6h+CXtqD8F
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
the problem doesn't seem to be happening in pd, I'm attaching @jln- 's patcher ported to pd

(though, we can notice that each message is output twice, which is probably unrelated)


[bug384.pd.zip](https://github.com/OSSIA/libossia/files/1876064/bug384.pd.zip)

**Comment by jln-** [comment]
Holy sh*t ! Thanks a bunch !

@avilleret président !

**Comment by avilleret** [comment]
oops
I was too much enthusiastic 
I just got a crash when opening `384-address_output_persistence.maxtest.maxpat` 
more work is needed on this side

**Comment by avilleret** [comment]
after double checking the crash might be related to #377 because it only crashes when reopening the patcher.
when opening it as the first patcher after Max launching it works fine

**Comment by avilleret** [comment]
this seems to be fixed now
