### ISSUE TITLE
[ossia-cpp] set_min() and set_max() do not work

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#386]
No notice, and the values are set to 0

tested with get_min() and remotely (with score)

**Comment by bltzr** [comment]
Thanks, that works !

Though, brackets are still missing for single values, e.g. in the OSCQuery JSON: 
- from my ossia-cpp app:
```
"size" : {
          "ACCESS" : 3,
          "CLIPMODE" : "None",
          "DEFAULT_VALUE" : 10,
          "FULL_PATH" : "\/renderer\/size",
          "RANGE" : {
            "MAX" : 100,
            "MIN" : 0
          },
          "TYPE" : "f",
          "VALUE" : 28.571399688720703
        }
```
- from VVOSCQueryServer:
```
        "my_float" : {
          "ACCESS" : 3,
          "CLIPMODE" : [
            "none"
          ],
          "DESCRIPTION" : "test float node",
          "FULL_PATH" : "\/test\/my_float",
          "RANGE" : [
            {
              "MAX" : 100,
              "MIN" : 0
            }
          ],
          "TAGS" : [
            "float input"
          ],
          "TYPE" : "f",
          "UNIT" : [
            "percent"
          ]
        },
```

The spec example shows brackets,  and the spec tells that:
> RANGE The value stored at this string is an array
So I guess we need brackets, as they are the JSON marker for an array, aren't they ?

Should I open a separate issue for that ?

**Comment by jcelerier** [comment]
> Should I open a separate issue for that ?

yes please !

**Comment by bltzr** [comment]
done!
