### ISSUE TITLE
[ossia-cpp] add helper function like `list_all_child`

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#391]
this function is helpful at least for debugging
some other could be also wrapped

**Comment by bltzr** [comment]
shouldn't it be call list_all_children, instead ?

**Comment by jln-** [comment]
I'd say may_i_ask_shall_you_list_all_children_please

**Comment by avilleret** [comment]
finally I choosse `get_namespace` 

see ef925b861a1137800e4a4fbb8dfdaaee5761acda
