### ISSUE TITLE
brackets are missing for single values in the OSCQuery JSON

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#395]
as mentioned in #386 

brackets are still missing for single values in the OSCQuery JSON:

from my ossia-cpp app:
"size" : {
          "ACCESS" : 3,
          "FULL_PATH" : "\/renderer\/size",
          "RANGE" : {
            "MAX" : 100,
            "MIN" : 0
          },
          "TYPE" : "f",
          "VALUE" : 28.571399688720703
        }
from VVOSCQueryServer:
        "my_float" : {
          "ACCESS" : 3,
          "DESCRIPTION" : "test float node",
          "FULL_PATH" : "\/test\/my_float",
          "RANGE" : [
            {
              "MAX" : 100,
              "MIN" : 0
            }
          ],
          "TYPE" : "f",
        },
The spec example shows brackets, and the spec tells that:

RANGE The value stored at this string is an array
So I guess we need brackets, as they are the JSON marker for an array, aren't they ?

**Comment by bltzr** [comment]
as reported on http://forum.ossia.io/t/issue-in-oscquery-implementation/77 this apparently breaks compatibility with other OSCquery implementations, which is a bit of a pity

would you have the time to have a look into it @jcelerier ?

I believe there was an issue with RANGE as well, isn't it ?

**Comment by mattbeghin** [comment]
I tried to control MadMapper (version 3.3) with Score and all values non array values have value "0" (rgba colours are ok for instance) because of this issue. It's easy to support both notations so you keep compatibilty with existing projects.

**Comment by jcelerier** [comment]
hmm, I thought that this proposal had been merged but it looks like it's not the case: https://github.com/Vidvox/OSCQueryProposal/issues/35
