### ISSUE TITLE
[ossia-max] refresh namespace when sending the [namespace] message

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#400]
sending the [namespace] message should do the same than when doing "refresh namespace" in score, i.e. it's not possible to do what's demonstrated in https://github.com/OSSIA/score/issues/682#issuecomment-397826277

**Comment by avilleret** [comment]
I'm sorry I don't understand what is not working and what you're expecting.

could you provide a patcher that demonstrate what is not working ?
and explain a little bit more what you're expecting

thanks

**Comment by avilleret** [comment]
ping @bltzr could you explain a little bit more ?

**Comment by avilleret** [comment]
@bltzr is this still relevant ? or could we close it ?

**Comment by bltzr** [comment]
will try

**Comment by bltzr** [comment]
yes, interval names are updated when sending the namespace message - there is still an issue with new names not being output by ossia.client - will update the relevant issue or make a new one

**Comment by avilleret** [comment]
to sumup a private discussion with @bltzr here, this issue was about the support of node creation, deletion and renaming.
The relevant callback have been added. [ø.client] object now outputs messages like : 

    node created foo
    node rename dev:/foo dev:/bar
    node removed bar

@bltzr could you check that it is OK for you in Max ?

**Comment by bltzr** [comment]
I cannot build for now

and, this might be related, but I can only access score's parameters (e.g. interval speeds) only after the scenario is reloaded, not just after creating objects....
tested with this: https://github.com/OSSIA/score-user-library/commit/eed4ba41e99a7425287b48b13f1aed335d060331

so I'll check that as soon as I have a working ossia-max build, and make an issue in score if that's where it should be done
