### ISSUE TITLE
remove extraneous braces from vecnfs when publishing them on OSCQuery

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#412]
currently, this how they look:
```
"VALUE" : [
            [
              0.020999999716877939,
              0.079999998211860657,
              0.079999998211860657,
              0.020999999716877939
            ]
          ]
```
while they should look like this:
```
"VALUE" : [
              0.020999999716877939,
              0.079999998211860657,
              0.079999998211860657,
              0.020999999716877939
          ]
```

**Comment by bltzr** [comment]
from what I see in score, there might be the same problem affecting the VALUES attribute

<img width="111" alt="image" src="https://user-images.githubusercontent.com/113982/43643306-34593cac-972b-11e8-9c91-22804709ff10.png">

**Comment by jcelerier** [comment]
also default values aren't correct

**Comment by bltzr** [comment]
depending on the outcome of https://github.com/Vidvox/OSCQueryProposal/issues/47
we should put back extra braces around the color values arrays

**Comment by bltzr** [comment]
and maybe around all (at least all those with units), if my observation there shows up to be right: https://github.com/Vidvox/OSCQueryProposal/issues/38#issuecomment-411158778

(-> our implementation would have been right from start, without us even knowing that it was - maybe because it was just consistent)
