### ISSUE TITLE
[ossia-max] models inside poly~ do not reset when changing number of voices

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#415]
See attached patch

[poly_init_bug.zip](https://github.com/OSSIA/libossia/files/2259803/poly_init_bug.zip)

**Comment by jln-** [comment]
Do you mean the 415-poly_reset.maxtest.maxpat ?

None of the tests in there passes here. Do they pass on your machine ?

And by the way, in my test patch above, after changing the number of voices of the poly~, the remotes in the model loose their connection to the parameter. I do not remember but I guess this was not the case before, was it ?

**Comment by avilleret** [comment]
> Do you mean the 415-poly_reset.maxtest.maxpat ?

yes

> None of the tests in there passes here. Do they pass on your machine ?

yes, all. less than 2 sec after opening the patcher, the toggle on the bottom of the patcher switches on
which means each instance in the poly~ have been correctly initialized

> And by the way, in my test patch above, after changing the number of voices of the poly~, the remotes in the model loose their connection to the parameter. I do not remember but I guess this was not the case before, was it ?

I think it was working before, and it still works fine here.
what's the build SHA you see in Max console after OSSIA library loading message ?

**Comment by avilleret** [comment]
this seems to be fixed, could confirm @jln- ? and reopen if needed
