### ISSUE TITLE
rgba8 Colors should output and receive 32-bits "r" OSC type data 

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#417]
currently, with this unit (only present in https://github.com/OSSIA/libossia/tree/feature/color_u-revamp for now), data is sent and received via OSC a vec4f (aka OSC type 'ffff' ) while marked as OSC type 'r'

obviously, this doesn't work (ie we cannot send data from OSCQuery Browser or Vezér)

we should, then, make a special (generic) case that, when receiving or emitting a type 'r' value (which is, rgba8 for ossia apps, a generic color for most other clients), unpacks/packs the 4 RGBA values into a single 32-bit value  

this could also (maybe ?) be displayed (as is the convention in graphic design/web/processing) in the hex format, such as ```0xCC006699``` so that is made perfectly clear ?
although, this is applying for OSC communication only, not internally, so I'm not very sure of this last assertion...

**Comment by bltzr** [comment]
I think I have completed the change of default value from ```argb``` to ```rgba8``` in https://github.com/OSSIA/libossia/tree/feature/color_u-revamp

Would you be able to check it @jcelerier ?
Are there tests we could run against this to make sure I didn't break anything ?

Also, now that a decision has been reached about the "r" question, as stated by Ray [here](url
https://github.com/Vidvox/OSCQueryProposal/issues/47#issuecomment-411807577) shouldn't we do as I suggested above:
> we should, then, make a special (generic) case that, when receiving or emitting a type 'r' value (which is, rgba8 for ossia apps, a generic color for most other clients), unpacks/packs the 4 RGBA values into a single 32-bit value

And if we want a better, floating-point precision color to communicate with more clever softwares than those just accepting "r" for colors, then we just need to choose another color unit (such as "rgb") as only "rgba8" set OSCQuery TYPE field to "r" (the others set it to "ffff"). 
  
If you point me towards where this is implemented (I searched a little but didn't find it), I could try to do it myself if that's not too hard.

**Comment by jcelerier** [comment]
> And if we want a better, floating-point precision color to communicate with more clever softwares than those just accepting "r" for colors, then we just need to choose another color unit (such as "rgb") as only "rgba8" sets OSCQuery TYPE field to "r" (the others set it to "ffff").

- typetag.cpp:72 should become rgba8 instead of rgba
- typetag.cpp:148 should become rgba8 instead of rgba
- the complicated part: changing the types ossia::net::osc_outbound_visitor and ossia::oscquery::osc_outbound_visitor which write ossia::value in OSC messages (the difference between these two is that the first one has "strict OSC 1.0 required types" compliance, basically like Minuit with booleans being 0/1 for instance, while the oscquery one supports bools, etc since it's meant to be more open). 

A good way to do this would be to change the calls to `val.apply(osc_outbound_visitor{...})` into  

    ossia::apply(osc_outbound_visitor{...}, val, addr.unit()); 

and change the osc_outbound_visitor to add the following cases:

    void operator()(const std::array<float, 4>& value, ossia::rgba8_u) {
      uint32_t v = 0; 
      v += ((uint32_t) value[0]) << 24;
      v += ((uint32_t) value[1]) << 16;
      // etc... not sure about the formula / endinanness but you get it
    }

    void operator()(const std::vector<ossia::value>& value, ossia::rgba8_u) {
      if(value.size() == 4) {
        if(value[0].get_type() == ossia::val_type::INT && ... )
        {
          uint32_t v = 0; 
          v += ((uint32_t) *value[0].target<int>()) << 24;
          v += ((uint32_t) *value[1].target<int>()) << 16; // ...
      }
      else if(value[0].get_type() == ossia::val_type::FLOAT && ... )
      { /* same than vec4f type but with .target<float>() } 
      else 
      { /* just send the values ? there must have been an user error somewhere... */ }
    }

and change all the others into 

    template<typename T>
    void operator()(int, const T&) { ...} 
    template<typename T>
    void operator()(float, const T&) { ...}  

(of course, other special cases can be added for the other OSC types such as timetag, etc...)

**Comment by bltzr** [comment]
> typetag.cpp:72 should become rgba8 instead of rgba
typetag.cpp:148 should become rgba8 instead of rgba

that had been already done!


For the rest, I won't have the time today, but I'll look into it tomorrow

**Comment by bltzr** [comment]
for the record, for tests:

CMake with -DOSSIA_TESTING=1 then ```make test``` 
or in qtcreator :
https://files.gitter.im/OSSIA/b235/tests.webm

**Comment by bltzr** [comment]
I have been as far as I could on that, only for the OSC protocol, for now.
 I haven't even begun with OSCQuery, because it seems slightly different: there's no ```val.apply(osc_outbound_visitor{...})```, it directly goes into a ```oscpack::MessageGenerator<oscquery::osc_outbound_visitor>```, but first things first

the (well at least, one of the) problem(s) seems to be that ```ossia::apply()``` doesn't want an unit as third argument
```
ossia::apply(osc_outbound_visitor{...}, val, addr.unit());  
```
https://github.com/OSSIA/libossia/commit/0c8e8b9079dab6479ec66545606e06aee2f0b0fd#diff-6aefb29778abaec42508e3c00675cea2R197

any hint on this @jcelerier ?

**Comment by bltzr** [comment]
we should also remind to change the attribute values to the ```#FFFFFFFF``` format for:
- DEFAULT_VALUE 
- RANGE
- VALUE

**Comment by bltzr** [comment]
I also investigated (without success) how to actually convert received "r" values to internal `rgba8_u` `vec4f`s, but we should not forget this either

**Comment by bltzr** [comment]
> I also investigated (without success) how to actually convert received "r" values to internal rgba8_u vec4fs, but we should not forget this either

if that helps in any way, here's what I did:
https://github.com/OSSIA/libossia/commit/91a6eeac303e54579ee0e20856ca23884a44208d

**Comment by jcelerier** [comment]
should be ok, please reopen if there are other problems
