### ISSUE TITLE
error in OpenGL conversion ?

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#419]
compare:
https://github.com/OSSIA/libossia/blob/11a58827c6dcdd47d29d709455e52c851684d646/OSSIA/ossia/network/dataspace/position.hpp#L128
and
https://github.com/OSSIA/libossia/blob/11a58827c6dcdd47d29d709455e52c851684d646/OSSIA/ossia/network/dataspace/position.hpp#L134

is this normal that different members are inverted in both converted, @jcelerier ?

**Comment by jcelerier** [comment]
I just followed this : https://github.com/jamoma/JamomaCore/blob/master/Foundation/extensions/DataspaceLib/source/PositionDataspace.cpp#L202 but this seems correct.

neutral is `[X, Y, Z]`, OpenGL (https://learnopengl.com/img/getting-started/coordinate_systems_right_handed.png) is `[X' = X, Y' = -Z, Z' = Y]` so the reverse is `[ X = X', Y = Z', Z = -Y']`

**Comment by bltzr** [comment]
OK, fine!

I tried to mentally (well, with the help of my left hand's three fingers)?make the conversion, and that was too much for my overheated brain 

So let's close this one, thanks!

**Comment by jcelerier** [comment]
> (well, with the help of my left hand's three fingers)

haha, well there's your problem, it should be done with the right hand
