### ISSUE TITLE
use HOST_INFO "name" value to name devices

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#430]
currently, it uses the zeroconf name, but it would be nicer to use the info provided by the HOST_INFO "name" field

this was first filed as https://github.com/OSSIA/score/issues/816 but I guess this belongs rather in libossia than in score, doesn't it ?

I'm marking this release-critical - it isn't really that *critical* but it could be nice to have this in the next OSC Query-compliant release

**Comment by jcelerier** [comment]
> this was first filed as OSSIA/score#816 but I guess this belongs rather in libossia than in score, doesn't it ?

no, since it's not the lib which gives a name to the device but the user of the lib - for instance one may want to give it another more precise name if the HOST_INFO name is not descriptive enough.

**Comment by bltzr** [comment]
so this one could be closed, right ?
