### ISSUE TITLE
update OSC Query implementation for last version of specs

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#431]
since https://github.com/Vidvox/OSCQueryProposal/commit/ddb64be6378825e0a27c2c34550d18db2b4f32b6 our "units" are currently split into OSC Query's UNIT and EXTENDED_TYPE attributes, so we need to update this.

I have done this on https://github.com/bltzr/libossia/tree/feature/unit-xtype-split but not in the most skilful way (forgive my incompetence) nor in a complete way: the order of accessor can now be arbitrary, so this might need to be checked, and the management of colors might be reviewed extensively (in particular because our implementation doesn't cover all cases, in particular because alpha is generalized in OSC Query, now).

I guess this is going to be a little bit of work - I'm sorry for contributing to this change

I'm marking this release-critical - it isn't really that critical but it could be nice to have this in the next OSC Query-compliant release

**Comment by jcelerier** [comment]
should be in master now, please test

**Comment by bltzr** [comment]
seems OK now
