### ISSUE TITLE
[ossia-max/pd] Max/pd crashes when trying to connect to an existing device

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#432]
(or when trying to connect for the second time to a non-exisiting one)

this can be easily reproduced eg. with client-example.pd (and device-example.pd) in the examples folder

**Comment by bltzr** [comment]
a few crash logs as requested by @avilleret 
https://gist.github.com/bltzr/323ba405cc4d1cda5dd96cb15629c2d2
https://gist.github.com/bltzr/15fe68765de0d50ac3b408372ee5a53b
https://gist.github.com/bltzr/b222680436353f8b82453279c7efc84f
https://gist.github.com/bltzr/570408b92a4e524fec69bf3fe56927ad

**Comment by jcelerier** [comment]
hmm I fiddled with client-example.pd and device-example.pd and everything seems to work fine (except the "dump" message should be "namespace" instead maybe in client-example.pd ? @avilleret ?)

**Comment by avilleret** [comment]
@jcelerier yes `dump` has been renamed to `namespace` a while ago

**Comment by avilleret** [comment]
seems to work now, could you check and reopen the issue if needed @bltzr ?
