### ISSUE TITLE
[ossia-cpp] device creation problem

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#433]
If understand correctly ossia-cpp98.cpp when declaring a new oscqueryserver (which I'm doing [here](https://github.com/bltzr/ofxOscQuery/blob/9b3c09cbd412215d6c8dbceade563699412d9ea8/example-singleServer/src/ofApp.h#L30), as this seems to be the usual way in of) an `oscquery_server` is declared with default ports, until (and if) it is assigned different ports
so, if there's another libossia implementation with the same port, somewhere on the network, this will fail and, in the best case, throw an error (or just crash)

BTW, since this is what zeroconf is for, shouldn't we try and find an available port if the desired port is taken ? that would probably mean changing the way devices are stored (e.g. in score), but wouldn't that be more clever ? I guess that's up for debate...

**Comment by jcelerier** [comment]
>  this will fail and, in the best case, throw an error

well that's the point. It's the responsibility of the application to choose if it wants to use another port, tell the user it cannot connect, etc... I don't think the lib is the right place to handle this. If you want to use another port just do a try / catch and retry with the same port +1 for instance

**Comment by bltzr** [comment]
Good point!

I tried, thanks for catching it! ;-p 

Pascal Baltazar

**Comment by bltzr** [comment]
OK, so I guess this can be closed as well, doesn't it ?

maybe a more informative error could be useful, BTW, like "port:n is not available"... but this is managed by websocketpp, isn't it ?
