### ISSUE TITLE
[ossia-cpp] Error reporting 

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#434]
Currently this api does not report errors and just tries to keep chugging along. Should it ? In which ways ? error codes, exceptions ?

**Comment by avilleret** [comment]
maybe the simplest solution is to output error on std::cerr
someone who needs better error handling uses fast API

imho exceptions add a lot of verbosity to catch them and someone who is using opp in some creative coding environment doesn't want to bother with catching error, I guess.

what do you think @jcelerier

**Comment by jcelerier** [comment]
100% agree, std::cerr (or ossia::logger().error("...")) is fine

**Comment by avilleret** [comment]
ok it's done, there was already some error report on std::cerr
I added some more on the same output
We might switch to ossia::logger() later
closing the issue for now
