### ISSUE TITLE
[ossia-max] parameter : default value is not fired at object creation

### ISSUE THREAD

**Issue by matcham** [OSSIA/libossia#441]
(issue in ossia-max v 1.0.0 ; did work fine in release from a couple of weeks ago)

open ossia.parameter.maxhelp
default value is not fired at loading 
(sending reset DO works)

**Comment by jcelerier** [comment]
@jln- hmm maybe it should be in the doc or as a comment in the max patch ?

**Comment by bltzr** [comment]
Huh, why is that a feature?

**Comment by matcham** [comment]
seriously, it's a feature ?
help patch says "Parameters can be set a default value, fired at loading"
and it used to work this way until now. If you decided to change it recently, I would be curious to know what motivated this decision :-)

**Comment by jln-** [comment]
Sorry guys, it was a joke (I'm just often annoyed by this default value firing).

Haven't check with lastest release yet but indeed default value get sent on loading with previous release. So if it's not the case now, indeed something broke.

**Comment by bltzr** [comment]
could that be related to the change you did to fix #377 ?

**Comment by bltzr** [comment]
@avilleret

**Comment by jln-** [comment]
@avilleret It seems to be OK, although I noticed sometimes not...

Could it just be that the namespace is not yet destroyed when reopening the maxhelp ? Or something like that.

![test_init 2018-09-15 14_53_53](https://user-images.githubusercontent.com/114325/45586400-39be3600-b8f7-11e8-89dc-eca16c3d750d.gif)

**Comment by matcham** [comment]
for me, with latest release (1.0.1) : default value is never fired.
open ossia.parameter.maxhelp : 
ossia.parameter my_loadmess @type float @default 1.23
do not output anything at loading

**Comment by jln-** [comment]
@matcham I'll zip you version I built yesterday so you can test

**Comment by matcham** [comment]
@jln- if you say that it doesn't work, I believe you :-)

**Comment by jln-** [comment]
Well, most of the time it works... I did not see it not working but when intentionally opening/closing again and again.

**Comment by avilleret** [comment]
according to https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-max/max-test/441-multi_load.maxtest.maxpat it's working

please improve the test patcher until it doesn't work again :-)

**Comment by matcham** [comment]
in latest release (v 1.0.1) : it (kind of) work on Mac (as @jln- described)
but it doesn't work at all in windows. (default value is never fired)

But maybe you already fixed it, so I'll wait for the next release (as I can't build myself..)
@avilleret or @jcelerier : if you have a fresh windows build, I can test it.

**Comment by bltzr** [comment]
as reported here:
http://forum.ossia.io/t/ossia-parameter-is-losing-its-value-when-ossia-model-changes-its-address/126
default values are not fired when created (only when loaded)
this is a different bug, but I guess it's related so reopening, retitling and updating this one
