### ISSUE TITLE
[max] Could not set TCP nodelay option

### ISSUE THREAD

**Issue by composingcap** [OSSIA/libossia#450]
This "Could not set TCP nodelay option" error is sent to the max window every time I change a parameter.  It happens on both mac and windows in Max 8.

**Comment by jcelerier** [comment]
@avilleret normally this message should only happen when an oscquery device is created - if it happens on every parameter change it means that the device is recreated all the time, I guess this is not normal ?

**Comment by composingcap** [comment]
It happens when I am connect to Score.  So, maybe it is an issue on the score end.

**Comment by jcelerier** [comment]
the message can safely be ignored, it is nothing harmful (it just means that you could get a small network speed boost if you ran Max as an administrator) - I'll try to find a way to cut it in the logs though.

**Comment by avilleret** [comment]
I got the same on Linux between an oscqiuery device (fast-cpp) and its mirror (safe-cpp)

**Comment by avilleret** [comment]
I'm on it, the key is to add a "log_level" attribute to [ossia] object that sets the log level we want to see in the Max console
by default I'll set it to not show those "Could not set TCP nodelay option" 
but use can change it to show this warning again
