### ISSUE TITLE
building for windows

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#498]
Hi

I am struggling to build libossia on windows:

I followed these [instructions ](https://github.com/OSSIA/libossia/wiki/Building) up to the point:

  Create a build folder, and inside, run :
  cmake -DOSSIA_EXAMPLES=1 -DOSSIA_TESTING=1 "%LIBOSSIA_DIR%"

but now I get the following output:

```
C:\Users\maybites\Arbeiten\02_code\libraries\ossia\libossia\build>cmake -DOSSIA_EXAMPLES=1 -DOSSIA_TESTING=1 "%LIBOSSIA_DIR%"

CMake Warning at CMakeLists.txt:20 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.3) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Downloading audio sdk to C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/3rdparty/win-audio-sdk.zip
-- Can't find dns_sd.h header file.
-- Could NOT find DNSSD (missing: _dnssd_LIBRARY _dnssd_INCLUDE_DIR)
CMake Warning at 3rdparty/Servus/CMakeLists.txt:27 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.6) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring WiiUse version 0.15.1
-- cotire 1.7.10 loaded.
-- Build against git revision : 2a45bd58, last commit on 2019-05-26
CMake Warning at src/ossia_features.cmake:149 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:52 (include)


-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR)
-- OSSIA - Build Type:
-- OSSIA - Sanitize: OFF
-- OSSIA - Tidy: OFF
-- OSSIA - Static: OFF
-- OSSIA - Coverage: OFF
-- OSSIA - Examples: 1
-- OSSIA - Tests: 1
-- OSSIA - CI: OFF
-- OSSIA - Framework: OFF
-- OSSIA - Dataflow: ON
-- OSSIA - Editor: ON
-- OSSIA - Protocols: AUDIO;MIDI;OSC;Minuit;OSCQuery;Wiimote;artnet
-- OSSIA - Zeroconf:
-- OSSIA - LTO: OFF
-- OSSIA - OSX Architectures: OFF
-- OSSIA - OSX Retrocompatibility: OFF

-- OSSIA - bindings ----------
-- OSSIA - PureData: OFF
-- OSSIA - Max: OFF
-- OSSIA - Python: OFF
-- OSSIA - Unity3d: OFF
-- OSSIA - Java: OFF
-- OSSIA - Qt: OFF
-- OSSIA - C: OFF
-- OSSIA - CPP: OFF
-- Jack_INCLUDE_DIR : Jack_INCLUDE_DIR-NOTFOUND
CMake Error at tests/CMakeLists.txt:171 (file):
  file COPY cannot find
  "C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/tests/../OSSIA/ossia-qt/Ossia".


CMake Error at tests/CMakeLists.txt:172 (file):
  file COPY cannot find
  "C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/tests/../OSSIA/ossia-qt/Ossia".


CMake Error at tests/CMakeLists.txt:173 (file):
  file COPY cannot find
  "C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/tests/../OSSIA/ossia-qt/Ossia".


CMake Error at tests/CMakeLists.txt:175 (file):
  file RENAME failed to rename

    C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/tests/Debug/testdata/qml/Ossia/qmldir-testing

  to

    C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/tests/Debug/testdata/qml/Ossia/qmldir

  because: No such file or directory



CMake Error at tests/CMakeLists.txt:176 (file):
  file RENAME failed to rename

    C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/tests/Release/testdata/qml/Ossia/qmldir-testing

  to

    C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/tests/Release/testdata/qml/Ossia/qmldir

  because: No such file or directory



CMake Error at tests/CMakeLists.txt:177 (file):
  file RENAME failed to rename

    C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/tests/testdata/qml/Ossia/qmldir-testing

  to

    C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/tests/testdata/qml/Ossia/qmldir

  because: No such file or directory



-- Configuring incomplete, errors occurred!
See also "C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/CMakeFiles/CMakeError.log".
`

```

**Comment by jcelerier** [comment]
pushed a fix, sorry for this

**Comment by maybites** [comment]
ok, it worked. the Visual Studio solution has been created. Though the active solution platform is set to Win32, and I am not sure this is correct. especially since I am interested in the max-build, which requires 64 bit.

the build fails for the following project when set to Release / Win32: 

5>------ Build started: Project: ossia, Configuration: Release Win32 ------
5>Generating CXX prefix header C:\Users\maybites\Arbeiten\02_code\libraries\ossia\libossia\build\src\Release\cotire\ossia_CXX_prefix.hxx
5>Building Custom Rule C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/src/CMakeLists.txt
5>CMake does not need to re-run because C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/src/CMakeFiles/generate.stamp is up-to-date.
5>context.cpp
5>thread.cpp
5>domain_base.cpp
5>domain_impl.cpp
5>clamp.cpp
5>clamp_min.cpp
5>clamp_max.cpp
5>wrap.cpp
5>fold.cpp
5>parameter.cpp
5>device.cpp
5>name_validation.cpp
5>node.cpp
5>node_functions.cpp
5>node_attributes.cpp
5>protocol.cpp
5>extended_types.cpp
5>path.cpp
5>complex_type.cpp
5>debug.cpp
5>device_parameter.cpp
5>Generating Code...
5>Compiling...
5>generic_parameter.cpp
5>generic_device.cpp
5>generic_node.cpp
5>alias_node.cpp
5>local.cpp
5>zeroconf.cpp
5>rate_limiting_protocol.cpp
5>preset.cpp
5>exception.cpp
5>value.cpp
5>dataspace_visitors.cpp
5>dataspace_impl.cpp
5>git_info.cpp
5>midi_device.cpp
5>midi_protocol.cpp
5>midi_node.cpp
5>midi_parameter.cpp
5>osc.cpp
5>minuit.cpp
5>minuit_impl.cpp
5>Generating Code...
5>Compiling...
5>oscquery_server.cpp
5>oscquery_mirror.cpp
5>json_reader_detail.cpp
5>json_writer_detail.cpp
5>html_writer.cpp
5>query_parser.cpp
5>attributes.cpp
5>typetag.cpp
5>wiimote_parameter.cpp
5>wiimote_protocol.cpp
5>artnet_parameter.cpp
5>artnet_protocol.cpp
5>audio_parameter.cpp
5>audio_protocol.cpp
5>port.cpp
5>graph_node.cpp
5>execution_state.cpp
5>graph.cpp
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\src\ossia\dataflow\graph\transitive_closure.hpp(41): error C2143: syntax error: missing ',' before '<'
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\src\ossia\dataflow\graph\transitive_closure.hpp(55): note: see reference to class template instantiation 'ossia::detail::subscript_t<TheContainer,ST,VT>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(54): note: see reference to class template instantiation 'boost::arg<9>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(53): note: see reference to class template instantiation 'boost::arg<8>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(52): note: see reference to class template instantiation 'boost::arg<7>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(51): note: see reference to class template instantiation 'boost::arg<6>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(50): note: see reference to class template instantiation 'boost::arg<5>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(49): note: see reference to class template instantiation 'boost::arg<4>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(48): note: see reference to class template instantiation 'boost::arg<3>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(47): note: see reference to class template instantiation 'boost::arg<2>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\3rdparty\boost_1_69_0\boost\bind\placeholders.hpp(46): note: see reference to class template instantiation 'boost::arg<1>' being compiled
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\src\ossia\dataflow\graph\graph_utils.hpp(263): note: see reference to class template instantiation 'fc::impl::flat_iterator<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,fc::impl::dummy_iterator<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>,std::random_access_iterator_tag>' being compiled
5>        with
5>        [
5>            _Ty=ossia::graph_node *
5>        ]
5>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\src\ossia\network\domain\domain_base_impl.hpp(146): note: see reference to class template instantiation 'std::initializer_list<_Ty>' being compiled
5>        with
5>        [
5>            _Ty=std::string
5>        ]
5>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): note: see reference to class template instantiation 'std::basic_string_view<char,std::char_traits<char>>' being compiled
5>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(2124): note: see reference to class template instantiation 'std::is_convertible<const _StringViewIsh (&),std::basic_string_view<char,std::char_traits<char>>>' being compiled
5>        with
5>        [
5>            _StringViewIsh=char [2]
5>        ]
5>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(2122): note: see reference to variable template 'const bool conjunction_v<std::is_convertible<char const (&)[2],std::basic_string_view<char,std::char_traits<char> > >,std::negation<std::is_convertible<char const (&)[2],char const *> > >' being compiled
5>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(3774): note: see reference to alias template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Is_string_view_ish<_StringViewIsh>' being compiled
5>        with
5>        [
5>            _StringViewIsh=char [2]
5>        ]
5>texture_parameter.cpp
5>tinyspline.cpp
5>Generating Code...
5>Compiling...
5>tinysplinecpp.cpp
5>curve.cpp
5>expression_atom.cpp
5>expression_composition.cpp
5>expression.cpp
5>expression_generic.cpp
5>expression_not.cpp
5>expression_bool.cpp
5>expression_pulse.cpp
5>loop.cpp
5>scenario_execution.cpp
5>scenario_offset.cpp
5>scenario.cpp
5>time_interval.cpp
5>time_event.cpp
5>time_sync.cpp
5>time_process.cpp
5>clock.cpp
5>message.cpp
5>state_element.cpp
5>Generating Code...
5>Done building project "ossia.vcxproj" -- FAILED.

**Comment by maybites** [comment]
ok, with the latest push I get now almost all projects build, except:

1>------ Build started: Project: ossia, Configuration: Release Win32 ------
1>git_info.cpp
1>graph.cpp
1>Generating Code...
1>exceptions.cpp
1>state.cpp
1>state.cpp
1>exceptions.cpp
1>   Creating library C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/src/Release/ossia.lib and object C:/Users/maybites/Arbeiten/02_code/libraries/ossia/libossia/build/src/Release/ossia.exp
1>wiimote_parameter.obj : error LNK2019: unresolved external symbol __imp__wiiuse_rumble referenced in function "protected: virtual void __thiscall ossia::net::rumble_parameter::device_update_value(void)" (?device_update_value@rumble_parameter@net@ossia@@MAEXXZ)
1>wiimote_parameter.obj : error LNK2019: unresolved external symbol __imp__wiiuse_set_leds referenced in function "protected: virtual void __thiscall ossia::net::led_parameter::device_update_value(void)" (?device_update_value@led_parameter@net@ossia@@MAEXXZ)
1>wiimote_protocol.obj : error LNK2019: unresolved external symbol __imp__wiiuse_init referenced in function "public: __thiscall ossia::net::wiimote_protocol::wiimote_protocol(bool)" (??0wiimote_protocol@net@ossia@@QAE@_N@Z)
1>wiimote_protocol.obj : error LNK2019: unresolved external symbol __imp__wiiuse_cleanup referenced in function "public: __thiscall ossia::net::wiimote_protocol::wiimote_protocol(bool)" (??0wiimote_protocol@net@ossia@@QAE@_N@Z)
1>wiimote_protocol.obj : error LNK2019: unresolved external symbol __imp__wiiuse_motion_sensing referenced in function "private: void __thiscall ossia::net::wiimote_protocol::create_wiimote_parameters(unsigned int)" (?create_wiimote_parameters@wiimote_protocol@net@ossia@@AAEXI@Z)
1>wiimote_protocol.obj : error LNK2019: unresolved external symbol __imp__wiiuse_find referenced in function "public: __thiscall ossia::net::wiimote_protocol::wiimote_protocol(bool)" (??0wiimote_protocol@net@ossia@@QAE@_N@Z)
1>wiimote_protocol.obj : error LNK2019: unresolved external symbol __imp__wiiuse_connect referenced in function "public: __thiscall ossia::net::wiimote_protocol::wiimote_protocol(bool)" (??0wiimote_protocol@net@ossia@@QAE@_N@Z)
1>wiimote_protocol.obj : error LNK2019: unresolved external symbol __imp__wiiuse_poll referenced in function "private: static void __cdecl ossia::net::wiimote_protocol::wiimote_event_loop(class ossia::net::wiimote_protocol *)" (?wiimote_event_loop@wiimote_protocol@net@ossia@@CAXPAV123@@Z)
1>wiimote_protocol.obj : error LNK2019: unresolved external symbol __imp__wiiuse_set_ir referenced in function "private: void __thiscall ossia::net::wiimote_protocol::create_wiimote_parameters(unsigned int)" (?create_wiimote_parameters@wiimote_protocol@net@ossia@@AAEXI@Z)
1>tbb.lib(tbb_misc.obj) : error LNK2019: unresolved external symbol ___TBB_machine_cmpswp8 referenced in function ___TBB_machine_store8_slow
1>C:\Users\maybites\Arbeiten\02_code\libraries\ossia\libossia\build\src\Release\ossia.dll : fatal error LNK1120: 10 unresolved externals
1>Done building project "ossia.vcxproj" -- FAILED.

and

27>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\tests\editor\looptest.cpp(352): error C2398: Element '1': conversion from 'initializer list' to 'gsl::span<float,-1>' requires a narrowing conversion
27>c:\users\maybites\arbeiten\02_code\libraries\ossia\libossia\tests\editor\looptest.cpp(352): error C2398: Element '2': conversion from 'int64_t' to 'gsl::span<float,-1>::index_type' requires a narrowing conversion
2>ossia_mixsines_example.vcxproj -> C:\Users\maybites\Arbeiten\02_code\libraries\ossia\libossia\build\examples\Release\ossia_mixsines_example.exe
27>Done building project "ossia_LoopTest.vcxproj" -- FAILED.

and

59>------ Skipped Build: Project: ALL_BUILD, Configuration: Release Win32 ------

**Comment by jcelerier** [comment]
indeed, pushed further fixes.
I've used this command by the way : 

    cmake ../libossia -G"Visual Studio 16 2019" -A x64 -T host=x64  -DOSSIA_MAX_ONLY=1  -DCMAKE_INSTALL_PREFIX=externals -Wno-dev
    cmake --build . --target ALL_BUILD
    cmake --build . --target INSTALL

to generate the Max package in the build-dir/externals folder (the built "ossia" folder, with package-info.json, etc... has to be put in `Documents/Max {7,8}/Packages/`).

**Comment by jcelerier** [comment]
hmm it shouldn't build the failing wiiuse / testing stuff if you enabled `-DOSSIA_MAX_ONLY=1`, can you nuke your build folder and try with that ?

**Comment by maybites** [comment]
where do I have to run the cmake command?

I am downloading VS16 now (might take a while and I need to go home), but I tried to run the 

`
cmake ../libossia -G"Visual Studio 15 2017" -arch Win64 -T host=x64 -DOSSIA_MAX_ONLY=1 -DCMAKE_INSTALL_PREFIX=externals -Wno-dev
`

but get the error message: 

The source directory "xxx/libossia/Win64" does not exist..

**Comment by jcelerier** [comment]
don't wxorry it should work with VS2017,; I just copy pasted my command line.

It should be `-A Win64`, not `-arch Win64` and you can replace ../libossia with ` "%LIBOSSIA_DIR%"`

**Comment by maybites** [comment]
I figured it out myself :-)

cmake ../libossia -G"Visual Studio 15 2017 Win64" -T host=x64 -DOSSIA_MAX_ONLY=1 -DCMAKE_INSTALL_PREFIX=externals -Wno-dev

works, but I think I was inside the wrong folder and the libossia folder is now a mess..

however, the sln file seems to work... fingers crossed

**Comment by maybites** [comment]
ok, it seems to have build properly. but my project is now a mess.

would you be so kind to update the wiki? Once I am back to this machine (in about two weeks) VS16 will be installed and I will try to rebuild it again..

cheers - martin

**Comment by jcelerier** [comment]
yep, doing that asap. thanks for the report !

**Comment by maybites** [comment]
@jcelerier here the updated text for the wiki:


### Building the Max implementation on Windows:

- Ensure that you have the latest[ Visual Studio](https://visualstudio.microsoft.com/free-developer-offers/) installed and up-to-date (2019).

- Clone the repository with your favorite Git client, the needed submodules will be cloned by CMake when configuring. Or use the command line version:

    git clone --recursive https://github.com/OSSIA/libossia

- [Install ](https://cmake.org/download/ ) CMake. Be sure to add it to PATH when the installer asks for it.

- Create a build folder inside the libossia folder, and inside, run :

`cmake ../../libossia -G"Visual Studio 16 2019" -A x64 -T host=x64 -DOSSIA_MAX_ONLY=1 -DCMAKE_INSTALL_PREFIX=externals -Wno-dev`

`cmake --build . --target ALL_BUILD`

`cmake --build . --target INSTALL`

Now CMake should have generated the max package inside ./build/externals/ossia-max.package/ossia
