### ISSUE TITLE
[ossia-max] min and max attributes don't work

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#499]
Hi
Playing with the [ossia-max] package:
When opening the Overview from the package, and linking Score via OSCQuery (or Minuit) to the example, inside score, the value

my_ossia_patcher:/my_2voices_synth/voice.1/carrier/frequency

has set the 
min to 0
and
max to 1 

but when you go to the fm_synth-patch, the object is:

ossia.parameter carrier/frequency @default 440 @type hz @description "Carrier frequency " @min 20 @max 20000

it looks as if the @min and @max is not working. using @range 20 20000 will work.

**Comment by jcelerier** [comment]
@bltzr is it just a problem in the Overview.maxpat  which has not been updated ?

**Comment by bltzr** [comment]
nope, this seems broken so I'm assigning to @avilleret 

the best thing to do would be to create a test for `@min`and `@max` but unfortunately I don't have the time for that ATM.... maybe @jln- or even @maybites, if you want to try ?

**Comment by maybites** [comment]
I have never created a test for a project like yours. if you can point me to an example I will try.

**Comment by avilleret** [comment]
@maybites we use https://github.com/Cycling74/max-test.git for automated test
creating a test patcher is not so hard, it's just a matter of making some assertion with [test.assert] and end up by banging [test.terminate] 
there are lost of examples here : https://github.com/OSSIA/libossia/tree/master/src/ossia-max/max-test

then there is some glue needed to install a patcher with package creation and to run it automatically but making the patcher is the more time consuming task ;-)

btw I'll look into this issue right now
