### ISSUE TITLE
[ossia-max] ossia.device deletes and recreates all parameters when a patcher with ossia.remote is loaded

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#503]
Follow these steps:

patchOne: 

<pre><code>
----------begin_max5_patcher----------
576.3ocyU0raiBCD9L7TX4yzTCD9qm548UXUUjA7l3JvFYLcSTUe2W6wjDRS
aR1tH08.F6gwy27M+wq9d3R4VVOF8.5mHOuW887.QVAdim8vszsUMzdPMrXn
sjovAtO0Q0Ua3h0qTrJsyLQwKHAnvhB6qDhcMJZAA8z3ULFfKZXZvbgGEJGz
6kFMJkWCPJKe9thiHpnsLMSshInkMLqFjwu4LgdWGy4JXb.BWREqwnmrZ7lu
ucIXloZLYVoZ9+iTMDRmQowyJUy9NnJ62Fn2CrlsEXHtSwE5KD.bI4bXMN5q
vex47OAOeDP12yoKTrVolgJo87p61vZ5d391cqNDdu.AcTaLCGMlu+KoX74T
LZI9R4Q3YNyitvvABilxdziVzQlDM5wZ1unCMZTXT706vSSgzNIalp6iubLY
9iG0rW3USKKtZk9xb2rsjuBkC+f5fOmxGrbkrQpbRIKBiRVVDX1jUjRxxs6x
KVFFZ1EZ8lIgHv.3Ft38+JCXmU9owsd4fpZO7i4CzQBVy50bAUykhI5T3z4C
yL2JN42.Nwy.N1ltqBT1L.T1Mfydm4eiQ2.PImgiqvf108BS0OpL.go04YWo
Vd.bjKbGggzXkocYu9ofDpxzlnM8HCJvsvaScC1vsxZlRLvg5deK4LP1q207
9hQgYHDb0ePakszUa3qMLe8FMqdkTY9eFy0hfGGMcZDgVUwD5IcHg1FSxhD6
B4jdhfwHqxbAvQ.TGMdqwxfuRlDgfoHV+qui5B6vvF+27+SH9OFh
-----------end_max5_patcher-----------
</code></pre>

patchTwo:

<pre><code>
----------begin_max5_patcher----------
421.3ockSskaCBCD7a3TX4uoTBoMIMGgdEphPFXahiv1HaSJQQ4tW60llj1p
n1O3wtrdlYmc4TZBsVMBFJYM4MRRxozjDLkOQRLNgJXiMcLCVFUNHpAMMK7o
dlsYGWtsRCM1.LydIuHiTtXt+wyEXPYdAYS7HN.3xNvhvM6RR0fcJaYLKuEo
TUu+gkWXTyDfEzUfjU2A9JJheK.g8XODjBklQn0L4VJYiuhyoo9aY+0VE9vQ
8DwVXzFjiwvY4ZPnr.olY3MOrC55W+n3X0Wp6NFzphqLnxnc8Ocn4+zgJehd
Oa.utwFP9ncb42W.PM6yeq2XTC5lIHiyDxEU2BFKWxrbk7pZ7pxWzuZ++Uhl
.4tLs7GDEZPVe+APahEib3Fy6UZe3pLLjKCg3hDUCG3S0u.yvztgn0MAGznt
niKBtMUnZAsbfiipTe24nzXO18cSU51Kvi9JSnDrpc7stVe6NKzVoztcTHL9
bc26rgN6sVBqoAj1FUWPmt+x7aME4O6u4daV9WsdVzZ0tCfBAYMBtvgLp0hq
bHbi2qOSOK363OFomS+D.Yf+vA
-----------end_max5_patcher-----------
</code></pre>

save both patchers and close both.

open patchOne. notice in the max console: 
print: parameter create basic-help:/my_parameter

open PatchTwo. notice in the max console:
print: parameter delete basic-help:/my_parameter
print: parameter create basic-help:/my_parameter

-> when a new patcher is loaded with an [ossia.remote] object inside (it doesn't even need to have an address atribute) ALL the parameters are deleted and then recreated.

This should be considered a bug. Its impossible to work this way. with this behaviour you loose all your settings when you load a help patcher.

cheers

martin

**Comment by maybites** [comment]
@avilleret I assume this issue is caused by this bit of code: 

https://github.com/OSSIA/libossia/blob/9ee58cd38943685f2047ae09e868693b2bde16e4/src/ossia-max/src/remote.cpp#L287

this is unfortunately another issue that keeps me away from implementing ossia and burns like hell under my fingernails...

**Comment by avilleret** [comment]
I confirm this annoying issue...
Unfortunately, the line @maybites  pointed to has nothing to do with this issue.
But I think the registration mechanism is involved here.
This have always been a big pain. I can't find a solution that works great under all conditions.

**Comment by avilleret** [comment]
this seems to be fixed, could you confirm @maybites 

I'll try to make a test patcher soon, and I also have some ideas to fix other issues, but I don't have much time yet (I could take the time, but I need to do some money for now :-) )

**Comment by maybites** [comment]
I can confirm, it seems to be fixed. thx
