### ISSUE TITLE
send a message through [ossia.device] right outlet when a parameter's value changed

### ISSUE THREAD

**Issue by avilleret** [ossia/libossia#505]
Thus we can monitor which parameter is changing even if we don't have an associated `[ossia.remote]` somewhere.

I think we should register to some parameter (with or without pattern matching) instead of outputing every changes by default.

see http://forum.ossia.io/t/indication-of-parameter-change/154

**Comment by maybites** [comment]
I had a quick look at the [pattrstorage] object:

it has the 
\@notifymode
and 
\@ouputmode

at the moment the [ossia.device] will notify if a new parameter is added. though I think it would be nice if you could switch this on/off via a \@notifymode attribute.

the \@outputmode attribute is quite sophisticated:

0 = disabled 
1 = output all changes to client objects 
2 = output all non-repeated changes to client objects (see changemode) 
3 = output all changes to client objects not initiated by a message to the pattrstorage object 
4 = output all non-repeated changes to client objects not initiated by a message to the pattrstorage object (see changemode) 
5 = output all changes to client objects not initiated by a message to any pattr-system object (pattr, pattrhub, pattrforward, pattrstorage). 
6 = output all non-repeated changes to client objects not initiated by a message to any pattr-system object (see changemode)

this only as an inspiration.

being able to choose the output through pattern matching would be cool. but maybe the above solution would already be enough?

some ideas: 

1. would it be an idea to add a dump-outlet for these infos?
2. could we differentiate the dump-output with messages? i.e. 

register {adding / removing parameters}
data {changing parameters}

this way we can use a simple [route] object to differentiate.

obviously: all the above naming are only suggestions, maybe you have better ideas.

**Comment by avilleret** [comment]
is this still relevant since we now have ossia.monitor ? 
or maybe we can upgrade ossia.monitor instead of adding another capability to ossia.device ?
what do folk think ?

**Comment by maybites** [comment]
Not sure. I will have to investigate. Give me some days to get back on this...

**Comment by maybites** [comment]
I realized I have already another issue open which covers this:

https://github.com/ossia/libossia/issues/612

I am therefore closing this and add my comment to the other one..
