### ISSUE TITLE
[max-ossia] [ossia.device] initialisation problems

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#507]
Hi 

I am experiencing the following issues with [ossia.device]:

1. open ossia.device - helppatcher.
2. press 'namespace' -  message

result:  [jit.cellblock] shows all parameters. 
expected: [jit.cellblock] shows all parameters. (so far so good)

3. now delete all the parameters below [jit.cellblock] (including the bpatcher).
4. press 'namespace' -  message

result:  [jit.cellblock] shows only 'no_recall'. 
expected: [jit.cellblock] shows only 'no_recall'. (again: so far so good)

5. undo the delete so all previous parameters are shown again.
6. press 'namespace' -  message

result:  [jit.cellblock] shows only 'no_recall'. 
expected: [jit.cellblock] shows all parameters.

once this happens, there is no way to tell the [ossia.device] about the parameters, unless you:

7. delete the [ossia.device] 
8. undo the action. 
9. press 'namespace' -  message

result:  [jit.cellblock] shows all parameters. 
expected: [jit.cellblock] shows all parameters. (good again)

in my opinion this shouldn't happen.

**Comment by avilleret** [comment]
> in my opinion this shouldn't happen
I agree... and I'm working as hard as I can to fix all of those annoying issue...

in the meanwhile, you can use the undocumented `register` method of `[ossia.device]` 
this will trig the registration of all its children

this should be automatic though...

**Comment by maybites** [comment]
> I agree... and I'm working as hard as I can to fix all of those annoying issue...

I do not envy you, I only can imagine..

> in the meanwhile, you can use the undocumented register method of [ossia.device]

thanks, that will do for the time being.  all my ossia parameters are inside of dynamically loaded bpatchers, and I simply can send a register method if a new abstraction has been loaded.

this also seems to cleanup the issue with https://github.com/OSSIA/libossia/issues/508

**Comment by avilleret** [comment]
it was easier than I thought, 
it was a weird side effect of some last week changes
should be fixed now

**Comment by maybites** [comment]
sorry, its still broken :(

**Comment by maybites** [comment]
I had a look at your test, and while it works find in the test, if you add

<pre><code>
----------begin_max5_patcher----------
470.3ociS0zaiBCD8L7qvx8JKBHgrMaujy8vJsmaqhbgYSbEXirGxlpp9ee8
LFxlzrUpWrwOO1uO7vaoIxmsGAuT7CwChjj2RSRXHBHYZchrWcroS44xj8f2
q1Axr3dHbDYbeiSOfBC7G6yu.MyeI1PUHdTZ8dsJeP4T8.BNAZQ6iRwlCJmI
.I3cDaFTXydsY21AqWiZqQTUtPT98xYB6zFnwNZXVWLAZF6siXGfrFKmPiP3
qCPzfRo3oosNQiKH03tKqWjWjIVTeKMUUTPSKWmWb5PAVzlYRpl.0sr8CV8a
0RB58zTZH6KlmwX5p3D2q8rHAm7+ZxpO0jYeMitbcMMsZMa2pOymkW6yxhYI
4UGlo8leRDegrEx6nga9EMBl1Hh3oyRIlS9M8CMg7kP3WFcd6nqYlxXlmI9m
xaAOpMJpu4rZH8REcEupggCfyOUMyQ3w4EqiVdaFuTahKK3kN3fdt9ULhxEx
WLDtiNVWxiqVJiG01BNynlSwTpkHPoGes6idk5+4idup21q1tWuKX8c6Qncq
0oLy+sEr2uUic3kQhpoALXisKpyGDkzCZQdMMD9pL+j0ylhVW3.rPXVmt79v
MyZs3rDh6SI8EdUi4N2Nm9d5eM1tL7J
-----------end_max5_patcher-----------
</code></pre>

to the [ossia.device] help patcher and create the 'toto' parameter, it will not appear in the namespace...

**Comment by maybites** [comment]
@avilleret I created a new test that is able to reproduce the fail: https://www.dropbox.com/s/30irq09afq3zg0v/507_newTest.zip?dl=0

at least parts of it. the effect of my description in the first post, where param1 and param2 are missing, too, cannot be reproduced with it.

**Comment by maybites** [comment]
@avilleret ok, I have now a test that reproduces the top post: https://www.dropbox.com/s/p8avfrfat6mffif/507_newTest.zip?dl=0

if there is another [ossia.device] in a separate patcher, the re-registration has issues.

so there are two problems:

1. if there is another [ossia.device]
2. if the parameters are inside a subpatcher.

**Comment by avilleret** [comment]
could you make a PR with you new test patcher (or updated one) ?
I'll try to look at that next week

**Comment by maybites** [comment]
whats a PR?

**Comment by avilleret** [comment]
sorry, a Pull Request.

but you have to fork libossia in a private repo, commit some change to your repo (ideally in a new branch) then on github you'll find a button like "send a pull request" in the main repo page iirc
a PR allows us to review your changes and merge them into the main repo without changing the author of the commit (which belongs to you)
