### ISSUE TITLE
[max-ossia] [ossia.device] creates bogus parameters

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#508]
Hi

consider the following patch:

<pre><code>
----------begin_max5_patcher----------
3269.3oc6cszjahqEdc2+JTwlroSGDhmYUlUSU25VScq61TobgsksICF4Bj6
GyTy829Uu.DX.i4gcO8zKhS.Lli9z4kN56P9y6uyXI4EblA3qfuCt6t+796t
SbJ9ItSc7cF6CeYUbXl3qYPIa2FiMdPdoji6IGowXp3hP0Ykmh95Ar7W1HJg
Z.9g5pQqE+Pjk+7yd4+NGBSC2io3zE3jvkwh6yr7YDkT+QbHjtZWTx1Eo3UT
4Swy8QyG.NNA7+xxN+SvO32wec+87OdnmixD7yL4KW5n3WDOCiCfCo3LtnbY
i+FG71PilFglsOBc77Eip.wPz0TbfEeHpeO3T0.SMxtyXSTL9IbZVDIQSLuy
H7vAsSem1svgieRD+P9OTbpnD4oLKNUJ9on762s3rgoLImxD6ioBDv3EWaix
eFxZbZxwHgnHOIahQIRhofDltP1gvUxalOSkeYsY6.K4vW.In.we4XAKQC1b
71XxpeGuVWlMHGvIQIh4wDZHUI7EWdMdS3wX5hMjDZVzeHDAH+Q0v02nDwFu
HePHj+eIMJLtXDrMMZMIgKDUlJ3mN+w8c.zgOZ3eVNXDeijvCMbyLsIFtzxE
yXCxiYKCS4yTJSKq7KRIj3pWp39hwanpKeHJIoFJRIGZ+hoQa20w8tjvt39t
9sEWIawwD4UWvTJnKxBepJZSCiiUFpU+4eILIZeHESijSAVlEWT5dYW1pTRb
bkwq7JO0vUVyTxWgeNZMcm3AoqLv95QGxUhLJlkWGsEmQqdNZ31rpmIi9pDz
0N0wkJi3ET79CwrQQ0uPEG15Vr5tzpb9Zt1VQ1umo4WXOp6e6ov3i3LvFRJn
vibF34H5N.yxiA2rIgMXPHklFs7HECX9BATB.x9NwwfDBErDq9prIUsGQbTB
dE4XBUW86TOnlZWQyUouQ063j3As4wzV3jv1VFMPZVgP4AEtKOvfxGz.QzJA
KpBnjrrnvGKvRFBsPhNfuoCnPiVQDcr5z3JOnEaoNn4LTPCI7kZ6oBj5TFlY
BAMlG9rvs3FQs+2WnLqGqG+YFytpUjA1IxzFpfZEUr5FUr35MLfvD8nyC.Oq
aDp.mETwdvnBzSDpxCJPE+2U5JvghJAB+Mv.22gpJVCETjJGPW6YTSoqfaUS
cu+AebLGpiTKGYxod7QriLccyq3HVFhoeC3kGWxR+geq6CS2FIygzr1u5JRr
bE.emkED5AsOzy6ttuk.iSdNYQqw0UYZIi6xapNh25TQkzu+2grDT9u3sGiC
SM5d9B5KB4gDyTNEed0luDY3dqms7+6xrkCrbxx18pOYElr9hckX6MTWIPS2
RWInfYwUReByRegN44dL3jObEYjAgA23vryAnL37Tgx5f46LifRGq3gEk8.N
YspPYfXR3PVG3.AsAGoVAZVA9BTSnWgbdmXeM3zX4q0Y1Mv5PWZEIYCIcOSx
1AX2CXIgPGfxzYWBsd4oOA8rFqNkiXER9VyhNU+sDqmbwrZIhBFWEat0Fhyh
Ocj6PMDkfxsxk9aAyPqQVBv40JTNbt3zAcG5Xx2VlFnnTTxLfQl0xoOO2U8p
GKd9Iqwuns2KU.fxsafOo1RclEBD+5MiLYjioqxmWUkQATU1VyLwhRJ17kuW
NGC56DykJDVuIDB+dJEb+mylTf5oPXaMmBg6agIjbb9rRg6LJD1uElO34Ne6
QB3aBnnu9Jxwr4QJdSXlZaOdyzxfJhM7rknJEk.5eEtmrObwtnsLAc6NJd8B
RZXhd9Z4azdyChvUqXA9zp9knPQl7XkhPkvpQ+ePCbRY23o6JKObO6oIXrfo
1v5d8e.Q06XhpXu3WTrEoY0IiwEsmwaiIKCiU6HbAB0vVJeeIlegTcoZMtJy
56+TtAvQIfPfbWvAqBSj6w6dBEG+JKYvir0XPIfiYrbT.eR90Vvk0u9ENUOh
+Rw1e9IP3xLRLeiiCWulsrjLP1qIzvWJ3STkTIQMRxlb9wzUIP6e4OaLGyZk
8L+Gs4RddZ4NalwRmqLmMVfKSwxfrkqCxxUrcB78kcPjZpsY5eAjcboXpBf2
uDudMdMHLiMkmSEAiNmHNAqceP6i1v5Bpe0BpNYXnkjZPdRhBYYpnBv.wvMw
Dlj0LfX0J8uXKtYIyCViz.yxsOjfiu.rPpFMq5Ms3bjTgyVtq9NlUW83zvKN
IMGj9D.KCyhV84c33Ce8KgIDJmKKRGA6ecQwXrYHD0EDVgsCUfPaiKETjKDT
AJHSmQgJsYXwF7bWlzcgTvpcLE.tGRFdn7k9oL.WYF77tnXLHhBhx.3WNPxX
1eOSR9DEriERAf2rgytK.IQbuqhiXOKfv4TSdMslAiUz0xX00BJmID6btkqn
vikKWehlWHor3Wr3y3mvRH8XJOvuX1XN70AuZvmrV.v.QkhfJpvNTecUKSll
ZcqvzkQ.VneilsVm0rUM9Tr5ZpsZEVp3SsSmAMCnyUSyPt01PWIyRUj5ZNzL
.Yj83eahTQbGpFhZbNSN1k5EYhjg4o8CBY4.y2pqb9gCHa.JxTNGpMWOGJJa
LIiysbFWxSsAm+JlB3bhrhImLgzD1mY4qVf+uX.sDXeSrjAnswMawAPOI06j
qJ.5HT7cm7NdXKltnjP9SfMcvkZSCMkUs2TlAuu6+j66AK47rksrp+1Rt5xY
GxG88vG88vG88vv1o7HV1+xEwJGzW7V4gF5V4I6hKUhJPIgKtpjXZULNLEzI
OQG11cGLXZm36jmkeCUr35QbBAqIvSNM.FNG.8kPgm3uBP2JbAN0Hh6XQDYv
PWmqMh7GwfrXdIdtxMvy4n.nSk0.cKMftdcev4TUj9QPRrwydVvDgzb85BEy
doF3TRS5ogjHyfFCEDCVNBanJUW+jXyvgqznEbF8txNxebXx7ZG0CLwbxQjA
GWVULsaUPnYNcEK2QhK2pzUnfkfOOz.yBGJmiShCtCayyvUESx+5ynyiIk6A
WCXicWXCGSdnbK45DhZu2Nb5UpcpEA3Bu1PTJgSSg5E9ZRyuCNxD7xW5H5uO
4xfrGZxL4lLliJcFqaOoeQNiLxqq4TmP2Mk0ubqfYi9ZhebXeHb6IR69n0GH
LeaY4EgVPEGYXL49RGz+WjDCRt6EQgguA3LMx4rnmibm7kkq1xt3f4Rx6MsE
8Nqn6KDc0KZHG6hCpbSjz0x8e.daGOmxp5BIybdjr9ZgIFBntPZDTzOCPeU.
MQLewQykVResxBNmRhUfPu.5I0UzNZtD8Kk97sK6RUZjJMhxClKI2quRt6ah
NwXNCOI7d2aimNmEQRJ+HWKgxmk3n4Tz6C.Nq3WucyOmRQu8.d9bLDShVPYa
2JiYJNZFk7adO3zWOYdynLzaeR8LaAk2z7zdlQ2oASVNZpnV8LGs2Ic+PWLY
axX7BbfLdQ89nwCMJRr8yH5iqvwwK4jBIWRRIOKqBiYiiOaMdIUisGrkXF2M
c2iixpTfnlwD2yvbJMtJn8jKXifksYWfZqLQoKBFIKXIRRXdnKRigQrG8Z7F
4WmcCrk.xommpghJ+PlxZym9yv7+.9wflHq2NFOEgeVvfkn3H5qUTK2rgWIX
EQ1jRQwPQxMn0oLqmSQ33nU+NcWJ431c5m+D5iT8BOc5EVtky2I8ojkkqDoS
V5oqjjuceFhFSoUZzYd14VG4qjMjjHiBlQ+OQ1i4qdc8I2qBGnYQuw+A6w9f
8XevdrVK1ak99Zx2gZupupyZsMvZtUvt3BIKsSP1yI8pNxbXmNW3kykfWWLx
3AuM7Nq9KK37lmq7LeiCR.ltXHE7MkaS91rZgLCBBli2IKC3MFaef3.O4ayN
6q8KEo5XrdKIpfWNWPK.WKzbryenQAd1Rvy7FofJaLiJc14jrMgUZ9h.+.KG
QavXC8rcsDovhf91Nc91qzZT.qqL+gt2N9YYyxPuAJll8nqCy68WzCSXKO8a
ZsF7qjihNISzsujj3WYefAeWmO5+.b.yem7Kxw4wtaoL8brgmtlJeiotQjbb
Cz5vdDxZTMIVmsX94CNtjkFbo6a3.5T+l+OqkKsCyyW2orGbQirWU6InbtnY
vxN4dr.BZn.RNwE7lO.Q8pJo7EQvfKhWkXRPKG6.tqEu.WSOe9+xOvFB8auy
uGHHYody1hZt8UEOppgejXVcW9JjqatYzmRcWa+sOYxZJevA5amxI0WGJ9OZ
.NYK4km1yu3nSEUywIp9WLHUeiUCTxp+id7zVfZG1hReeENqdhili84X2GPv
cJdRt84IYOAOo9Lj7lhmCbzJP9xW22H4BRkuFdqdjk7Medgtk6iiUrcmP09p
Z8iUoOnGRFzsKQSILHjNnINpA+q0pyKWppUe2Z018z551dMcqWOWQ1o0RaVh
N8Mc4ZoJq.wdmhrJ83VRMtZZw4HTKkc99+59+Obe8+GB
-----------end_max5_patcher-----------
</code></pre>

and paste it into an empty patcher.

result: output shows:

push default value for another_parameter
push default value for my_parameter
push default value for another_parameter
push default value for another_parameter.1
push default value for my_parameter
push default value for my_parameter.1

(side question: where is the print for this message? is it a post inside an external?)

1. press 'namespace' message.

result: [jit.cellblock] shows the above parameters.

expected: 

another_parameter.1 
and 
my_parameter.1 

don't exist and shouldn't be shown.

2. delete the two [ossia.parameter] objects
3. press 'namespace' message.

result: only the parameters in the bpatcher and patcher (no_recall) are now shown.

**Comment by avilleret** [comment]
thanks for the report

> (side question: where is the print for this message? is it a post inside an external?)

it's here : https://github.com/OSSIA/libossia/blob/master/src/ossia-max/src/ossia-max.cpp#L274 and has been committed by mistake, sorry for that

you pointed out an issue which is quite hard (one more...)
when pasting several object, we can't known the instanciation order, and depending on how you paste them, they receive a loadbang or not...

currently I can't reproduce it with Max 7.3.5, which one are you using ?

I noticed that when I choose File -> New patcher from clipboard, the objects receive a loadbang while when I create a new patcher then paste your patcher into it, the objects doesn't receive a loadbang
I also noticed some strange behavior when removing/recreating an ossia;parameter when playing around to fix some issue but I can't reproduce it in a reliable way

**Comment by maybites** [comment]
> currently I can't reproduce it with Max 7.3.5, which one are you using ?

I am using Max 8.0.6. here the above effects are reliably reproducible.

> when pasting several object, we can't known the instanciation order, and depending on how you paste them, they receive a loadbang or not...

why is the instantiation order of importance? 

and

what is the ideal instantiation order?

**Comment by maybites** [comment]
the issue is indeed not present in max 7.3.5.

maybe there has been a change in the way the loadbang is issued? I am in direct contact with the developers and can send a bugreport if you can give me some meat.

**Comment by avilleret** [comment]
> why is the instantiation order of importance?

for example, when you add an ossia.parameter object it looks for a parent ossia.model or ossia.device and register under it.
then if you add an ossia.model object besides this ossia.parameter, the parameter is unregistered and registered against the ossia.model node. 
In this case, the ossia.parameter is registered, unregistered and registered again.
This is not a big deal when you only have one parameter, but with thousand this can slow down the registration process a lot. 

> what is the ideal instantiation order?

on a performance point of view, we should first instantiate all objects without registering them, then register them from the root to the end of all leaves, and only after that fire default value following node's priority order.
This is what happen when we load a patcher. At least in Max 7.3.5 :-)
I'm pretty sure I read something about loadbang in a release note today but I can't find it again...

On the practical point of view, there should not be any difference for the user experience between opening an existing patcher, creating a new patcher and pasting some objects to it or building a new one from scratch. But that's not so easy :-)

**Comment by avilleret** [comment]
well... it was easier than I thought this time :-)
it's a weird side effect of `get_patcher()` routine that was introduced last week
it should be fixed soon

**Comment by avilleret** [comment]
could you test with the fix of #507 ?
I do have some bogus parameter registering when deleting the bpatcher, but they are removed as soon as the ossia.model in the bpatcher is deleted, if I understand it correctly

**Comment by maybites** [comment]
the ghost parameters are gone, but when deleting the bpatcher and undoing the delete, it will not pick up the parameters inside the bpatcher. 
it looks as if the loadbang is missing, since the parameter will not output the set default values. this happens only with the register message to [ossia.device]

**Comment by avilleret** [comment]
iirc I got the right namespace after undoing the bpatcher deletion with Max 7.3.5

Could you check that they are not registered under the default device by sending the [namespace( message to an [ossia] object ?

**Comment by maybites** [comment]
I actually have to retract: The ghost parameters are still there.

and no, the bpatcher parameters are not registered under the [ossia] object.

I am testing with this patch:

<pre><code>
----------begin_max5_patcher----------
2275.3oc6aszjiZCD9rmeET9Rt3cJj3gM4T1SopT4TtlZKWBP1VajAWf7ryt
ox+8nW.BadH6A1Ylj8vvXj.ot+5GpoUq+9gEKiyeFWtz4mc9SmEK96GVrP1j
ngE56Wr7H54DJpT9XKOhKKQ6wKWo5igelIaOCw64DJotmSHVxAR19sE3DlZF
B7CezckSzZw009hqP3itNeR+JjT4PkG+4O.VWMNYmORxnXlb5g5F2kmwJIeC
KZCvGhlmM+Lq5gAFOrf7jC9GKHHZ0XqdX1WOgUD3xkNeRzy+7vChKqrDSxve
gSyWAImJHYrwgCPvFw+TW6EOh5DO.2Bd31OdLcLcdYIAYASCWONSCgCxzI4z
7B0n59H.F3Gsh+i0Qgtq2H90lHe.f+Kfwn+1RwoOioB7dRICWL.N5EHPtMxq
9QCp53NnoT2r9Dwfr786oC4RHzSx.PIe.8qt1EerdPkgtYiSnBt7iijawYnX
J1zL3JVTXsdWbYR9wi3FS8Zw3GcJOGeLOEScvGiwoo3TGToCxIVhDCJegJQa
PjBSbU+Czigx5oy6ff5aYYEtx3xk1R0lG+Nhk67G38monhkSHF9qXlChRcXG
vNo3mHI3epzQgoY7qbzLMsfaFI9UVpySH5Y9BZ5QgRxvI4myjCkmtw3ywbMA
wDbDUrmjIQE29kDfPI164qbVKvOmvdzQA9SmfPQmlu9UhFuUFWlMQSeKu4rG
y1Zy59aj9m.5U72DNj2pnIxYkI0fKzbml833CgheBWTRxyLFnEKQmNYz7BiW
QfIeVg7aVU2DIS0jacSEbczp2OrtUTAGSXb.4bgRl7bXklhXX3JxEYmIRRQ0
HW5nIIobnAkEurPbU0sgGCkpIz2UotJWZ02MrAm4B58z7j+BmZRyKyOgyHYm
3VQbCPDSS70cmh2gNSYa6V4sc+6zjXmc14RoKVtufjlmIHhVhBQyUSG2HLPY
8YxLxmHCcpiWlqIwwkd5rjyjmKiQEBIk1DCV0IKOm1tq52ih2wzcehjkcAJx
xO0emEj8GF3ciy4cdbnwV1S41yYpd2xUJXaKQO0FsYbOkZq01C+ynLxQDCyH
JQ.zstS0BiGJSJxozV7qpmm5nGki3uPRYGjSjox.+wImpThVVKkSI6wkr1sw
P6Ka2RI6qJP2noyUqVtkgOdhx4h1OPqOgwzh0zuVq1Gx+VGgv6Hio8QESa9X
cEOiz3C3pTWc8tzU2kt67LGutVynqEHp5P5GW6s3N481Qf1l4SnXTgXw2Q3Y
cnJfHUDKtiwyQ8xyvd4YSznuXSmHHYP0AL2YRpSIOnD9eifKfMJnXs7eQipK
r9NzEdagK.KQD0RTgAigHguaQjuQcJob2EiCIJamPsCiQMdBtCiG3fPxpWGC
nQwEUXLJ745jEc0m.81VUQRN1oJHu54VcsOFFzKC6d2LrQ2UeOl4RsRJHKE+
rQfpysFCyg5DaGv4ZfbCtlK3NzUF0FJFks+MoczsYFs4c+hPtifH9A2zZPv2
+KKaW3JZbw1nUfueWbl4D67AfkQ0pWGZyn3QvT6UQ5QYkYdImenQlsr5DSNR
bb5H9CAihM98hMA8hM9CgMxcVQG7x2YHpfSLXmKy60v9eq9rvQsp.uChuylX
YprdbsLZFO+W4vYfSH.onE6VXNz0R.5dbu39RCnqIYahTo2SVVjLmn+tglx7
yEIURE82+6zlOSwkLRVcpG+yFV9hG7HI8TN2XWSIvH+GCpy0Ir4FK02uUJes
kTNbLBGrIRRqJGBffl6lIJOzRJWygyBMDXK5sYlIBvjHB4t1BDaImoHTd2LQ
4BWj1geAyH9I93IqnhYmHrRJ5OlXzSJEAp36zlkx6lIRuR41ZueyCUXsmrv4
jJBuQOB8KFC7M7mB8ma2oPa8kEY4RXf0J+GF2Mmjt01NdCZ6v81In1M5vZAJ
anYD1s0E30JV4EopsA180kx5vxq6XCfPUYg4WeS27CXd3mIKFspfa9dEiFvV
SypUxlOpvFqLuwiyXi.xTIjILp52yEcaI3A5e0IciUUvvRwtTmtUsi7aQLVA
Il+AzkWVRF2zNGumlGin58EtttB5Xikeng3lnZyy9BdIPkyUuAKNuWuZy6yD
1iIXJMVTRHKMJbnKJhi9YPHP5w2SU2dfPOCdLImVWe.Pe2N37v6oBeKx+hJs
QtMyy.Pl+sWImTRYqTK0TKQF0Hgwrmh2odStoJ2.UTibqjUDgwE0Bic27G.U
+47o6RNdYwD9DA+EY4qPnD1Wao3ramHMv5hGSQE0bmpvfRK3lNWylTRxewNT
jed+Ay1up1QZ2wSW2Q7dQwNYJvhaVYdL8MecxRhhp9jqtso5trgGtZ6jEnY6
RG8+MUN1FfrXrApsDI.n1Asf0+nxw9Qki8iJGafD8tily8lLRhdU5epxGd7h
ixtcabWdAWnzxSwf6Jv.0A+20cz9L2KagM30Zfcv0KcS2dq.L8ucSphOrlNc
PY4LgJcSK+hf7b35hHlyuncaJ1MWnmaTTqhsqU8vCsPLnNpVdp5FvKne4f+b
TREuZX7wudE7JpCzZvE5YiNruB7Fult79O.3oNRFUJmx6rAiLOAbu7x6p0gi
HZSDLPdtU7Aq8Cgxvc8.a7CZcVIllpTXV1nL+2.aZi2KNc+MPibM5dvl5P79
Mzw7insG3w8PEw9HxcPA2gqwFsWEaX2r.JIgGMpgp.P8oNAMe0kIctx.ZJ3u
30ARHrE3yFwL6gFo4XhO6jV3pOlGTWiyHvnIhPe7577G7H25eCmuNXuohX0D
eHZuUWyfZey8iGdQgJOyqGBO7dCiGpvnchQkjjOb.SOM9ouBp9mWvfm31I+.
2dWovR91s8jpfrK8doAtqSiYqrr2Wp3gM9rtR3X8L4ZyLMASjuEyy5IXdhrX
d.s1ekKyXcjLg0PW4wQy3lWHgAsfvhlBIpkyCXX9G3FJ2pivf56peg1aF0rR
osQs16Zz8KJrQV.tVXnrquHUYhI4hTjcQ5wtN0X8mVrKSIlbA9Kh7Pwr1Fww
EQanwDqixPGgQOQWzNxhJDpmL28v+7v+BPaka0.
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
could you test again @maybites ? I can't reproduce it with cd465f67

**Comment by maybites** [comment]
I just compiled cd465f6 and its still there.

**Comment by avilleret** [comment]
damned ! I've added a test with fd736ad4
could you try it ? and report what is not working for you ?
on my side the toggle is green...

**Comment by maybites** [comment]
The test is green, but when I test it with the patch above it still shows the same effect.

**Comment by avilleret** [comment]
I'm sorry I'm confused.
With the very first patcher snippet you posted here https://github.com/OSSIA/libossia/issues/508#issue-460450408
I do have the following in the Max console : 

```
OSSIA library for Max is loaded
build SHA : fd736ad
ossia.device: node created basic-help:/another_model
ossia.device: node created basic-help:/another_model/my_parameter
ossia.device: parameter create basic-help:/another_model/my_parameter
ossia.device: node created basic-help:/another_model/another_parameter
ossia.device: parameter create basic-help:/another_model/another_parameter
ossia.device: node created basic-help:/no_recall
ossia.device: parameter create basic-help:/no_recall
ossia.device: node created basic-help:/my_parameter
ossia.device: parameter create basic-help:/my_parameter
ossia.device: node created basic-help:/another_parameter
ossia.device: parameter create basic-help:/another_parameter
```

So no 'push default value to blablabla' because that print have been removed.

When pressing namespace I have : 
![image](https://user-images.githubusercontent.com/504914/86453497-296e8980-bd1e-11ea-8742-d8e7bad63001.png)
Which seems fine for me.
When I removed the 2 parameters between jit.cellblock and bpatcher and click namespace message, I have the following : 
![image](https://user-images.githubusercontent.com/504914/86453786-a00b8700-bd1e-11ea-8424-374010edf8ff.png)
Which is fine also. 

Do you have something different ?

**Comment by avilleret** [comment]
Ha... I think I saw what you experienced.
When I delete the bpatcher, I have: 

```
ossia.device: parameter delete basic-help:/another_model/my_parameter
ossia.device: node removed basic-help:/another_model/my_parameter
ossia.device: parameter delete basic-help:/another_model/another_parameter
ossia.device: node removed basic-help:/another_model/another_parameter
ossia.device: node removed basic-help:/another_model
ossia.device: node created basic-help:/my_parameter.1
ossia.device: parameter create basic-help:/my_parameter.1
ossia.device: node created basic-help:/another_parameter.1
ossia.device: parameter create basic-help:/another_parameter.1
ossia.device: node removed basic-help:/my_parameter.1
ossia.device: parameter delete basic-help:/my_parameter.1
ossia.device: node removed basic-help:/another_parameter.1
ossia.device: parameter delete basic-help:/another_parameter.1
``` 

and yes all the `*.1` parameter are strange.

Also there is a lack of consistency in the posted messages,  we should use either `removed` or `delete` and `create` or `created` but the same word for node and parameter.

**Comment by avilleret** [comment]
but deleting bpatcher and undoing doesn't scramble the namespace return by ossia.device

**Comment by avilleret** [comment]
I think I understood what's going on.
I observed that when removing the bpatcher in @maybites patcher, the following appear in the Max console : 

```
print: parameter removed basic-help:/another_model/my_parameter
print: node removed basic-help:/another_model/my_parameter
print: parameter removed basic-help:/another_model/another_parameter
print: node removed basic-help:/another_model/another_parameter
print: node removed basic-help:/another_model
print: node created basic-help:/my_parameter.1
print: parameter created basic-help:/my_parameter.1
print: node created basic-help:/another_parameter.1
print: parameter created basic-help:/another_parameter.1
print: node removed basic-help:/my_parameter.1
print: parameter removed basic-help:/my_parameter.1
print: node removed basic-help:/another_parameter.1
print: parameter removed basic-help:/another_parameter.1
```

We see some `basic-help:/my_parameter.1` and `basic-help:/another_parameter.1` node and parameter created then removed.

Here is the explanation : 
The `bpatcher` contains a model that holds `my_parameter` and `another_parameter` nodes with parameter.
The root patcher also contains parameter with the same name. 
When we remove the `bpatcher`, the `ossia.model` is first removed.
Removing a node triggers the re-registration of all its children, i.e. `my_parameter` and `another_parameter`.
Those parameter register against the root node because the model they belonged to was just removed.
But the root node already have parameter / node with those name.
So they became remaned into `my_parameter.1` and `another_parameter.1`.
Then, since we are still removing the bpatcher, we now delete ossia.parameter objects. 
And then the `my_parameter.1` and `another_parameter.1` nodes / parameters are removed just after being registered.

This quite a long story. But this is only an introduction to the wonderful world of parameter registration in Max :-)

Btw I harmonized the node / parameter creation/deletion message with afdcdb3a.
I'm cliosing this now, since this is not a bug but just a detailed walkthrough parameter registration. 
We can't remove the extra `my_parameter.1` and `another_parameter.1` creation / deletion without breaking lots of things.

I hope that helps and I'm closing this issue for now. 
Feel free to reopen if you think there is still a bug around there (or better open another one since this one becomes too long...)

**Comment by maybites** [comment]
Weird. 

When I copy paste my first example (at the top of this thread) it looks on max like this:

`ossia.device: node created basic-help:/another_parameter`
`ossia.device: parameter create basic-help:/another_parameter`
`ossia.device: node created basic-help:/my_parameter`
`ossia.device: parameter create basic-help:/my_parameter`
`ossia.device: node created basic-help:/another_model`
`ossia.device: node created basic-help:/another_model/my_parameter`
`ossia.device: parameter create basic-help:/another_model/my_parameter`
`ossia.device: node created basic-help:/another_model/another_parameter`
`ossia.device: parameter create basic-help:/another_model/another_parameter`
`ossia.device: node created basic-help:/no_recall`
`ossia.device: parameter create basic-help:/no_recall`
`ossia.device: node created basic-help:/my_parameter.1`
`ossia.device: parameter create basic-help:/my_parameter.1`
`ossia.device: node created basic-help:/another_parameter.1`
`ossia.device: parameter create basic-help:/another_parameter.1`

and this:

<img width="358" alt="Screenshot 2020-07-04 at 10 17 17" src="https://user-images.githubusercontent.com/148945/86508344-9bf36e00-bddf-11ea-8abc-d53c71a8e9c8.png">

**Comment by maybites** [comment]
I don't think this issue has been resolved. I can still observe it it on both windows and OSX. I actually was also observing it inside score (when connected via oscquery).

**Comment by maybites** [comment]
It looks as if this issue has dissolved. I tried all the above examples and I am unable to reproduce.
