### ISSUE TITLE
[max-ossia] [ossia.parameter] set 'value' with @type string is not working

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#511]
Hi

when sending a message

set "test text that is NOT output from the outlet but is malformed"

to a [ossia.parameter] object with @type string, the content seems to be malformed.

set seems to work fine with @type int or float

<pre><code>
----------begin_max5_patcher----------
2052.3oc2ZkzjahCE9r6eETb1wijXeNMyg4xTyxgjKSkjxEFjcqL.hAjS5jT
4+9nMvfsAKuf6NIUE2f1du2mdaH895CyrWQeBWaa8yVu0Z1ru9vrYxlDMLS+
9L673mRxhqkCyNGWWGuAaOW0GC+DS1dMlY41zZYLK4QRwlkU3DlZ0C.dK.ys
PghecTOiV.rdudJEayIEYXljJHcijT4ZSW8gWg.16FIcKqYnPcqplXetDqnm
ss06E87sGdP7ybCEO9huBWMhb36ErvatUTjPB7.iKGvCkCX3tEuJNGyvUKwE
wqxj7M3nxHZPYbtk8p3hMWlrNzVo2oEe01HJR974rMB8tOai3Owo1ARFstlD
unE3sVSxv+DI05WDDzhTvNsj6KkbX3g67IzLZkZrfEPjmazb9CAQ9ffPwSgQ
tPH+I34ns3Xe9ZD2VsAgg863uVyrDsYwdLlYQps3jtbKyZcEMm2F1RwJuydD
HzIPAdttJsGzY6E.hd9Uepv4TFVo6TvUjFUfcV3A18OHzkK9.GIJfhtKpPgG
GwbFUC5toE8W+8aFPSxZ0V4HxiyVSqxwocTspv03BVLiPKVlQJvIzsErtpLG
Yu.4A244xg+x4p64eWT8FB.uUlfxHuPfx+sqyYiBd+HfBbkfcAwfmupfyKtf
XBGQ5vX0rJtzdRo2WK8A2EuPt2u.YefvVjfyxVkQS92SqDDIA.ej1obPGgZM
sfUS9hjkfhfUs3SOd+nZKh4JiNHXoeshDmYejvYCjTqamEYcbRuTC4T+SjT1
iRm3.vP3WFol05J+l6NG+TIslapUm7eawUeliNNtVQgA9if2h3db.G5oRBv+
7M6fAOm1ckVavrkh8z5RwdxI0rzwXB8OaAM57kytbCtRKcZwiqHw8Q7QbUMO
fYmEZlcbYYmlm0YJBL4CJ2.gyaahTnZBz1TE9ijl4621ZbEGSXb.YakxB3I+
lONTrLzTbUwVhjUTMx2czrjbeXGJKlrX6po6tAzU4O5JSE2wUpV4B72gy7M5
MBm.3zt7rMsDWPJ5lDQutSwqi2lwVdbq+98umwY+NOp4+L6MUjTZgfI5sUHZ
tgbbiEUbZutBibDEwkGYxbkFNtLPm0bgba8p3JwNk9CMQMcxnzr9c0NuL7Zl
t6RRQwdnHiVNbmUjMONxbWQ4clO1ZK6od41BUuK4JErk0werOZyhyxzVq8W9
mhKH4wLLin1BPf1NUer8i0IUzrrdxqpmOdjdR4J4I3V2tftJC7gSJaThra2k
SIa3YpzuMV7l59sTy9rBz6zz1UZi3kLbdYFWJ5OfdGYSWK1t90509X921yGG
O0AlkJCCkP2cXG6qhAp7I0oUdP9jClbvPoTcD2dflNj9w0dKtPYue.s9BeRF
NtxhqRcBYFEpj1HuieFPC5heH27C6pezvZ2HHYT0AL2YRpk3q23++D3RyghD
H+SzkqKD78Bt.MDQTgn78tXDw+kNh7kLq5Lt6hSCIJaGesCiK23waXHAMJjL
+4w.5j3hJMFE9D3dwpJnWDpJR1zLUA4uNfleGVfAGWfgWt.2o6DZdNtne.aI
gJRwO0IQ0oVigYkYsxLfCzA4trXtvqvFpy8N7xxN5FYFE98RPHvIPDWuaSLH
TvOVoqnwkqNaEzK9fyLqUVuBZXVs53PgWNdboQlkdTlKhcvtaPi7lCZuv2Sj
GmNi+CO4pCwFuAvF2gwF2wvF4cSt6z7tmPTEmYvV6etWi6+s4yBct3z6fubx
uyjbYZrd.Wa1LNt2mzYP2P.RwKlEX1GXJ.MTRKinX.t1D51cXahqUbfSYQJb
h9ONzTS2VkzrqnSP0publhqYjh1id7s6T4ECznclylIDKNz.tv4.tMmjVR4d
bpaNGe4waqhX5G077Tx2lfdNvID8PlxDdmD87jHl93pQtsuLUbtqgrtH8tSv
5g558Qx5dtsuzaRzpT08O.edkG+CFWKmAlFNyTKLoH3LFR6.UWUVnN9ITUyQ
SmUFxTqrnSojfhj5Ev.ktRm2lJV22TE7vSw6JUZGcVK6dYp37.S4b+oz0V3Y
5aaR3Bo2aiMdFcWzwSpx4nKTun12lRV2D.bRwOicyOkbgwd.OcNFxMQDTUUF
pXlx2lPN+bbhLILgodxBlPdvXeRFlsf1aZSZOSn6znaVNZ5nVFliltwlJXvV
bK0oKU2H+xXFqhrh+Az06WRFm0MGuIitJNSeuvs0UvQtX4G1wb2nR8w7BdQW
YOAmeQEBe9qmN0scasllkNZ8+qqsGUYy0TGkSc0ycc08jjL8+fVEbsuElFzN
LEAPWKlg95UmcdkNXiwTJ0+q8lTJ4XBkBuATxDB4dKDIWSnjND8UQH+6kDEZ
xdD5FHQPCHTuHi68YtSJgi5lU0AY6p7.APpvqdsucHmBtNNMvbL5pHTfgPx0
RmHSTt.GPHk2z8JbRAM1qfI2qXIOrPIGtHI2u.IkoVnpUr87fuqDC2lRnuVV
neK+SbwVU.ilxQrORrZyZRVVabptIkzDCQGEqslL6FSCoCfAV3.cBP9xm3O3
40M4e0bfMSxkGGDfDC00GE35IeJD434HdBr2zP6nE.Fon.HJD3pdh2DrW.TN
VVrQWXiAcpNuxJZIspsBOW3D0N9sL5lp3Th9HhA8RbZtVQph269knmcNGPIM
yoqhW6lwuGmSyiW9HYCWObyiLQ5fUbNDO1tRbRBmZcPZ4g9.VHgJfVbuIr2q
ey+7G+lNkqKeU9fNaT.37VJk8y.U46Ce6g+G58YWm
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
confirmed, easy workaround : use list type instead
I've updated src/ossia-max/max-test/368-set_broken.maxtest.maxpat to reflect this issue and will fix it asap.
