### ISSUE TITLE
[max-ossia] [ossia.parameter] ignores when initialized with value driven by [loadbang]

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#512]
Hi

technical not a bug, but maybe a feature that should be considered:

consider following setup: 

<pre><code>
----------begin_max5_patcher----------
1922.3oc2akzjaZDE9rleET5rrR2M64jygbIUxImKorSoBAsX5IHZBzZ7X6x
+2SuABPfTqEzLNGrFnW38deuUZd9aOLa9Z5K3p4V+r0GslM6aOLalbHw.yz2
Oa91nWhyhpjKadN9yz0OMegZJF9Elb3LZTx5n7z5IJhXwORxSWUhiYpmuCve
o6BKGmkfEVtAheQnk.q+Vuk7caI4YXljNP8fjD4imSx2gluegzcr9qTMD6KE
XE4lKYGq+VL62e3AwOKLTF2hqphRwGHjepQLsRvah1kw9z7SKvPeOor5XebQ
FcnH6blh7sUb0xn0kI1A.g3BcbOao16tH0iXHSqpHQKKhJi1hY3RqMjL7OUi
DuWPUqJVIWhsde8n5+Zfkf.FVXYCcN.ShoYzR0hAKgHWmvE7K7C8.9AhqBBc
fP9UvyvgIXXbDMJNt3FikFDTv9JiI.e0CJXf1WJcWQX.2W0v.mo6ucauef2Y
Kr1u479y42bwt91c77AA2EOeG66lq+SD1xXbV15LZ7+bRbv1SlNvCIcBfH+V
B0FZNqh7UIKAEvUC9zg2Gz9QrWgZRxR+RIIJa9gnBDLLp3z5grIJV9PZQ8OS
RXOJFyF.FC+xHULIFt3Zvxw7.wuTPqvVzp3+cGt7Kbzw1wJLv26H3MjCgtBS
MoGHzCd1NhP+WSOwBqTLakPmVUHzImzxBFJkvfyOhS34Kms4FboV5zhG2PhG
03YbYEgl25AMadTQQqgm0ZKBL4IUXffEMCQxUCAZFpD+Lod+dMiFUxwDFGP1
Up7.dwqtxQwiglfKy2QjrhZPt1QyRR8vdTVrYg5pd58nLxEoReICra6HCj4H
huWiFbEcpHH.NoMOOmVfyI4Ek3JbNKhoY9lo0QPWMr2e2464b1cxAc+mMOsj
jPyELQGUgX3ZxwcVjQkD+tWXjqHOpXfMyMZ33xHSVwExcUqiJEZp0Y3VFcby
aJMq6TM6KCugomtfjm2CEYzhwmrjj93Q16ZJexsG6YKmoZ0tb0rq3FErUUQO
2EsYQYYZu0tO9WhxIaiXXFQoBPflIw4QbA8wp3RZVVG4UMyyCLSB2HOF2D1E
z1XfubRQsQz7FsbBIEWw5NFKJsp6HUrun.8VCsas1IdECusHiKEcWPmWPtsG
a63ZcF+Xw25EiiWLAyRUygRnaurAB04oqpRYtBNnRxQKNXrhrFHrGndBYbbc
zhKT16lPqqvGmgiJs3lTmPlQAJoMT9GWvokYzvxb33xbaTZrzZ2HH4nlCXdv
jDqJLS7uSfKPUI1He4eBubaA+eTvEngHhJEkm6EiHdu0QjulYUkwCWbZHQ46
3oCXb4NOtiCIniBIKdcbfNItnJiQgO9NWroB5MgohjMMyTvU8dn0+Nt.CFVf
gWt.2Z5X51s7xA6jpURn7D7KsJTcpsXXVYVqMC3.sPtKKmK7J7gZctUus7it
QtQA+njDBbBDQed2WcNHj++uJWQiKWc0Jn27ImYVqsdGzvpZ04gBtb73RyLq
NXdQtC1cCZho6xY3RypiSWw+gmb0gXi6HXiy3XiywvFAlz5z7tmPTImYvV8O
2qiG+s90Bsu3x6fucpuyjZYp8d.Wa0L1N2mxYP2P.RwKlkX1CXJ.MVQKGwv.
bsEzs+v1xH4icJKRgSL+vPSEcWYbsVQ+Z9VckyDbEij2bziebuj0agaIIETt
ytlSPgNxSVVcVmn82Xn894x49Fx4nSw3vfPIupBH.c2e2Dw4dFx4ZIbR3AWS
QufIlIf2DUHOzl3y2.aqBk2MQbtHRnY3m6Dheh2QxHtXxYBizhNmRMZK0hPU
8cZ2R4cSDqWababzuogKLNRl2TxEdmYDgwUitNshmhbl5voHSikEZXJLnuJ9
Qq6lRV2XeG6i56vi1I31.cYsPkOzDB6lFB7PCKZYh5y.Cdc4rA77Ft1.DRFR
RYXKuYX4ANMxyMqFs5hatW0nAM00rNS1zwEl3kYe55LBDPl5.Y7Bqudp3aCA
O33YmzCV2ACyEek5jUpuH+pHFqjrl+BzU8aIiy5KGmlQWGko+tvM8Uv.eX4G
1yb2nV8w7FdQ2YO9me6DBe86vN0W61ZCMKo43fNhnV+592mtm6556IIY59Bs
J3puyhFzN9KvNlCBXuCxA5ESITfADxQEn4pniuAzI7FHOdFPmfa.cbrMfPt2
.fyD5TyLWEgPPCnzMgPFPGua.cflXy4eKHjg11MIq6m.1wu96h3t++Y.h6Z1
P2ZKmTNsKp0sHvNg250IiBZ1qCF608hG14hi20h86XQYtdUya0Kj59d9aWBg
9AYm2s5Ov46TQva5M+NHy5zMjrrlDGsqRnNntNsRSSR1NICRmQArj+BJ9HO4
U7KbcaWRlZOv5M4vSLAPhk53g7cbkWEfrcsEWA5sMzdZAfgJJ.BC.Npq3CA6
jQiik4o5NMzuU6xUTRKnkMsb4R6vl0uiQSKiRH5yrEzoRlEZCqR9r86Yt4a4
.JodOsMDaTF+VzV51nUORR41koOxD0mUx4P7wzJQwwbp0BokutmzqP80MV13
pdkr2G9y+52+UcMPW9S4Ic4g.v48nT9Oiz1sO78G9Onw875J
-----------end_max5_patcher-----------
</code></pre>

copy paste it into an empty patcher, save, close and reload the patcher.

the value of [ossia.parameter] file/name will be "default", even though [loadbang] has sent the value "loadbang default" to the [ossia.parameter].

this is (probably?) because [ossia.parameter] only accepts values once it has received an internal loadbang and is registered to a device. 

I propose, that if the object [ossia.parameter] receives a value before it receives an internal loadbang, it considers that value a the new default.

while there is a workaround, I think it would be sensible to do this automatically (or by default - pun intended), this is especially helpful for novice users..

**Comment by avilleret** [comment]
thanks for reporting
you're right, since the object registration is delayed a little bit (2 ms at most), then a value send by a loadbang is not taken into account.

your proposal is fine, then someone have to dive into the insides of the monster...

**Comment by avilleret** [comment]
I'm not sure if this is fixed or not.

At least I can say that a value sent by a loadbang to an ossia.parameter sets its value.
But a default value might have been fired before.
It pushed a test patcher with 34b6ad33

When a loadbang sets a default value, the default value is well set but the value itself might not be fired.

I'm wondering if those cases are reproductible.
I'm not sure that the loadbang order is well defined.
For example: put two loadbang objects in one patcher : which one will be fired first ? why ?

That's why even if the test patcher seems to be fine, I can't garantee that the value passed by loadbang will be fired before or after the default value.

But I think that this is a non-issue, because setting a value with a loadbang **and** setting a default value is a non-sense to me.

**Comment by maybites** [comment]
I concur, its a non-issue since it is nonsensical. there is no point of setting the @default value with a message, since it is meant to be set on initialization.

the sequence a loadbang is fired (and an abstraction is loaded) is depending on its layer - which can only be set via 'Bring to Front' and 'Bring to Back' but there is no real way to introspect the position if an object inside the layer stack; you can figure it out be visually lay them on each other and see which is on top. Where something in the back is fired before something in the front.

**Comment by avilleret** [comment]
well, setting default value with message does make sense because the default value will be fired when the model is `reset`.
But setting it via message at loadbang doesn't makes sense.

Thanks for the explanation of the loadbang order. I think we should write a book about writing externals for Max with all of these little tricks we found there and there since we are making our own...

**Comment by maybites** [comment]
> well, setting default value with message does make sense because the default value will be fired when the model is reset.

you are right.
