### ISSUE TITLE
ossia-unity DLL won't load

### ISSUE THREAD

**Issue by pach** [ossia/libossia#530]
on some configuration, DLL won't load even in Plugins folder in unity
`Failed to load 'Assets/ossia-unity/Plugins/x86_64/ossia.dll' because one or more of its dependencies could not be loaded.`

-> installing vc_redist might correct the issue

**Comment by pach** [comment]
vc_redist link : https://support.microsoft.com/fr-fr/help/2977003/the-latest-supported-visual-c-downloads

**Comment by andybak** [comment]
> vc_redist link : https://support.microsoft.com/fr-fr/help/2977003/the-latest-supported-visual-c-downloads

If people want a page that's in a language other than French just substitute "en-us", "en-gb" or whatever your country/language code is in that url.

**Comment by jcelerier** [comment]
thinking abou this, I think that we should link against vcredist statically for unity & java builds on windows, as they go through the C API which takes good care of doing the whole alloc / dealloc dance inside the ossia DLL...

**Comment by andybak** [comment]
I'm getting a related error: DllNotFoundException: ossia

This happens with both the Unity example included with Ossia Score as well as ossia-unity3d.zip downloaded from https://github.com/OSSIA/libossia/releases 

Is this the same issue or a different one? Repairing my install of vc-redist didn't help. I'm beginning to think this deserves it's own ticket.

**Comment by jcelerier** [comment]
[New Unity Project.zip](https://github.com/ossia/libossia/files/5293830/New.Unity.Project.zip)

Do you think you could try that Unity project ?

**Comment by andybak** [comment]
![image](https://user-images.githubusercontent.com/60035/94489543-88885100-01dc-11eb-989d-9cad947c1cd8.png)


What's the other script on that meant to be?

**Comment by jcelerier** [comment]
oh, I forgot to remove it sorry. I moved things around - this was the "Controller" script but I added it back.

**Comment by andybak** [comment]
OK. This seems to be an improvement then. I can't test fully as I'm still trying to understand how Ossia Score works in general but the original error has gone away with this version.

**Comment by Victor2kyang** [comment]
How to download ossia.dll? 
i find ossia.dll in ossia-unity3d/examples/example-preset/example-preset/ossia.dll
copy then,
i have a new issue:
EntryPointNotFoundException: ossia_protocol_multiplex_create

i think idownloaded the wrong ossia.dll.
where is right ossia.dll?
----------------------
my download path:
http://ossia.io/site-libossia/download.html -> Download Unity3D asset (Mac / Win / Linux)

**Comment by avilleret** [comment]
@Victor2kyang indeed the libossia.dll is missing from the latest release, there are .so (Linux) and .bundle (macos) but nothing for windows. It is also missing for 1.0.8 & 1.0.9 release.
I'll report that to the right guy : @jcelerier :-)

**Comment by jcelerier** [comment]
argh, sorry, typo in the release script.

**Comment by Victor2kyang** [comment]
> 
> 
> argh, sorry, typo in the release script.



> 
> 
> @Victor2kyang indeed the libossia.dll is missing from the latest release, there are .so (Linux) and .bundle (macos) but nothing for windows. It is also missing for 1.0.8 & 1.0.9 release.
> I'll report that to the right guy : @jcelerier :-)

TKS ，you guys are so nice！

**Comment by Victor2kyang** [comment]
@jcelerier 
When can I download it by http://ossia.io/site-libossia/download.html -> Download Unity3D asset (Mac / Win / Linux) .
I am not good at cmake T.T .

**Comment by jcelerier** [comment]
I'll make a release today, keeping you posted

**Comment by Victor2kyang** [comment]
> 
> 
> I'll make a release today, keeping you posted

That's great news! thank you! 👍
