### ISSUE TITLE
fresh clone --recursive leaves 3rdpartys empty

### ISSUE THREAD

**Issue by thibaudk** [OSSIA/libossia#534]
This seems quite recent but I cant find the point where it started.

**Comment by avilleret** [comment]
I think this is a git bug since I experienced such a behavior few times in the past.
Btw I usually make a non recursive clone and let CMake clone the submodule it needs according to the enabled option.

**Comment by thibaudk** [comment]
Thanks, but it is Cmake that complains it couldn't find the files in these empty folders.
Did you find a workaround that git issue when you had it ?

**Comment by thibaudk** [comment]
fixed with 
cbccfff

**Comment by thibaudk** [comment]
Apparently one bad submodule messes up the entire clone
