### ISSUE TITLE
building max package on OSX 10.15.2 fails

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#537]
Hi

I have troubles compiling the current master branch on OSX:

on the command `make -j8`

I get the following errors:

-- Build files have been written to: /Users/maybites/Arbeiten/02_code/library/ossia/build-max
[  1%] Building CXX precompiled header src/cotire/ossia_CXX_prefix.hxx.pch
Scanning dependencies of target ossia
[  4%] Building CXX object src/CMakeFiles/ossia.dir/ossia/context.cpp.o
[  4%] Building CXX object src/CMakeFiles/ossia.dir/ossia/network/domain/domain_base.cpp.o
[  4%] Building CXX object src/CMakeFiles/ossia.dir/ossia/detail/thread.cpp.o
[  6%] Building CXX object src/CMakeFiles/ossia.dir/ossia/network/domain/detail/domain_impl.cpp.o
[  6%] Building CXX object src/CMakeFiles/ossia.dir/ossia/network/domain/clamp.cpp.o
[  8%] Building CXX object src/CMakeFiles/ossia.dir/ossia/network/domain/clamp_min.cpp.o
[  9%] Building CXX object src/CMakeFiles/ossia.dir/ossia/network/domain/clamp_max.cpp.o
[ 10%] Building CXX object src/CMakeFiles/ossia.dir/ossia/network/domain/wrap.cpp.o
error: error: C++2a was enabled in C++2aPCH  wasfile  enabledbut  inis  PCHcurrently  filedisabled but
 is currently disabled
error: C++2a was enabled in PCH file but is currently disabled
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/detail/thread.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/context.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/network/domain/domain_base.cpp.o] Error 1
error: C++2a was enabled in PCH file but is currently disabled
error: C++2a was enabled in PCH file but is currently disabled
error: C++2a was enabled in PCH file but is currently disabled
error: C++2a was enabled in PCH file but is currently disabled
1 error generated.
1 error generated.
error: C++2a was enabled in PCH file but is currently disabled
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/network/domain/clamp.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/network/domain/detail/domain_impl.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/network/domain/clamp_min.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/network/domain/clamp_max.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/ossia.dir/ossia/network/domain/wrap.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/ossia.dir/all] Error 2
make: *** [all] Error 2

any advice?

**Comment by jcelerier** [comment]
oops, sorry, a -std=c++20 made it in master while it should not have. Can you try pulling ? should revert to c++17

**Comment by maybites** [comment]
that did it. thanks for the quick fix.
