### ISSUE TITLE
[ossia-max] latest master will cause maxmsp run hot on 10.15.2 with the upcomming release

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#538]
Hi

I am observing heavy CPU load on max by just opening the latest maxmsp release candidate.

with the help of cycling74 developers we found that the ossia package is the culprit (with the latest build on master a few days ago).

> Some of my colleagues (JKC in particular) are more gifted at reading this than I am, but there is an awful lot of curl activity being logged, coming from 5 requests started from the main thread in maxurl. Maybe you should logout/login again to Max and see if that helps. There may be stuff installed in your packages folder which is initiating maxurl/curl connections, though, and I can't see where the requests originate.

now I am surprised this is happening, especially since there is no max patch running. so max seems to load some externals in the background and ossia code is being executed, but here we are.

**Comment by maybites** [comment]
I have to retract. I can't reliably reproduce anymore.

**Comment by jcelerier** [comment]
What is strange is that ossia isn't using maxurl at all AFAIK ? @avilleret  @bltzr do you know more ?

**Comment by avilleret** [comment]
what is `maxurl` ? :-)

**Comment by jln-** [comment]
Just checked and still see a CPU overload after removing ossia package so I guees ossia is not the problem, here.

@maybites Do you have Jamoma package installed by any chance ? Here it seems that disabling Jamoma package stops the CPU overload, though.

**Comment by maybites** [comment]
Nope, Jamoma is not there anymore.

I made this report because I observed this CPU overload, and it stopped when I removed the ossia package and came back when I put it back.

but when a cycling developer tried to reproduce there was no problem.

so I removed ALL packages and put ossia back and voila, everything is fine, an even the launcher is working again without a crash.

then I put one package after another back and now the issue has gone completely.

so please excuse that I thought ossia was the culprit.

**Comment by maybites** [comment]
I am beta tester, so I am under an NDA and I can't reveal too much, but it looks as if there might be an issue with packages in this regards.

@jln- if you can reliably identify if a package is responsible, I can pass this info on to the developers. they are keen to get to the root of it.
