### ISSUE TITLE
[ossia-max] mute message breaks connection between various ossia.remote

### ISSUE THREAD

**Issue by vincentgoudard** [OSSIA/libossia#542]
Steps to repro :
  - open ossia.remote.maxhelp
  - select tab "Messages & attributes"
  - mute and unmute the first instance of [ossia.remote my_parameter]
  - drag the flonum values
=> the two instances of ossia.remote are not synched anymore

**Comment by jcelerier** [comment]
I guess some callbacks aren't saved somewhere @avilleret, what do you think ?  maybe pd is affected too...

**Comment by bltzr** [comment]
I just tried, and the bug doesn’t appear consistently… sometimes it just doesn’t appear, sometimes it goes away after muting/unmuting this or the other remote object...

**Comment by bltzr** [comment]
OK, got it - the other remote objects need to be unmuted once one of their pairs have been muted
this is definitely a bug, but maybe this will help tackling it ?

**Comment by avilleret** [comment]
I can't reproduce it with 05879337

Feel free to reopen if it occurs again after that commit.
Also please make the test fail in that case.
