### ISSUE TITLE
[ossia-max] duplicate parameter in namespace

### ISSUE THREAD

**Issue by vincentgoudard** [OSSIA/libossia#543]
Step to repro :
- open ossia.parameter.maxhelp > Multiples
- click namespace to display it in jit.cellblock
- create a [ossia.parameter my_spat.1/source.1/gain.L]
- click namespace again, you will see :
  - my_spat.1/source.1/gain.L
  - my_spat.1/source.1/gain.L.1
  - my_spat.1/source.1/gain.L.2   <= where does this one come from ?

**Comment by bltzr** [comment]
I confirm this bug - this might be a side effect of the wildcard thing…..
When feeding a value to the newly-created param object, it goes to both of the parameters (visible when pressing namespace again, e.g.)

**Comment by bltzr** [comment]
could that be related to #559 ?

**Comment by avilleret** [comment]
I do have very strange behavior on my side...
First the jit.cellblock is not resized, thus lots of name/value are lost.
Then ossia.device return the namespace twice : the whole namespace is sent 2 times in a row.
And I experience the same doublon when I add another parameter.
