### ISSUE TITLE
[ossia-max] select and send messages bugs with ossia.remote

### ISSUE THREAD

**Issue by sacreyoubeurt** [OSSIA/libossia#548]
Hi everybody,

Alongside with some colleagues, we are working on a project which needs the modularity of the Ossia environment. Initiated on Jamoma, we decided to port everything on ossia for windows compatibility and the benefits of the ossia implementation.

However, we face some issues concerning the ossia.remote object. I saw on the GitHub issues tab some others seem to encounter similar problems so we wanted to get in touch with the state of the development.

After compiling the latest libossia for OSX, we currently have issues with the dynamic addressing of ossia.remote. Whereas using the “address” message to bind remote to parameter seems to work quite well, whenever we try the “select” and “send” messages, the binding does not occur. The same problem occurs in the help patch presenting those objects.

The idea for us is to port the use of the index (right inlet) defining the old j.remote_array object.
In addition, we wanted to know if the dynamic use of “address” instead will affect performances for the exchanges. I’m talking about 40 to 50 parameters at once.

Thanks a lot in advance for the answers and solutions we may find together.

Gear :
Mac OS X 10.14.6
Max 8.1.3

**Comment by jcelerier** [comment]
@bltzr  @avilleret I don't really know what j.remote_array used to do, if you have an idea..

**Comment by jcelerier** [comment]
@jln-  too

**Comment by jcelerier** [comment]
@sacreyoubeurt  regarding  the state of the development, right now there's not a lot on activity on libossia as there's a lot of focus on getting the next version of ossia score out and we're a bit stretched thin :) but eventually things should be worked on

**Comment by avilleret** [comment]
@sacreyoubeurt could you make a small patcher that demonstrate what is not working ? 

It seems to work with release 1.0.4 under OSX. But the select message address one node twice.
I'll try with current master to see any difference.

**Comment by avilleret** [comment]
it seems to be fine with master, I  ne

**Comment by jln-** [comment]
Not 100% sure I get what you need to achieve. Does the following patch works as expected ?

A couple of notes:

- 'select' and 'send' messages wont make a remote bind to some parameter. They allow to send a value to one of the addresses defined for the remote. 
- regarding performances, I did not make tests recently, but using the 'address' message will more likely cost more as the remote need to subscribe to the given address.

<pre><code>
----------begin_max5_patcher----------
1009.3oc2Y90aSCCD.+41OEQ4I.Uh743jzvS7.7.uvyHgPnzVSmmRcprcGEl
12c7eZ15ftD2FOZgIsTkat97u6Ne9NuaGOJdVyVpLN5MQeNZznaGOZjUjQvn
cuOJdU0140UR6vh4zu2L653It+jhtUYEuVv3pVoqqTyuhwW9UActxM4ojxDz
jHRQp4iTr4IV+L5K69NrE14QO2ul.sSDeyJFulprpFdPXyFUqTjQ3ciGadLw
SFVQkxpkz+.BAcMUwTrFtLB0AL3LvRAIy7A3X5Qz3Vfperl59FwwGBzzoGDT
7AAEBHnuFkja9onCHyIggwhmYFex.RsyjunK.QVBycNyrSEP7ziHZMf.NuY0
LFmFwTzUxjnO7w289OE8VkfsbIUHifNcs18eYSsLCkYdf9jmB+xiv+hCt+MR
RU5e61Q6vMGJr3hfSMTFcd7z+rNQPuo+H4LTQBfyzaZKFfCMENONzZlT8sMb
Nst6XWGqjhhjBMp448ipYlOLp3yiCcC+5FFOB6gKk.IZJy.OcnOoSM8HHM8T
NoYSshIqYKnBObdtsfoX29xb+iSm2vUKpTU6u3WdUiTMqRXjQZEJY+zNC.5.
FCxCKQQ0JphJ9JkWMq19MP9anv2qrkb5h.GjzHkrJ8F+UMp1j72BII.5NONS
qbpMUGoXfwM3hKh3F.O0cFM9bF2fy9WHt4wGL1UM4XvlbgjYMtkm5whXx4IK
5df1enCoz1+QA9Tg7Lc1uftjtc8t8+uH4UurKTKszQRs4.JOl89ckC.Nlb.Y
ADc8zRipVrPn6hwCrAj4io3AT6CjeVKls2twvSICpWEH8etdU.jygB4CuWE.
t36UoE2Lzv5UAtX6Ug3pLAEfVUJur6TwQpNszfaTo3xsOEGjEjfzlR9kQWJ6
t4qyZOJ++1hhyt5NmN.cn7LGxzI526bdL85i1zq9nuU2To52R.6pXobHmrcD
Vg8yDZmKcdG9u+OAvtbMxeroQ1rQLuc0zVWbzCq3ETohwqLWg9dCxbg96MnF
gY+2Sd289pZyjB8nYyMraFzfUTeHZtl6AqHyUI2qlLsjaFzfzj4JP5mIbHzD
1GMAgPSd4mRCglR8Hzybw3COhnzGlPgfIe1H2FfNbq2eEMAE93mHAPSXe1Og
CgexqDtlap5PIbggoZerlgfQSa38xHDh7fFjv8on7PfjOA8gHKnWltPjDDP+
0zjOI1ATfLd8EgCP.xq6SZ8PD1U3gdJCQNcOzyete0U8Y0502PExcC1pBcI3
W2XyXMch8UF28psh1XA8FV63ysRpD5hqU5Jq2HrKq3s4takNdUiN2GeCaW5O
MbZUZKumqKcWttxwgsKfw2M9W94VAuA
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
There is also an ossia.remote_array abstraction that you may find to be useful.

**Comment by sacreyoubeurt** [comment]
Hi,
Thank you @jln and @avilleret for your replies.
It's been a few months we didn't work on it so I maybe don't remember well everything.
However, I tested your example patch and it works well with the latest build of Ossia for Max.

When i first opened this issue, we needed a system that allows to dynamically create and delete "engines" with a unique interface dynamically binding from one to another engine (we work with more than 100 parameters sometimes).
With Ossia library, engine were ossia devices and interface was an ossia view. Once ossia devices were created it worked well : we dynamically assigned ossia.remote objects using address with good performances.
But creating and deleting ossia devices with so many parameters was a too heavy task for Max, resulting in latency of several seconds, too much for our purpose.
So, despite Ossia's practicality and flexibility, we decided to use Max pattr object. It was an industrious job but it works, faster than ossia and so better for us.

Thank you for your help however.
See you around.

**Comment by avilleret** [comment]
Ossia parameter registration could be time consuming, depending on how many parameter are used and how big is patcher.
Despite we spent lots of time improving it, there are still some edge case that doesn't work and we have to browse the whole patcher to gather every ossia object and build the right node tree.

I'm closing this issue now since I don't see a real issue. 
But feel free to reopen with a patcher snippet that shows what's going wrong.
