### ISSUE TITLE
[ossia-max] [ossia.parameter] get range is sorted for @type 'string'

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#565]
Hi

when using the @range attribute for @type 'string', the range-list gets sorted. This is unfortunate in cases like the below patch, where the range's sequence should be preserved:

<pre><code>
----------begin_max5_patcher----------
1725.3ocwYkzjahCE9r8uBU9Rt3wChclScpLmlqSlKSpTtjA01JAj7HI5kjJ
+2Gs.X.C1z1t69hMnmjd56sqG+b9rEaXOgEK.+A3KfYy947YyLCoGXV06yVT
fdJMGILSaQAVHPawKVZoIwOIMi+IBMkA9TIRxYf+jI.+Mln9gfkXvm4XA3en
Lv+h4r5UtGIS2QnaWywoR6Iv20ckyR.L1S+maXn4O0XfuVsHVoLGKkOuGaWw
hEMjHYlyAay29MXTMSnkEDpZElyt6gAs6iYTndveMet9mkSTHPwOp3yQxfej
uhie3D.zyKw.vDn9OunIfukifwjW.DcucPbOmPkmBggFUnU044dD.ag.+AQ.
bPD3bAHXLK0zbLheJqv.6w1OvfgfKzHL38wFLmgx1fnaOA.cS7OncBhOO9L6
2PXz8EnBg2RiP7dLMCf1q+679aUpxjKNdx6DNkfMfbv4rW8bcLAUBMQMChln
9boM3hc2GB0wu.P6cSChRjXN.NA8Jz.V+qINZ36SbTtZaw.tRQfmfp0yX4F4
bE3L5UFmiEscKVdVXVEPxlzHH4R8Rcdki3VVfokmGFtwvUQd9vPnWTXRfGzM
PE6whJuSgJSl0iTgRbQUAZKrkOAVrT+ipdplm0EX07holqCuoJCq4EUcYMOa
KU6vq552Nv16YT48nTyQyYfb29GjCbTghg70XJZSdmEn2DA4Glwf5nSSOdRq
cfp1eCi+HmfxWb67AYBAAopXqfobEEkaJXY37eWH4Z0pAWmWYCcrIUbBmnuY
GkaJKmwsTcVorS7SVpdHJIzIJV+TbhODpdBNbETP3qbH5MFfiax97.A+3CDA
YCImHetMuX2eu.Kqghi9ve3HmyR+NNKii1JR4r7711Ho4jzuK2ohGtcW6wsV
S6NdAVBObLgMa0Jv1t7aX7LLu8bFrbOSwPdvUt8cZCpRlBiWEEFD6EG5543G
FGELn1vqVLgK1fy5oINndbFtB21mP6gdViVQ4HPTXFyEDFs0FOagpDnVCOq0
RzpxuYsthW1LDgZGB1Lj5FKj50G1LJhqjSRkPpjac9dJr1kWuMJAMmVRZhjZ
LppNRFyGsSqXeU.DiUVM41YwMWCxOvXvD5aSu42xXWqTsFOsDQJiMUYeDppJ
PAlJQxpCeC4L78nxb45NgebWMH8dw35RrWjm5orkSxXT8gnipPObM69B.ZLq
z+d.LlYPQ6GXwJCHkbYDhBEHKEaPbiuWdaabU3LFKuKol0kiuWVQdOgR6IEk
r8iSjS1t6DqcCSQr3T6sghXcI0RcsxnPtVfdnqzVhxyqhN2c6eBQIEHIVRrp
.WmFhGEY.1kxCCPISYjmhejjIsAYZaLnlNYesQzhFsbFYKVH6NlTEAq6HB4y
VgdqgJqCatVk6detBEcmfx8fHjhcrGEUSr1Pqs.3PaYZ6T2NhcmwOY4Xcy60
pKLiETrx50w0FaretsyTU1X0XOZwYiUf1r5TVUQXdEDF15dljzHFZcocuRwg
+6r3HkUnpjUNn33y6HBfoPHf5AShrLbFfPAHPsY8JvjjW9UxopBj5ItzbrS4
Od0k+3oRHjXJ+wKxNFr2ZG3ZMiVEzXMS5MPV9wJAo16NC7g5JL+vjjd16KXa
Tnaz3B.XR6sqSJu3lnbuSBmN0cOTs2MWd.ztpavcUIgM8KFbm1mpZBf6L2kz
RP2QYcmlMsWtpyy11P2p2y2oJvbOPkuZW6yQNghSYkTYeutw89sEqD53U2Uv
y38u7DQ.bu.qV22REi0vs1hcRFrQ16C44bkQGgWfrYnniGJ6RqrGIYpAMZ5C
KzDrRdZ8ItRwA5BLU8CRBsoHzuzDhG.AecRprW5YHbhmgpy5fhl4GF4F0mG7
S6YBLfIR+uRL+YUA2d9fj3nvSbG5Pau0CssuDdg88w048oS6VOEakkfMHAI8
rPMJpcOCtfVbcg8g1rWc8Cr.uusWE7OxlKpsM2H1a5u5l1nuFQM28dPQ9T4L
zcBrV2NpZa8KlSSAiwclSCDgWEimBB0M278gy9Cy3qTq5LELCuAZUe+NVkml
SUSpfjsmQnxJmEOeuUApb9p7bG0WW8Go9LzRrMXxwq9kqDQAuUNDgSQG4dCX
jQ76dFNEcqXzahrKdBH5lwHmqy71MQaY55X+RvQwG+1s1DNdB9jI2.gSxDDN
g2.93NovYGwHaZ4dsvUyidstsWaaOtksi2t19sp0zlVaWq5UJPSyN+KTAq.s
dGYqB5a2IwYqYs9Bd0cHsqHAklptFbqKzCseDffk1OG.7fMyxJQKWsf9sOaQ
gZmI04WpkPizQ44+Z9+CKo2z5
-----------end_max5_patcher-----------
</code></pre>

I personally would prefer no sorting of the range-list. 

Or alternatively an additional attribute like @rangesort off/up/down.

cheers

martin

**Comment by avilleret** [comment]
I agree that would be nice to keep value order but I'm not sure we can handle that easily

what do you think @jcelerier ?

**Comment by jcelerier** [comment]
hm, I think it is doable without too much trouble - problem is likely that domain_base<std::string> uses a set instead of a vector to store available values. Maybe we can just store a vector and if someone puts the same value twice, it's not our problem...

**Comment by maybites** [comment]
awesome. thanks a bunch! works like a charm :-)
