### ISSUE TITLE
setting unit from remote / attribute is broken 

### ISSUE THREAD

**Issue by avilleret** [ossia/libossia#573]
see test patcher 387-*

**Comment by jln-** [comment]
@avilleret Not sure what you mean here. Setting unit on ossia.remote seems to work now (it used not to - so great !).

Remotely setting ossia.parameter unit attribute with ossia.attribute indeeded seems broken, though.

**Comment by avilleret** [comment]
I was referring to the failing of the 387-* test patcher. Where when we set parameter unit to time.second from attribute, the parameter isn't updated. 
And when we set the unit of the remote, it doesn't work because the remote is not aware of the parameter unit.
