### ISSUE TITLE
a remote beside its parameter *sometime* doesn't work

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#586]
if a parameter and its remote are in the same patch, sometime the remote doesn't bind to the parameter.

This example patch contains 3 models, in each one there's 1 parameter and 1 remote.
_to reproduce : open this patch several times._
sometimes everything works fine (you can see the 3 parameters receiving data from the remote)
sometimes only 1, or 2, or none of the remotes communicate with the parameter.

_**If you remove the device "myDevice" from the root of the patch, it always work as expected.**_

<pre><code>
----------begin_max5_patcher----------
2694.3oc6as0iqhiD94t+Uf349DgMXtLOs6nQZkVMizJsOs5nQQjD2o8YLWD
3zWliN+2WeACFBPHcGR5QCsTS.aLT0mqpb4Oa9982YuI6Ubos0OY8Uq6t662
e2cxhDEbW002YmD+5VZbo71r2jGy19Dtv9AUkOSvu7LojrgPIr2D2BnplrGe
rDyTOamUNOHNX86UURy19G3c6Jh2WtsHiRE2lSUcaojs+A6ohrC6exrbbZ7F
J9oiafphmOthM6Sx1gaURVwNtvaHlwE6q..6j29M9sSA10hIYmToy17sufzZ
b5gDRJEyJMet7ByNv5VJNYCdm4KSBdjz8qKvaqfFem.A3.8BWg3+D5ItBDAV
gpkBMjq5Up5Vty9QBWowEkjrTi2AWixyMJ9NilH5K+Vl7AE9PcQjzLSDgWTA
VzkpZePcowEbYmwE7CERL09UeO6lGCG5JROPjOIUg+3dsHIseRiSvk4waUMV
XloqtAMPQR0WgItgQJnwswxQzopLdL.ZtwVNNkjlWfKworXVkrWW8N7iwGnr
0OlkxJI+oTB.vU8V+iURXuUJzAo3+OKHwzZEXeAYWVpPHZ0SHJV+59pE.I0M
joxHuiz37dZL2niCKCTYIWIOTtItP56QkuAntRVVFscU0sihejUUcNIMsCJx
xxGtxBx9mFosax3UlL1yVVS45CopZWysIXqKietMZyhozT7Kbsuyi+03TRRL
CyHpt.nSckGEY.ztlm6olcba7s3WH6XpfLlFC7amjqMhrq6k2Q1iKYsKiEqB
ezTRI6MEnaTzAcXy0LbRNkqEsuAt2AojU9T1KkU2n1PyD.ZhTa5SaFwtU4ch
byCQsoNtc2na.fYE4wE7WOiKtJ7yTPNJDHncEFgAgF0nJl8Vdky.W24w.hS2
WGrcn.j.fvsIxUbDIGHABEtP5F8i6uWexCyAzD84EYb8UQKcWEflMvYyAtic
5.fS3L.Nfw.myvjAHfBMrfbtz1LpXTFBBC+pJ3v1rCorAsmP1CAInAgDuwfD
RJSXxn+Wb4DsbBBD4b3ClGmpgAHtQRQlH.t0+HdKi7L1BL.X4NHXAmS6GE7f
TlQfnqM9jwGNHdUANIigsRd6+H7qF.f7sOeGL2SE8Q9+Ti935n9AdaPo5fN8
ATTRJV5M10hw.Ag1yP76IFhBAUAvkPnK5Zichb1oVUS6Yk6P4FXegigO432x
idiaX0jKsnydfLjjuCQ88iZkYGJ1pktpw7sbZIk7jBYjz5YV70ZuOqo1mctx
.ZhxPzLJCtSTFPynL.mnLHRgc1DB8C+jRQ3fBQUgpRjGUB1BqKiv5h6Lw5hK
vcg0kEVWVXcYg0kEVWVXcYg0kEVWVXcYg0kEVWVXc4Jy5Bbg0kEVWVXc4yHq
Ks7ja7hys1iYqalW8wrVD0KqEvdYsnl3lA8W6yWURaQju3HHHrwU8uebW.UQ
ygdpn4dRvvyweg7hExKVHu3CRdwvoxjWvmwikJgFEtb1ykX37XbFOQEeUtuN
H87vmiTf4QdJi2i6eplTbbgE2paJjWbIl+zIycCFp.iHzbRXyXlCXd7lcVkX
l3+AvkfqeNsgJnHvogNqaAt.tfSj7xfHpwK8QWaD4OoVkTd3hAgDz6v44BLy
Pk+iOxXpg2HGH6K2Ll+flJp3HtJrIvaVvDoZb1yA1Y1TYcBWb81QerUq1lkj
fSaOltTtS2ge0HW141hgYQs1Lzft.6aF83HiAmc+L5GEdCbjle+nIfINCgHW
+wk8P2zAglV5JP+aEtbqRWgYsw5KCMvLDcoCpHCnLwEOQmga0XRgWanY7kWB
58YX8kTo1UMIfq+BLUvUBrUWhwNZP8aYBd5oN5d0ykw06pmLi1kw4CkNC7BB
PJcXHDBc4oJnZjWemKcBc2zE.w83UoHgrKOiGjnRRfQdBtgqnCE1bwLwTevD
kb3oDbPXjTVUdn.TyUyjj6OQIO3SvhNACmYg.bQ5B4waDapRfYWn7p4Z8x7l
J9MmqXlK3Svx1IEhI0K5cptQWYuHPkoUkao7p4ZEGCOyneyiTL4HYy4pPC8O
yHBC2Mh7LhmB8l6vovybAzO4PXf.U7CiqlSQex9Nti56vi1Ij1vp7LU6rhvY
D18Nu8NgYdk58luysUx5wyq+bCfPYHIkgs7h90GvMciQb5bzzI2bsxQCLUWS
2YcOcLUuL2SmmgZWPH8w7izmOWx8T2PLnSuWTp1kFhExd2Z0h1uNlwJHa3Sf
tr6t13rVb48zrMwzNqHbeq876eawzdkQal9+X6HFuqyNhQdHnyj6OS06aD1p
sXJciXOizip.7GUW5e+hzOyO1Ct+PNV4ojxVDB0.Faynsjfg.GfqbPIW097K
vXSkX2ylXQ7Xq2pCPOco87gfUj8hhnKiVtC+n5MycS4Nm9OH9Q+8nUcPMnX+
E+Ef9eqe+c0KNvd2xbCKXk71uXtyE5aw15kFhKm8JJPsKdAeHK1+190ABlou
NPnyxGG3xGG3x9qaY+0s7wAt7wAt7wAt7wAt7wAt7wAt7wAt7wAdk+3.AKeb
fKebfKebfWyONP4CrsgqhCltxWESLianNDvzZYXNdcNT9ZpU7p4hAHGZpBl2
DDrHSx46Wt7TKqePf9h5au8JIMqxYKKvNK4y69ECmH.0lkNkASGFdDuhNL6z
gUmiYzYX1b5xjijEG0rZ6Xj1PFxgcjr+qjRh0+FN8fZ.CMwIsAhM6ejPoayn
YGQnkdHBaUs0jGouWAMhvHO.HTvknKvM.5KOieBBYtPOp1.zMxC4E4.E2pmO
LvCIOKD5hbaQJYUyfMuKGPj5M3DE53oNiWDPRbbSy34TVQASfAOB4EY4YE0b
QsxMp99Ovx1WDuiTsSvbZEY3gJ6nBdscISvNgCnDcaLs6p6L92wIYIwqehrm
aFt+IlXUeJ3RHdrdk3sa4uMCjFnHrE0vSt1N7CJdwO95aXJM6kpVXrg3ZDGQ
dJs51QUvt4YNs5EZsVHeUrBmsqRK.eUycWa8QJ3kTxtZdV+98cs9pvjPPnua
PORvl8sMUc7.JqN.DAhjFsNNPWwYGgmr3MC9dcV4GDgbjO.DJDnrZc7AByeS
A.SwIs6FE19fnfnG58Ly1VC4qIohfKX8CHj+Bcj1AGe1Qpgd45ZoJs6YL2Rj
C8VOEROPG5CSODSs6W+QLNYeW+QL7Ckvi4OGe2W+vKqBhdGQX.C4B+DllKV7
g0z3MXpd9A8GXYRdxni05NFM.2yyc9cGd5aU7u53nUq28iJw643wflNZHbJN
icW7xI6QzpOHHTL3mzCSdvSLVZ0PgWDTTn5Bcvj6v9AgtgWacXz.aPe9v5RW
TnmuGn5r.fKbTCIuQBXOwmXIWb1Jb7Z05HemfPoSbnHGCogM.4yif0t08OTa
G89xzKnBF2XJ+tSHaznkC2ucTBUOXb.LTXwN2zDhbo0qoBLJhQ9Y5A73AuNp
qRj0YfumzWwuNoxHQQfKYOmg.B+rKftehEv+UAFmd18wpLecE+Ich49vvf4R
3felEN2OmB2+SNAhw6WOdzUTjiS3vggEwsQ.ogY.OwS0TLPQHOzro.v+pq.t
+ETAJII4T7GM4NVb9ozcizw90XVl0uJlM96JOUEqOCrIZt+G2++AzCRnD
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
thanks for the report
I wonder why it works "sometimes"... non-reproductible behaviour is something I hate with computers...
btw I do have a similar behaviour with objects inside subpatcher instead of bpatcher.

**Comment by avilleret** [comment]
while working on that, I'm refactoring the whole registering process... hopefully I won't break too much things...

**Comment by avilleret** [comment]
this is fixed in refactor_ossia-max_registration branch
