### ISSUE TITLE
ossia.address_router unexpected behaviour

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#589]
In comparison to j.oscroute, ossia.address_router (in [branch 581-namespace_object](https://github.com/ossia/libossia/tree/feature/581-namespace_object) ) exhibits a few unexpected behaviours:

#1: ossia.address_router only matches a single level of an OSC address at a time, which makes it impossible to route multiple levels at once.

#2: ossia.address_router doesn't route top level addresses.

#3: ossia.address_router doesn't allow matching addresses to be set dynamically.

Here's a patch illustrating these issues:

<pre><code>
----------begin_max5_patcher----------
2670.3oc6csrbqpbEcr8WAkRpJSbr62OxrT4CHCxvTobgkZeN3HAp.jOGmac
+2CzzHCVRPCMM5w8Lwt.iDq8p26t2qcuA+a2e2hWR9oJaQveK3eGb2c+182c
m9Tkm3Nyw2sXS3OWtNLSeYKVlrYiJNewCU+sb0Oy0mOSkGrILe42ih+VP3pU
ophOf4h1ZN+yopk4U2LAh9H3g.FCT9KHU+KTwOC9OlOT7tMQwqU45aKzbxnU
5aVxKu8Wgb7hOuzjc40WKn7j+982W9iGbzpd6wjrkoEe4pfv0qS9Q1A1nJKH
OI3EUPIAr5i3vMQKKtzOp+pVGEqVlrKV+8gpIjhOYwsKLOJI94ieEGRYTCkA
0+BQ0+BiGDkAmNJaSgwG9M0AT1SEXPkFt9oBZXYztM0WP0sK+ispJyYwh839
0j37BhS+GV72SiBW2gmirx9YRsKirhLPmhEPGgEXxiyBvFvIK5+ogCr3adJI
mWS2Ek+T31sqUSMwTGRUQLrQPLbf2IlWWmD+oOwqIoEwSk+A1IIiGBV7RX72
9jTNhoahILylXlLAMjHCp3SlMsfwyUoOqhCeYsFGfiRKHOF0D7mgSs+AqUfC
rb.bnNHT4UpCBE4pCBCLONHwpeTb+Nv+XaZTbdPxyIuqRKnnez07.Ds4IpVf
PhGgsNgKSzi8TNVtaoZQuCcFyQPFg4flgU8ZLwtGhcoslaW.GwhdXuG59xt7
7j3SZ58GjVMDyEUgmj5eNfQZxvCRgmAKUvAtZoz4wROQ3ai7hsKklGb00miq
x2EdXdMkecuFt7qVdOwCriGOfNQ7f4zKSVmjVALviBLEIIPHmQ3.p7ghSAPM
OGq7TTA.KQPJSvPbBsXo2Rr69bOSVdilYVq3YHRLhIW3CaxEyoWUb5T010lw
N3kCmPMqg5BmHNWbheRgBBbNGa1EaN18KHep7rpoQWxBm68kxOU8P9SntLsl
0m.COnhNMmmFZqSCgLcIu4o.CWiKHrqEoEPF0QoED9EjzBnqJKHhylxhYbFK
WkdPjW7ROHtp7fBtNTd.kNaovypxijrrnvGMEe+YsDjTiFDen9.1T7AjMBwG
GkCQtK9PJjHpVfAAxILjV8AFJt.UX.ENmMMEeiov.6NkPNWTxoxN7nwlqRTY
w+k7p8Oy2aeF9zDNu0tmUouaX6dFkNcq1uMLVYwhtfZUB5CGz7zD7biVSsYF
GZQ9eybsP7BtJrbxDu.mAqB1qUMwJx.92nRRCd4ifmdW8MUtN0hd2tCitZHZ
DcR.VLShRdyFQVxpLsQU0HVHGtrDLb1rm8iPOsMoXB4j9GnL1EDOB0i3IbVh
IpF9lDpGSlzX7UhlA.xYSkbwrcEGLmxTJWndxHpYca4zrYEX5u1rhZeQPyD3
FUhyX1MlVBSErbhS3WZhIZDytLLtR3PPVgguVETjdvlcqyiJKI1Z06p0Y8uA
hlD+4iH+.D0+Y7j+8nrfHS+EpV0N8GyhqO93iSeaExpp8U67mFlvHD4LyOcy
JGKs3V4LRGiMOCce5Q0SmDu9CCKjEDVGQniBBRdMnHT4e9u9G0xqCBKDdGjG
sQ8PvO9dTQDzlv+awmKJOHZy1xu+B1qTAdUf1WBpJ+zIwKUG2qC2qWGqCuNv
AwjD9f3+YPZklTVUROOY1Lgfp6TWy1HpDawoitwlQf4zzrPQB2YSBJuz2EOy
pDFibLaiGfbArMdVovjYLRyFeMBElf4Swr0cHXs4LlgN4LrOd0Sg3stCjXZs
.xvS+CBtV5NPx324JH75PuMG3rkhtXja+kvWOzYfDG1btiFKf+kXay5DUUhj
5vlTAo2lcFnSbB6Fqy.cLyII3Jq+mnit+mjjKt1ehN51eRRupyZB5XRSR1UR
aMM9DIj7qptZxACUbA1TSdL0IX6LmvSRaMIk+QrqlbIS..7lrqlbhRPWUc0T
kJm7jslJvtuslFZIo4M6+Diq0fpHsfekThsQmmn.NO4I5yrjGswymoGPcWWJ
Fa1NoQ2q.XvYco3AnF.2Z6KFgZ.778bVaSmTUWAESis.fC2fPyuA0eiG0ZXB
h4C2rvWNscjygWzqpT5cvPYWfoz+UuVqaGIWS0udOtgSySvvoZWD7sYp9lzx
bnAavharL8gBmoD4Mo3GGXDB3BgQ9r7aGLgkupCWcu3.4Cm1fduPbS1dtO9t
5FQtDapailNGZpazETOcapE93S5PdUsCyi2NEWdsy8W7U8vFMW20fT1zrQy7
esOys1mYGV4DwtM2lYWnD4eDSlnNTc7YSPG+KJM88PWw2u7J0UCzxy2l0xR1
ktr1f2+fgG7IVWoxxih0cVaqqpHUf.39qZSzpsIEqbatoESjSKeQMnWJFRD6
OZ+GHIckJ8zqwNLzB6Es3tPKrHygOgKR5Q3V9J+pexs781zogKE2jcYTeBWo
Uvk0EbkUNCbjFtBLX+QmX9eqQW46JVWQm.6KzQsm6.mBcrVbGsAVcFcBqhxM
1fi2KtU2KTWLAD1jIPSGQ7E2iSMLA6BbF2FQ0RjBhb+QGFQhlkIP5jKqm.oB
tMOZ5gK18ffZ2dPS3pOZlF64cOARyEOjb7YewChMjIqhLYedzgvENKrK0hHK
CbEboGgqcqlfmjYDsZjrddyYICoNmfyjgjYX.A7nWikoeB5BtnV93dDrDo6q
rgZN6FZ5lbyNhjH5GalEJPdbcB6bRIbKbRMnEx8HbIVE+RlhrmnVsBJ2h47g
3lKfpOZxCHrISuxpBzq5FT0nnQcC53ih.2Aae9bnNUOv3vFfU.7LX6kYsIsO
DooXB8QSd7gMfUZiKq.2HME8QdwksOufNmjz3DXvJGdlwJhXAXMNALgGcBJa
yi9mSG2YhGxJsTFtUJkcvsyCbI1CWH.I8mu.lZyBCXbmoW2BulzqOqvEYAbM
NuMO5b4MzckuL.zjPBDg82xCVRucKksFurFRY0GM0v0tjZvT6ypo1SF6AxUJ
svWP14ZDPlN0.RKATDenIQZijDIu+r9IMkO4On1aLV4CnPG0tuhXospcO0Gk
ewJhU+rCz29hPasuH9Ar1HPQJsvKnYAWISPAWsy+j1OxnMUkR8gLO6h6IVD2
SaoI0KfU+Liag+oMocSaUYXOB29C96NyaAnAbMIy5I3ZU0AgXKXWRUMMadjq
05wtwdHyBg2zVaqnWlbxxwdHsSo2lw9J3Zjd6Q31O6BsYruUc28xpp1xtHKh
rLv0no0OvEPrhcASPszj1DDWuzoS2IrMJ06VrCjiZH1wrzgWD6nAKpOv1o6M
FAZ.VLxyfsWlkYAyZT8ZRF2Kpdw1THLrEI6TWHL+AUBzFnZgtAifLTypLOCt
m.KbOMrHl54Q7dcOkc2NRnFkMvHowKUMvJ2yxmHf9TzTWhCxYFqcWsKTy5ei
N2ym1YOdUOep40KUMuRmddUXSbOcJ10atMsbT8zPGzRiga29tJMyb05axhMg
uU0GxhGzGFEWcntOIWjpdOp950O2zKBSW98nb0x7coUsx4OM+2ZcwljBxLdW
jYBfByq3Vlk+w5u1Fk66Bz2zlsJET+BTnrOzUECfkeH8UXNs9EZZ83Ts0n6T
0xuqrsltbU2Pq2+62++wHONad
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
fixed with d69574d0
