### ISSUE TITLE
[ossia-max] ossia.router outputs both relative and absolute addresses when routing multiple node levels

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#594]
When ossia.router receives an address that contains multiple node levels, it outputs two versions of the routed address, a relative one (no /) and an absolute one (/). This causes unexpected behaviour when using cascadede ossia.router objects. Here's a demo patch, with j.oscroute for comparison:

<pre><code>
----------begin_max5_patcher----------
1877.3ocybs0bahCE9YmeELd1Gcc0EzE1eB6K6K6a6zIC1V0lrFvCfaSlN8+
9JjDN3DLHrkvNyTaPQhy46b+HQ5udZ17U4uJJmG7mA+avrY+5oYyTCUOvLy8
ylmF+558wkpoMecdZpHqZ9B8uqR7ZkZ77iUGNVUFjms+sfBw93pjeHBh2roP
TVJIgY96SxDqyOloVDxL3A4bjOS4RxydtyYr53pU6E0i.MijrQS1Uu7kHTyS
O6XZR1dQUY6YpW6g7D8iDrD+9rkbcyzAmM8xjMh1idHtZ8tjrsOWHVWokWPN
XIXQ.DSTeQT2QPKAAeqdM+9omp+Xgijqqxq10RtlsIHdUY99iU1Jj6UDxuSh
PhCkfYheJgxmDfGJRdWr11pA1Kj6FYcfAJPw1Xr9KT8mnqECqNVUkm0vXZFn
5sCBMoluJNa67fu0g9iM+DGVDmJpDEOKxhMJbf8.E1CP0HLDnzVnvlOmVfx8
OPIrGAfFMA.E9..zHf+AZnNBycViR8OPQOBZTNw+.0jr3NCzP+CznGAbhmBE
p6vYU91sRd6R3TUESGvjMANnTlFfZ+zaDmoxp9h2J9TIOecS91uVlk+y2B9C
3EECcKCXcVUD5ZwYnBmb5MUUz0pOm.2SD4AWeRbi9rAmNQedodc965dGq1IB
xxy9RpgIZZuIHoL3f7IH1DHYY0zJR1tq5K6paFRihNa.BOXWlXaZQhBFWKRQ
itQBsKioQhltgfN1VZ0wMadKXjVQTnarhBomAQD3lLitDDAiDbHGANSQl5uH
f6QHO5Djo1zv6DDxqP75nC3QCcTBLCJ0A7nQ2EsIYx5AbBzl5HOiVeRci9rA
mlDXj6g9DOYc5NApyumrIezZyPmFp0nLYPujFQWv0XMWibT3GylsoAZjSSTZ
Yki.G43w.tKs3kzUispXnSCp3Frcg8u9kk4kqKxq2nekKmNLpL03kg7hV+qS
32cEOgcB+vAcCwz1gV8H9qi6zOp6BsioCHzvwbzoN3LuzAz+H6poqFe1JgZ8
P2yFfHQdtAHDCLAM.UWT4HCWPbzlhD5wterDINZ6.f2+VcHSwlRxeja0g3np
oZP48rUGLep1J8G1NcBcTTln6eiNzo57BdT6yg4xvrdoMG6vAxQsyff261YP
bWoR7W6LVhDmFmvq8tjWVlDuTU7dgy5dAENhWbmvgbtZZdgP7t.35ZegOBzh
FLThNePD2GfU8lVE7d+Zc7RWgby6bUyqdmtD5arWrdQSaEXG3wQuCYl2CNMb
tQky0lxlMYkSCIOj4robmVNstYuaLosu1SDF1MaJhAqQtvO7Z6bXxJ17A0tE
CcZO8dzr0AYCQXWlNLpu.tJxq1IsO7Bxqdb0ietDnL+Xw5F.X5BJ.bBDaDkU
IYpMeq0bX54zoL1V5vrfNbGPGL2BBE5BDENBHYlSZxF0dOZzUQQKIRcJCabV
at4FYr5McZPFqdeYtYQPyC45EAPtejA1XETuioAvKwYZdAC45npjS2cZA4Ea
j0aUG+9lXUpMpKpKTW0GU+vTh5BuPabBcgOnMpYWH4n1SntMmHv1F5ggNyRm
FdqrFE3IVyJyMXeNgFlw3ERX84EBuIdEYkXjXQDiHkXzDvHB69.F1Da6Cvwk
BI3Pjt2vpP.dIj15GF7jLChAdSnoXczPrNuWVmCWxws9ID+NqG4YVGODqG0q
oIEzx1D4Qls9X6G1oGYiSulYCYD+xrCYOy5MBEQFL5L6YTTqX.dVNOj8b8qG
SOrdzGrma4JRgdl0Gxdl1q8LkRZYhv7HyZSNrOXyehxnaSLYSFIlKptgQt0x
3QzPuTFOyp1ScR+oratLJdnmJihMhD99OSCm1ukvYYZzU8dAOSn+ynyI828Y
OYzIdl0GJuCOrWVum5nh7LmOXnBbuVHsyt25FWypVUIR8eXuA9gzCpei5uew
dpqvidUVUWAu2jA8UWAg4YVevnWrdigeVcETr+XVaR4V++9CAtu7Ka1bFjKx
lXCgftX2lroJArSnDzFYG1E63jMI8otXGyo1reBrOiI8QODe3vODEklYqHx7
z3WxUFp7EpaSxz2pN.j4EhejzLelZj3h06RpDqqNVnXr4uZ9CjZdZtzjO6Xh
weSBOIIKqda+GOtir3T8R+q3z7z3m2krUh8s6pDadNuHNq4vrjv66wG2WctL
Id8ZQV0578Z9Tlcs18WUHi9vfeuFtEFYagbAJFQQUyCOU9jSZ7PaqKNwdunz
JhB.vbfX2xiJI6+5CUmL.ZALvRpBTu+IrUrsUaOapbJhEplHmAHbt9JdHFd9
x9j3S9jgQT.2H9.KwTfbcmup5SbarqQrWjdEjZryuTRm00d.ilP6ERi41KBB
wLjVXWOcb6qNWz+8j86OszYmTiRAk4HGMvXgY3QxalE.aVAlQCqSLKupViFV
eUmq.0rBTDPRE0J.QbPn9J4PvOrLo6l1XV+xxaF8PQ9g7hl3JxkFcZ9Gqx2V
DuIQXds7UiqByLRONcLI0Y7V6mTdHVGpScTvO86m9ebmUx4L
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
fixed with 4c31e19c
