### ISSUE TITLE
special characters (like =) are not properly registered as part of names for models and views

### ISSUE THREAD

**Issue by navid** [ossia/libossia#596]
special characters (like =) are not properly registered as part of names for models and views.

As a result if you name a multi-cable model and view "limiter=" for example then they don't bind. A visit to namespace explorer revealed that the special character "=" was converted to _ 

I didn't investigate nevertheless why this resulted in the model and view not being able to bind. I also didn't try all special characters. But "=" is used pervasively but the community to label multi cable  instruments.

**Comment by avilleret** [comment]
surprisingly `=` is not a forbidden character in OSC name, according to OSC 1.0 specs (1.1 link seems broken for a while).
so why is it filter out @jcelerier ?

**Comment by jcelerier** [comment]
good question ! don't think there's any counterindication... I don't think it's a regex / pattern-match / whatever character so it should be pretty safe to add

**Comment by jcelerier** [comment]
should be updated here : https://github.com/ossia/libossia/blob/master/src/ossia/network/base/name_validation.hpp#L19
