### ISSUE TITLE
FR: Improve [ossia-max] documentation in regards of @priority for [ossia.parameter]

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#601]
At the moment the reference states:

`The priority attribute allows on to order how several values of a same hierarchical level can be recalled`

better would be:

`The priority attribute allows one to order how several values of a same hierarchical level can be recalled. The higher the number the higher the priority. Higher prioritized parameters are recalled first`

**Comment by jln-** [comment]
Done. Thanks @maybites !
