### ISSUE TITLE
ossia.device (+ossia object) and osc messages : FR

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#603]
When an ossia.device is exposed to osc with « expose osc / oscquery » it will output received osc messages that do not match any existing parameter prepended with « osc »
This is a very useful feature.
It would be great to be able to send osc messages in the same way : 
Sending message to ossia.device inlet prepended with « osc » :
osc /fader12 1.234

(A message prepended with « set » do not work in this case, as it doesn’t match a valid parameter address)

The ossia object doesn’t seems to output osc messages at all.
It would be very useful to make it behave the same way as ossia.device : send & receive osc messages that do not match valid ossia parameters.

**Comment by avilleret** [comment]
since we can expose a device with several protocols at the same time and several client can be connected, we should provide a way to select which client to send the data.
in the meanwhile, osc message will send the data to the first protocol first client.
