### ISSUE TITLE
Cue-manager instacrash

### ISSUE THREAD

**Issue by petervanhaaften** [ossia/libossia#606]
**Issue**
Max instacrashes when cue-manager from 'ossia overview' is added together with 'ossia.pvh.complexosc~.module', saved, and reloaded. Behavior also apparent across lots of other modules we've developed. Possibly related to ossia.explorer or namespacebrowser.model. Crash log attached.

Directions: 

1. Create new patch.

2. Copy the cue manager from 'Ossia Overview' into the patch.

3. Add "ossia.pvh.complexosc~.module" ( https://github.com/petervanhaaften/PVH-maxlib_ossia/tree/main/ossia.pvh.complexosc%7E ).

4. Save & close

5. Re-open

**Result** 

Max instacrashes. Please note attached crash log. I am hoping some useful information can be extracted from here.

In my current testing, objects that don't include ossia.explorer or namespacebrowser.model seem to work okay? But I am unsure if this was the case in my testing last week. I will be digging further into that. 

**Setup info**

MacOS version: High Sierra, 10.13.6
Ossia version: 099f7a8ef

[fail_with_complexosc.txt](https://github.com/ossia/libossia/files/5532063/fail_with_complexosc.txt)

**Comment by petervanhaaften** [comment]
I was told about an updated ossia-max library available in the gitter. Here is the crash log from that.
[ossia_fail2.txt](https://github.com/ossia/libossia/files/5532171/ossia_fail2.txt)

**Comment by jcelerier** [comment]
Hm, that's pretty strange - the crashlog seems to mention chromium & max but not ossia stuff.. not going to be easy

**Comment by jcelerier** [comment]
Tried to run it but I need ossia.nav.oscroute stuff it seems

**Comment by petervanhaaften** [comment]
Thanks for reading my log. I'm pretty sure this instability has to do with ossia.explorer or the namespace browser model, because this issue is not happening otherwise so far in my process.

It seems on the new build I received this morning, the situation might be slightly better. About 30% of the time, the patch will open now.

I'm having the same issue with, for example, a patch with 'pvh.osccomplex~.module' (https://github.com/petervanhaaften/PVH-maxlib_ossia/tree/main/ossia.pvh.complexosc%7E), and ossia.device with 'expose oscquery' enabled. Crashes about 70% of the time.

I am not sure if my 'ossia_fail2.txt' was actually the correct log from my attempt with the new build. The report may have been hiding beneath some other windows on my screen, from a previous attempt with an earlier build. Now, everytime I hit 'Report', the report window crashes. . . .

**Comment by petervanhaaften** [comment]
Hi JMC. Sorry about that. Yes, it requires ossia.nav.oscroute, which is part of our in-process tml-ossia repository:

https://github.com/evanmtp/tml-ossia

Thanks for trying it out:)

**Comment by bltzr** [comment]
> Now, everytime I hit 'Report', the report window crashes. . . .

Did you look into console.app? That's usually where you find logs...

**Comment by petervanhaaften** [comment]
> > Now, everytime I hit 'Report', the report window crashes. . . .
> 
> Did you look into console.app? That's usually where you find logs...

Interesting thank you, never seen that before:)

Anyway, I have observed the same behavior with 'ossia.client' and 'ossia.namespacebrowser.model'. Pretty sure the problem is some fundamental element of our namespace browser and how it interacts with core ossia functions.

**Comment by avilleret** [comment]
I tried to reproduce the crash following your steps.
It's a bit unclear to me what I have to copy from Ossia overview, so I copied the content of the "Store and recall presets" tab to a new patcher. 
Then I add an `ossia.pvh.complexosc~.module` object to the patcher, which gives me a lot of errors in the Max console :
[606_maxerror.log](https://github.com/ossia/libossia/files/5546523/606_maxerror.log)

Then save and reopen the patcher without any crash.
I'm testing under macOS 11.0.1 with Max 8.1.8 and ossia-max at 4c31e19c.

I'll try on an older machine this evening.
In the meanwhile @petervanhaaften could you try to isolate what causes the crash ? 
It seems that your abstraction have a lot of dependencies which might increase the time to fix exponentially.
Cutting them off until the minimum crashing patcher would be much more than helpful.

**Comment by avilleret** [comment]
@petervanhaaften & @evanmtp could you test with https://github.com/ossia/libossia/releases/download/v1.1.0-a1/ossia-max-osx.zip ?
@jcelerier pointed out some line in `ossia.search` (formely known as `ossia.fuzzysearch`) that might lead to crash.

**Comment by avilleret** [comment]
oups seems broken, see #620 
gonna fix it asap

**Comment by avilleret** [comment]
fuzzysearch seems to work as of e24fd148

**Comment by petervanhaaften** [comment]
Hi, i think we can close this now:)
From our testing over the last week, it appears it was related to #635 and #620.
If anything else comes up on this topic, we'll file new issues.
