### ISSUE TITLE
[ossia-max]: [ossia.client] doesn't understand 'getdevices'

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#609]
This is with the latest commit from the branch ' 581-namespace_object' [4c31e19c]:

when opening the help file of [ossia.client] and pressing message 'getdevices' there is an error:

ossia.client: doesn't understand "getdevices"

'getdevices' is documented and should be recognized.

**Comment by avilleret** [comment]
the correct message [get devices( but it is not implemented yet and the documentation should be updated
