### ISSUE TITLE
[ossia-max]: [ossia.client] help patcher example works only unidirectional

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#610]
This is with the latest commit from the branch ' 581-namespace_object' [4c31e19]:

when following [ossia.client] help patcher proposed steps (1-5) it becomes obvious that the connectivity only works from client -> device and not the other way around, even though it states in step 5:

`ossia.remotes now automatically bind to the distant ossia.device`

to my understanding this means it is bidirectional.

**Comment by avilleret** [comment]
I can reproduce that. I noticed that only remote with global address (ditant_device:/my_distant_model/foo) receive values from distant_device.
Others with relative and absolute address are not notified.

**Comment by avilleret** [comment]
this seems to be magically fixed
could you check with v1.1.0-a4 @maybites ?

**Comment by maybites** [comment]
I can confirm. The bug has gone.

congrats for being able to do practical magic.
