### ISSUE TITLE
dumpout reports wrong address when using wilcard and pattern matching addresses

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#616]
See attached patcher for step to repro.

<pre><code>
----------begin_max5_patcher----------
2246.3oc0aszihqiEdcU+J7MqlQhFE67fvHMKlMyhQZjFoYYqqPNIFvcahYr
MEUc6p+uO9QRHAHPfJgpuKfHrShOmuya6C+34m7R4uRjdf+F3qfmd5GO+zS1
gLC7T4uexaC90LFVZuMuL9lMjBk2D2bJxqJ63ISUh2.p0TIfWP.E78.7JLs.
rmxXfLAVtF7uwuV8bE61PKXDk8kBKGbKVkslVrZgfjobDEJIYp+DPTvLyETX
r6xTevuW9Po6RSYjsbZg8Q702P8Rv2opVipQo4Vxkm9suDD305cXIEy.+74m
MeM4CBI+SNiogA0ZMbraSJQPxAREYqDn3.AYqfC9saEORBlFoA.nEF7CcWZf
FWmoQdCHKNaZAQyR4frcB1afTANiH0BeEVQ4ZYOeGKGjR.38DIeCYBHcmBrD
SYVLXEofHvJ8zfLtvvjfB7Fhbq9sTsTLZAIiuyIbQ2HZEEL2fPvfXCpE3aTN
.FUo9iWnjwUIIbJX5zoVbgp.anxTxZ7KDveQRHFCFs8SQNe+eEj9FPRJx0Ln
A5HuPzlaawB7lAAoPIVrIDZufBPmfTmZmA6MFNabwv3o09cvLIuRACKVQTZC
MIu.WjQzyyd6d8+3Tc5k+mjndiKwiKtDLMmnuKAQqDoVC1rionaYD8TZUMs9
0FqU3dt36f8qIE.Fm+ci9EVYcZUYdlevpTqpdqHXXh0YEzOvpfk3eBBdcbJZ
bwIzTyL6JnYFmQVrZof7+1Uj8F3uCVpsq7tOyofRtEFdM0FX+CagF4vVvozB
phhYz+PK5OfFDMbbq3P.xZ9fPV..FGe6BeX3vvtEj85W2Ib6VA8.Fze1xkNR
hksbNKQnaJL78DEdIiqew2JwNOzD7KBF3bjcEZsJvgaH0aaIt2hm2DfWJtXk
W8C1TmrVHsjK1fsqbbMIoCRQTDwBRAtT.5+f49f4giI2iFetuC0WtTRwSEjM
bsmq5Pc2JHA0.yAcDXYx1cCSAWBlreNKL4eOJ85HOR7JxIbtMwQc5JmkWQWv
0r+7F1tPH7J7JrSd8b7Hbt2HIbuaevkB2RS.XPvnHbgQCov8G0b660J0uukp
4s2y2IrEW7to5x2WRYFaqLNY4OfSmN6muueMVoK.4m2pdALAYfIXnymdzrgU
uv2aHiYQ1pKE.fyy0ni7lUHhcUEkLykXl+fxoy9r0CteM.W18kYpFflOn3R3
iKhODVZiGOhA8R9ji4UuHe.OiwyafSvH3GAnNKHEOjV85BxTKNYCR5q1cTjS
oHwksZR7fpcO2q4JSDkrWI+oURnLyVVH0FrMd4O4g2tswvO03QLfx231WTxj
5gnEtgP0CIHuPqdd+5QwBM+qzL+Ngkt8dMtJEUyqgmSDE6n00RXEOkjjUPb.
lMOrQdUMcCDcdS2Ew1Kw9QGPTsfdEim8cRdShyiqcdSKzNwk5xur9vZMcNYI
VWo9hk7BkTWClkHQSO67KKovyNogGrj++PnqlqlAVIn47BCQzRRXFtZ4LIM3
LIZxL16n.u8LOrVEPCKcLoTyj6joXgQPU5NnR94o3bV6opeNFYopb5szhhiP
QEea2SJnqVegmMkqmbykd21YjK1U3lcgVmPsPheoMZqvLVo0Z6W+q3Bp1oHQ
Qch.je8jNWhqkYBNi0hecy7xYlIWqimQ1SyUqasG2lYz2NcakRjWsTNmthHU
sGSgWIaOhT8lCzaLztzRa3EJxlsLMWz9FzVGToRtluWVdiUJZMAfCmpPSa5l
t9ZM9EyGnsevLFAK.Zju4rmyKX2t8sahNbdGUD2syvq3P7TmhUCai.T5l4Ng
jVQENe9fRhYa8TchKvKiKnHWsxgVDYdvngKydv3B7tQjXaoSn4VugwQiFhD+
fPj+fAjLsqjK.IWw3I.Z0QzIGGc1ZG5Nsodj5zwvRzi2.5dUULYOdnJ6Ygil
pBZHwDK60IK6eYVNxcpZ1DIC7q9dvY3VppUaZcyHR16uHm7Ziz4FaMFEfARu
WckxPNtCmLXPLgZUl1Ia1L7OO1QggOHynjGLl3e2dVRfOlfPnY+4JekJWtid
9JnGU3YMb.RAe4tyWAFNyfHystjim0C.InWNVlXhTn5FedTwoss2.QzI7DcE
3YtMhUoi2XXOvmvKgO1SN7v9heQHJ7AAQBMURNoMZt4z7bgnfQgM1hiQKMOX
zuL4zTZAM5I0DDdSY0fFP7wQj2qKl.K9D4i5M.42ABD8gyq6vVSY58oN1vAK
OXl+7PijuSjUItJ2ISPa1ImHUzh5Mp6qGneyM1KIysRDy5IQfFQZHtmzvrQj
Fh5KNjLxDA7SVXX7WzOjXLUK0ERzOpXzIhdIOBGQpnRi6y0OAp2NJhGSpH9W
AyTTesSmO1DApuJmAiEUzWuEmJ33hb2o24+4RYmQytlzfiCo8qfAMruQ7pbE
ONTQOIBX2PQ4fUGqpm4ryxW3NmvEXkRPS0EpHO9bhuoyyZEimhYGcHTm63td
9.wcimE+2npoYDFK0bNtG53gNNb0a8v3CPkWb6ykoWy63z3CarzGcnu5bmYW
t8DXTYqBUOeGJU2L552W8QMhBqVkFmXoeCh4zSn1774jkt0VWQktR63IlK1h
EN7kqsvO+veAV8A76NMogr0QbGmJ3+pkILx+o4+ghd+GKorYJJqOd1v1BUCZ
qz8gaXDnsEtmELr8CWRSdzdGsKhywxG63pjwubQac4rpUvNuMzba22KqNLCa
6+E331l+pC8u9RZI8fzZjb1cuNydPqSbOVmjAZcfWYcBZQKsScYTWX37V2T6
LSt6UNpGP67A.ZC6w5La.VGTeVHj+PrRn93.HZHVI+9vSgCvJAS5o5.7J9zL
+q0zWRbmYu8WCsMSun0nyas9wrYf8wnAgFB4g+cY13hscTeNZVii5uwi5swS
6qwt6owi6mQaR2td65n3o0Ys9uva3avKVSWoY8UqUlbyE3hp7Gp5iv1PBNKi
Tnzo24nyu5xUy1hLUotUw5SJgVg9ANtIy7r+QDqT5pPnNZ6xm+4y+erhZtp.
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
there is an infinite loop in your patcher around ossia.parameter
this put max in an infinite loop and might lead to crash.

But there is something weird with the address on the right outlet.
I'm gonna fix it.

Here is a non crashing patcher : 
<pre><code>
----------begin_max5_patcher----------
2259.3ocyaszaiiiD9ryuBN5zt.tMD0KKu.6g4xdXAVfEXO1XfAkDsM6lVzC
Icbxzo+uu7gjrjsdkNRI4PhgIkHq5qdvpXU9GOrvIg8DV3.9GfuBVr3GOrXg
YH8.KJ99BminmRoHg4wb1QY4mO5rzN0IjL8.Ie+VNNUZWFHzak6RfWju9iPW
yWTCA9ih2Q85ryRJVZVPuhQsCIe9D1tLNNKANIn78NUuHIyPArju8EuqD.Gc
DKw7s3bTB07xtEysiwOhLTUz0sljWtyP8X+7gGz+a4H49T1wi3bY4tKwOYVe
m3UR9y.4Ah.vxwfb1E.ZOhjCtPnTPJGIN.9Onm5A17hiM3k+ZCfEDY+nSbqj
ISNmTv1v6gIeemFO1IFI2reZoxLCI+KFkpfA4AEbb9XBliy.BI9j.HY.N9Dm
A9sdviX+UgJ..ZfA2.6GChF048JcjYiEWuJGqXoLP5YN8YPBGkhEJguDIILk
rmcllARv.zErfcDuDjbVB1gHTCFrGmi4HoZZPJiq4bPtRWVbRsJkaEkjiSYm
sBMutQqP+MZDB5GoQMeWiUmVU5sn83EO6HXvJvpUqL3BQBNRDI3CnGwf+l.i
0FLJ6m7L1k+NH4Yf.mmo3ZMzgeDqL2L19uVjxK1fMAPqiIeuIAoV2scFbtwv
nUU9cPTAqTACw2ikJCMAKGkmhUySedD9erpNSj+GunNwk3v4FW7WkgUOEGqT
hjG.GOSkjSTrZJkplR+5nwJ7Bi+cvkC3b.kw9tV+BIMNsJMOytZUpTU6AACh
MNqftlC9BhcmDDLb1sA8Vom4bNIU6LxfU633+7bd5yf+IXmxtxYPyI+BtEFL
ILcWGaAm+isfqH4DIAQI+kRzeEMvJ3nGbv2K1FniA.fQSh4CLXxD943KpU7N
t8DmbECZksrgiDaXKqyxdBlqsigmLVXvHO2DnO7KDNqAdF7AE44H4d+MAyI2
+QE2cGpuLgffVwwGYJOWUG00WxIJf4pNBrHX6tgI+9fIyesBStSlRu5jGAZO
9NNGkko3WA3.Rph2rOGztapYACgvA3XXmbbabJbSqbp2LIhGim3BQbgg.z2e
VDwvvYWD+iJt8kJU6WNQTL7KYm4lTLdQmi4K6HTsgXJCu6GvUqV+yWtXUK9Y
evTrmFlfAVO6gqmV8B24Vu3jJERUBAfBCg93zHatQwqsgm4Nob55Ok5AiRCv
FieQ7p9dalTbIXxT.F6MNUHfmoi9h+LdxWEsLNOiQEhXqbOD9V.pVAonYOdU
UZYxs2cMIsciHgVG+w1XViilTs6NN1qN4f4ErWA+ozNHT8EWHTFr01wENnSm
pM7hZuhFT9FyrPwKqFhjaGBVMDG+Ho78u9fHtBTjJD4L2vLNOEUZUpWFVFlm
elTIgLhmBRxHHtBy5WVKuJmtFLuotOD6c9F4FdElUB58TV52wY0LTTvrx4MI
W4DWnRBy3CqwzY3cHU95a2wxkBUlXFhzaUqyuqfBacRMOXH+emqxoqhA1yIY
rbMQzPRnGtb6zQRXsSpyLlmHGcpkWVoWnfkNlTnXxyhDDWKnJ7Z3UNojwnMm
p58n3cxhoOQxyuAEkrScOImr+POuaBSM4w9VayLhsmysytUoSH2JPO1DskHJ
svZs4x+DJmn7FhkDqHvysZRqmyChTNiRavu1YdrkYxT53o3KjL4gF2fsdF0i
SNUpD4TIkyH6wBYywjn8hliHjOaA8ZCcNovFdqDe7DUwEMe.k0AQHEGXWDEO
XohVc.3ZkUpaSW20Wiw6Mdfl9ASoXDGnP95y1pKey0nC2zQNwc6Hb.mgc4Pr
ii7WTdBPgaleQHowoBsGOn.qubO4.3hWnMa4.Chrwe1vk0chKv2WbANDhDYR
axaiwoWT3rgHQezHxeQABpxUxfPhOzninBLNr07F5NjoQD1zsvR3mHCngbpD
Bqkg85fYSUw6cQUwrpCvxg15pYBhz2s7+SNCC6jgcqMQ4UWW+DIyBkmge5cz
PRBnfjg.thxrs4Jx8VMgZjh1cW2L7yhC2gsiBBdmLih+rfItC4YIF99bHj25
OQpIuBWtyd7Jde3GOqfCPB3KCc3LLXsFQ1XbIGsdD.h+nbrrTeffra7I7iFe
LM4.lOD7rwbhUgi2H3Hvmf9vGSYBudm38BQAcBQguOPDWQ936Zll9OhBFFT6
lLlsv7fuOw4MlXZJrfl8fZ7CllnZlR7wR8CE+uAeBc8FM.41ABziSi2ZbcWu
ZJcGP0wENXXN87sCMB1YdZobrHNTPS9LCKjj7pKp6qW0l0O3njLuZhHbjTgO
bFoBuwRDyITncoNJpPGWyMOHimYuJZ3GKoE0Mk4NOTlVh3MFPSyB9yknSSEv
QPEalS8mnwp+DOmTw5wREQyIUD+Yvh13yBNVkyYkJFCVLqPwnctMmTwXMS8l
YZ3C2JcrtJVOizvncTLizvl2tahhAKKqpit1YYas0IbKRJ4jDUhJhaqS7qpd
V6orDD8lhP0V4td3Jw8JqE+2HxUoXJMQWG2gK4tuWwG1azR2W4UkPuVI+bas
L7AUcRwcE1UEeLs+9RfRDMxRs8VSppIEZu3x5sopJidAt8Un+NqvrdQxv6rz
kJUKUJ3QK0eXxh35+rcLd6C+EX4ef+vpIMksNhsbpf+mRDRw+25+RJ5oYJJx
Qd8z1BUyeqz8ZZXDnoQtW6Os8CW7fsCk40ZlDmkku0wUAi2ui6gcXdGzN18Q
2aeCtQqmhMJbLbzjvRwiXmZRMMSqZd24M0iMw4HIy7ChPTVZJSibp+E6n9H1
VsRy2tmVceSzp2XD70iW8Wem7FwNU+xG902ofwvStSvNE7NY0DNREp259D0P
orCQTSM2IxlYL6re6FquMCf0i.Zil.nM9cZe1LFqrlGqztyGe6gl0+VCRyd1
1M84nlpto+Fuo2FuuuF6tmFuseFMAca6sqaNOsJfs+M5H6HZ6AxdEXs+fTGa
NGkWF+PYeD1DDQoo3boJ7NKc9UarZldmoLzsRVeYgvfqdgaaxLGyOGwRUxRD
pi1t7ge9v+Gv07yNK
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
moreover, the jit.cellblock was not large enough to display all the nodes which makes me thing it is not working, while it does

<pre><code>
----------begin_max5_patcher----------
2275.3ocyaszaiiiD9ryuBN5zr.tMDodX4AXNLW1CKvBr.ywFCLnjnsY2zhd
DoiSlN8+8kOjjkrkjURjbxgDGSJIVeerphUopxOdXlSL+IhvA7afuBlM6GOL
alYH8.yJ99Lm83mRXXg4xb1v3YG26L2Nk5O4GkLhzLIpXT6PxmOPrOYGm4.m
Xb1VGveUbIGvxjczrsqyIIR6UAgnEtyAnPO8GAtlunFp5d1vy2iMWbXwHzTi
Lwi+1WPNUO4b7dhjjuljgiYFQv8r3RyJkVndre9vC5eMefnOgueOISVtVRxS
F4wIZgL+YfbGU.3YDPF+D.uESy.mnLFHIGK1A9u3mZm1Jkt3iwExKraVBEEY
nGukF9wOz9QMZpFo344z3YefSyLOGM4NwTx+lyXJZPtSQGG2GSxIo.gjbP.j
bPN4PNG7K8yGsf9HuEAJ3BMf1029QGXG4L0Pb4hLhBRofji4rmAw43DhPs4K
wRJWs2yOxRAwD.9DQv2SlChOJAavTlgC1RxH4XoZZPBOWiQPlRyUbP8TJWJF
MijvOZ2zPuesm.uUZNC5Ep4QOWiQlVUpMFDEM4Ln+BvhEKL7BUB1SEwjc3GI
feUPHZCFk8SVJ+z+BD+LPPxRUnQScjGIJyMik9TwTnHC23Cs9g7P8xTK61NC
N0bX3hJ+NXlfWpfgy2RjJCMAOCmkPTyyddD8+XUctg+GTXm7RTvTyKdKRIpq
JmnThj6.6OxjzCLhZJkplR+ZuwJ7DO+6fS6HY.Fm+cs9EVZbZUZdld1pTopN
BLnejw8Ez0bNmejauLXvjaChVnm4XFMQ6LxvUaxI+8wrjmA+NXixtxYzLm7J
PKzuWP20wVvo+XK3BZFURwL5+n15OyFDEcLB7fGJxFWig.fg8Z9.8GsM+LxI
0S7JzdHmdlCF7ovdHavGQFPXcM1HRs5GCOZPX5h7bku9zv.3aKvS+6RjmSM5
8V4+lP+8It6NTe4BAEuHmrmq7bUcTW6jjWejj4mdSNQQLm0QfEQe2gNOxczT
5Um7HvaIWgbSfipXSZGqvNwZeXD4tplYMDB6CivUshQzDs4dCevixlagI.zy
qWfGL4at+nBsuToT+xApRteI8XtI4hWzYW9xFJSavkvIa9Abwhk+7kS6vRUB
H+bL0KfQHM8.8st6C5U2G5N05EGTIOpRE.fSSUriXTQZnM8nnk1Hzb6CoK+T
pGLMZ.1v7KBY0CspOdwezT.l720TwF8q8PunO9y7pV4a4YrWdZHFCHjcuOn2
iCBm7HUUIjIWe0KHYLztCBrN7irAxFE1GP63Xu5OcRdA7JvmRahxzuxBgxfs
lXNyAe3PsgmU6Vzjx23lGTz7pgnY1gfUCkSdjVd+muPbtBiRE.OlaX.mmBKs
J0OFdJIO6HsZGxr8THRlMhyzr9l06WkSWi0VUOK1UlOVpUYJYM0F8VFO46jz
ZlEp8FkyaZlxItPk9kwGVioSIavpL0WugmIEpbvLBIZQqyuoPBacRMFLh+ej
qxlqB.ayoo7LsPzXmPOb4xoCHvpxWGLlqHCenkaVoWnnkNlTn.4QQLNWuQU3
i.UNojyYMmp59XjMxhoOPyxtfEk7CcOYNc6tdt2XtZx888rMyHVeLyN6ZkNg
bs.+XS1VhYrBq0lO9mvYTk2ShjZ2BPtUSZ8StSjjyYrF30NyisLSpRGOgbhl
J203cWqmQc4zCkJQNU6xozsDgr4XR7VQyQDxmsjdsgNFWXCuVR1efoPQyKPY
cPERwN9IQwEVpnUm.NWSk51z0c80X7diGnoevDFAmCTLe8Ya0K3M7D1saey6
XGtpirg6xgXGG4Oq7DfB2LuQJowoBsGOnfnesdxohWPA17j8MLxJuawKK6jW
f2WdANYLRnIsIzJi2xvfawHgezLx+v.BlxUReTBpWJY9.nEOnQOQEjbPq4Pb
IsD7Ix.ZxbpD.qkg8R+awIn6hph4oNUPNvVhMSvjdtk+tK.C6Dvt0ln7kVW+
DIyCJKk7zczPRBXf32gMTi7y5j.Kp71pyLXepLdvOKNbmP6He+WmYTzmENwc
x7rDAeUGBgV9IRM4d3xcnwqf9vOdVQGfXvW54vYuA4XYt1yt71Dj+RMAsx3g
Nb4M4mfOZ9wzdCj7toG+9nGSg9N+BwGDCsxbFVgK3P3MoH+Nonf6CEkqfM4p
1nYRByyd7DLvu1qAoOxAdehyaRioovjYnA034ONQ0Ll7iEzcSPt2H3dCAD3h
FHCziSi2abcme0T5depiW3fAB54amZD7i4Ika+EYyCZhlThPRypdQce8LvzW
3f1YdsBwxAJDnITFBGnLrbBkgfgxCQSrP.+f2LzNRFFSLkpk5LLFjTL4Bwf1
O7mPonTi6i0OAZvNJBmRoH7yfYJZn1oqlZg.MTkSuoRJFp2hq2334o1p249w
JYsnYWIZvoQz9LXPCG5IdkthmFoXfBArapnXvxxp5nqcV5ZacBWikxbZrJQE
wk0I9UUOqsLdLlcQQnZqbWObV3dk0h+aT4hDBiEqqiqSUqQzQwUaOaTUNYmr
A7VVEPmZk+ysqJ1ynhF4qdtB9Ib100bu0J56gJ9v9hxzctdsF73p5G2Hasv5
v85BQ2d4+UhVUYJQ9tmGMkrwJYpbnTYRGNW+gI6gy+x1U3sO7Wfk+.9Kqt0X
1LI1BrB9SEIxH+u5+WULlsWQQlxK6sopl9lqaRagDno6tW1eCDFcyFjxbaMS
qyB4KckU.79SiqK2WMN9yYOM0zm8hxxWXZ5OOKhp+sNz+FpnEM.QqV3Zu40Y
4cZcBqG2UWGW0PVZFjwjtv5tzs1E0LFh27JGL.pc0HPs9CXcVNBqCZHKjtot
e+qDZHFlAiwJ4NDL4OBqDLZfpCva3qQ+OSl5iHakyMearsYFjrFzt056ylAN
DiFDZL1ObuSlMgCAQWsN1y1tnyG0KwEc73Ec630c5X2c43kc3nILba2dcw4o
Uww9ev646wq2Q2pP91cRcz543rx3GJ6rvlLBNIgjIUg2YkyuZiUyzTLkgtUB
84ELat5FtrsybL+qIVpbWxPczHlO7yG9+VJO61A
-----------end_max5_patcher-----------
</code></pre>

**Comment by vincentgoudard** [comment]
> there is an infinite loop in your patcher around ossia.parameter
> this put max in an infinite loop and might lead to crash.

I thought there was an anti loopback (like sw) in ossia.parameters, like ossia.remote. 
Any reason why it is not so ?


I still have an issue with  the patch above (even yours I mean) with release v1.1.0-a2  (db4e3ee) : the first letter of addresses output by ossia.parameters are dropped (e.g. output is "address requency" instead of "address frequency").
(should I open a different issue for this one ?)

**Comment by avilleret** [comment]
this have been fixed since a2, you should wait for a3 or build it yourself :-)
