### ISSUE TITLE
websocketpp::exception not catch ?

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#62]
when trying to expose device with websocket on address already in use with : 

            try{
                proto.exposeTo(std::make_unique<ossia::oscquery::oscquery_server_protocol>(settings.oscport, settings.wsport));
            } catch (const std::exception&  e) {
                pd_error(x,"%s",e.what());
                return;
            }

I got : 

    [2017-03-29Error 01:53:23] [info] asio listen error: asio.system:98 (Address already in use)
    terminate called after throwing an instance of 'websocketpp::exception'
      what():  Underlying Transport 

see https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-pd/src/device.cpp#L160-L165

**Comment by avilleret** [comment]
to reproduce : send `[expose oscquery(` twice to `[ossia.device]`

**Comment by jcelerier** [comment]
ah indeed. I chose to let the exception go through because maybe the user should be told that he can't connect (for instance in i-score it would be possible to ask the user to choose another port) and be offered an alternative. But in Pd it makes less sense.

**Comment by avilleret** [comment]
I would like to kindly inform user that the port is busy instead of crashing but how can I catch this exception ?

**Comment by jcelerier** [comment]
hmmm it should work given the code .. maybe try to add a `catch(...) { ... }` clause after the first catcj ?

**Comment by avilleret** [comment]
nope, the following doesn't catch the exception : 


            try{
                std::cout << "expose to oscquery" << std::endl;
                proto.exposeTo(std::make_unique<ossia::oscquery::oscquery_server_protocol>(settings.oscport, settings.wsport));
            } catch (const websocketpp::exception& e) {
                pd_error(x,"%s",e.what());
                return;
            } catch (const std::exception& e) {
                pd_error(x,"%s",e.what());
                return;
            } catch (...){ }

**Comment by jcelerier** [comment]
ok I got it

**Comment by jcelerier** [comment]
fixed in master

**Comment by avilleret** [comment]
thanks
