### ISSUE TITLE
[ossia-max] bogus parameters on pressing 'register'

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#628]
this issue might be related to [https://github.com/ossia/libossia/issues/559].

1. download ﻿https://www.dropbox.com/s/x1lpmss6y7zsrxl/OutputWindow.zip?dl=0
2. download https://github.com/tecartlab/SPARCK/archive/development.zip and put the 'sparck' folder into max packages
3. open OutputWinSimple.maxpat

you should observe the following:

it first creates the namespace based on the default address inside the abstraction:
```
ossia: node created sparck:/node
ossia: node created sparck:/node/Window
ossia: node created sparck:/node/Window/slice
...
ossia: node created sparck:/node/Window/internal/nodeid
ossia: parameter created sparck:/node/Window/internal/nodeid
```

then it removes the namespace again
```
ossia: parameter removed sparck:/node/Window/slice/rows
ossia: node removed sparck:/node/Window/slice/rows
...
ossia: node removed sparck:/node/Window
ossia: node removed sparck:/node
```

then the address changes due to the scriptname of the abstraction
```
ossia: node created sparck:/node
ossia: node created sparck:/node/Output
ossia: node created sparck:/node/Output/slice
...
ossia: node created sparck:/node/Output/internal/nodeid
ossia: parameter created sparck:/node/Output/internal/nodeid
```

so far everything as expected.

now when you press 'register':

it creates a bogus 'model':

```
ossia: node created sparck:/node/Output.1
```

then it removes the namespace
```
ossia: parameter removed sparck:/node/Output/slice/rows
ossia: node removed sparck:/node/Output/slice/rows
...
ossia: node removed sparck:/node/Output/enable
ossia: node removed sparck:/node/Output
```

and creates the namespace again with the new bogus address:
```
ossia: node created sparck:/node/Output.1/slice
ossia: node created sparck:/node/Output.1/slice/rows
....
ossia: node created sparck:/node/Output.1/internal/nodeid
ossia: parameter created sparck:/node/Output.1/internal/nodeid
```

**Comment by avilleret** [comment]
could you test 3fe90969 @maybites ?

**Comment by maybites** [comment]
works now perfectly. thanks a bunch!
