### ISSUE TITLE
[ossia.max] ossia.attribute does not output anything when address is a multiple

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#633]
In ossia.attribute.maxhelp, clicking the "get default" message on `ossia.attribute multiples.{1..3}` does not yield any result.

**Comment by avilleret** [comment]
with which version did you test ? 
with 07a8b2d I got : `default 12`

**Comment by vincentgoudard** [comment]
I originally tested with previous release (v1.1.0-a2).
But I just tested with release v1.1.0-a4 and  it seems to work fine.

**Comment by avilleret** [comment]
Ok so I'm closing this issue
