### ISSUE TITLE
[ossia-max] ossia.parameters inside models break when ossia.device is present in parent patcher

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#635]
When an ossia.device is present in the parent patcher, ossia.remotes inside of a model _sometimes_ do not output values.

Please see the attached demo patches:

[modelRemote.zip](https://github.com/ossia/libossia/files/5592291/modelRemote.zip)

The two patches to look at are _modelRemote_noDevice and _modelRemote_withDevice.

In _modelRemote_noDevice, when the value of the float box connected to the ossia.remote inside of the view is changed, this value is passed out of:
  - the remote inside the view
  - the parameter inside the model
  - **the remote inside the model**

In _modelRemote_withDevice, when the value is changed, it is only passed out of:
  - the remote inside the view
  - the parameter inside the model

This can be monitored in the console via the attached print objects.

In other words, when ossia.device is present, it seems that ossia.remotes inside of a model stop passing values.

Adding to the weirdness, this bug only occurs erratically. I'm attaching two videos showing _modelRemote_withDevice . In the first one, the remote in the model doesn't pass out values:

![model_remote_not_working](https://user-images.githubusercontent.com/5342408/100144264-87824180-2e64-11eb-8cc8-e619eb44a51a.gif)

In the second, it does:

![model_remote_works](https://user-images.githubusercontent.com/5342408/100145474-60c50a80-2e66-11eb-8fa1-fce996516f07.gif)

I can't discern the pattern as to when it happens or doesn't. Sometimes it seems that the remote in the model works if I open and close the patch a few times, sometimes it works immediately when the patch is the first thing I open after quitting and reopening Max.

**Comment by evanmtp** [comment]
(Tested with 7c49e83)

**Comment by evanmtp** [comment]
Tested again with v1.1.0-a3, and it seems to be fixed in that release. If someone else could check this, I would appreciate it, as this pattern (remotes inside models) is something I use all over the place.

**Comment by avilleret** [comment]
I can't reproduce it with a quick test but it sounds like #610 to me

**Comment by evanmtp** [comment]
Seems to be working fine in a3, I'll keep an eye on it going forward but close this from now. Thanks!
