### ISSUE TITLE
[ossia-max] crash when trying to query [ossia.remote] object that is linked to a 'inbetween-node'

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#640]
Hi

consider this patch:

<pre><code>
----------begin_max5_patcher----------
1614.3oc6ZkzjahCE9r6eETbIW73Awlg4VtNmmacMkKAHaqDPhBDc2YRk+6i
1.Kg2vcG63YJeHN1Osv68o2l9n+9SybynugZcc9CmmclM66OMalTjPvL8um4
VAeKuD1JmlaNspBQXtyUiwPuwjxA8Rpgr7sXxlUMnblZmC8SW3M2wOQ7YPj7
6gK7b9a8Rx5xxJQh4BzRHcUXRIh0ZJDWHeRzru7afP2cyj1w5mpm0N1hKj6Z
fP3Od5IwGymncVgZagaP6YmvhhF9PNscYUzBT4oL633clMvao7G9F1sRwYeq
FoVfq6vPV.f+9.Pvgsev6vRyjpNpoeGeAid8EbKNCWhYey7.ftdcKRabdBqw
yvXJo4eEwAG3l17FZYo4wQdIN+qrsMztMaMkiHP9wz18WfZfW1efrMBT2DTx
nMEbk2XNG+nHVdFDFqbGSMU+C5wgpxPEGwEL4zdf8fpB20.+L20XtYgZZwTh
w9NyEVWaHdlwRDmVegJ2nj4ChvDkH+AQMHwglZ8dCRgMbnfwwgtFIp49Vben
iXa3XYCoCO35H8azpjzCg.4AB0vb0hENR8CuCbiSk3YvRkGdh7+BBS2gthyM
k+go14RqQDLolGOwyn.YiTd2BzZXWIa0ZJg0h+GUBBd7ygFesVEO3fBiPp+e
tACKGrfMM3BJQnDVGEBw8Otmc.xzUhO2YLxYPf0GXwbOCNtbjAa4FYWaFrQF
dUZ5FyyvPok1CMrtRzZld3ZLgLBEYz5iOXCdy1Sr1LJevpSs2xQZW0QTith6
TvV0BewFsYvxRB5Ut0OZ6eCRvUPFhgUGA9dCCtWvOvdjWNvHEbm7bzq3BlJO
hoy.e535dmH2gS4B7FTKyVFimjxVRK6aJP2PTWelwULTUcI2Jrm.O7.2xZ2R
esUOwdGMS.XW4UyfZyjxVxOYYH6RQaPLGDKewhElCefreAp7dfPYknnnwEhN
SwniVPZupxKcsWw3JSy5qNoyzbk.ELoOJZZ3hurXVx0CWhuM3hcuY13Rv4vh
.IHj5e3dzNbeZGsx4dHPzwQ.u8dBV8scCvF+yfM9.v0DaB+UiMmKdpifYSKT
RAQp7LWiHoje8IX5u..qp9btMJbPgIKudYW7uMfht99gvDJuRHbQCphxPSCT
.AxFxWtbhnxb8+rlVNsT0Er35Hgodfz34xuk3EjJ9VDXYb3R9Saz9OovxfiC
q+LC9jJxY.MUSnIAx7Od8e9tcj7NrEeppTVntJSpYuPxchTfd6msS25RJWSN
asKUJY40Ph7ltKUFjrwFmVSa3sqJlRr0yrg2YGi2Inp0zwf3T7mNg6j+sOJU
j952gqjF1zPWuX0Eg.2sQrQ2l.1S0IwesE25HHPwg++R1CJPE79QcfN8WlXg
yjB1C8U3rhBowQ6hGnEVF3GEJAvfvHuzD42Vpj8dfxSzHu2MBJ+rBGy3oU33
iCi57odN29jiI0amFG0T8n7ZW9dpCjNs1yrXofWi6VmDzWUX3NOKX3cXVPBk
Itj+TxE1Cx5jgS9Ji29jg92ljgmEnkAwiHK+zQr.e8sxAumNls.UPeVwkowd
KkYESRCAfj2YKgWVi16HLrDSNFMPRXPL9gA6VZWSdukpuAjislWfZYXx.8oO
uq8UwDmzY8kpDgSTI72adU3hZJlvZ6imRWDIRLGJOqUN.i9kmpRndldR+gqh
U4OQqJ7JhrQSTGtlmtASTGhN2oKuGlcGtfDiyV8OTGs5ocEOYimZPyUDUA92
CQtf3OtVnEpj73kMteYrPi20ntA9jvi8tF8lv6ZD73cMpw1jHUJiX4kRiC8T
7M583cM93cM93cM9wdWiS5ZlZezvnGbscI.luhEs6U.K9N4Z4C1xEvOo1iLU
Bs.8eaOS6J4W7M.StM3zYoXTda5GbL9w4XTAjhboEF7K9fYQ6W+c3+Ax4GcG
kyWiX24I8CuOS5eIzwp8LS0rxFbMy86em.WpTVWDkpopRjAde3+FDtiYFM5x
Hk7+sTHNUFhiuCnPL4hHYRtg1tLJNmFqdZlmNsZcdUx5wNh0DwiXDaIiXJYe
VRNNCIiYGQxLh5hhiL0A9E9SXEsBtZK+R2khKdyuuLsgW8P+GfSOoD1HBLOm
2KjQWc.EyZQyUbrAVLX5y0HaCeAiuwpaEemw8cp0iPGgDmm9wS+ax0i4J
-----------end_max5_patcher-----------
</code></pre>

1. press 'address submodel'
2. press on 2 -> this registers the [ossia.remote] to the 'submodel/tmp' node (which has no parameter representation.)
3. press on 3 -> crash

this is a regression, it used not to crash until recently.

**Comment by avilleret** [comment]
this should be fix now in master
