### ISSUE TITLE
[ossia.view] with global address doesn't work at all

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#645]
Hi

consider the following patch:

<pre><code>
----------begin_max5_patcher----------
1925.3oc6aszjahCD9rmeETT0daxLH.wibJ608v9GHUJWXrrsR.DEHOO1T4+
9pG.VBCdXrgXOo3vXaTCRc+oVc25CM+7tElqHufJMM9rwWMVr3m2sXgnIdCK
ptdgYZzKwIQkhayjhdgtZOkRxLuWJFuVHfr56eJnts7nhnTDEUrDkEsJAwuC
qJYq1FSRHExAE7f08FVMevtz3aU2W19TbVBhJFWPSGSi2gy1tr.ESq5hPQm.
.hurcEe1piH6o08jSUqbCgjonJV8qJEj8YqQB6zkKT1prSoulijcfo48x+vY
LU6aJii.f7L4M7q6ti+w8iAb6eMfaeeH+QcBg21vMbzga.7Zf2AVOXCY3Mz5
1FucGe718Zf2PKmOF.ty3C3NWC.2yWf227wusGe7FbUbvgAeHxWBNG7NC8LC
YMa2WTijNveOy2IzYC7Elpm7qPAzY2KzA50vM91YXaqDZDpnVqeBid9IbIdE
NASeUa.2roDQ0mlZzwDR7OPqWWDssLtfjjn5qEmfi+AcGa9a6N01kdk6N9Aj
Bd5XAq1lRVKrW65VHEqQEp2ixTA7jSEnzURuoSUWhrLPaaOQ4IdNhqfg8N6X
o1WREaQCxuvbClYWnhRLao6gQdgYTdtRyKTdD9z02kqNBtuoIblrI6llJP7Y
M4ya0zZTAyhnLyYeg.1LewqN+GuaXfYQ1drPUjMxbbpTIgKRFK.RYdTr7g4d
R0hUJU1BHfE+PYIbhKb.AGvH9DmzAQU6LI4nLbVdApDkQinsTdy0nMQ6SnK2
Pxnk3+SnB.6G5T9lJUrSgbiPn++cANJowB1VfWSx3Jg1TAu45giYbhBR4edv
XD2QVTdGOLyqigK8HrjYj6KWEUHVekn5GyhpPHI5hZdtDzFZk3bbVVKTjRx6
WXAd6tS7rqHLgompuERJWtOSJcIyoftrL5IczlFkjTEjTu6eIJCmFQQTrbJv
1pQ3Qq9A5RdpCIqYN4wnmwqox.IpNCraGmW6DY1LKuFuEUR0aixhRo2RI8UI
nqzz95PiKonz7DlUneCrkG3RZ4NxykU2XsilJ.bXivpKpUiJq0dqnyrUekQa
QMKYUS+DwB2xDarJpDG+ocnj7O+XFaE8irYh+kGlT4gTqOvRUfVjQaEAcDLz
QD0OPlnOzucdp9yUcx7UKpyYUE94LQJsbz5.EKBCao3ZiJ.qGbInWXAbZXAH
J1wS.NggeXPkx7BVIRazbe9q9.GuKCbbDoOA1N2VnivJ5aYRuVr0PrXoYaU+
4EXuJhiIoonL8fYB0lUW7KJIwGEvYSBgon8fN9lZfPu6yPVzCofkCf2p2E4E
YaKh4TsE5S6EYeRTks8fUQYaG40Z6YETVzCfAeO.16GZ.dA2zPS+ggHrrnQO
TfRITjQTFgxS31.P8fltWV3HaKI4tACIdjyaAWh+tJvU5quIR4bYHEvU9kb2
8e.QJ91Yabq362IoGfx1TKPqBgDgAg1PO91ccA9td1hM9x1eiKTiehyEgqA5
IpdpCaaIAm0WwnBsiKuaHujruHtdXpqgzPWQYEfSwYM6h6qMnJ+9FzL96UIf
CTGbN59RwqyIrhepPCVYIPdPAQvSu1+F3HiR3zbwDYO9CzdbGn8.EEc4292f
p2whSyESj83NP6weB8QbFnN.mPc.LPcvaB0AuApCASnND79hYnFpqliOvUUw
DQ8.u8Ju.WwZNfe8EcaLVmLZsfQhdBW2Pn0+DkRRiVtCukYua2QQqWRJXUuo
r2+Zlv5FKhhiYan33WE.Tk+8C548JXbA6AOl1DNlvFMrpAxMq6NXniC46cuo
9tJRbvDwGJeGc.Out2J+LQ7mKQ7NWLQ7v52Khm7KYNLn8LQ7yDwOSD+LQ7SM
Q7SHUgxHaybENtbEJCENyUXG9a1NybENbzx2alqvAgTxBlmoJbxnJr5HV8wh
ova.hBuEHA5VfLrwlfQW3ABFU9MvSkfQuoifwQl.X.DdfzWkeKOvCUT6Dzi0
LSbyab1UTN2JcDhsqxo67robpCPo7rmF7al2FsZe0RS3MjCh6QE7N7ibafpY
eb4bcWJ2aVF23POmVsGpGwDsY+G6npDMH7cygmmLPTEn3XAeCTw4sNFwmGpz
mueGmOqNOaVC12ulyxqiu+exbVBruXRKqlbpHszUdpClIsblzxYRKmIsblzx
YRKaCpAdyjV9mIokMHxw7VZ7Et5YvbGinFeoJ0iAqNVaGqvvP0Nku43Xxd4J
D6oguSW4Jae4IXFdYH8UCkU2XQE.y1u+A301YJIA0wZT7S+Midhsj8QfAzAQ
w7LCn+ocT7l4X68w9hrdWE1W5hgk51zVECrgtgbqzOzyxOf+qfPW.H379mCW
toNeIn4.GGNJDOs9BUIh01wrB2NxgzVaUQeqJUNUlGM2L3QxaHij6HLRCwjz
VH1lJbfk8C9P46Om8EzN3g5qZdD8Sv3jpq.sCCZqCB5YOx5Ge8g7VPFsQ9Vd
f85dfsldrdRF4grnCdp0Bbd6fM+qtFXY0bUGAhZwAGWoZw8VKd2Nlys94aqM
WahjMsxBJAmgl8qUluJLbvY7px10SlN8rb0HTOTBd2ut6+cDLJxM
-----------end_max5_patcher-----------
</code></pre>

when pasting the patch into an empty window, all works well

1. change value and all the attached model-parameter and view-remotes adjust
2. change address - now the value of the model-parameter has switched to its default (in my opinion a bug) and the value of (3) has not been updated - but it is linked -> when one changes the (3) one sees the view-remote is linked to the model-parameter (4).

however, the view (5) that has been set with the global address is not working anymore.

even switching back to the default address (6) is not fixing it.

so there are three issues:

1. switching address  sets model-parameter back to default - in my opinion it should not - separate bug report : (https://github.com/ossia/libossia/issues/644)
2. if it should - it should reflect on the linked view-remote
3. global address to view-remote doesn't seem to work anymore - it used to until a view commits ago.

cheers martin

**Comment by avilleret** [comment]
thanks for the detailed report

this issue could be sum-up as : view with global address doesn't register even if the node already exist or not

**Comment by maybites** [comment]
I can confirm on OSX: it works again as expected.
