### ISSUE TITLE
[ossia-max] [ossia.remote] helppatcher examples don't work anymore

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#646]
Hi

it looks as if the examples inside the last two tabs (Dataspace & units, pattern matching) are not working anymore.

in case of units, the remotes all output the same value.

in case of pattern matching, none of the objects interact with each other..

**Comment by evanmtp** [comment]
I can reproduce this here. Also, in the "basic" tab, when I send the "address submodel/another_param" message to the ossia.remote on the left, it seems as if the remote doesn't bind to the parameter - changing the value in the number box inside the submodel does not cause the ossia.remote to output values.

**Comment by evanmtp** [comment]
Also note that ossia.remote does not output anything from any of its outlets when it receives input at its left inlet. The corresponding parameter does still pass data out its left outlet. Tested with cd386bb6 .

**Comment by avilleret** [comment]
this covers at least 2 bugs:

1. address message to remote object was broken (it has been fixed since)
2. remote unit is no more taken into account for value conversion

**Comment by avilleret** [comment]
could you test @maybites ?
