### ISSUE TITLE
[ossia-max] address message to ossia.remote is broken

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#647]
The address message to ossia.remote is not working as of d87ab758 . Please see the test patches here:

[remoteTest.zip](https://github.com/ossia/libossia/files/5623145/remoteTest.zip)

Seems like this is related to the issues that @maybites identifies in https://github.com/ossia/libossia/issues/646 .

**Comment by avilleret** [comment]
it seems to be fixed, but in your test patcher yo have some message `[address test1/myval(` connected to ossia.remote beside an `[ossia.view test1], in that case, it will search for node `/test1/test1/myVal` which doesn't exist;
it's quite obvious, but worth mentioning it.

**Comment by evanmtp** [comment]
Ah yeah, I just had those there in order to see if sending either relative or absolute addresses might work, but you're correct, those messages don't make sense (and are not a thing that anyone would reasonably do). I'll test it ASAP!
