### ISSUE TITLE
Threading issue: patcher stops working at some point

### ISSUE THREAD

**Issue by avilleret** [ossia/libossia#648]
With overdrive on, the following patcher stops working at some point. 
This might be a thread issue between UI and scheduler thread.

<pre><code>----------begin_max5_patcher----------
636.3ocyW1srZBCDG+Z3oHSt15PBHxouJc5blHF0bJj0IIn14Lm28FV.01iT
wOaugLYy59O+1Ma.eOLfNC1IsTxWIeiDD7dXP.Zp1PP67.ZoXWdgvhtQygxR
o1QG0rlStyg1ENhEJkj0fR6HaWI0DXizL2n1HItU9EDt7URCw5f0VxVv7Ckd
IoKNEJsLGpzXv3sFUywPCyd6Kbdmm5pRktP5vsCq0HFbe7d0HycM3vyhGGMh
vS40Croo0CwdajueHRPkqKTQ0F+HLr9wnaLYvGSJAjaeZwKiOJjEBqOunbq7
KUYkCF7nKG7oHwSZGhdhfyF6quBiiTJcFf9YbXYWJNrDrxklcDM7n6JMKJ.e
P51XMAy8y0xlM.kNhPmIzKo6k7XfRo626FgGao4UoVLq.+0Qsqs.LkBDnzKs
ZFO4npYK97dwmeE36fkKKj8hup9r4oHOYHjO3xLa5gxLOo6YOXxtBL0xs9s8
mNxZD54PIgEEc4YfSeoD+rTxlf2MMM9LUy6HlXCIg0Ki8e.mcsPxX0CIu7.f
7V5XydrMroH0woSdX8q2B7oOE3iRdXv2ywavZUhw6ghr.f+ZB5jImD50ga6U
zrI+mUrieFEaNK8eSw1HKAm77U59p1L508JpVfeY5Y.N9HfQWvu06O9XaTlZ
6+dVvBUl7NJZ2rjCBMWZcJsvo.8Q9D23yIyyCUm3AnC6NnS8qNeNBk9jDZH5
jbGzIY.5jcORbCQH1coDMjC2cGX9TSkX8Z++yz15MJh+Rj2.S8zrQ3TktYJ1
bSMxMpN+abPX785NeidkA2XzcoMuKfVBykFckp8CU734kDufR6uQ0tVzPBdO
V3Gg+B.njJ4v
-----------end_max5_patcher-----------</code></pre>

**Comment by jcelerier** [comment]
@avilleret I think that this is the same case that #777 and can be closed :)

**Comment by jcelerier** [comment]
letting it run on a mac to check

**Comment by jcelerier** [comment]
Looks like this here: 

https://user-images.githubusercontent.com/2772730/162058261-014ec20a-dc29-4b57-823b-8ca6591292d2.mp4

**Comment by avilleret** [comment]
not sure about the cause but seems fixed

**Comment by jcelerier** [comment]
Yeah still runs after two hours and does not use one additional megabyte of ram
