### ISSUE TITLE
[ossia-max] ossia.router - routing with wildcards is broken

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#652]
When sending addresses with instance numbers (e.g. /track.1/play 1) to ossia.router, there is no output. Tested with b206e461.

<pre><code>
----------begin_max5_patcher----------
874.3ocuW0zbaBCD8L9WACG635HAX.2a8ZmdpW6zwi.KSTBHwHDoNMS+uWoU
BBDamfG6oW.wZsZ229wakeYgWPt3.sMv+K9+z2y6kEddfHi.O22dA0jCEUjV
XaAEh5ZJWErz9aJ5AEHmK7Ecpltgeg2UqETQUfdHmz7t77JpQBdzITHpDRqW
fVEsbzC7Jj+ub6jsCrjH+gOGg5MydAW0x9i8HCWM0NlytlHKYb3mQizgSpAc
B9NQI7+AsrqhH6OzFhp3dFubqjVnr9U5Z8Y6iWifWgolWQqG4cZ7x38vEaj8
2EKLOVNyHadmRI3mN7gONDDl9p2J0fQQkaobhK51CU6YndtgZgQPNgWFL3zm
.nXKPifWgw8Ouc3rl11RJoGUAcmRRJdbU3cMUjm8QyNPDEEbNvNCfFCOyrnM
7b3L71iSrEm34iy3qAm3+W37iwQxUgiD3UB51CDN82Z+6n7knskQVI0NKU56
Rde5znM7DnM87nc4XDeFhrITi3v0waP3MInzr3HrgiLs+inTyOZDksIFiSSh
SQqyxBimRhNg66qRFoJ3iB4arbdfS8Ngb7HKrmTXogFkF.sBpX72NvALrQ9z
bSqnSVzGq5az8e036nsJFmnXB93MkZ2zIy+y1RwWfkbaplsqQv3JG3zblq0S
H1XGW.SKFsNC63UWaWes9a5L72vY3u3vnWcL3ig8Kj6nxyy4eScUCEgOdVtp
lN37t5wkejllmnxVm4.uTSB7fsEKaI7Iia+DJnCjzmX862tAhT2mnzMIcRaa
zgDK0bPsPaXdGyElzwGsIaUOW81R9gNvuQpE0js2yJ0Aux6UzcaER8HZGcpN
9rmzUolFTIEE5qfMhY.plPl.gsU80BpktjiTq.3HfUcGds9jY8wowIyA26AH
sRkHjaN00bTL9iuGpxKmv0kkDlFCHJCHxrqrzdiIzN59iIF9wLWnPeIRfebp
NszJc5SmTuTEKpn5r+DJYf30reKO73Ui0LubOqpZPUuAbqQfajfiqeoS7E5a
NEvCWi1LA.FQDYBZwlUmTivdMBgQKfFnMYnX6JsH7aTSWeZy9gon9AU5JCon
QH66j0ptYX+cJQojriY9iC8sk8EmWLPOt7eVZMPPMUQapa34XMzEI0Whgt7N
NKmDbCDSeRaiarIbQkE+cw+.9V7E+C
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
I'm surprised you said it is "broken" since I can't remember when wildcards worked with `ossia.router` 🤔 
anyway it's coming...

**Comment by avilleret** [comment]
but pattern matching in router is not that easy...

**Comment by avilleret** [comment]
fixed with 13731ba9
