### ISSUE TITLE
[ossia-max] ossia.parameter does not output @default values

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#654]
Please see the attached patches:

[_defaultTest.zip](https://github.com/ossia/libossia/files/5639133/_defaultTest.zip)

Tested with b206e461.

**Comment by avilleret** [comment]
to avoid this kind of annoying regression we definitely need some automated tests :hot_face:

**Comment by avilleret** [comment]
overdrive seems to be (again) the culprit
