### ISSUE TITLE
[ossia-max] FR : output index in the multiples

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#657]
Hi,

when using braces notation to create multiple addresses, OSSIA generates a series of adresses which can be used, for instance, to adress the various voices of a `poly~`.

Could `ossia.parameter` and `ossia.remote` also output the index of the current adresses in the list of adresses ?

That is :  if I create an `ossia.parameter myParam-{a..z}`, Ossia will create a series of adresses like that: 
- `myParam-a`
- `myParam-b`
- `myParam-c`
(...)
- `myParam-z`

Now when this parameter receives a value on its address `myParam-c`, I would like to get something like : 

address : `myParam-c`
index : 3 (or 2 if you are zero based, although my preference in this situation goes to 1-based numbering).

Vincent

**Comment by vincentgoudard** [comment]
The goal here is to address targets on `poly~` and/or `mc.*` objects, without having to parse the name with some regexp (assuming you use number in your param name like `myParam.3`)

**Comment by avilleret** [comment]
fixed with 1084ae2f
