### ISSUE TITLE
mute on nodes

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#66]
- [x] Add the attribute
- [x] Implement muting when the attribute is set

Note: should the muting be : 

* On outgoing messages ? 
* On local callbacks when pushing ? 
* On incoming messages ? (ie even if a value is received, it is not set)
* On local callbacks after an incoming message ? 
* Any combination of those ?

**Comment by jcelerier** [comment]
also should the "mute" attribute propagate over network ? 

e.g.

* server sets a node on mute, does it also mute the clients ?
* clients sets a node on mute, does it also mute the server ?

**Comment by bltzr** [comment]
I'm not sure I get it... only the server is muted, right ?

for me, muting means the parameter doesn't output anything, that's all (but its value can be changed internally....) Mileages may vary, I guess..

**Comment by jcelerier** [comment]
> for me, muting means the parameter doesn't output anything, that's all (but its value can be changed internally....) Mileages may vary, I guess..

well, if on a DAW you mute a track, then there's no sound going out. But here if we only mute the server it means that in the client for instance, if you set a parameter then you will get messages for the value that has just been set.

**Comment by jcelerier** [comment]
current consensus is : 

* `enable` attribute: entirely enables / disables an ossia.parameter. Shared across network.
* `mute`: locally enabling / disabling sending / receiving.

**Comment by bltzr** [comment]
created https://github.com/OSSIA/libossia/issues/140 for enable

**Comment by jcelerier** [comment]
done
