### ISSUE TITLE
[ossia-max] Default values do not fire from ossia.parameters when opening Max by opening a .maxpat file

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#660]
If you open Max by double-clicking a .maxpat containing a model and a view, the ossia.parameters don't output their defaults, but the ossia.remotes do.

If Max is already open and you open the patch, both the parameters and the remotes output their defaults.

Can be tested with 
[defaultTest.zip](https://github.com/ossia/libossia/files/5669265/defaultTest.zip)

Tested with https://github.com/ossia/libossia/commit/85b6b6398aa2668b3df145fcab7867e8960fc84b .

**Comment by avilleret** [comment]
could you test with b27ebc0e ?
it seems to works to my eyes
also please note, I just pushed a test patcher for this (in the commit above)

**Comment by evanmtp** [comment]
Yes, looks good over here:

<img width="877" alt="Screen Shot 2020-12-11 at 5 53 24 PM" src="https://user-images.githubusercontent.com/5342408/101962301-d278b480-3bd9-11eb-882c-73f5e0a730b6.png">
