### ISSUE TITLE
[ossia-max] for windows compile woes with commit (9e98396)

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#664]
when compiling libossia for max on windows

on commit (https://github.com/ossia/libossia/commit/9e983965a98f4e8c872fe5f92828a3b2e6230b32)

the following compile errors occur:

https://pastebin.pl/view/55922bc5

**Comment by maybites** [comment]
I just tested the process on a machine I previously was able to compile libossia (a few months ago). The same errors occure.

**Comment by maybites** [comment]
the errors when executing 'cmake --build . --config Release --target INSTALL'

  CMake Error at src/ossia-max/cmake_install.cmake:179 (file):
    file INSTALL cannot find
    "C:/Users/maybites/Arbeiten/02_code/library/ossia/build-max/src/ossia-max/Release/ossia.explorer.mxe64":
    No such file or directory.
  Call Stack (most recent call first):
    src/cmake_install.cmake:37 (include)
    cmake_install.cmake:37 (include)


  -- Up-to-date: C:/Users/maybites/Arbeiten/02_code/library/ossia/build-max/ossia-install/ossia-max-package/ossia/exter
  nals/ossia.client.mxe64
  -- Up-to-date: C:/Users/maybites/Arbeiten/02_code/library/ossia/build-max/ossia-install/ossia-max-package/ossia/exter
  nals/ossia.logger.mxe64
  -- Up-to-date: C:/Users/maybites/Arbeiten/02_code/library/ossia/build-max/ossia-install/ossia-max-package/ossia/exter
  nals/ossia.mxe64
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: The command "setlocal [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [C:\Users\maybite
s\Arbeiten\02_code\library\ossia\build-max\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTAL
L.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: :cmEnd [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Users\maybites\Arbeiten\02_code\librar
y\ossia\build-max\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: :cmErrorLevel [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: exit /b %1 [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: :cmDone [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTAL
L.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,
5): error MSB3073: :VCEnd" exited with code 1. [C:\Users\maybites\Arbeiten\02_code\library\ossia\build-max\INSTALL.vcxp
roj]

**Comment by avilleret** [comment]
should be fixed with b48f53dd
