### ISSUE TITLE
[ossia-max] crash when sending 'get unit' to a [ossia.remote]

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#667]
<pre><code>
----------begin_max5_patcher----------
303.3ociREsaCCBC7Y3q.wyYUMoQqs6WYZZhlXkQUBDANcYpp+6CLIqcqQp6
g.3iyw9NyYNSdvNBdo3EwqBF6LmwHnH.aJlI6TiUsJOQS1AdupAjYo6PXDI7
F.ECFMNegYnSaZAjxp3Jnc.mQymP6UX0GZSy6NnBS8Rw9cqVmIxKKhakTPQ3
r3sobR+F7qdHkfT9yU5ZpgrGN9zFYD5BmGWx9mJz.eFx8NAZ8dsZkC5rHrnH
yWTjadrH2tMtkVefHyl9VRr42JVhfrUa96zk5iH9uc.ucvUMWlj0kIt1I0fG
0FEpsla3jm3bWYU88m.mehLUhfEez5hg6xnPsIEROMjN3jdl+ZBQ4B1EF7pA
G0VxwmKkoTs0fyLnIOmGGrgRRiOiJ75rWkzAMk4W3eS8V8pM
-----------end_max5_patcher-----------
</code></pre>

**Comment by evanmtp** [comment]
Seems like the same thing as #666 .

**Comment by maybites** [comment]
fix confirmed.
