### ISSUE TITLE
[ossia-max] ossia.parameter @type list - storing lists longer than 255 elements

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#669]
Currently it seems that the cap on the length of lists stored as presets via ```ossia.parameter @type list``` is 255 elements. It's worth noting that ```ossia.parameter @type list``` seems to have no problem passing longer lists from a remote - I only notice the list length getting clipped when recalling a preset. Please see the attached zip:

[listLength.zip](https://github.com/ossia/libossia/files/5711292/listLength.zip)

Would it be possible to make this maximum larger, possibly with something analogous to the ```zlmaxsize``` argument to ```zl``` objects?

**Comment by maybites** [comment]
while I have no immediate use case for this, I would second this.

**Comment by avilleret** [comment]
afaict, ossia preset support huge list, and ossia-max too, but it seems that your `simple_cues.maxpat` doesn't,
see the attached patcher
maybe we can add this requirement to the new preset system, along with other features, for now I'm closing this issue
[listLength 2.zip](https://github.com/ossia/libossia/files/5734348/listLength.2.zip)

**Comment by evanmtp** [comment]
Ack, my bad - thanks @avilleret!
