### ISSUE TITLE
sending value to a remote using wildcard crashes max

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#670]
See patcher below.
Using libossia  v1.1.0-a4 and Max 8 on OSX 10.14.6.
	
```
<pre><code>
----------begin_max5_patcher----------
3326.3oc6ckziaibE9b2+JHzgbHncOrVIYtMSRfQBrAF3AHAAFFBTRUql1Tj
BjTc21Cl42dpMtJtKp1TFx.sVJtTeu82qpGk+8auYwpvWXwKL9aFez3la98a
u4F4PhAtQ+8aVry8k09twxSaw5vc6XAIKtScrD1KIxw2E9DyH4QuXi0QtwOx
hM3WV5Ys5vpU9Lw4Azir2MY8idAaWFwVmnle.Eeu4cF.r5Mho3MH+KFeReQA
G14E3yRhKdm71Hm+vUe9M3E4mX3gjzyzTL3eb6shWtqmjY.6Y9c7HpLLN1y8
98tQt6XIrHEs9SIO5l7SEH25HN.PRNH4a.KK42fCf3.0SbP8npgR95dlZBWr
3N9eFeZDz9C9g74nahAfQh2zBpgPKVn1IlLF7RVfqVywrMBckav1EYS+CgQ6
bkXkN0h9H1tvDlVt+W6AOxxQ9Fvd3LoFj3nVk3iVp2.Yu2XKKYY.WbDu2cMq
EJFSoRRUohCsosSwvioXm5IXPiDb1cVBGVjl7zzGWQvym8DKJ1KLnvM5lEt6
2WX3aJbIBlxmCk2H66xFxKPMDLanH1SdoWuY1ntQblRBmibHRhwEuPS8IItM
gaXQAG7jPQMHW7ngjTPjylEWrPdkd3b1LwTxXcj1dHp7MpIImMyEza8CW+E1
lhfaQ3dVfWv9HVL28saREruXC6A2C9IKeHLHI16aJm0bgWcG+AMBq8fBZPB+
eNxy0Oi.1F4sILP.hRRBwvoSG2ngnb8WjXjmQf69ZtXtNCmszvAi4D4g3UtQ
BAk1GRp7aQRXne4Ckcc9rGRzGduWPPEtXR39lOXj21Ga4ZWExO3t1t2xiDu7
Pf5nK45DIKicepL2Nw02WasV91+hafG2wGKwSIBflYGT4G8w30Qg99knW0Qd
plirgqiul8r2ljGkSTQkA9o6sOUIZQlTdi2VVbR4wRb2FWdj3jupX5EF5vJs
M7xD1t89bpn7IvsN7hSheL74X8IlpnUjAjmKSQa5ht9JMdEWfbiuX2srLK1h
9AW6ybiL3b9hGs1rXP2S35vNMDarQGgM4LrYGhM5TL8nxH.Z2LijkTJpPkHC
QLtM2FiXVh3uN3KPBVvWPXybuWsyW.0yWrtT3Kft3HTSAGA5Hc5QIiliPm6b
ju4aD6yckzIKgm5fPGA5HMgLGuwCoYVBrUVxceeLf5xoBQwXbjkFYgGspBbV
npHgYGjLgJoXYtNHyzWalfMqmfAimfKb3zhdKFQRNQAaXuTHctysFShguwpt
XbJqFjSNmaTpJHvIXCoqGatYGgwSjYj8kRPHyt7rXCllfPPqerxWI0k6ImuB
b1GdlyNLVY7ltBNCvVBNhizkL0Z7LjVBNi5kik6DgPRd03OqCODjvh5h83Hi
Xoc7RAcyeHMvevMyevsweD7j6xWFnWSVTDGLLipqRT6gn.D0B8ZhFcZdf4Sd
d8ImFsEzImTCB+5jUCbB4OJrzU9+R9CwD1WFTS4tzhdg4olWW9RS46EzzBNH
INwwqm0DGdHZcpTQWsuQY5bCKNwKHag59XNkINwdIYFJHr5IHfmQLP6IFrNi
XfzW9f8YFDfuyBCgil9wINmpkhJQ5EJN6fnWxC7YDEoZbee8S.6siB54DEz4
fYJru1oNmaP.6qxI5bgh95s3XAWXzF0t2Y98EY0nYmAMv4AZyACZPei3k5J9
7fhdBBPyrB8foaq5BwdmsYoZeBW5ljD4shWnRb08IdP6m0V+vUt9U1Dp51tq
ayA2.2K9xaDUdYVCXa3UEYXgF7lvmk67.1E9QPhe1K490Le+UhspNcFiBeVU
YrYVmbzvFJ2VCHnVEKDTs9d11EH9Z1855YHE1oTyZ5EGZ87Hbgo43MQmWtge
oIg+8rcWEharAW78hKUXedaOvuAaXOnNMd4k2YPo2IdSV4T9KpNQo9geCH8O
iOMk8MhpcYDs7fuwtutT9gtkc5lFwBdjZKmTU8fwG4fG.IXGAUX4PMsrEex1
AC.1Rhp2cXC7jzzkSS4Z.U7qp98zbsiK2BUzgWS04Tvi6QRl9NSN8Xh.khJu
Xm2l8gdAIZZCaQj6IGU1GSE+1IBMDoGXyoXNVM.Man3UKLL8KYme4jKNuHsT
37J4NL5YF1SVjYM5mUZ0IwTToEmpzdSG2ZSM2VSUaoIYbWU6cTwlH2I9gMdg
+lr2bV9dVvAkIXZGDUlQrZ6Cd99YV9EiXmZUp8Kj0EUE8R.0tDLuGAPVPp7S
7OPHEyXWcMfzKBy8rXBEmJlBsvD4mrgHBR50rxkAymKSfiZFLcrMwpOwGBTx
kDmWFrU2KRVEZnl8Qg6CixZJq6QNYm+gjvsQta7zqSkYorJtSqGEwOZ0tpYw
NNC0K8ZJp2UVXry6kSUHjAv54oHKJ1RF+AYiQ.IyAWguLR1YEA9DKDlRd8+P
wbM.fegG013WCEwV7ZiyWLKBQCkl6qchfx6wuqq4O8Z9nN8KCA3WTJeppPrX
PdgysdKh3AwISOE1WN8vnTyYHkltCd8mFWTahwerPr1VDvWcLLsNFdu6KV8Q
Y8JeeZ36+ye98+qOzFi1c8Z9ctDAwKSgRsDjALKOAQEHXT4JOJcQ14r2xmEy
msq5LzfnQP7Er7JcINhDcjPwhPsonZloxl24iKJWSduV5EHRSjkI4DoLIS4A
.ADpiRxQrsgkuwmXJZ1DSnJyJajkIQNM1B1YspUZ8WPdMsUnyu6Yk0dDgV3o
boX4.B4M38jnPVUkAw46ZMFB1RyIE2jynJSQx6vNQt+GEfZNpiZkEzFCD1WR
cTadwARFHx5hSIcR7d9uc2Etyc4ida4J5aeLQrLqQbDxFjGUsZGIeEolnzh3
ASM.PiOv1dv2UKXG+ca0gjjvfew+.q8.yk8jCDtxkFjYllNZu6SGgpf1udHZ
u+f.mU5RnAxVBMrVod5.W5yEj5RGjiMJgaLHYdYd3n5BxazuVy1bM6Do5JhV
lx4FPZatbvVBlGe4sDa2xlSIRccaSfss5SXdHPXqNqoHJ1VwA3hHhxGuMO2.
mZPrRenEDKE2RmL1B1ozwFHOugFAgMzDolZtSJEHr3vBPGgBCnWJLY0ybUk4
pJSi9Xdj4uW7bdtz2cEy+TpANSfmR.jrH+G+opYWWnHYzjQaed0pSqj9bT4b
sx8IuBxOq2DXSSvhS9V4E7kAVLJUD51NyaBRak1Xcn837qyETOtrX90sVvkG
5EVwigc1RtaaIRjugxAO1RsOrBwCvY4cQTrq.jhUL0TsSmT8CcisWQiqWkBc
oJlZ1qSmy9uD66sgE8eEaGUaVKcDgeRvxN7StBEQc3yAW1S8YczuypN6THES
vxfrPLUufPPtdDB1Gi0QFiuuSZkPj3oSJ3FK9cB4hsBistdA+Y6JuB+h.LVh
U.0AB5gO6NnshH3gCAqS7ZMAvFSYsZFeCXZYeai65+bpxStuQNNA.OsI1OFs
uAlRM6atatn3vJm6s.XLE.LUaIuC2yiLfGwAXaYedX3cE6P5dpST2Oqmtlqu
zw7LvnECQtzQAhZmTNDSB3LWV6PT+Es6opyTZbUv5KLFou8z13rDDFv8Z5JW
qmDZ0zJ6mMy4tjsgrd10ruBWYeS21A.5SZXWlqa20DwtlH10DwtlH10DwtlH
10DwFVlD2eMUr4SmYnU1eaDiEz91gMdww31TmLgHfRrvpE3lG7fnRnBq8nXg
+wpSYzxish1IdNJLDa1foNBNDPj1Ffr867GNogm32HU+AtUanztkAgScjj1A
MMtca4mJIailHYscikc6sAZySHOmKbGKledJhbyLfkTHAzO4K7wZb62zYQV5
Sh9oCO5nvSzVnk48txGZQstmDyYVq1YZ2IsiZSzwaGjmwrnu19K+Olue3y8b
O0JscQTKa0yVkoM1FzdQHs0SbhmlyIh3TK7fftZO.XcV5uJcsWA.Bm6.DM2A
HdtCPxbFfQgOGLXqjbbkGQCcVQHb1iPzrGg3YLB+6e0c3pglPGhZwmrrPHnk
p8E...Z5AXOpmpNDJ4dHw+TqZrH0ryE3fyYvglyfCOmAGYdBt2yKpMHwcvlD
1XSJU8zzSM4fSZ9Rc.NjoGiprZGNDgDfkpJMfsZoTIbOMjV6oIn3jLMsOGD.
7Rm.PW5D.9Rm.HW5D.8Rj.NraEu.6gm1fXUaTOegYOdVVDwy46j5iTht2NCS
pQArP+MCFassZlmE.Bm6.DM2AHdtCPxLFfeX3VHYOSAfr0V1Dh3dWlRzs2Mf
4+e7By9Q+9r7S7TaOFql2CGyOxS+v8jZGoVk221w9OUtxeLOEcGc4zVVpBq4
wNcZ+oA30QwO1aW9C67nuKIt6GvyV26bSBMdm3AcewDQE74+MabiZ8g9hswK
Q76jXE1LHOz6QepZtMEe9.WwMFCCL9M2fXEsj87wmcIp+iibrS3QOWV1XYKJ
I8tne5P5yPSmth.QBt3a6b2W6shrn6WN0FRoezi5WvuF9eFza+ia++jL7YPO
-----------end_max5_patcher-----------
</code></pre>
```

**Comment by avilleret** [comment]
it doesn't crash with 14e26c27 but it doesn't work either...

**Comment by avilleret** [comment]
this is fixed in current master, but your patcher doesn't do anything because I `crash/*` only matches first level of children thus `crash/that/max` won't match.
To access the second children level you can do : `crash/*/*` and I don't know if there is a way to match any children recursively, maybe @jcelerier knows

**Comment by avilleret** [comment]
see the following:

<pre><code>
----------begin_max5_patcher----------
2466.3oc6b01aaibD9y1+JH3G5GBbb39F4xBb.MWaQPKR.NjqnGNzqPXkzZY
lPQpRQl3jC28a+12HknDE4J4Uxxox.wglhqlm4Ylc1Y1W3ud8U9iyefuz26O
68e7t5pe85qtRcK4Mtx72W4Om8vjT1R0i4eWZdV0b+azezBV4j6SxlMpfOoT
+0PBg2FbiG.EH+Oh52Pws79ul1bWdwbl5gCM2Q7ElWUlxKUh.Ztq9VkeYAW+
E66eim+XV1L+lupjoJLkO9CuDuBREr47RdwHdFabppwAqDTRVsb.x68aWes7
W2Xo1mw+rPX0hpj+PoF.KWlvtsfOOuj6Mofs79W8hW8hdHoPX3ZjDP+WsXo1
bBpONQ8ut3Dn+IQuK4KKeYZ9rY7Buew+8ZV3yIk26IzbggH6W789Krpx7+WU
RoGnGZABTDAAonCJd.VArKVYmdIPfynj47kKYy3awI.RvvZXLPoZw2RNLEra
kKnSkC5Z6s3g3Ekd+KVwLdYelS.PolHTrxKGrsW9j7z7B8Cq5Iz5WNgT.zSS
mfVjBrGRAQIO8jRzwlT9tuyq+NB0zPfR+wgGZW8jrxtUwvicmgAUwZ2+ilJR
blJN3n5FcAp0hS1n5.3IYX8AUei2JDSNspevSeVMMR1jXS48rxWIDnErUjNI
mHz.d98RNcRLQ9Og5N6AK5nTq6QNW2cWJLC2qmD9TjKeD5LKYdkc+ECmVWc9
7XvQIe9ngM8pl4mljsYUcJPKueaBYYdUwjZgWy8dqf8TQt8IYrxj7r0eHf9g
5jzsVR.ajDxERxBAIyW3QKHrEBB5.4.sg5jkC73kTvoxc.ZgfvNPN0F598Fh
bgjH1HIpKjjMjmKLR.qbGbgfrQgHaIHc3O1hEehWrz7zJYHh7+AcQUzaT+YR
l9OUYc6Wv+TR8yqe.VgHFeoH.eUgBW9ODpmhI+44S4EYUIlPuBsSHxkkeIcy
PtYhgtTM80USSx+wRVY0xQuimUoihKzp6XUoksYhwytKIMsoDvqZ9DwHTlgI
LEHdi41sJWDFiA.prRQD.EACUWItfPDCKUyml1.paDlfiCfxGEGBivD0UTHh
fZUxooYvUxJ.DqkPPLM.quRbKfPVq2Lw375gtgQxwGM2cQQ9h7hZapnowMOe
UY9rB1zDdlhcBT2WYh0zsNy.wmpncEmX3z4BBMotMq6301XLO4gGqQnAfcyo
nnPbDPQITLBnHG7F7xARmaXvcrQvkb8eSSthjh+97zod+PtLYmj9X96xEBJ4
q75jouso+sifx6vusO42DexZRN3VJYs7g2F9q8Q0nQD.60EIrTOIs36dMzFl
1sZZvSjlVWMzk9w6ne7Z1j6X0CwBNTGVmaAYODYiy5ECoaBH+2e869GuuOht
kpPWwQsv9iMIEJI.pysfhhBHwpqhjVktHViErFDaCmm77R5rO15rUKsOVlil
JaqHRHMD0A+tiXyxT5TzF.BHgwZ8hPopur3lVylLQ.vVMEGJ9IR9Xvlb8BCj
TdaAyS4y2rs6niijXZZmbxSTMZTRlL0atMXdqA2qlKSN1koCG0LzEFHIakmF
UjjqJGWTz2ZtZtwNXlXrsRLyFmajnqsw2lfiLLnzsyEtmtQ8N3nm+S1774rQ
2mLSz4b18k7oixKDVVdeQT2RcMLBwrldtCdhAS8.Pu2ymUkxLcHN7uswUkk4
YeeZEu+AlaGq.HCVnLeMFxXS7C2onZn8CUEKR2KvEI8tTNIwRuKcYt5fAtCb
FjLR2Tcqz.tmQZU3QE8fJK.WEwBrZzgc0aKjBCP5dKhnOD8fJXZDHrCMRDPw
DCZGfn0RM2mTQgBYnjpf9zRMjJFYHd3AShnhN5JWeZ.fR0WgE4CXabnVXY2A
p6JJSHQDiVA1lvMgl46vpfLayO6iCCvJGll5Yt3xbwkYmwXtmmtPjWDeTJaL
Os+ZfavVMlHM4Ds8UaV+2ZkFhNQkF9gwiuTInskzux9DepLOpZS3EAA.+G8W
UR1GstXzP4f1zl9SHS3OGVV5vR3D5I43BF1HdLsYd9oQxzj2QE36nPzPxMs9
8PAQG1xsUPJKZSWiUXQyVJZ2DICtuMbRJmUzpQ.4RrPVuXkMJawI8393xzjo
7heRtbTV1aoqA4bBVli+DSZqLYmb3noa2RXHlfUIG.wglIIAJ5ggfC3j0iH1
XXL7.dP1BgtciFLoL2XEXKkaIl0qvf+0orI+tKxTytLd5h5FLnx5Ju1otG.i
CAf.8RQFKLJpXljX.UV21NweO9AcFtX.kcc.OPB4lp5iIAZqdviKKbWkO7LV
R1uODnog.LVwCfvXHvs7lxcdPqsctmCEW6tprI0CNdj6GbbJS5Q3VrO.l+U1
zmUQK93.NPGw98G3jROPMHC1It6zGsiuO10grO6Si5iIyEBb+SZ+.mVAVYYg
d6IsyoB0R16PQv+eLwcqmFVybvbIQrKIhcIQrKIhcIQrKIhcIQrmsD3sWRE6
4zBhYbteSAmmcr1RnG1hA0zOADRhv50JPjDEQOJO1LJSD9aqMYuwdLStoeOG
MFx0sIvjIKDPT9wflUC8aNqQRVxbVp0K0FBW2KmzrBGjlMOSD0YK3VSvjMtn
GKWclIstRtQuNoq6V7gtta1gdKW2sA1zmnZK1J6Y8VfZv874tapnLP7.qBxp
LJEQ7.QJZGXNDRh68zMJwpJfj6qs+zOySSy+r0cKVawcBin5yVU.ESAfdSMu
u8DmfMhcjxoGnWpW8O.XWNJmjcs2Z.DdtCPz4N.wm6.jbNCvh7Oms28RVgqU
iEhNpHDd1iPzYOBwmwH7u9E196FF.iI5IgMJBgfQ5Ma...PtGfVTOUWHTwdH
4O5oxTlOvwBbvyYvgNmAG9bFbjySv8NQQsYkr8tKAEGDFpOM8gABvo59FFCh
ItGi5rZ2eHBIfHc8c.pdkSHhHMjd2MUP4CEDPOFJ.74tBfdtq.3m6J.44tBD
9bTAplOVTf89m1fbpBzmKylimUDQdXYcZLRE5dyYXRMZfkmNcuwVeyl4QAfv
yc.hN2AH9bGfjyX.998uGRywy.zLglAPjH5hKQ2BVFO8emHecVbDeEO02wXM
3V3g7RdB7s1K4oB8r79lAV+o1U9iEonGaJmNJRWXsXry39OPkmFG+kIyWcXm
O3ukR1hgd4Ks14F6srxbu2JOn6t5viIj+KmxJ58PeklO4i7oi1fkAqF4cqq5
8fDQwpM0hput43bXysZs.ISSJkutOOPHs4owarH7Pdl2OxxVpY2lSruqXYAG
Hw7aFb0Ws1QVtinNMKai9M3m5kzpTgVtv7NmP8tb85e65+.ve0b7m
-----------end_max5_patcher-----------
</code></pre>
