### ISSUE TITLE
[ossia-max] reproducible crash with a more sophisticated patch

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#672]
Hi 

following these steps I have a reproducible crash:

https://pastebin.pl/view/3533b278

1. download https://github.com/tecartlab/SPARCK/archive/development.zip 
2. drop the 'sparck' folder inside 'packages'
3. restart max
4. copy-paste the following patch into an empty patcher:

<pre><code>
----------begin_max5_patcher----------
642.3ocqT1ziaBCDF9L4WQjOmhv.IA5sVodop8R2doppJxXb.uqwFYLYSzp8
+dG+Arjtq19g5A.y6L1y3mwddXUDpRclMfV+10eecTzCqhhbRVgnv+QnNxYp
fL3bCU0SLzVlFswa7DQKIcLmsa5ACrYKb18m3C7JtfatXc.GrnNdbfY7QMIN
Yi805eDLJTz6X00ZRy.UqDBqaIAaTAmdmoUqFaZWpyjjJAq84Sva3zyMT0zo
pYWonz0v1ZghamxkMGzLZHaK2aS2st23BWtmsaQxqFMBlwbom48Gg1.HiHaP
ytLSqpgXIjCweg2vqeup9RL.ZHlS7iW6bSUc6avSZxwNtDhfqVj9jnOtdUq3
iqVYes4OrnJY2CgYJHF1YiOzCCbRbM6DmxVOzSzz6P+N1fSwtO3L6mzzWENy
lnJgROcf.mtMuzdnXe4tj8E1QEk4XLLBuX4VvmhWjO3WjO3E7wsVHRe+Ildf
qjNDYADfma8ITwF2ubo+WGyQZl8fs2e2oEDvlVtAXwn1WcOuKG4mJTi0xQdH
1PQAB4f4h3Wu2Mev3ci0b0MFhYb3vmYxQ+lCUyNRFElqKiUMG4BwL9hls.kw
.nCvcSP9JTmF3ZRbFNae5N2HXv1s.qmHcXN3oIkCkmjTqq46R2mu0MpHMaa1
U2jCSK8oXkfK8QHorHI2OBjvWUWAVJaDtLOcu8FVPsWq5UZyD0iyJm8eznZz
jZNS5nShS2Uh831cdUCVcX2wj.S6.fxmlyx6KyEiOR5TcjCs7lVA7XX0GTZH
CYuVUgPoPzVPZruKmCUIgs6+kz6lu9sO8gP6g+8U41PS8jj+tkxe+w0GwtVP
KBZn2FztY0iq9Ivk7BXY
-----------end_max5_patcher-----------
</code></pre>

5. there is an abstraction with the name 'Sphere' and next it a symbol with 3 horizontal lines - click on it
6. select 'properties' - a floating window pops up. 
7. close the window and from repeat step 5 until crash, usually about 5-10 times.

there is a java - external inside the abstraction - if you have no JDK 8 installed - the console will throw some errors, they should not have any influence in the crash (theoretically - I haven't tested it) otherwise: https://github.com/tecartlab/max-mxj/wiki/Install-Open-JDK13

Q: what is the property windows doing? - it creates the ossia.view / ossia.remotes for the ossia.parameter inside the abstraction on the fly.

**Comment by avilleret** [comment]
running your patcher in a debugger crashes as soon as I click on 'properties' due to Java stuff.
The key is to run it outside a debugger, open the properties window once (to trigger the Java initialization) and then attach a debugger...

**Comment by maybites** [comment]
nice. I am indeed unable to reproduce it anymore. thanks!
