### ISSUE TITLE
Using 1.2.0-rc1 libossia-native-win.zip on Windows, I get a build error, when the earlier version worked

### ISSUE THREAD

**Issue by onar3d** [ossia/libossia#673]
Hi!

I thought I'd update my project to 1.2.0-rc1, so I updated the ossia library, and made a clean build.

I get the error below:

1>C:\(MY OSSIA FOLDER)\include\ossia\network\value\format_value.hpp(2,10): fatal error C1083: Cannot open include file: 'ossia/detail/fmt.hpp': No such file or directory (compiling source file ..\...(...))

I guess this is a win bug with the released package, you forgot to add a dependency...?

Best,
Ilias B.

**Comment by jcelerier** [comment]
Ah, it looks like a dependency update changed the folder in which things were leading to the library not being copied correctly at the install step
