### ISSUE TITLE
ossia::presets::make_preset doesn't handle boum.1 address correctly

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#68]
from PresetTest.cpp, the preset is :

````
{
    "bim": {
        "bam": 3.1414999961853029,
        "boum": [
            null,
            "don't forget"
        ]
    },
    "foo": {
        "bar": {
            "baz": 13579
        }
    }
}
````

while the namespace of the same device is : 

````
{
    "appVersion": "v1.0",
    "appCreator": "test",
    "mydevice": {
        "foo": {
            "bar": {
                "baz": {
                    "valueType": "integer",
                    "valueDefault": 1234
                }
            }
        },
        "bim": {
            "bam": {
                "valueType": "decimal",
                "valueDefault": 5678.0
            },
            "boum": {
                "valueType": "string",
                "valueDefault": "hello"
            },
            "boum.1": {
                "valueType": "string",
                "valueDefault": "bye"
            }
        }
    }
}
````

Note that `boum.1` doesn't appear in the preset, while it does in the namespace

**Comment by avilleret** [comment]
address name is splitted [here](https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-c/preset/preset.cpp#L448-L463) which explain the result.

But I'm wondering why is it splitted ? why not adding address directly ?

**Comment by jcelerier** [comment]
mhh... it's a bit of a complex issue. There is a workaround: if you name your first node "boum.0", the next one will be "boum.1", etc.. and the presets will load correctly, with an array for the object instances: 

    "boum": [ "hello", "bye" ]

**Comment by bltzr** [comment]
what we did in Jamoma was that boum was actually a « shortcut » for boum.0

does that help ?

**Comment by jcelerier** [comment]
@avilleret I tried to do something if you could check.

@bltzr yeah that's more or less what should be done, but it would be hard to do "like this". For now I added such a shortcut only when saving / loading presets.

**Comment by avilleret** [comment]
thanks it works !
