### ISSUE TITLE
[ossia-max] feature request - attribute to allow ossia.router to output either relative or absolute addresses

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#680]
In older versions of ossia-max, such as 4c31e19c8, ossia.router output routed addresses with a leading slash, i.e. as absolute addresses. This is similar to CNMAT's osc-route object.

As of ossia-max 1.2.2, ossia.router outputs addresses with the leading slash removed, i.e. as relative addresses. This is similar to j.oscroute.

```
<pre><code>
----------begin_max5_patcher----------
848.3ocwVsrbaBCEcM9qfg0DGIdS20s8WnSGOxfrsRAIFIQpSyj+8pGHBX6j
ZG6ztAPWz804974EdAqY6wh.+u3+ceOumW34YHoI3Mb1KnEsupAILWKnh01h
oxfP6+j38RCcJ9WXt+iXtfvnBe1FelPPP2oX1ul4K2QDNdZHTbEqmZXLZfXG
GKTxEIUru5j2Xc+50MXMEniGjrZGgtcEGWIsNALNcIHzGV.Lu.lSoQKA9+Xl
XDjZin.CTo8sDZCVJlJeRsw0Xqe3tzfWuHqW5tIPS7kEKzOBuRDj0TeUH34g
OeNvSxsCdZwBAZK9H3A000fumiq8ic+ypI4ScXqyEDL5FaXTIE0Z9QvW4DTS
v6AJV3v9JqT+LZJnTqjFG20fplguyPkniQknfIVif7aKyJAeRvBdCAq6+TQq
IfUdzsBrfe5fkpEkRQGW2oqxVxUBWU9c+FdOQ91PV3UBaYFTqr3HTSKqMCP1
4V0EAtHLyA5UrFF2ZTfkvnzjR.rLCjWjDCCUjxcGhy0+TSpnLAByyRxAoEEQ
Ipvu1zu9D1abNoseFDBtYUvk++JgMYh+KJjMYjoGAY+MrIM6CiMFcXlhcvtG
FqTSeNfIX87Jm25zs+jnKVHITytCStjt7XxkZI0cLBUNnxnjkopYeo5mu98a
jTet10Ap7MrKURkO78sqxXalbp6vLCyhepTigsELVk1lToVOXqsKBMGIT6QS
Be.G+Hwce6EPbUVgTkRzysIM6yryxCZYp0Qn8jgXmBMTpTHep4vX1X912Psr
VzpcjsJnZ6NItdEiintbaEZrA02HmCgnpJ0xPSZIA0NNP611gxu55gCgBthA
igXz5fvaURl314XZnaz7dvDDwb.XXTy0HJB8mumWU0fUH6r9rltoZmx1bc5W
vo6escCooYjUuQYpZMLTwOz.Obf7L0jo6jWLfcfkwFULSCCL.cbDqaqa56Gq
64mn+5jbD43HxLuvvAnr.jX+RQBd.apXuEYixAttB5M8YcLtqlPwZ4386krs
bTMAa2r0r9nKvehTkywcU.5LNJxhxSLwgByvL6W1QeSYarhet9rQvwmS4.2f
a+.1mtg+kxykdegx1pzH9Yy3kWwY6IYlqoqSDcCiZMi+V7xh+LGnVEH
-----------end_max5_patcher-----------
</code></pre>
```

Would it be possible to add an attribute to ossia.router (maybe @relative_output 0/1) that can serve as a toggle to select the output format?

**Comment by bltzr** [comment]
We're currently looking into that, and:
- there is missing information in your patcher (nothing is written in the text boxes)
![image](https://user-images.githubusercontent.com/113982/106887123-03123180-66e5-11eb-8319-a606afe8694e.png)

- what if we did that by using (or not) a trailing slash (and not an attribute). i.e. sending `/fruit/apple/red 3` 
-- to [ossia.router /fruit] would output `/apple/red 3`
-- to [ossia.router /fruit/] would output `apple/red 3`

What do you think @evanmtp ?

**Comment by evanmtp** [comment]
Oops, sorry about that with the example patch. In any case, the proposal you're making concerning trailing slashes seems like an elegant solution to me. @navid and @petervanhaaften , if you have opinions, please feel free to add them.
