### ISSUE TITLE
[ossia-max] ossia.remote.maxhelp is not working properly with latest 1.2.2 release.

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#681]
Hi

ossia.remote.maxhelp is not working properly with the latest release.

one of the latest commits where remote still works as advertised is [7eaf809ce99ddc6eecdd0eb6f5ab467708659eac]. 

cheers

martin

**Comment by maybites** [comment]
I actually thought I already posted this bugreport, but I didn't find it anymore..

**Comment by maybites** [comment]
unfortunately I am unable to compile the latest on windows.. I tried to compile with the visual studio 19, but it gets stuck...

**Comment by maybites** [comment]
yeah, 1.2.0 works ok.

**Comment by jcelerier** [comment]
@maybites what's the build issue on windows ? as it builds correctly on the CI (which uses VS2019) : https://ci.appveyor.com/project/JeanMichalCelerier/libossia

**Comment by maybites** [comment]
shall I create another issue for this topic?

**Comment by maybites** [comment]
ok, I was able to compile the latest commit (I didn't have the latest vs19 installed on that specific machine).

but still:  the ossia.remote.maxhelp (the last tab - pattern matching) is not working properly.

**Comment by avilleret** [comment]
this is a known issue as I said in my comment, pattern matching has been broken in favour of other fix... one step forward, two step backward...
hopefully this should be fixed next week

**Comment by avilleret** [comment]
fixed in 1.2.3
