### ISSUE TITLE
[ossia-max] ossia.remote outputs value twice (or more)

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#682]
when value is changed from the bound parameter, ossia.remote outputs value twice (by both 1rst and 2nd outlets)

If value is changed by the inlet of the remote itself (or from another remote) : value is output 4 times.

if parameter / remote "repetitions" attribute is set to 0 : same issue
(this attribute seems to only filter repetition on the outlet of ossia.parameter)

<pre><code>
----------begin_max5_patcher----------
945.3oc0YssaiBCD84To9Of3Y1Hrwbak1ef8WX0pHGh2DWAFDXZS2p8ee8EH
MsEBNEm1lGRAaLLy4XOybr6S2dyB20k6IMtNe24WNKV7jnmEp9j8rnuiEtE3
8Y43F0.cyJKJHLtqW2C4j8b0CpIEkbhSYKupk23bONuk3fb3zBgI5GMqsPLf
bBW8w766ltQ8IJWe22f9GFbElmsix1tpljw0dIHBsLzyAjltz2S0RbA5uz24
2GYBJq2B.Um+61ajWEW7LFmqa47R1Q9RMtfvI0qHL75bxKb+WhJv.nB7Lpzi
j+XEQCI20X1V2m8+APMRhvCnFh5+q0AMi7fvae6baVYKSf8QlFQCAX33.lJW
9331+S1zD3CC.xKwApFvQge36G9sEqOBkmwbNbHJ.MNEHwswy6vvD4kP+I.t
8m2KaZn3kcQ1EOt5.iLxJgfgngvSSCpeFQCIcA8CvCYk4k05Q6uD.CQodhah
Si7iSj2kjh..wcfK.4cdYD4OPyHmQ9vjSlND.koCgQWWYCCmSxP.L4ZKYXj8
xE1g9qsbgAyMUXOtu3oBGMZ9GN0jJBleNZYhOUvKLNVhBjuZgbT3URvKDLmn
WHJQlwpCzeBQuMjbGe2ynJd5DvcxxWcPNHVAYzTgrvuJxWRlcLapF3fzOI4K
+M2IamvMImy7c7DxULBxZvFkdsLWO67yhJQBbmbomos7txlUpLMj0ZutJjgj
ZOYHZrqKFeIEgLB1qporypPr6zRK5RSgfWk6xBM2MY0Kv5K5lrNM2cfwLg9F
LAXzbx5qiF.PfdiInInNTpOHMxScWhefhECAwQn3KC2g475V5A.Ja1s+zJBm
xokrwNftA0+chS1YhkXI.sFd8RrKXYBKi3f2MhEUGDqLRAuO.qGlaNk8lSoU
YL4CdEMzT1Vm06b8NuyQFbCogSYXIGbznjq+kiZbF2bCBMwfHqYO.xH.FZOC
5ajAg1yfFwn.6QoQlXu.qYtPSLm8VfF7wt9L0nIO6wlFEN.sp4.SBuD6ELXD
eJOjBaYvDil.ismAiMhRSsmA+nKQ..lXvgAXWMQbU08j5lt2PaJgFf6zprR7
zsoLcasjOQ4+6o8uhdaBt3ZQMatnfcasxCc2G0Ik1snbColIjQzUYVBVooa3
Ol+l5wLgjS06+SbQYAd0N5VAUrcGmrYUY8QmAg.r+A2lyeEGgyxHL9QxDURF
7kpGz+u+VdDU30y20h2Q4NJS2agBwmW409ujyT5ijNZSEVOenzQc6Mhg7eP9
flpT
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
which version are you using ? I think this have been fixed in master

**Comment by matcham** [comment]
I'm using latest available ossia-Max release (for windows) 1.2.0

**Comment by avilleret** [comment]
fixed in v1.2.3
