### ISSUE TITLE
[ossia-max] models in poly~ are not properly renamed

### ISSUE THREAD

**Issue by jln-** [ossia/libossia#686]
When having models in poly~, models are not renamed using an instance number.

See attached patch (poly-bug.maxpat)
[Archive.zip](https://github.com/ossia/libossia/files/5918442/Archive.zip)
. When loading patch, model are not actually renamed with an instance number, but parameters are:

main-patch/polymodel_voice/param
main-patch/polymodel_voice/param.1
main-patch/polymodel_voice/param.2

It should be:

main-patch/polymodel_voice.1/param
main-patch/polymodel_voice.2/param
main-patch/polymodel_voice.3/param

It works fine using ossia-max 1.1.0

**Comment by avilleret** [comment]
fixed with 557d8ceb
