### ISSUE TITLE
[ossia.max] mystery crash when opening large patch

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#704]
Just testing out 1.2.3 and had a mysterious crash when opening a large patch. The patch itself contains a bunch of non-ossia externals (mostly Spat and a bit of residual Jamoma stuff), so it's possible that one of those things is responsible. I do see some ossia things in the crash log, though, so posting it here anyway:

https://gist.github.com/evanmtp/6663a83a0cbf5791d9be515d24a2f90e

**Comment by avilleret** [comment]
1.2.3 suffered from various edge case crashes which have been fixed this week

could you try the [latest ci build](https://github.com/ossia/libossia/releases/tag/latest-ci-build) and tell me if it works now ?

**Comment by evanmtp** [comment]
Testing now and haven't seen that crash again, so closing this. Thanks!
