### ISSUE TITLE
[ossia-max] model instances are not properly mapped to poly voices instances

### ISSUE THREAD

**Issue by jln-** [ossia/libossia#710]
When loading a model in a poly~, model instances used to follow poly~ voices instances. This is broken.

See attached patch. Click the button to get poly and model instances to check whether they are properly mapped.
[poly_voices_matching.zip](https://github.com/ossia/libossia/files/5957345/poly_voices_matching.zip)

**Comment by avilleret** [comment]
The poly~ instance number 1 receive a loadbang after all the others in ascending order (starting at 2).
I don't how this could have worked before... but rewriting the registration system might have risen this issue.

I'll try to figured out how to retrieve instance number by code and force the model address under-the-hood.
In the meanwhile, the workaround is to use the poly~ instance number to set model's address, see attachment.

[poly_voices_matching_workaround.zip](https://github.com/ossia/libossia/files/6017612/poly_voices_matching_workaround.zip)

**Comment by avilleret** [comment]
@jln- could you test that to see if it's ok for you ? 

only relative addresses takes instance number into account
and there might be some issue with relative address including parent node (i.e. ossia.parameter ../foo)
if you need to support that case and or absolute address, please tell how you want to handle those cases :-)
