### ISSUE TITLE
[ossia-max] mute~ disables ossia.parameter

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#714]
I just spent a while hunting for a mysterious bug, and eventually realized that the [mute~] object disables any [ossia.parameter] inside of the subpatcher it's connected to. This is a bit surprising, since the documentation for [mute~] says that it disables "only the signal objects in a subpatcher" (as opposed to pcontrol). I think this behaviour should either be removed, or if there's a good reason for keeping it, it should be documented.
```
<pre><code>
----------begin_max5_patcher----------
936.3ocuW0raiBCD9L7Tf3b1Jfllr6dae.Vo8dUEx.NIt0XirMooaU2m80+B
FBjepZ6EKwLi8Leed7LCuFFDWPO.4wQ+L59nffWCCBzhTBBreGDWCNThAbsY
wkz5ZHQDuvnS.OHzxwT5SQHBGUAc5vHBrj1RzFjYE1.Dk6Pjs4LXov33ejbS
xhnU5002oVuc8MIQOX2Aosl1JvPgN.RrRQUZ2RKd7aqbNrnsn.CUxS62Kh31
ZpR1aggpkEWHbEzsawcHZhfOUGvl0rkt0YBdWXYDIdoAZNjXjhjd3Xnsr2yL
PMT.Y4PBvBxjOJPRfOKc1QWo0sB3+NKzWZVyzPO65g9j3NK9SFaMQ0u7aZED
eV7YxHWs9L3ah7xzoAguCgLanai8f3MHLbOjwQThm0AwflFOwAdaQA3Go5C5
6K5DgHFQochXv8H296MDvjvVHwbKSeiDeXkKoScLRJhQZQcrul5sgjljIxzR
dCnzrY0cgScOQdWp9gQZllDWlX951U8jo7VbKlV9DrxiKkIKMPBhzvfbYIGf
vF7cpqfa.sXQ9FJQvQ+07xWkHNg9M1PbRkJPni+ewP.bGB1xPUThJH7pfYD6
bmeAfdvnsf.ZlXyxDCIuLTYWLwkfrkW.XpaJ6q7tcJnT7PUcIGX3FgUcChPF
whBZy7JYns6NwdKnRk0m5r0Z34sDi1bYRgHmC1OjsE.L19Tb3we.PP0.ATfL
WAYIcJMU51wKYTLd.dMZ1OglJYRdI7YTkXm1Q9ICRyQMtjn3ta4JzVHWLTl.
rkOTBW7hgz8D0VXeDmKf0MXIJzF.2CHcFIehf3B9N5ybqwtjMeRnuGr+Ca+Z
aCjexdxSTDOpBwULFORrCFQkgD3ltNJ9aappfq76vkc23VbyWKbt9zS2qdlx
8AtR91ZOuSJRepmAoYo9ifj3VOAP8C84arMWS8iQrOw4tT8S4zGDoBd3ildF
zkbXBznrEYey+boYNdyGjtNYbCzI3yrSxmKNAmlE+UjEcVZR0uDOZzhSSOlg
eSsuqx9DR2R+RnFfPvjyIbIP1slbkPV4BSAVyHvuK131qhM5aoq9YlYJRqAp
R+zzDm1xJcwkMDhFhYYuIAhzMfy8c4zJ6lLrB8GEKV0tsJ2LZQthlPExx97w
yVdUs.kyiU.vi5YMUGxv9fyNatFaCYLyn5iYJ6.6GwPY9LzLrSZO6bzuDbo9
Y4E3mri7iAdiFHW4hQChOZH7iG.e9guGO3s9ldtAtCeK7+Pt7jnQ
-----------end_max5_patcher-----------
</code></pre>
```

**Comment by avilleret** [comment]
> the documentation for [mute~] says that it disables "only the signal objects in a subpatcher" (as opposed to pcontrol)

so this is indeed a max bug : `mute~` send `enable 0|1` to every objects in subpatcher, since ossia.parameter do have a enable attribute, it is affected by mute.

I see 3 solutions : 

- change attribute name on ossia-max side
- catch the enable attribute change and discard it when it comes from a mute~ object
- report the bug to cycling and wait for a fix

I'll try to implement the 2d.

**Comment by avilleret** [comment]
unfortunately, 2d option doesn't work : the sender is always the object itself, so we can't use that to filter out mute~ change.

2 other options remain...

**Comment by evanmtp** [comment]
Thanks for looking into this, @avilleret . Since this is a pretty niche situation, my preference would be against changing the name of the attribute in ossia-max. I made a post about it on the C74 board: https://github.com/ossia/libossia/issues/714 . I'm fine with closing this issue for now.
