### ISSUE TITLE
network discovery / announce seems broken

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#723]
open ossia.device.maxhelp
expose osquery
open Score : the device is not visible in device explorer (oscquery)

expose osc seems to work fine.

**Comment by avilleret** [comment]
I can't reproduce inside Max itself : open ossia.device.maxhelp, "Network exposure" tab click "expose oscquery" then "load distant_client", in the opening patcher click "connect oscquery" -> all sliders / rotpot are updated

but it might be some issue with network service discovery (Bonjour/avahi) on Score side, to check that, could you enter manually ip/port on score and check if it works ?

**Comment by matcham** [comment]
you're right : entering ip/port manually in score works.
But I guess there's something wrong on ossia-max side : with same version of Score (latest release) , if I revert to ossia-max 1.2.4 : it works as expected.

**Comment by avilleret** [comment]
this is a regression, network service discovery seems to be broken on windows since 1.2.4 (might affect both score and ossia-max)

**Comment by avilleret** [comment]
@jcelerier do you have any idea on what happen here ?

**Comment by jcelerier** [comment]
arf no idea, will look into it

**Comment by avilleret** [comment]
afaict it works fine on Mac OS with Score 3.0.0-a30, Max  "Version 8.1.10 (f1acba9) (64-bit mac)" and ossia-max 36e2923d

**Comment by avilleret** [comment]
inside Max itself under WIndows, the discovery seems to work (open ossia.device, expose oscquery, open distant_client, connect oscquery)
so the issue might be either on Score side or in between, maybe a firewall issue that blocks discovery between 2 softwares. (I did allow both soft to access my private network when Windows defender asked me)

**Comment by matcham** [comment]
I don't think it's a firewall issue, as I said, if I roll back to ossia-max 1.2.4 it works fine with same Score version, same Max, same everything.

**Comment by avilleret** [comment]
hum... the main diff between the 2 versions of ossia-max involved here, is that 1.2.4 is built on appveyor while latest-ci-build runs on Azure Devops, so I suspect a configuration issue on Azure side rather than a regression in the code.

**Comment by avilleret** [comment]
btw I can't make it works on my VM with ossia-max 1.2.4

**Comment by jcelerier** [comment]
> inside Max itself under WIndows, the discovery seems to work (open ossia.device, expose oscquery, open distant_client, connect oscquery)
> so the issue might be either on Score side or in between, maybe a firewall issue that blocks discovery between 2 softwares. (I did allow both soft to access my private network when Windows defender asked me)

I checked with a Bonjour browser and with latest ossia max master build it does not show up

**Comment by avilleret** [comment]
I did the same with ossia-max 1.2.4 and it doesn't show up either, did it on your side ?

**Comment by jcelerier** [comment]
can you try that one ? with it Discovery seems to work fine on win32 between max and score
[ossia-max.zip](https://github.com/ossia/libossia/files/6473742/ossia-max.zip)

**Comment by avilleret** [comment]
ping @matcham

**Comment by matcham** [comment]
seems to be fixed, thanks :-)
