### ISSUE TITLE
ossia.parameter do not output default value when @clip 

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#724]
When @clip is set to anything else than free : default value is not sent on patch load.

<pre><code>
----------begin_max5_patcher----------
421.3ocuS0saBBCE9ZLw2gldMRZADvckuGKKlBV0ZJsMkhyEyd2Wo05HSMir
K1MbN87+467wk4yhf0xyzNH3EvqfnnKVKQNaCVhBFhfsjyMbRmKP3NtTz2Bi
u5ypK6Mbpw4MMXVQLMGXh8azzFiuAUYInX.FiFDKceSSSPf2B4rSpaItfKBl
7k17gh5qADFCf0Dwd32ooHZRK0P0anBRM2EIJ3js0Mzx5iKxFOyLQXjwNieN
e1fzJhmLRHnuaq6spZnmcCOToYBCXsRp5U.7SPJzuiT44NA5AP0n0B+esVxt
NFI4FZC1SXBv5szcjdtAr.mBVqsWFpUEg.Hv5FNSApklC+YxRYwv2rR78HvC
YFiXEMRtT6cgRvoKyWEaUJWUfJqFzpVkiwVM7Sf0zpogq9jgbl3tejbq0fie
f1cxdcSXrC8BLZL1R6LLAwvjhQQk4C5420I2urozN7Ca200knTmn5tqY36jk
EczC4Uw92Lg+s+PC0zSrPJd5OjnsGdi8p2qcCH7bQN7Z1xsTsnmE.8gccn0N
hpvxA6TD+V4HzymYC3K.y35EvA
-----------end_max5_patcher-----------
</code></pre>

**Comment by matcham** [comment]
consequence : fm_synth model (used in several example patchs) doesn't play sound because it's gain default value hasn't been sent.

**Comment by avilleret** [comment]
this is indeed a bug, thanks for report, 
quick workaround : force default value to float by putting a dot after : 

<pre><code>
----------begin_max5_patcher----------
425.3ocqSEraiCBD8r8Wwn4rqEX6l3rmx+wppJrCIkJG.gwcSUU+2KLX21zt
a1rR6EXX3wLyadCujmgclSxQD9A7SHK6k7rLxUzQ174L7n3T+fXjfg6GL5oi
XQ5JqvINJ8R28RsnaPFgvluK.SoGjd5c7Ym6MtiBezypOfYl7K3pdOv99GT5
C26j89T80VWxJ.NmE2tkVqpJYvcyOQsiJPS2i2TuTeoH6e1JSw.wB.6D5CHb
WDwq44wkhqj7Z4uBgeI3d4IpzPqSo8vVqwNYANdI9eNaY+U11zParKRWN9+i
KlwQkn7ccENHTZX6N4dwzfGtgWUBacgFnLXyX.C11OnrPmw+v+.wWj4dyfwk
HLqjWcaylhfw5MqXqaiVsaZ37fE+SD+O1rVuJtV2bwdUU6EmMNetfB.Nnze8
OBUCQ+m2fGMSt9kvsjM3i5XmbzqzBuxn+Dn5DleqFdsIp9JxC+a4IwOg09jz
MNClRQXT4wjvzVPGU5zQRNQm7I0BdNMDiBWPT7AEYxQ0EdZUCldqYmzomTD3
7H6B4jlC0gYrQqHQDZbM+072.LZ0TnH
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
not an easy one, but should be fixed :-)

**Comment by avilleret** [comment]
fix confirm on Windows & macos
