### ISSUE TITLE
installed ossia.hpp is empty, is that ok ?

### ISSUE THREAD

**Issue by avilleret** [ossia/libossia#730]
after installing, my ossia.hpp is empty

here is my configure options : 

        -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13
        -DOSSIA_DATAFLOW=OFF
        -DOSSIA_EDITOR=OFF
        -DOSSIA_GFX=OFF
        -DOSSIA_PD=OFF
        -DOSSIA_MAX=OFF
        -DOSSIA_PYTHON=OFF
        -DOSSIA_CPP=OFF
        -DOSSIA_C=ON
        -DOSSIA_QT=OFF
        -DOSSIA_PROTOCOL_MIDI=OFF
        -DOSSIA_PROTOCOL_AUDIO=OFF
        -DOSSIA_PROTOCOL_MINUIT=OFF
        -DOSSIA_PROTOCOL_OSCQUERY=ON
        -DOSSIA_PROTOCOL_OSC=ON
        -DOSSIA_PROTOCOL_ARTNET=OFF
        -DOSSIA_PROTOCOL_WIIMOTE=OFF
        -DOSSIA_PROTOCOL_SERIAL=OFF
        -DOSSIA_PROTOCOL_JOYSTICK=OFF
        -DOSSIA_DNSSD=OFF
        -DOSSIA_STATIC=OFF

**Comment by avilleret** [comment]
seems that source file is empty too, I thought it was a configure file

**Comment by avilleret** [comment]
@jcelerier what to do with that ? could we remove the empty header ?

**Comment by jcelerier** [comment]
oh I think it's a leftover, it can be removed. Doing it (as it may need some grep to remove files that include it as it used to have some stuff in it - it was originally a header to include all of ossia but that just caused too long of a compile time)
