### ISSUE TITLE
ACCESS attributes for all Minuit parameters are now BI

### ISSUE THREAD

**Issue by bltzr** [ossia/libossia#737]
I know it's pride month, but all access identities should be represented :-p 

I noticed this in score a39 (with Jamoma patchers)

**Comment by jcelerier** [comment]
can we agree to deprecate Minuit and leave it as this ? <.<

**Comment by avilleret** [comment]
yes please

**Comment by bltzr** [comment]
This means I'll never use Max again because I prefer investing in porting my stuff to some other environment (like... score plugins ?) rather than porting my patchers to ossia-max.

So be it, then.

**Comment by jcelerier** [comment]
I mean, the parameters being "BI" does not break anything right ? It just means that they show up differently in the score UI and that operations on them are a bit more restricted, but otherwise it's functionally the same

**Comment by bltzr** [comment]
In my workflow, that changes a lot of things, because I’m using SET parameters to exclude them from the cues—which I batch-create by dragging the top nodes—so that will mean going in the states and removing every SET parameter by hand. 
But that’s OK, I’m tired of Max anyway

**Comment by vincentgoudard** [comment]
@bltzr Wouldn't opening patcher as text => query/replace do the trick ?

**Comment by bltzr** [comment]
I don’t think that’s the problem but thanks for the suggestion
