### ISSUE TITLE
 [ossia-max] corrupted namespace when loading models with dynamically set addresses within abstractions

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#740]
Hi

I am observing the following phenomenon (tested with the latest ossia for max package):

0. download attachment
1. open main.maxpat
2. press "expose oscquery.."
3. open browser "localhost:9876"

you will see three nodes under the root (1. slot, 2. slot, 3.slot) that have no content.

if you press "namesapce" inside the maxpatch, these nodes don't show.

these nodes are created inside the "subModel.maxpat", which are loaded as abstractions inside the "abstraction.maxpat", which in turn has its address dynamically set.

these "corpses" of nodes appear when attaching the device to score, and thus they obviously are cluttering the experience.

cheers

martin

[ossia-bug.zip](https://github.com/ossia/libossia/files/7091333/ossia-bug.zip)

**Comment by avilleret** [comment]
I got this :
![image](https://user-images.githubusercontent.com/504914/134810050-faa00e43-6984-4747-a418-6589763e4f6e.png)
with 82dc72ff on macos
and this seems fine to me, so I'm closing this issue, feel free to re-open if you still face the issue

**Comment by maybites** [comment]
I can confirm, with the latest [ci-build ](https://github.com/ossia/libossia/commit/fb9de4b95b7135fe9e4fb22e592defec4220cfee) this issue is resolved.
