### ISSUE TITLE
[ossia-max] latest ci build breaks patch that works with v1.2.4

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#742]
Hi

consider the attached patch:

[subAsbtractionBug.zip](https://github.com/ossia/libossia/files/7109405/subAsbtractionBug.zip)

0. download zip
1. open main.maxpat
2. press namespace

the [abstraction] - object contains a [subAbstraction] - object that contains a subpatcher that contains a [ossia.paramater] - object (enable) that is not being detected by the device.

with libossia v1.2.4 this parameter is detected and appears in namespace.

cheers

martin

**Comment by maybites** [comment]
this might be related to https://github.com/ossia/libossia/issues/722

**Comment by maybites** [comment]
upon rechecking if this issue was resolved, too (which is no the case with the current ci-build) I got confused by my own bug-patch:

the [subAbstraction] inside the [abstracion] is a bpatcher with a white button, barely visible inside a locked patcher...

**Comment by maybites** [comment]
Do you have any plans to fix this one? It keeps me stuck with v1.2.4 because every other release after that one is broken.

**Comment by avilleret** [comment]
@maybites could you test with b08724fc ? it should solve this issue

**Comment by maybites** [comment]
It indeed does solve this issue.

Unfortunately my SPARCK app is now hanging with this commit... urgh...

**Comment by maybites** [comment]
I compiled v1.2.7 [528a3783f] and while it doesn't work, at least it doesn't hang my SPARCK app.

**Comment by avilleret** [comment]
> Unfortunately my SPARCK app is now hanging with this commit... urgh...

Could you share it ? or could you build ossia-max in debug mode and break when it hangs to know where it is ?
This is pretty hard to debug on my side without a minimal non working patcher

**Comment by maybites** [comment]
I totally understand you. I mentioned it in the hope you might have an insight. 

But the issue has moved from parameters to view anyway - there is something else amiss.

I was able to avert the hanging by adding a [deferlow] at a strategic position (While setting my parameters on startup I was also loading a view-abstraction of the same parameters. [deferlow] makes now sure this actions will happen sequentially and not in parallel). I guess I could simplify but it would be tedious and seems to be solved. 

But I still have an issue when I load a view-abstraction with dynamic address setting. But this is another animal. So for the time being this issue can be considered closed.
