### ISSUE TITLE
[libossia Max] feedback loop ø.parameter

### ISSUE THREAD

**Issue by fxw-fxw** [ossia/libossia#748]
here is the patch...
Maybe a message like 'set ' could be usefull

<pre><code>
----------begin_max5_patcher----------
564.3ocwUFriaCBDF9r8SgEmcs.hSrSu0qU8VusUUQDaZBqrAW.uMQq12qdu
uXEFrSa1c8V2ropWvhgA9muggw2GGg1pNvMnj2l7ojnn6iih.SdCQCyiPsrC
UMLC3FRx+lZ6snzvRV9AKXtQwp2xj6FWP12p5sMbKrKxfUQM3r6.dCczyfa1
ic7PXffiI4yCK2wrU6Excaz7JavCBYQFNMoXkebYoejRyvm1hSag7jzdaODG
6GRmIisbigsi+DH4G5TFdhxT80dt9XBgtHOYcYwp4SMdRreQjWCTRngOqHuL
yzKf4ItWUFifkUyuSTwSt4c2LaRIWFnDLEPrL7ASt92tlFQMWOaPVrFcJb0r
Vtkq2vkrsM.O3KhxbbQFcYZxBxRfOL.aN9+IlEWeLIkvCUZd4+LJmnr8GeOC
vH4ieX5r.8YxB4SW1l9Gnkthl4tSokvc55+hJWvCTiP93VwfJd6mmALpdc0X
bMF1I+RnZtwJjLqPI+cmJNyIk1mXlLsOWooyPYeWOuSuNgvyPIxUPn4kLW+7
IS7qS5h4Hc9SfLT.w55tiqMCdCh3drbqBBrxTXpPFlB09Hsqu9n+vSbDS6Jq
stZ5dMDXnCqBOIPsJGhxdwPIiCOmjF6wlGWzJccOfs9dVqpksYuXmi8c6s75
MJs6m6C+X0g2WX8M1yyIrpJtzVoZBwoqIh+cD1+xJz+H6D5oC4VsaCPf.pNb
3stSVLdiLlgf9F93yzwBIdn8R7Cw+DfvmrgF
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
Here is the problematic part of the patcher :
<img width="313" alt="image" src="https://user-images.githubusercontent.com/504914/161921204-418f7963-11d3-46e0-bbd9-c965351ad915.png">
With such a design, when the `slider` value is updated from the network, `[ossia.parameter]` outputs the value which then goes through `[pattr sliderP]` and `[prepend set]` objects and back to `[ossia.parameter]`.
The `[ossia.parameter]` then try to send this value over the network which is not possible because the mutex is locked.

I got the exact same behaviour without the `[pattr]« object : 
<img width="172" alt="image" src="https://user-images.githubusercontent.com/504914/161924817-00812113-fe1e-4d91-9d4e-b14dc0bd6244.png">

When used locally, there is no issue since the `set` message avoid the repeating of the value at `[ossia.parameter]`'s output, thus breaking the Max loop. (But the value is sent through network).

**Comment by jcelerier** [comment]
thanks for the investigation ! I wonder if there's a way to provide an object which would have a behaviour equivalent to this subpatch directly (parameter -> pattr) -> set.. what do you use this for @fxw-fxw ? is this for some kind of preset system ?

**Comment by fxw-fxw** [comment]
HI,

The patch below works for me, but only with libossia 1.0.4 (2020/06/17 - OSX).

<pre><code>
----------begin_max5_patcher----------
1957.3oc6bssaiaCD84juBA+riAuHRJ0m5ts.KPwt.EsOTTTTDPay3Ua0ECc
IIaWr+6kbnjhjsiijMSZ1VYfjXKIxY3Yl4LyPImub4EyVlcupXl2248GdWbw
Wt7hKfCYNvE0e9hYIx6WEKKfKa1MwYoUIylaOk9sQowpR3b3GNXVUYyQI0Gc
qrb0GiR2bctZUoUhDJdAZtGQDZ9CCAefr.48m0iwNMkedqxNfYyl6MaoLcyr
1K4lr7DILe75iDsFTzrke5JxrVgmKSTkp7qUoxkwvzgLm5qWdo4WyG3pOUcm
ddal0R08fjmsMWsUkt1qPUNBjAeLjAsHvWvEXJNf3Ghvz4dXAdAly4TQnuvO
v724dBx.Ps1S0Aa7ErFccUVbVt8ZQKB4H87SCBI9hfP+4dfYA9E1HjyF0tUl
mpMFvYhuMdevTVVl6oOi22GkFUFIi0ReDvJcjvJgHVDZdE3yPZeQBkqWpH5v
7FgeNL9xaT5B4sp0WqOnVQt1r5hVVUZC6tnExzC1tZaLDsB9Qbe2+jIxsa64
caMTNxIOqnHRtnUZVKjAM7zbBxRWQIbHG+PMAg9EV6aRHTeBGahFFpE5vVGw
rNPCbIyhiR2kLDTQyw6iWEYU4qZDRq016AMYspnLJUVFkk14pH8tlr70p7Gm
IxshFB26bUIQq2lEkVVudI9nEz8hLXg6GYPH3y4Jwbz9jXGT5G3J2G5vmIzI
FDzUCvmorXCRVh8jk04TGaeqJun9xAwnCa+jk3NXN7wnT6Gg.rY4paiZtd6Q
j453sRcvVUtk+8dt+L6Pyz.ZZUTMlpWfZQVT943cCHZoteS05nresTVVUb8G
ToU13e8x5FYUbYevX4lahhiaSyzkzqIXsNITCoVuTRjPeLNvjDhhoBBGdm9M
Ll1K4AVRXL3lA4yz9QDyk5yIBeF7t.BkQm2mbEFF4AYYnY.IfBCP912oODtN
+WyvzUgXYZIBSxwFx37rsY4MFU8PCau9pxrM4x0Qpzx8InmW6KkqOK.6.lTi
oIZ.MpYLc885aLRht+bMBsJ3gwTpf6Kv.jD3Sw.33uCtbhv4NFbGaDbIV+iV
v0CieaV7ZueNyjxI5XH+MYZAE820rA3NkQ4HU4C9u+ojeyXz7LuI2TSkQ46V
F89pX2rzFBtAahzovYteENTjdbqTzqvU5U3o33iFG2wTdirIKKtmIdWufi6p
6VKn7dwPbVmLjtgP9mjIYIxq+XzFcv6lOVZ50JWqHpiA9xUqzRqyhDaaykse
utmo5ocG7vDueQsoJVVWgyoOaxkEk4xU.VdTeqd1u.tOiys7UTNBJAJ.KvDV
O623hb5RcZ5RDj30QolxTUscw9HafvYBC5FnKyReabkZDn.EaBWL5Bus3vv5
HHWqZ+bU913Qob55Y8CMpjoMWQfsdUcoqLWpb2DWU7wGwGT2RXT81oM3o696
t9N4sJyvFi6HFrDHVPaA4G5Psezz..oumZu4Coqu2vKQCIXFG.QDvXowQeSO
Cv7Q5Nc19IBeHogJVkzmQPSFzcNH.0.qqZR.Qw2W5zf14sPOwP3ZeqsUIZlK
vXWOAAP6JXamKceIFfivSwE9zlzMwYK0EMkOByIWqmTXcGPvBgvxy3yBoCPi
y8pkXxm+grjjVZsAqoEOh6bwIOweZ4xo71Cs.rgltHzYbX+UQbzZU9uY1Jii
Ym1M4due4HcIN5V0B6N6NppMzTOP3OvezZjZX96RzsK0YHMf.1w.dPfcaMBn
bL5a0L4wYx0vsz4wSJYoPG7Ll7LrUT3QVIkaBeexBVb8lQ8slyShpnPtQ8tb
kJ84pq4SyD15vf4LgukpWmmjAo5w5b8fwT3+eq8gr1drwriKuFMFP8VvvXlZ
sfPKb6d47eNqwtEz6BxU8PhRc67kU4XEr2PFZB4glYsWB4CUXwoPhR9WjD0d
+dM8RebJzCfYuLcT2QAIulUv7r6RGMD9fdwZ2A.5yjF9CeVNdEDQBY9.2mPP
oDQcedXL08J3.RjeHMDPOp4EPnCsP6dk6C5LaokxQqdA9Hc+wPXKGoUN.J4g
3Pl60weWEGmc23UQBCCFVQ.N.xEhXZq9A5onOmEKDgBdNV.juEW.UIKU4uSW
6ynw+iUWh6bQxFwMoD8TR8DRMm0hKm9Rn0y3jmhsiN7ky67Xv4yBBDtqhfge
2IeoKKXqb0e4tcJdazVk6JxK26pqtZ2M1aP67r.CakrtJ.FCY23MNIjSHeiV
7VejX7DOsM+3Ca8Ljbu6ccX9KGLhdEAinIbzE3HYBFcALRmfQW.i9SvnKfQ1
DL5BXjOAit.FESvnKfwfIXzEvX3DLdhvn8g03kb6cerZ9Gt1N0AJ.FSnfFEr
OTJu6Iuymiae+NzS61Y83VM3ETwouEKLD0uKQF7Htv3z9qIGYgJF+y2Uw4sm
IG61ML+rfji6s+R6RWbd8x++TXhNASCAlFcu3sOmjX3osEzu5GA2mcr5UTgR
EmWu3+O0aiOASCAlDSvzPfofIX5QfoSusH62yBaQsMe8GfNheEU03IrrDDD2
lrByED6CAR.BZ3wc3dob6H9Rw9dYYl26Me4Pl4J4mKSKhkkN7F7Vk9D294iM
e1+gI.+CMwLgEaq+NhB+eO4xud4+.sJThX.
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
@fxw-fxw could you try this https://github.com/ossia/libossia/suites/5951824853/artifacts/204240881 (on OSX only)?

**Comment by avilleret** [comment]
I've inserted a gate like effect in the code to avoid trying to send a value during a network callback

**Comment by fxw-fxw** [comment]
It works well ! 

but the Namespace is completely disorganized :
I use instances of poly~, and instead of : 
> model_A.1
> model_A.2
>...
>model_A.x
>model_B.1
>model_B.2
>---
>model_B.x
>model_C.1
etc...

A random organization is displayed :
>model_C.6
>model_A.4
>model_D.12
etc...

everything is there, but it's not easy to find your way around !

**Comment by avilleret** [comment]
I'm sorry but you lost me

where this namespace comes from ? 
from Max itself ? from Score ?
