### ISSUE TITLE
[ossia-max] FR : ossia.parameter @mode BI @exclude 1

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#752]
Sorry to come again with that same question (after this has been discussed in #624 and #713), but I feel there is a missing case where one might want to have a BI parameter and not store it in a preset, and this does not seem to be possible currently.

A pratical example would be the playhead position of a sample player: I may want to get **and** set it from the GUI , but I would not want to store it in a preset (here, I am not saying that it cannot make sense to store it).

Anyone think of a pratical way to do that ?
And if not, can that be a FR ?

**Comment by avilleret** [comment]
what if you store it but you don't recall it ? with `@recal_safe`

**Comment by vincentgoudard** [comment]
Could be... I cannot test it because it is not there in the latest release v1.2.6-rc2
Is also @recall_safe preventing the value to be sent to the parameter internal memory ?$
That is, if I bang my parameter, will it output the preset value or the latest value it had ?
(In my current situation, I would want the latter).

**Comment by avilleret** [comment]
`@recall_safe` is available in [v1.2.6.-rc2](https://github.com/ossia/libossia/releases/tag/v1.2.6-rc2) maybe it's missing in the XML documentation. @jln- could you check ?

This attribute prevent the preset value to be recalled : the parameter value is not touched.

**Comment by vincentgoudard** [comment]
OK, this does the job, as the value is neither output **nor** sent to the ossia.parameter internal memory.
And indeed, it's missing in the documentation and does not show up as a possible attribute when typing the box instance.

**Comment by vincentgoudard** [comment]
Closing this one and opening another one specific to the missing documentation on recall_safe.
