### ISSUE TITLE
Option to make ossia.fuzzysearch case insensitive

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#762]
It seems as if ossia.fuzzysearch is case sensitive. Would it be possible to add an attribute to make it case insensitive?

**Comment by jcelerier** [comment]
I added what's needed in the C++ part here: https://github.com/ossia/libossia/commit/1c07c9c8fdc9668e6d8487af9f19a58f3060a080

just have to make it into a max attr. now

**Comment by jcelerier** [comment]
fixed by 69f51632be0e9ebe2d20072aefb44f06831bec53
