### ISSUE TITLE
[ossia-max] always exclude parameters @type impulse from presets

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#764]
As discussed by @bltzr et al in [#624](https://github.com/ossia/libossia/issues/624#issuecomment-731762449) and [#595](https://github.com/ossia/libossia/issues/595), parameters @type impulse should always be excluded from presets. As of 1.2.7, these parameters are stored with a value of "bang" in presets. Please see this test patcher:

<pre><code>
----------begin_max5_patcher----------
3224.3oc6ck0iiiaD94d.l+CBFA4oNMDont1m18sjfDffcCxKCBLjs43VSjk
Ljn6omcQ9uu7zhRVGT1RxZ1tafw15vxU8UGrXwh07ae7COrZS1q3hUV+f0mr
d3geidlG3miclGTm3gUGhdcaRTA+FWkh+Z1lur5Q40H3WI7yez5XNt.SJVSx
VSdkr9ywIzms59ROcHNMgdY1Maqc1rSD0oApSGui+Ho+N+Ej24GwwHx1miS2
uNGukHHZG6mrezBD5xeCBYuwd05+p9RhGO4aGwhuwpUkWi+.w4RtUwtOrhQ4
ufyKhyR0IqGVEc7n14eP+KwPoujweVAOVdt3Tw4fkmKG+Rr5Qnc5nbJyQnb1
obNot5UOzJsmT1Nbd5oXNAIO6++ie3LowEPoQGvEGi1Jd.LA44qWhYv.PHCm
B8Yu54DvdC4GngZTkf8IYa+e3c5RKJXdDmFmxkyojHhjIJu9N7miNkPE8Yoj
h3ekSF.lPooa3yR5r4qxXENW7S4wQIk7w973cYoLBoB9wOu5m7SV.gBgaEdh
eKoQGa5qSU0n.T0qVRXETl8TwlnbljaSBt52kjkkT8ZkZLI3OSjW+XbZZc.k
jcriqlGu+4t91axnW8PmOd9kJVeJUb40TsDx5hnWpg7jnjDogcsegWiRiODQ
vjXg7.ZWdUbZDkgetXadVRRU9VboWZ5R6n5+aweMdG4Y9OVE0C5WH9nRwZUo
XeW7dbAo1IIQ6KpcpBx2Dh.8ycZizReMAe3XBka32A9knz0k2F09ItfT7b1W
Kj2tRGrBdT5urh4uteypWnl+ysYGNPsdJMs0ch9y3sTIgE90HJchsxxsNUfy
snFFwTomxCqUkubB8RayNkRp5PgQQm1TWg7BWwUtRECu+QDIy5mw6OkDku5x
GaQ7N7E+hU8maqeIMe5NnJOul7q6e1.l9pO2utGR2ZVAaayRDdX+DUSx4QsW
.0u817JUxSrG3gn78wB+91muApmV0mYNcmFg+ufIVLz25OaQgjmsnveAIKGK
E6euKzc5SnKj1xgz89CiLuZ.SUE4QaJxRNQvL48JyDWMGxzEnMnWSLowkC+M
+vKBcp0vmFcDhFzRQzdbyPzN7gr0BK.3Sz3JaGlfWALY2GLgfb8wPgVosy2A
vDXzgIXngZSKAXpK6MJ.QCtSMPpURVztQ0rC50GPAAbHR9F.3uPQpsYoeNK+
.efH5WxZSVF4pfJXaPkqgPEHP7lXfASfpGsVEyFYb7QrMmnQbmVivyoCdRnA
WJh48hw.uYcJaCAJgwGDodsGXZST594VqhM0pcz4ykseT0k.AlpKI7l6EN.U
o6ANM8VeAlEMFvOXwX7M.G67Y3NlFg.Wyvqp5YKR+5G1Pm6f0+5m92+UqqNP
gVMDQFpV4hDAJLDCw+n3PG.LCj9NveNyN6F7m6zBBYpyIA13ELDknIzit3G7
pPh1l0LxT+NtZSdl8ZUnPk2gJIFi+SktC+pdNkqiFZ4Okkyg1R9EmvX2PK3T
Q1o7sJ4fxHvpFUtCWPhSOmW4OcVYfcilKsFNsfLkVfy.wDXLw3N4DCK1SyHF
vziLJ90.jwa5IFiESfYPLEZJw3.lbhwwdnDi9cdHd2wLZ.jEpzuD9jKadxAO
Aou6P83e9vokK.C0LrCtPQ1xQp.gmOZR4AyUQQSuaMiMdQyf8h2PIlNDtRwI
D4HCTScPqrf5BkqeqHPp0hUgbcDgjGSiLULZakkldfqP19jrMQI0VNqFWAsy
TD+Cx2kv8sVX.G91u7sTxy+mX7WGT8.X2P8.bN14UZqB.fg71OA8f9HW6v.a
mPHvicpPnKJzFD5Y6Gfb.UWgfFy2qHe3HQD3fKKnf2lEMfimnbA.1R3giL.j
+6UMv6UMv6UMvjW0.2i7T326h9XWNmykcZmoBonmxwGxHX5nQ+sCGOkTfm2T
VHfIO4ZYDNvTVbePrWniXqF8dbSmpYnkbzF..cyYScpxig+xIMFFGtue+SXg
GRa.prHbz+rvV2QF166A5VOP2+IMrqjaNRW37DoqLWyAuGoqT0GI71.b3XMx
1Sbz6Q59djtuGo6zGoamU4DO3wwrxlBMa4UDkip6RcQcEQqcdBAkg3Z8iLpx
Jtg.dauBRu4ZKvz0.V7pXRDd2sk.tefkM3Rx8INXIHIiCF5rXiCFZZvmrkp.
zcBU4oP0Cxd00U842XAYVqRw0pRbsRBuvJN0JxZW71xarQ65U5wjrt4a4xBG
uY069KXbCBt0oys0kJzT0z+3tHPg5AmZdcf2VMf2U8eOpRL4l5PIx30z+tua
kbPeSjbA5kA0RWx01D5XkGrdDGsfp8uIFgntvLHRKOZd1FrGF0yg10vvL0Nd
xcFDm0j1PXWLlafaIK4HK04.34DFbMjdsvCKEV43ncVZUAewSeonLioMGnnA
hN.z.Qmb2J0PV8Zen4qg4IQaJY7nMxwKWIK6eV.RxMJQ4GcpreWaOiwFoA3z
D.4zI.IpKI0Nz0GbQVhuDgXkOZszdNpooQVpn4b2x2rsMvy.9WpmD3+VTAw2
DED6kmBBef5aW+HzD1WLKHg+xIT+nuMu+5CQoTuq42dLIl.WvlFpzD+sPAPE
FdwTGadZirw6njZT92dyu6+AtN7cVobr4.watt1umdy2Su4apzaN6Y1rqDMQ
r1XkLt6Ipd2JFpXS7E9TEKmGzrEv+NjKtwGh5M4un.4rwzJt96LBMA6wf.CU
Tb7rus8X.bd2RzrYDNpKV.n2VXfL8GJEFuE55ETfSrt5kRoUGNPCQGYr9dnE
f4TmJPeMmFR13pA0aB+cce6pA4aH3rjTfLYSo1idzUrtQ81lA7r0G4JXo2OF
tvU8su5jsAcHCGzG3IlYjmoKO4b6cZaBtVO54V8Ng5c7M+piucOadE2iJhE0
q6aYYxCgdK9hhUY6s+JCmr0dpCzzId.0pshEnyI1DNt1ob3b08kIUlPkazhg
Nmi6VvRr1t.UiJIZK15OAl4tzDnxxNFrTiZ5WSrJRho.DXTiaBZPwmaqMCNW
+6bWWnKLhu1jz3kxm4FyjDhPR6tvEeDSBSMBKuXiJRYXs4K8dub6zIbEo84Y
mNNtkrkgaKFouHOSC8txZTL6.0U4OB0FD4YZFk.psYo6PwnGqr2Xz+V8T7W0
foGVgOroVhyMJXR863PzwimumxaQS3Mq9FJF4H5.82AxDKijLAO9nEpKApy.
B1575jIauphBAvZGlURQ7oh12L18aGC8aACcGx9CyENzVZyE+atC+qbwGG0H
+LbKHJdy+dllCNe1NyaeEiDa3.Mc14e5n+2eicFnE0ZXXXPKxb6L9sIoIaIL
Nj8x3Oep9mu.ReF5ddK5seIvjxNe56HPFuSPASeO3g00RbGmsBJhFAqm9eAd
zH1bD4FkWo9gNOM8biiQMTnf96VKgHUCsj0OgbEMlG1QSNK.MhEf8yB1gOAz
kHt9mYHn2LxPfQpIOw5ieN5+ACUpXrs98bohYlwq+rX7hLhV5WWwwO3o.cnE
fTPKBMOPKZH6LH6ouodYlYnc+ZsNtBSMQGxEgNezzyClY4Yfgmq1RcAt7.Ys
AI2p+91yAuMHyvtXN.RS9HXgYP7Xb2uCNCshOigy4oeIBFRyarKuZHe9n2BG
YN1gmOZgz13.1SOfZJsL8sSOf+BRmG3MvNxRWQZIhlxAIRGi1QSOK.FR+nsK
dHH3x32kbjxxY54HnobzLzIJM1xA3L8Di8.cQ2yTanRSjm1.dnIuIiZdibto
1rbMVPNiRnqtAG+nokGbFQdPFW8byCvwTNHC3alYAG3Bpg05DLl3o6cQm.Ml
5D91dBpNTKQC7ilVdXLsM8uO1ldiHK3YeWrMCMc.bS7xaaeuXgQyIevcQJX9
+SE.7LN5V4+asoczzyCfwhG7kq9k47f1RQv2tXssVDm2Bh+8nCYGhV+b7dJe
t+YBq5BxiRqrlMpMuXKfPz1s3Txk8wO2GsDqgWc58Qc.Nm9caXmswPC5OYbk
pN3MWWWTzhlD6pP0tXVunnt5MtseS8eQ6m.r9rHSr4ya0hrOEDh.ff963hpN
kq84NJ3UrYuE2b0UQShf0MEU33kwJVMPKiVanK6RSh4NJqwYNyT4.nfAkgRJ
5ehsK8Ml18MgzqyfMGdqpYCTdznPgHuAftivuGr5jq6N65sgHhs+oinoW5JP
lpGIJIRW4jLCGIvBhLArTyYeD9AAgifBjZY1BPZZP7iFGZz2DIJnGQJxVjx6
PsgF4GMNzn23giPYk6nrDcFKZzwHbzyDbDB0wQ9QiCMBGCbTC45AGkieTqYV
vIu5Mwh5MvhFZdEcz3JtnoUHiGoslUwG+.8F9cr27QmO
-----------end_max5_patcher-----------
</code></pre>

Steps to reproduce:

1. Store a preset
2. Load the same preset
3. Check the stored values in the [dict.view] on the right

**Comment by jcelerier** [comment]
I'm no Max expert, but doesn't the issue come from the preset_manager subpatch ? 

When I click 'preset 1' to store the preset in a dict, it sends the 'namespace' message to the device, which asks the device to print out its entire namespace, and seems to implement its own custom preset handling with what is returned from that ; the saved preset files themselves don't have the impulse nodes at all.

**Comment by avilleret** [comment]
I confirm the issue is not on cpp side, the Impulse parameter are always excluded from preset as well as those without bi access mode : 
https://github.com/ossia/libossia/blob/master/src/ossia/preset/preset.cpp#L1283-L1284

**Comment by evanmtp** [comment]
Hi all, I just tested with this patcher and the "preset save"/"preset load" messages to ossia.device, and I can confirm that everything is actually working correctly according to spec. In other words, parameters ```@mode get``` or set are not stored, nor are parameters ```@type impulse```.

I think there's been a bit of confusion around this from our (TML's end) in terms of the two strategies for storing presets that are demonstrated in the "OSSIA overview" patcher's "Store and recall presets" tab:

1) storing preset data as a text file using "preset load"/"preset save" messages to [ossia.device].
2) retrieving addresses and values using the "namespace" message to [ossia.device], storing preset data in [dict] objects, as demonstrated in the [p preset_manager] subpatcher (as you may have noticed, the subpatcher with this name in the patch I pasted above is just a slightly tidied up version of the subpatch of the same name from "OSSIA overview."

As of my testing over here, method 1 behaves according to the spec, i.e., does not include ```@mode get/set``` or ```@type impulse``` parameters. Method 2 does include these, but that isn't surprising - it's based around retrieving the full namespace via the "namespace" message to [ossia.device].

So basically, everything is working as expected with regard to presets! I'm sorry for the confusion around this. I think this means that we can also close #760. I'll make a note there too.

The one outstanding issue here I think is adding ```@saveget```, ```@saveset``` and ```@savebi``` boolean attributes to ossia.device, in order to allow users to choose which modes they want to save, so as to facilitate some of the use cases that have been discussed in other threads. I created another issue for this at #770.

I think there's also another question: do we want to facilitate a similar method of filtering which parameters are stored when using the "namespace" message/[dict] storage method? Perhaps with additional arguments to the message, e.g. "namespace get set bi"? I also created another issue here to discuss: #771 .

I think we can close this one, though. Thanks, all!
