### ISSUE TITLE
[ossia-max] boolean attributes @saveget, @saveset, @savebi for ossia.device

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#770]
As of 1.2.8, [ossia.device] only saves parameters ```@mode bi``` to presets. In order to allow for flexible approaches to including parameters in presets (e.g. @bltzr 's comment in [504](https://github.com/ossia/libossia/issues/504#issuecomment-505881487) ), it would be useful to have ways to allow users to specify which parameters should be saved.  Per my comment in [#760](https://github.com/ossia/libossia/issues/760#issuecomment-1046044142), this could be set at a device wide level by having the following boolean attributes for [ossia.device]:

```@saveget```: 0 or 1 (default = 0) - choose whether parameters ```@mode get``` are saved in presets
```@saveset```: 0 or 1 (default = 0) - choose whether parameters ```@mode set``` are saved in presets
```@savebi```: 0 or 1 (default = 1) - choose whether parameters ```@mode bi``` are saved in presets

**Comment by jcelerier** [comment]
just added the attributes, they should be available in the next nightly builds in a couple hours at most

**Comment by evanmtp** [comment]
I see that they're available, but I just tested and they don't seem to be working yet.

<pre><code>
----------begin_max5_patcher----------
1516.3oc4ZkzjiZCE9r6pl+CTb1oGjXwlbJIWlK4TlicMkKAHaqIfDERzKYp
je6QKfYowX7zX2NSNzMF8DRuuu2hdRv29vcKriXOi41V+r0CVKV7MYKKzsoZ
YQcCKryPOGmh35NZuMkQKyrWVIS9aVoHEKzRg0MmiJPYXAtXClhhRwJgN0BM
Of3kbrYpssWZYGgn6rs9RceHI5YiE80eJ7vjskUjgDJAAMSjHdOgtaSANVXF
N2.m6cVZAB8UW702.g26zL3RklPq0Yftw+9C2otJurbxTAE+jT+NncB7yBiR
y4Dz8E3Ll.ak8xmegJ1+wrW9MxQXM2QIF8eCRL.G6SSCPnlF.9qtX7v02k.3
+c5S.cts7I9LVL2NEASvo.XX.Pf+ORNEq99bJ7twxS7oY2m.NAWhUlzDAAWc
ZH2JikfSOBlcF.OdSIu2ZiYEbB73zYnvEUHnFBReIRJ9QbAmvnZ7urV.JOuU
6KZ+PJj+UldrVuroMB0zFrosB7ij5gnUynBIrDRLUVnMw1OGb.zpQRRXEzRR
iAwXKpUMMoSkQV7bTrY.TFmCxaXq0dZytKTcIvyDPr1oEcIsq6RYw+INoMcI
8AywTBMu.ywTARTggF4I3snxTwlsLpfS9KsV.TSyPcXakZNrTERzf3WKHnzF
XrqfjvnJEoC8oaudJePlryjxqClzcghxG5wktXR9oqzFEiKAaIOBUnLbUorZ
dVAik1UViCSJdqnRdNgR6SnBV9HRKH61O1SGwjRyFc30h3aJoFwajNIhMbzi
8XdAJMsJVs2L7LhRj4UwBhwd.cZjZxeumGWvRS6hainGGRThz8OF+DIQrWOY
cbOjO.Iu1wxtwrmP1g4hdMJP638ZhKdwXBZ2VYTUf9FANKOUhFcOvOhnaZ5l
L7gvE78rm3Ucu1GrCezT7bmn+1oB6JXzThCs5vgEHsZW.4HKoNx5CMt+GKe5
wxoZBgpVh.95hFN1xDKZVpnNE0UhqZUX0LSVtSirLUUTkX8Fmr9zEirfSirp
9uq6MJYoKPotDsQnJv3T0QoIvToopcw7V3oVKBlRn0Yvr9howlpHrUqLjrwr
X3FjPTPhJEl92o.oyLQsrXhHTZurpClH+fFcgp71r3i0un.5Nrvxw7SdyOiH
VfiTWJ330hO7tSFslUsc00jfEFDdwpAWYFKImBRpdo6dEyXelXczsfFZvpa6
MhdqfU94i0UigUnm6sKXiHmKVWOpObXvUBqwrrL4dNFXmjpMiHG8ouSR+QOB
MnY06vvVGPfy0DPRUQVL9ovSTYjr9ZNIoydQr6ryoeGIXV+AdWYJpvt6C1wC
ocUggiwMf.sqcH3d+ZtwuC2n.QLK0ri2Gjk16tr0+.GmF6pcpgICUriX18sS
az0dakyO4q2Yz6D0OZjlozRSdTufe.YdDM4bNMnQSACbz7T3Jkepa3EKFNCy
4nc3WCl+4ixhlDv6EOKloRI7F87uLGzOXUnBvqfmHKL7RAXvbBX2QsvUUE6o
A9EDwG8.LKv4XZhkY4GqTFpw8UUhcLqjJ5je3MRGNSfNf9l8raJ.I3+3d7iV
8LXkwkeM3cxAHlQUuwAops2R9.VQLl3r7.fidv9D0yNHs.mhi.vUkIXM7h4H
Lw3hNqmdIhKbCO8drfqbdeCKly7htAmFv.Y0B9+uJp.tdBtAlCw7rCJLcq8A
mbfkzykRPOthyJKhqU7pyDyp07kHcJHzCu.kGZdYls6UFIImIgLu9kboWd2r
yD2pBBaeioRmptoto5.dFz.OYUuuVMrtWAv4X97mDWELeSXvjlP+oXb.q7ZY
P5cGvqk8Qe27n+NSQ+Cmh5C8Z6O08Nv51tW56lE0ObRruyrYt8lDcAFkt.9l
XLPPUnV8MyhF5FdFZ3LLepjmmd9p0p4.fSJhqVslCaNXJSn27kDyaRI78lQu
Z2qMB8tx1v0u8vVOGccQtliwpJrUcyrnfqd6JHzGdAUvf2tBFFNQ8qpnodeu
LZUq+2IS+uQlA99XF4ai4UeWLUuMqi88v7g6jc3eAGW.e4A
-----------end_max5_patcher-----------
</code></pre>


1. set the ```@saveset, @saveget and @savebi``` attributes to 1.
2. set the number boxes attached to the remotes to any values
3. save a first preset
4. set the number boxes to different values
5. recall the first preset
6. check which parameters had values saved

As of [f0d0bef](https://github.com/ossia/libossia/commit/f0d0bef8410f14767f1bf8b15063e72ebc550436), it seems like no matter what the settings are for ```@saveset, @saveget and @savebi```, all parameters are always saved.

**Comment by jcelerier** [comment]
hummm thanks for the repro, checking what I did do wrong..

**Comment by jcelerier** [comment]
fixed by f60142c593612930b6eff0e09cef031f5c4bb059 : in short, bi can now kiss
