### ISSUE TITLE
[ossia-max] allow namespace output of [ossia.device] to be filtered by param mode

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#771]
The "Store and recall presets" tab of the "OSSIA overview" patcher demonstrates a message for retrieving address and value data by passing a "namespace" message to [ossia.device] and storing this in a [dict]. When [ossia.device] receives "namespace", it outputs the addresses of all nodes in the patch, regardless of ```@mode```.

On the other hand, when storing and recalling presets using "preset save"/"preset load" messages to [ossia.device], only parameters ```@mode bi``` are stored.

For the TML's use cases (and maybe other roll-your-own preset systems), it would be useful to be able to have a way to filter the namespace output from [ossia.device] by ```@mode```.

Perhaps this could be accomplished with additional arguments to the "namespace" message - e.g. "namespace" retrieves all nodes, "namespace get set" would only retrieve nodes with ```@mode get``` or ```@mode set```, "namespace bi" retrieves nodes with ```@mode bi```, etc.

This stems from discussion in #760 and #764.

**Comment by jcelerier** [comment]
before I embark on it, @bltzr @avilleret wasn't there an objet / feature that already did that ? e.g. among ossia.explorer ossia.fuzzysearch ossia.search ossia.monitor ... maybe one of these already has the feature ?

**Comment by jln-** [comment]
Hi ! ossia.explorer does allow to filter nodes using the mode attribute. So retrieving parameter's state using ossia.explorer rather than ossia.device should work, I guess.

**Comment by evanmtp** [comment]
Hey @jln- ! I think the issue there is that ossia.explorer doesn't return values along with addresses. The "namespace" message to ossia.device gives you e.g.

myDevice/myModel/myParam 1.2

whereas ossia.explorer just gives you

myDevice/myModel/myParam

It's necessary for the values to be included in the presets, so as of now, I don't think ossia.explorer on its own is a solution.

**Comment by jcelerier** [comment]
thanks @jln- ! maybe the simplest is then to give ossia.explorer the option to output these values ? e.g. 

    [ossia.explorer @values]

or something like that rather than port the filtering logic in ossia.device and bloat it more... what do you think ?

**Comment by jln-** [comment]
Hi @evanmtp ! I initially thought like you (that ossia.explorer does not return values), but it seems to do so, here, using ossia.explorer help patch.

That been said, I use an old version of ossia for a current project, so maybe something broke at some point ?

**Comment by jcelerier** [comment]
hmmm just checked and at the current commit I also see the values out of ossia.explorer

**Comment by jcelerier** [comment]
can you try on your side @evanmtp ?

**Comment by evanmtp** [comment]
Just tested with [f0d0bef](https://github.com/ossia/libossia/commit/f0d0bef8410f14767f1bf8b15063e72ebc550436), and it looks like it's working - thanks! I'll revise our preset module to work with ossia.explorer.

The fact that ossia.explorer outputs values doesn't seem to be documented in the help patcher. I can add a note about this and make a PR.
