### ISSUE TITLE
[ossia-max] ossia.remote disconnected from view when patcher window is closed

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#772]
when a sub-patcher containing an ossia.view (and remotes) is closed and re-opened : all remote are disconnected from the view, and can't bind to a new address sent to the view.
(Only way to "fix" it : delete and recrate the remotes.)

<pre><code>
----------begin_max5_patcher----------
1600.3oc6ZsziaaCD9rCP9OPnCsH.tNhTuryo1qEn.8dRfAsDWalHQZHRud2
Fz+6cDodaYuZ2s1wAwWVulCE0LeyC9wg9au8MSbVIefobPe.8QzjIeCFYhYr
hQlTMvDmL5CwoTkYhNwxrLlP6LsTnl8f1Hf7NTbpTwPTQBRtkIPz0Tt.8wsn
64r8eFlymDwo73uhjBT1i+kLgkNCi9k5+m.SQH2ijJEmNKmkI0LDWgT5cvCo
kH8FFBTDMJqX9vxoXhDtXMhhDr8HZRRNSoJlocIJdunDISI9UMZuL+qeR7Ig
Tj9HZO8whocG+ADWCuVX4XZqpmyhyYT3KsUiZyMkKXwxcBiMGVMJOw.AxUe4
2VTOUwtL4NMrtFfysZ3sTc7FPoWBuHsE6IjfYtSQX2nYASQdvGv2luXlK5ys
VLtnZsvlA+229lhOgOl958d32Y8YOWuEfS5MTcWeVLUfVwArrzmQpbMLE7Pl
otDTqkIr64wrO79xkT8952C7e+MMmlMlISpl7vNofAbRguBmzBiOBOu3KQAm
AeDDJC53gtHqmwY.yw+oLmXYpL2ZF3B81clmOFGE5G4FLeNwKnXH7hP2n49d
XuHRf+hoESsw3F.Qvdtl.Uuh+FXBZIjiBHcwVVdIDTgASbtimxtmkq3RgA.m
VIftcaqwmz9gJftuXMs4SaFiKri40LVND9TsDtMCSyAqRClztblAOeHrFMKV
IHBKWri23QsNyJUy30DzLlZKM1t.Ed2Z4MfkWnI7wuHsFPKavjeTTK7BhLVm
Ji+JKoiR5TjXxEagDHH0kp6aDNIr6n6R0KuSJzJ9+XTCL3HFbB2UpmCKsvTL
VwejyooM1w5bdhTTnHccMEiW8Jg.BaFRPGaxLEAc6POND7B.zwjp.icmZEMu
vysJ07RH0R0RYZWYMOYJ6Nco7sbgnOfpkaOgzb95Mm5oWIAoYmb4MhTK2Irh
WVro0RE89dHulllVls26M7.UvyfMgzbq+f31HkInfAuQEmKSS6Z2VQ2OjHa4
y87D8FyKqS3A7.7sUAVNMt8D9ZlR2aPMcsp2PJ8iVWP6w1spLSeolksMErld
y.Rc3JsZibupblUgecfhFFJcx7aWGsqfd0SgjSEcMqIqtcQ05MQ5HtUs0tB5
VeE2Vjcb8iaKSFbbZRBN1VJ9gEILdlBngGV.8vhnjZAk6rTUP57hN3igNgmQ
zAG4+cGc5tWbWvIGrIFBpXuhltrjfSmY1gFB4HHH1+DPH4zP3zQEjEY1xmDU
xwzrmsW3EFHWsCJZJb5pq.mMf0c9RaYqt6L2Ck7dwAZqnh0iHXiXBvv9FTh3
W82S.R3Kat3QYBeHA3CPO2whdcnPDNy8UlB6QLAaAF3z2vIAQhtz4v6xVAzM
eogdQup7ywE8YwIhmY6f.2QTpCeQK004zcOQvVvIvKumtd1npogIg1DTCtgC
8u5PLfsNvmMAMz9BsyLIm+MPmaAIW7UZXU6S0d.9bNgmE1R9l5bUaLdwwmSV
yeMSeJBFC01oyAPYy1vVhDXr+qfJVqCFVPO5XT6MZQwDNBDpj6xiqrfR6G0S
efi0n4h5yK+w5xSESb79wmspDc8nJgiUUJpCcl0kfwpKQWDUgLJXw+rqKjqH
WTk4NBkAXThvmWkwarJyhyOvLduz.ZsLOw1tS70gJdBMz8oKaa50ywpaW2+v
+jlIynK2vWCVw5MZVxRYNvEt8FcUcd7HlHMNlIzG15ZSypcKaOca8cZa3KGd
1AZKUw1uvqj2wXMFn8KMKiSQ+5.s1zhxkTsNmCGh0Z4c5a8yr8Y18y60vqAa
uVsFcFtJgC56UaxDdufqGwdgH16BXHtT2tLfVWFvBeSrrmkAZ44iwAd2tLfa
WFvsKC3bdY.uxlA4eAZFD1TTHZ9UcufpAsp1Ag98xRGnWzUo7+Qmts.mu83o
dWqs6v9aW4Iu2oyZmOrM9vtWssGZuPf5bcb9QSl8zGP6mUVc3gX0Qdwr5BH2
X0MFVcdVJO1eaGd1eQL3f42X0ciU2MVc+rypyTC0diL+HxpC+ciUGw9Kk6GI
Vc3uKr5HUkluwp6pgUm0Z6yuwnO840zmSy.7YNAWlC3wThN85WaICyQ2m1d8
nshO536MasS5X8jsW+XavriP75suAlx+Azeqb1B
-----------end_max5_patcher-----------
</code></pre>

**Comment by jcelerier** [comment]
weird, thanks for the report

@avilleret you know where I could look for that one ?

**Comment by jcelerier** [comment]
(also @matcham which version are you using ?)

**Comment by matcham** [comment]
I'm using latest release, but I have this issue since ages !
I couldn't isolate, I thought it was random... I finally managed to understand & reproduce only today.
I think @jln- can confirm this issue has been around for a while ;-)

**Comment by avilleret** [comment]
I also confirm this issue with a fresh build from today...
thanks for reporting @matcham but I have to admit I have no idea what is happening

we should track down what the address message is doing
I will try to have a look tomorow

**Comment by matcham** [comment]
bravo et merci :-)
