### ISSUE TITLE
[ossia-max] Instacrash on macOS

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#774]
Happened spontaneously while looking at a patch with a lot of ossia.parameters and ossia.remotes.

Crash log: https://gist.github.com/evanmtp/7b6dd0f523c65db21decb46e58054c0f
Max debug data: https://gist.github.com/evanmtp/18d856649a4eac4bb8857d9837958e90

**Comment by evanmtp** [comment]
@navid just had another one: https://gist.github.com/evanmtp/67a5030a0cf4ad9bccdb725f3e86d8f3

**Comment by jcelerier** [comment]
@avilleret do you have any idea of why that could happen ?  both are the same crash it seems, but I don't see anything weird in the trace

**Comment by jcelerier** [comment]
humm this safe_set class does not look safe at all. seeing what I can do..

**Comment by jcelerier** [comment]
static ossia::safe_set<ossia::net::parameter_base*> param_locks; 

indeed does not look safe. lemme try something..

**Comment by jcelerier** [comment]
Can you try on f0ab85dd0 ? It should be available as nightly in 10-15 minutes or so

**Comment by evanmtp** [comment]
Sure thing. I'll also forward it to @navid , who's working with ossia-max intensively right now.

**Comment by jcelerier** [comment]
Yep. His last crash is also the same

**Comment by evanmtp** [comment]
No crashes for me as of this commit. I'd say let's close this for now and if anyone gets similar crashes again we can reopen it.
