### ISSUE TITLE
Does ossia-max (and mac things in general) still need 32-bit builds ? 

### ISSUE THREAD

**Issue by jcelerier** [ossia/libossia#778]
ping at Max users - Max 8 itself does not support 32-bit anymore

**Comment by jcelerier** [comment]
@ossia/max

**Comment by evanmtp** [comment]
I don't personally. Is maintaining the 32-bit version of ossia-max causing a lot of extra complication?

**Comment by jcelerier** [comment]
well, it takes twice as much time to build aha

**Comment by jcelerier** [comment]
although we'll likely have to replace that with aarch64 for M1s

**Comment by evanmtp** [comment]
My instinct would be to say ditch 32-bit, but in the interest of covering all angles: how much of a pain would it be for someone to build a 32-bit version in the future if they absolutely needed it for some reason? I mean does switching to 64-bit only (including aarch64) allow for using things in the source code that must be avoided if also targeting 32-bit? If not, I would vote for ceasing to build 32-bit versions now, and let anyone who needs it do it themselves.

Also - and I really don't know if this is a thing - if there _are_ certain language facilities that you've been avoiding to maintain support for 32-bit, and they would in any way improve 64-bit performance, my vote would definitely be to drop 32-bit completely in favour of better 64-bit builds.

**Comment by avilleret** [comment]
I think we can disable auto build for 32bit but keep the workflow to be triggered manually

**Comment by avilleret** [comment]
btw, @jcelerier where did you see 32bit builds for ossia-max ? the package on GH Action seems to only contain 64bit 

<img width="540" alt="image" src="https://user-images.githubusercontent.com/504914/162068605-1e10903b-a544-4ef6-9ddd-e877bc553b4a.png">

**Comment by avilleret** [comment]
for the record, to manually trigger a workflow, we should use `workflow_displatch` : https://levelup.gitconnected.com/how-to-manually-trigger-a-github-actions-workflow-4712542f1960

**Comment by jcelerier** [comment]
hmm on my Mac I had to disable it by hand - but I think that this is because I may have an old mac sdk which was picked up

**Comment by jcelerier** [comment]
but if in the CI it's good then we can close :)

**Comment by avilleret** [comment]
> hmm on my Mac I had to disable it by hand - but I think that this is because I may have an old mac sdk which was picked up

or maybe you configured with `-DOSSIA_OSX_FAT_LIBRARIES=1` once.
(which should the only thing to do to build 32bit and 64bit in one go @evanmtp)
