### ISSUE TITLE
nested parameter callback is no more called after parent node renaming

### ISSUE THREAD

**Issue by avilleret** [ossia/libossia#783]
- create a node, create a nested node with a parameter
- add a callback on the parameter
- push a value -> the callback is called
- rename the upper most node
- push a value -> the callback is no more called

see https://github.com/ossia/libossia/blob/master/tests/Network/OSCQuery_rename.cpp#L99-L195

**Comment by jcelerier** [comment]
fixed by 7b38678be6707d361a01921653a656f0ccd7a2fd
