### ISSUE TITLE
[ossia-max] with v1.2.9 [ossia.parameter] seems to misbehave

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#785]
Hi

I just downloaded v 1.2.9 for max and [ossia.parameter] doesn't pass on the value it receives on its inlet to its outlet. (NOT using set!)

case in point: open [ossia.parameter]  maxhelp and test if for yourself.

I am testing on OSX 10.15.7 with Max 8.3.0 beta

**Comment by maybites** [comment]
indeed, this is fixed with your provided version.

**Comment by maybites** [comment]
Hi @avilleret, Is the  https://github.com/ossia/libossia/issues/784 fix already inside the current release?

**Comment by avilleret** [comment]
Hi @maybites, since #784 is still open, I would say no, it is not in the current release.
