### ISSUE TITLE
ossia.client broken > crash

### ISSUE THREAD

**Issue by navid** [ossia/libossia#801]
when I follow the numbered steps suggested under "ossia.client.maxhelp" (without anything else open)
as soon as I click on the third step "connect oscquery", I insta-crash:

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
Pure virtual function called!

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib         0x00007fff732382c2 __pthread_kill + 10
1   libsystem_pthread.dylib       0x00007fff732f3bf1 pthread_kill + 284
2   libsystem_c.dylib             0x00007fff731a26a6 abort + 127
3   libc++abi.dylib               0x00007fff7037b641 abort_message + 231
4   libc++abi.dylib               0x00007fff70387ad2 __cxa_pure_virtual + 18
5   libossia-max.dylib             0x0000000131bb4865 void ossia::net::node_base::set<float>(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::optional<float>&&) + 213
6   libossia-max.dylib             0x0000000131bb4781 ossia::net::set_priority(ossia::net::node_base&, std::__1::optional<float>) + 33
7   libossia-max.dylib             0x0000000131ae4856 ossia::max_binding::object_base::set_priority() + 70
8   libossia-max.dylib             0x0000000131b1d2da ossia::max_binding::parameter::do_registration() + 314
9   libossia-max.dylib             0x0000000131b3cf3f void ossia::max_binding::register_objects_by_type<ossia::max_binding::parameter*>(ossia::safe_set<ossia::max_binding::parameter*> const&) + 303
10  libossia-max.dylib             0x0000000131b3cc6b ossia::max_binding::register_children_in_patcher_recursively(object*, ossia::max_binding::object_base*) + 235
11  libossia-max.dylib             0x0000000131b3cd02 ossia::max_binding::register_children_in_patcher_recursively(object*, ossia::max_binding::object_base*) + 386
12  libossia-max.dylib             0x0000000131b3ce00 ossia::max_binding::register_children_in_patcher_recursively(object*, ossia::max_binding::object_base*) + 640
13  libossia-max.dylib             0x0000000131af02af ossia::max_binding::client::connect(ossia::max_binding::client*) + 703
14  com.cycling74.Max             0x000000010ce33309 typedmess_fun + 377
15  com.cycling74.Max             0x000000010ce1e662 outlet_anything + 1426
16  com.cycling74.Max             0x000000010ce33309 typedmess_fun + 377
17  com.cycling74.Max             0x000000010cdfd00a aeval + 2314
18  com.cycling74.Max             0x000000010cdfc6ae atombuf_eval + 142
19  com.cycling74.message         0x0000000130a9ca17 jmessage_atombuf_eval + 567
20  com.cycling74.message         0x0000000130a9ac1b jmessage_mousedown + 155
21  com.cycling74.Max             0x000000010cab2699 BoxComponent::sendMouseMessage(juce::MouseEvent const&, symbol*) + 1225
22  com.cycling74.Max             0x000000010cab37f3 BoxComponent::mouseDown(juce::MouseEvent const&) + 1107
23  com.cycling74.Max             0x000000010d14edfd juce::Component::internalMouseDown(juce::MouseInputSource, juce::Point<float>, juce::Time, float, float, float, float, float) + 669
24  com.cycling74.Max             0x000000010d1c58aa juce::MouseInputSourceInternal::setButtons(juce::Point<float>, juce::Time, juce::ModifierKeys) + 810
25  com.cycling74.Max             0x000000010d1532df juce::MouseInputSourceInternal::handleEvent(juce::ComponentPeer&, juce::Point<float>, juce::Time, juce::ModifierKeys, float, float, juce::PenDetails) + 431
26  com.cycling74.Max             0x000000010d1b7910 juce::ComponentPeer::handleMouseEvent(juce::MouseInputSource::InputSourceType, juce::Point<float>, juce::ModifierKeys, float, float, long long, juce::PenDetails, int) + 240
27  com.cycling74.Max             0x000000010d1ebf26 juce::NSViewComponentPeer::sendMouseEvent(NSEvent*) + 310
28  com.cycling74.Max             0x000000010d1e9532 juce::JuceNSViewClass::mouseDown(objc_object*, objc_selector*, NSEvent*) + 178
29  com.apple.AppKit               0x00007fff44838f7b -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5724
30  com.apple.AppKit               0x00007fff4476f8b2 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2295
31  com.apple.AppKit               0x00007fff4476ed73 -[NSWindow(NSEventRouting) sendEvent:] + 478
32  com.apple.AppKit               0x00007fff4460e557 -[NSApplication(NSEvent) sendEvent:] + 331
33  com.cycling74.Max             0x000000010cdd132d swizzle_SendEvent(objc_object*, objc_selector*, NSEvent*) + 109
34  com.apple.AppKit               0x00007fff445fcccc -[NSApplication run] + 755
35  org.cef.framework             0x000000011832a3bc base::mac::CxxPersonalityRoutine(int, _Unwind_Action, unsigned long long, _Unwind_Exception*, _Unwind_Context*) + 4764
36  org.cef.framework             0x00000001183291d3 base::mac::CxxPersonalityRoutine(int, _Unwind_Action, unsigned long long, _Unwind_Exception*, _Unwind_Context*) + 179
37  org.cef.framework             0x00000001182e83bd uhash_compareUnicodeString_69 + 754989
38  org.cef.framework             0x00000001182b43fd uhash_compareUnicodeString_69 + 542061
39  org.cef.framework             0x0000000117f98d3b __gxx_personality_v0 + 401403
40  com.cycling74.Max             0x000000010cc50282 MaxCefEventLoopHandler::runMessageLoop() + 18
41  com.cycling74.Max             0x000000010d0c9e10 juce::JUCEApplicationBase::main() + 144
42  com.cycling74.Max             0x000000010d0c9d63 juce::JUCEApplicationBase::main(int, char const**) + 83
43  libdyld.dylib                 0x00007fff730fd3d5 start + 1

**Comment by jcelerier** [comment]
fixed
