### ISSUE TITLE
[ossia-max] on osx: loading an abtraction with [ossia.model] rebuilds node tree

### ISSUE THREAD

**Issue by maybites** [ossia/libossia#805]
Hi

Using the current [RC](https://github.com/ossia/libossia/releases/tag/v2.0.0-rc1) I am observing the following issue:

[Sparck2](https://github.com/immersive-arts/Sparck2) is a collection of abstraction and can be used inside normal max patches. I am using ossia with for my UI. This is great, since the last working version with sparck was 1.2.4.

So: YAY!!

But..

When loading a sparck patch everything works fine. The node tree is generated and I can populate the nodes with values via a dict like illustrated in your launch-patcher.

But when I load a new abstraction into my patch, the node tree gets rebuild and the previously loaded values get lost. This happens only with the first abstraction - each subsequent loaded abstraction doesn't initiate this.

It doesn't happen every time, only 90%. 10% the node tree rebuild is not happening.

**Comment by jcelerier** [comment]
hey! that looks like an interesting bug. I don't understand why specifically the first would cause this and not the subsequent ones. @avilleret if you happen to have an idea..

**Comment by maybites** [comment]
I just verified: The same thing happens on Windows.

Unfortunately I was unable to create a simplified patch that reproduces it.

If you want to do so, you need to:

1. pull this repo into packages: https://github.com/immersive-arts/Sparck2

launch sparck from the package-manager and press dependencies (all needed stuff should be inside the package-manager - with the exception of ossia and java)

2. pull this repo somewhere else: https://github.com/tecartlab/SPARCK_TestBed

open SPARCK_TestBed/OssiaTest.maxpat

select one of the abstractions , for example "Grid" and copy paste it.

**Comment by jcelerier** [comment]
thanks for the repro!

**Comment by maybites** [comment]
I was able to reproduce this issue with a simple patcher, and so this issue can continue here: https://github.com/ossia/libossia/issues/832

I would apreciate if it becomes some attention :-)
