### ISSUE TITLE
[ossia-max] ossia.remote @repetitions 0 is broken

### ISSUE THREAD

**Issue by matcham** [ossia/libossia#808]
in latest ossia-max release [v2.0.0-rc1] ossia.remote @repetitions 0 doesn't output anything.
(windows - don't know if it's different on mac)

<pre><code>
----------begin_max5_patcher----------
675.3ocyVt0aaBCEG+4Do7cvhmYQ1FLW1S46wzTkg3jQEXiLltTUsu6yWfTZ
ZgQaHs6gVjsO9b4ms+exSaVuxKSbh03A9N3GfUqdROyJ6blYV0OwJuJ5o7RZ
i0PurVkRv876VSzpJYJ0i0Lma7xn7idfe1udMUk+qB9w6jrbkyDR7VnO.GEY
+D1++m2Cuspfq8pMfnm8jjVwTL4cLNMqzFOX+hE6sImH69ugR8F3HW947jc1
+rYs4q9i+rq4CkBsqFul87mScifcENx7g.sCvCK7CBYE0ZczBwh3QXA9KlE3
HW46PxmCKHKNK3req87Y2pXmTtv0zTP2JYUBECnDJwz3x92j3J.G3vkETHX5
q40aCmg0ev4rHWTJjNOC2hvjvTHJMBFmDFf70SkjFhPwQgwPRRBNzLEAiHQI
Q33PBLMQmCWD6A7L3FwyyGzVjBxDhRvNIqloJTEBdC.ddmkEbVtnka2NdZ3O
I3SSFbME4NEBhdebGOA2MnM1h9ybeZ39wurd8B2nnDGFhuQJ2nEW4VINdTGv
QK5ByUjIEpH1xjbiZVs78ppXMMzirW+HBMgHz+nuEwcrGMlV8KX.9MJS7hWl
yUpntj9HX2d1AZaoB.A6Lk870NBtBsiNt4t5zocXn26P6H.9+g1wrZzYP801
nCm5dtE+w6yEC+h5y4ryd+4xeSssRMKbAjaDsx7dB02jFLHh6YMpBN0bGcnU
DmUiedN+.RlU.CVt.hmU.ieoUB4dl8jD94kBoijBnEHELOrmQJftgTXdofAU
naDDhmUFjtXW8RmS35Sp29wMst9AlroaKtPokJu2Iyj36FWvciItwR1CE8aw
0cziJ0JeJsrWqzlgdmhB851sPiXdaQOkMEqIzV0XttsVSM0UVVU6Mq0F7WPK
jF3L
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
> (windows - don't know if it's different on mac)

It is not.

**Comment by jln-** [comment]
It seems the default attribute is the culprit here. It works here (on Mac) if no default value is declared.

**Comment by matcham** [comment]
looks like there are several different issues...
When removing @default attribute, it works a bit better.

But this patch shows that it stops working after a couple of seconds.
<pre><code>
----------begin_max5_patcher----------
1490.3ocyZsrbqhCDcs8WAEq80WIw6YUl+fYepTtjskczcvRTB47XtU92G8.
vfC3PH.2rHwIcqG84zOnkL+d4B2s7WH4tN+ky8NKV76kKVXDoErn3+W3dB+x
tTbtYXtLxy7s+xckUkj7hzH9Hg4bmz4f.y1yO4b2IJyAn9.+hCrbvryJooDo
YgfEByvxcORYG2HH6jVCwC4uFrxwC3sFEGDEFFBfAgnfUNHPjVCBsF37vkUk
eVd8xZEIeMiXWS2CobrZ8KmEcuwrUP4GnD251BQTf9B3uv8.Mk7DQjS4rZaw
BWbVVMwKpMEMm8KtYghWUIhxrhBpDIHOQKmOpRJVnXDohNNKLVu6Kg9tWVF9
dhfclZLEqv2VVZRF+DCehjmg2Ym797r0JuS4B3dgmCRzjIDXXa+jPK0Buvsp
Xgio7c+KwPVfRg7LBixxDjbBShkE1ek58jC3yoxMG3LYN8+LVAT4wZS+gBqr
UkZbXfveKn3zJ.bTP2yYZing2PKtb6t2AFXvVPcvXFACm0xjUwAJZoCk4JPd
NeKVncVaSI08VtRNOsopp4kRNHKTmQYrqXQIOqakB5wGuwb2xUJOcq01nIey
YlU6FUbgbSN9olrsDmlVjP2b4eAynmvRhjZcAHPkRBCq.5i46D7zzF30p4oV
zrWEmui7Lcu7QyFUOXPMbZVYPjakWdO8HIW1TlDeLuojb4qVRulnyaKxi2HI
mxRUnn4.TYHzbY9i7myKFXYfVcB3RUw5400qN1P9UUI2wOcRkbTk0VuTY9Nb
JQUoTUl79e.UAoO3H4N2qJOrxQsHOTeRsUxrqxlvP+0pZjPHvD5GY9.ApkA7
9xkfZZpURL1sT7aKWV9Gql.tXOQMNAwQ9HQicmLrP4KjDwOwRoft8rx4MP5.
4A0zQHzvFIICmMh9ivFpGfN9rAJ1xFACmMBGS1nQ2Dskl7CnCzvEpo0I1Q2F
6A1DBPRsOp2BQ2sQzdqDtMlXMpwalnl+QGW3Tu2p2yIfOnXQ.xjcXnlXvjQI
v4kRzcc9EoDaJRTzjQIIyDkv3zbxPICaNikK7lNt.MSbgxhtQtBrW0OrsK6E
zCxniRm9sg1K8mlRYc00gwpz5amFx4mE6JIaKutxooApZzRRYUcqeeYEKy35
kS3yZCd8zF76zFJDZkX9s0t5y4Tk7iGSIC7nm5mVp+vu72e1SaRYseVynKG0
r3Q6arcMahZlMXhRrHKXZPo+2JTBg1VeFcXBC+dfSHvdzc.XZbmvQ2e1wkHk
ITlfi8lZ9jbfs+deXQOdfO3Zh.sfRf6XijspigOTmosBzfPR7HBDk2Vv0lQq
3.8gIeAFzD5MzqsaKlcr0fxfQDjpycQ2SFHBiMEQsGybHHrqrtvQ2Kh9rHr7
ogQdWbkipSzaHXTcLXIm8YyqBLsx5+UqQ1ITfIicQRUcPkQMrBgdwld1C9np
Gntvopmraf0a2FSgtCbwIrwpBmMzir4gd9voD9ASO76HQlmmSwqEjSbIwQxk
7xQrimZ+xEt2ArFhB7S.vjPPTruGT0d853DeHLJzOBDDGi70hBPvfv3PTje.
HIV8rllzzm5qpwyui6V4JB26VDt4mVIbO2wlBq7bFVz4NAIiHo5SljWcCBlC
jsielIqGq7dlVSlQFxthoGHcVj7ZidgHuxCbNjv21YRz7Uws3VkltJtvuIGy
HvF76kLMsemLSceechQVJ9Um6zFnoQ19ji3MC4HPPPM5tHIwOYDSR7.tSTEa
Mk9Gthc4gh8ASYE6nFTnYDMudKKid8UJUvq29pj53ZjzeM9k2iz6bc8cih5w
F4MB6SowdyMBNF6j9RJ9vcR4t956Te1nRq4qAo93kfiAj7.8YmfMFDWr29Jj
.+ZfD0msNp8sFLCacxTf5j4JXMpOd1wnhh9vByTldepRVZNyPZg+jDa52isN
dDvXebaiQwr9fm26yrOQ8pW.M8Vb0Kd1UuzYu+ENq6W1rqeQyLujYs8BloaK
Z4aK+evjyIDD
-----------end_max5_patcher-----------
</code></pre>

in this patch : with @type bool : it very quickly stops 
with @type float : it takes much longer (with metro)
if I change value with mouse very quickly, I can freeze it quite easily.
https://www.dropbox.com/s/uks8xw877o5ual6/repetitions%20issue.mov?dl=0

**Comment by matcham** [comment]
(same issue with overdrive on or off ;-)

same behavior on Mac & windows

**Comment by matcham** [comment]
might be related to #809 ?...

**Comment by jcelerier** [comment]
yep it's the same issue, i'm on it

**Comment by jcelerier** [comment]
do you know the last version where it worked correctly?

**Comment by matcham** [comment]
until yesterday, I was working with a quite old version which used to work fine 
package-info.json says : "version" : "05347bb"
files are dated 28/04/2022

**Comment by jcelerier** [comment]
[ossia-2022-11-25-15-38.zip](https://github.com/ossia/libossia/files/10095012/ossia-2022-11-25-15-38.zip)

should be fixed here, can you confirm ?

@navid @petervanhaaften

**Comment by matcham** [comment]
seems to work fine here
(tested on Mac only, no windows externals in this package)
THanks !

**Comment by jcelerier** [comment]
okay, hadn't put the right commit in the release, it will be there for good in the next one sorry @matcham
