### ISSUE TITLE
libossia on gitter-element ?

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#827]
Gitter seems to have moved to matrix, but I can't find the libossia room (found the ossia).

**Comment by thibaudk** [comment]
Hi @vincentgoudard 
the address of the libossia room is #OSSIA_libossia:gitter.im
you can find it in element by searching plublic rooms
select the gitter server (default) and enter
OSSIA_libossia
you should see it.

**Comment by vincentgoudard** [comment]
thx Thibaud!
