### ISSUE TITLE
Joystick haptics support

### ISSUE THREAD

**Issue by jcelerier** [ossia/libossia#839]
@edumeneses started work on implementing haptics support.

My investigations so far: 
- https://github.com/libsdl-org/SDL/issues/5125
- https://github.com/libsdl-org/SDL/issues/4859#issuecomment-951532706
    - Do we know what are these magic HID packets for the DS5 active triggers?
    
- SDL_GameController is a wrapper on top of SDL_{Joystick,Haptic} that expects a classic xbox-like gamepad so this wouldn't work for joysticks, wheels, etc.. I think we have to use SDL_Haptic directly in addition to current SDL_Joystick use to keep compatibility with the full range of devices

- Haptic APIs are terrible ?? https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_haptic.h seems like there's no way to directly control the motor, you have to send "prerecorded" sequences... makes sense for video games but that's artistically debilitating :| 

- I guess the control API would look like a message which would set the parameters to this struct here and send the effect ASAP, hopefully this does not have too much latency... https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_haptic.h#L81-L89 

- For this it would make sense to think about implementing a proper way for https://github.com/ossia/score/issues/1483 as we'd want to be able to change any one parameter and have it send the new effect. Basically having a "Tuple" type where we could say that a push to any (virtual) children actually triggers a push to the parent, e.g. 
   - joystick:/haptic/effect [ all the params as a list ]
   - joystick:/haptic/effect/type  "sine"
   - joystick:/haptic/effect/periodic/direction/type "polar"
   - joystick:/haptic/effect/periodic/direction/dir/0 18000
any write to a children of effect triggers a write to effect
   
- Some simple init code is there:  https://lazyfoo.net/tutorials/SDL/20_force_feedback/index.php

**Comment by edumeneses** [comment]
To add information. The code we need to port is available at [puara_controller.hpp](https://github.com/Puara/puara-controller/blob/main/puara_controller.hpp) and [puara_controller.cpp](https://github.com/Puara/puara-controller/blob/main/puara_controller.cpp). The code uses SDL3, so some work is needed to match SDL2 functions.

The idea, as discussed, is to leave the [joystick_protocol](https://github.com/ossia/libossia/blob/master/src/ossia/protocols/joystick) as is and create a new **controller** protocol.

**Comment by jcelerier** [comment]
this is mostly done, it's just lacking an update to the ossia SDK to base new releases on as the current one uses a pre-PS5 dualsense-support SDL version. Builds from source are ok. :)

**Comment by jcelerier** [comment]
next step would be to think of some interesting interactions we could have with the haptic stuff, right now it's mostly going to be LFOs, automations,  mappings,  step sequencers, and the likes, I'm sure we can think of funnier things to do ^-^

**Comment by jcelerier** [comment]
marking this as done for the core part ! :)

**Comment by edumeneses** [comment]
I think we can close this one as it was tested for the PS4 and Xbox controllers. If something doesn't work for the steam deck or other fancier devices, we can open another issue
