### ISSUE TITLE
sort nodes by priority

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#92]
as discussed in https://github.com/OSSIA/i-score/issues/344 it's important that parameters be recalled by order of priority (this e.g. allows setting the loop points of a sound file *after* the sound file has been chosen...)
IMO it's very important that this happens when recalling states - the way things are displayed is less important (could be alphabetical...)
also, when no priority is set (i.e. = 0), those addresses should be recalled last (at least that's how we did it in Jamoma and it was quite efficient)
this is an important one if I may emphasize this...

**Comment by jcelerier** [comment]
> IMO it's very important that this happens when recalling states

so this is the same issue, but in states right ? again, for this I think that a list would be more suitable than a tree (else there is really no good way to show 
```
/foo        7
/foo/bar    5
/foo/baz    1
/bar        3
/bar/bof    10
/bar/blop   3

**Comment by bltzr** [comment]
well, we’ve been discussing this back in the old Virage days, and then with Jamoma, and the conclusion was that there was no other sensible ways than having priorities working on each node level

i.e.
/foo 7 
/bar 9
means that all sub-elements of /foo will be recalled before those of /bar

then inside of /foo 
we can sort /bar and /baz
and inside of /bar
we can sort /bof and /blop

but doing otherwise is just a very good trigger for future headaches, I guess (just ask Raphaël M, I think he still remembers this :-) )

**Comment by jln-** [comment]
> the way things are displayed is less important (could be alphabetical...)

Do you mean in the inspector or device explorer ? I'd say:

- Device explorer: sorted alphabetically
- State inspector: sorted by priorities

**Comment by bltzr** [comment]
> Do you mean in the inspector or device explorer ? 
> 
Yes, I meant in the Device Explorer.

So I agree with your proposal:
> Device explorer: sorted alphabetically
> State inspector: sorted by priorities

**Comment by bltzr** [comment]
> so this is the same issue, but in states right ?
well, yes... I first reported it right, because I thought that was libossia's responsibility to reply to the namespace query by ordering nodes by priority, but then we discussed with @jln- and the issue boiled down to this (which is probably more i-score-specific than libossia's I guess...)
should I close this issue and reference it from https://github.com/OSSIA/i-score/issues/344

**Comment by jcelerier** [comment]
yep
