### ISSUE TITLE
[ossia-max] add default device 

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#94]
the way it is done in ossia-pd
(i.e. collects all nodes that don't have an ossia.device in their root patcher)

**Comment by avilleret** [comment]
so we can close this, right ?

**Comment by bltzr** [comment]
it might be working, but when I tried (patcher below, just change the value attached to the remote, it froze Max and I had to force quit)
<pre><code>
----------begin_max5_patcher----------
400.3ocwTsraBCCD7bxWgkOmhxSnp+JUUHmvB0nD6HGGZPH9u589i030N.sE
AoTj5g3nc8XO6Ndr246QykcPCk7D4Yhm2NeOOLkIgmK1iVw5JJYMHL5xRons
hFXmploKdkKVMWAEZ61LMcRX.IZZn4WFNFGOIj7haIxVcIn0aqAKdJMfPyYh
UzCP3KPpj4qeH8HSJVEnA0bPvxKwEG5lquf3h9MEqvngEnfFPnYZtTbR4k5J
ojHyuP2vApWJUULD5TWlF8VKaT5Q5rMAxWrI4deeyPvHEQA7VeyMreZnCYj9
w6STPkTCDMznufFmMC03XqTGNRQF+NmHmQujPdMAH4FDfq5hrc3rz6hIJ4lM
Q+21Arfupa.0mjG+clgyITQ+IivosNt6zRt36utf0uI+W0iFYqpXn9bW7IGa
gE8J.Wf2kOASlEyYU7wxS1H3I8NvSzH3I4G7XkQVc8FP03.iTzafVKUlvYAX
HWXCSvPErgOfOEyvT81FcumoUYOC6lZeakVIW.JQKGOp8MLu2+S.KRcZBB
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
this seems to be working (the bug's still there but I'll open another issue for that)
