### ISSUE TITLE
CMake fail to find BOOST when crosscompiling

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#95]
at least when crosscompiling, if `/usr/include` doesn't contains a `boost` folder with lib header, then CMake fails to configure project even if we pass a valid path with `-DBOOST_ROOT`

look at `feature/rpi_croos_compiling` build log on travis for more details

I have to copy boost header to system path to get it to work, but I don't know which version is used when compiling, the host or the guest one.

**Comment by jcelerier** [comment]
seems to be a known problem: 

https://cmake.org/pipermail/cmake/2009-March/028283.html

https://stackoverflow.com/questions/24659753/cmake-find-library-and-cmake-find-root-path

so I think the best thing to do is to write in the documentation that one has to copy the boost includes in some hierarchical path in the cross-compiling root.

**Comment by jcelerier** [comment]
or maybe since Boost are moving to [cmake for their build system](http://boost.2283326.n4.nabble.com/CMake-Announcement-from-Boost-Steering-Committee-tt4696934.html) they will fix it :p

**Comment by avilleret** [comment]
here is the key on Travis : https://github.com/OSSIA/libossia/blob/master/ci/deps.sh#L53
The boost header are copied to system include directory.

**Comment by avilleret** [comment]
for the record, to definitely fix it, I use 

``` 
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
```
 
in toolchain file, so that Cmake search for boost header on target sysroot and can't find it, then it search on host and find it in 3rdparty folder
