### ISSUE TITLE
[ossia-max] add default device

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#98]
as in ossia-pd

**Comment by bltzr** [comment]
for now, if nodes are not in children patchers of the one containing ossia.device, they simply won't be included in the device, so, really, we are in some Schödinger in-between state...
in order to figure out how this works in pd, open ossia.help (and also ossia.device-help in parallel - also, you can always ask me on gitter)

**Comment by avilleret** [comment]
duplicate #94
