### ISSUE TITLE
[ossia-max] fix ossia.view

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#99]
and allow bind message

**Comment by avilleret** [comment]
could we close this ?

**Comment by bltzr** [comment]
it doesn't seem to work with absolute addresses (such as /sub.1, I also tried to add the device name, such as device:/sub.1, but to no avail) only relative ones (such as sub.1) did work

is that what is supposed to happen ?

**Comment by bltzr** [comment]
![Yes we can](http://themelkerproject.com/wp-content/uploads/2012/11/YesWeCan.jpg)
